### ISSUE TITLE
Can't build with ant any more – missing grabcut.swc from build.xml...?

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1011]
Everything builds fine if I just add  ````<library-path file="${LIBS_DIR}/grabcut.swc" />```` into build.xml in the appropriate places.

Wouldn't others have noticed this sooner if it really needs it for the build using ant?
Or is nobody using ant now? -Or am I missing something?

**Comment by wendyhoy** [comment]
I ran into this too, but I thought the problem was on my end. I ended up building with gradle instead.

**Comment by TheLogFather** [comment]
I've always used ant, and it's still working fine for me (when I add those extra lines mentioned above), while gradle actually fails with an exception while trying to download various things it needs (complains about redirection of some download URL from https to http – not happy doing that...)
Since ant has always been fine (up until I updated my github fork to match LLK/scratch-flash, and foun problem in OP), I just stuck with it, rather than bother trying to sort out my gradle build.

**Comment by TheLogFather** [comment]
Here's a link to the patch to fix this:
https://github.com/TheLogFather/scratch-flash/commit/749b9565f71dcf03f6e49302ff5c32ccd6751b53

**Comment by thisandagain** [comment]
We have dropped support for `ant` in favor of `gradle` for building `scratch-flash`.
