### ISSUE TITLE
[improvement] Scratch Timer is not accurate than 'days since 2000'

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#1014]
Lots of Chinese teachers said that sometimes the block of 'timer' can not meet their demand of accuracy. 

Because 'days since 2000' gets time from system function, it is accurate enough to meet any demand of timer. So I think we should modify the algorithm of Scratch Timer.

I wrote a example on [https://scratch.mit.edu/projects/92505204/]. This project want to do something every 0.1 second, but Scratch Timer lag behind 'days since 2000' obviously, especially when stages has lots of render task.

**Comment by lize777** [comment]
@TheLogFather we can discuss this problem here.

**Comment by TheLogFather** [comment]
OK.. but there isn't really a problem with Scratch, only with how you're doing the timing.

You shouldn't try to 'fire' events at a set time interval in that way if you want it to be accurate.

Here's a *much* more accurate way to do it:

when GF clicked
set [nextTime v] to [0.1]
set [test3 v] to [0]
forever
wait until < (timer) > (nextTime) >
change [nextTime v] by (0.1)
change [test3 v] by (1)
end of forever

Try comparing the "test3" counter with the two counters you have in your project, and you'll see how inaccurate yours are.

**Comment by lize777** [comment]
![image](https://cloud.githubusercontent.com/assets/8316018/13065245/841cd2f4-d495-11e5-83bc-58086338a0a5.png)

@TheLogFather But when I add some render tasks:
![image](https://cloud.githubusercontent.com/assets/8316018/13065308/1016df98-d496-11e5-8ead-68684995a0dc.png)

The test3 is very very slow.

**Comment by TheLogFather** [comment]
Well, if you will do things that take more than 1/10th second!

Since you're asking Scratch to do something each frame that will take longer than your firing time, you can't possibly make it fire *during* the frame while it's doing all that processing.

What is it you actually want to do with this...?

**Comment by lize777** [comment]
I want program performs something every the real 0.1 second.

**Comment by TheLogFather** [comment]
Then you have to make sure you don't ask the program to do something in a frame that takes longer than 0.1s (or you have to put a timer check after every intensive operation, such as an effect block, so it get chance to check it again).

However, you should note that if you're asking Scratch to do so much work like that, and getting well under 10fps, then your project will not 'feel' very smooth to use at all. -I'd recommend you rethink what you're doing, if that really is the case...

**Comment by lize777** [comment]
So if this task is irrelevant to render, is this no problem?

**Comment by TheLogFather** [comment]
As long as every frame takes less than 0.1s then the script I gave will fire every 0.1s.

As soon as a frame takes longer than 0.1s then it will miss one (or two if it takes >0.2s, etc...)

**Comment by TheLogFather** [comment]
I'll also note that if it does miss one (or more) firing event(s), then it will still catch up at the next chance it gets (i.e. it will fire an extra one, or more, in the next frame(s) to make up for the one(s) it missed).

**Comment by lize777** [comment]
Ok I know. Thank you!
