### ISSUE TITLE
add separate Music and Dance themes in Sprite & Costume media library

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1015]
We want to have "Music" and "Dance" in two separate themes in Sprite & Costume media library interface.  We also would like "Dress-Up" added as a new theme. 

![image](https://cloud.githubusercontent.com/assets/4721032/13081978/dea08e4e-d49c-11e5-9ff3-c59e8868247e.png)

**Comment by ntlrsk** [comment]
We need this for the Scratch music cards and Int'l Day of Jazz.

**Comment by ntlrsk** [comment]
We would also like a new Category in the Sound library called: **Musical Notes**

**Comment by Tymewalk** [comment]
@ntlrsk About that last one - couldn't you just use the play note () for () beats blocks instead?

**Comment by ntlrsk** [comment]
@Tymewalk Good question - we have some new sets of sounds that are sung by a person, sound harmonious together (and are better quality) than the play note block.

**Comment by Tymewalk** [comment]
@ntirsk OK... how about **Melodies**?

**Comment by ntlrsk** [comment]
@Tymewalk You can preview some of the sounds here - they are individual sounds: https://scratch.mit.edu/projects/93194596/

**Comment by bsb20** [comment]
Completed in [1055](https://github.com/LLK/scratch-flash/pull/1055)
