### ISSUE TITLE
looks effects breaks "color is touching color?"

### ISSUE THREAD

**Issue by yokobond** [LLK/scratch-flash#1016]
When I put a ‘set effect’ block, set any effect except ‘brightness’ or ‘ghost’ and the effect even if 0, in any script area, the “color is touching color” block, 'color is touching color?' will be broken in other sprite. 
This behavior can be fixed by turning the Stage3D off with 'Ctrl-m'. 

Testing project: ["color is touching color?" with looks effects](https://scratch.mit.edu/projects/97345823/)
Tested: Scratch2.0 v443 on Flash v20.0.0.286 MacOS

**Comment by TheLogFather** [comment]
There are numerous problems/differences/inconsistencies with colour-sensing in Stage3D (even just "touching color?"), especially when you start to apply colour and brightness effects to a sprite... :/

Does your Mac have a retina display? If so, do you have a machine without it that you can try with your project (in Stage3D mode)?

I've only got a retina-enabled MacBook here right now to try your project, but I would be curious to know if it actually works with a non-retina display when using Stage3D? (I should be able to try it tomorrow.)

Also, if it does work ok on a non-retina display, then does it still work in fullscreen mode?

**Comment by TheLogFather** [comment]
I should've also added that you can work around this problem while still switched into Stage3D...

What happens is that the colour sensing is offset by an amount that corresponds to the half-width and height of the costume. (But note that rotation messes around with the direction of offset, so the sensing offset is only aligned with screen x & y when direction is set to 90.)

You can therefore work around the problem by using a separate sprite (or clone) for the colour sensing, with a small costume (2x2 pixels, say). You would then do all your path-sensing & movement through that small sprite, and just have your main sprite continually go to it.

**Comment by yokobond** [comment]
Yes, I've tested it only retina MacBooks. 
So, I tested on another 'not-retina' MacBook.  But it has the same problem.
