### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by NoMod-Programming** [LLK/scratch-flash#1022]
Whenever I try to build Scratch-flash from the source (modded or unmodded) using the gradle method, I always get the following error:

> download-osmf-zip:
      [get] Getting: http://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download
      [get] To: /home/travis/.gradle/gradleFx/sdks/77b6510675e9bf47142422c374af153591fe4734/in/OSMF_1.0.zip
      [get] http://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download permanently moved to https://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download
      [get] https://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download moved to http://downloads.sourceforge.net/project/osmf.adobe/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip?r=&ts=1455860500&use_mirror=iweb
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'scratch-flash'.
> The following error occurred while executing this line:
  /home/travis/.gradle/gradleFx/sdks/77b6510675e9bf47142422c374af153591fe4734/frameworks/downloads.xml:125: The following error occurred while executing this line:
  /home/travis/.gradle/gradleFx/sdks/77b6510675e9bf47142422c374af153591fe4734/frameworks/downloads.xml:144: Redirection detected from https to http. Protocol switch unsafe, not allowed.

According to the log, it appears that SourceForge is redirecting the request for a direct download to the web interface, which is in http (not https). I can't seem to build with this error unless I manually download the file, track down the folder it will be going into, and place the file inside it.

**Comment by thisandagain** [comment]
Tracking in #1057
