### ISSUE TITLE
Custom Blocks strangely append empty text sections to the end

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-flash#1026]
When I make a custom block, it looks like this:
![New Custom Block](http://i.cubeupload.com/Ip8o6b.png)
Note that I have a number section on the end.

When I edit it, it looks like this:
![Editing - Wait, what?](http://i.cubeupload.com/sZZr06.png)

There's an empty text box on the end. This doesn't happen if the end of the custom block already has a textbox.

Why is this, and is it needed?

**Comment by chooper100** [comment]
I always presumed it was there because the ST presumed anyone editing a block would likely want to add text to the end of it, and might not realize they can expand the window.

Also, it doesn't matter particularly as you can ignore it and it will not affect the block (if left empty)

**Comment by Tymewalk** [comment]
@chooper100 Oh, OK. I thought that wasn't supposed to be there.
