### ISSUE TITLE
ant building problem

### ISSUE THREAD

**Issue by kuomingwu** [LLK/scratch-flash#1030]
hello guys,

this is my first use ant

when I run the ant

I get the error:

![image](https://cloud.githubusercontent.com/assets/6070952/13422016/fd3091d4-dfcc-11e5-9f71-b2c372404cc0.png)

how can I fix it ,

thx !

**Comment by thisandagain** [comment]
Hi @kuomingwu we no longer support `ant` and instead suggest `gradle` for building `scratch-flash` from source as per the `README.md` file.
