### ISSUE TITLE
Stage - "Say" alignment issues between normal and full-screen modes

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-flash#1034]
via @mresmres 

Example project:
https://scratch.mit.edu/projects/99539790/

> When I run this project in full-screen mode, the first speech balloon has a text-formatting problem, but the problem doesn’t appear when the project is run at regular-size (on the project page or in the editor).

/cc @ntlrsk @cwillisf

**Comment by Tymewalk** [comment]
It looks the same to me in both modes.

**Comment by thisandagain** [comment]
Moved to backlog pending repro.
