### ISSUE TITLE
[Suggestion] Could the list of language be ranged by frequency?

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#1036]
I am a Chinese scratcher, and often switch language between English and 简体中文.
English is first, however, 简体中文 is last second.
Lots of Chinese scratch teachers also think it is very troublesome when switch language.
So I think it's unreasonable for alphabetical order.
(On the other hand, why English is not alphabetical order but first? The reason is that English is most frequency used.)

**Comment by ubertao** [comment]
Maybe remembering one recently used language will solve your problem.
