### ISSUE TITLE
WeDo 2.0 tilt block

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#1040]
The new tilt sensor blocks for WeDo 2.0 are very awkward?

One of the most popular WeDo 1 exercises we use is to move scratch cat around using the tilt sensor as a joystick. This is much, much harder for youngsters to understand using the new style blocks...

Was it a deliberate decision or just simply arisen because you are trying to use the tilt sensor in the default mode 0 (TiltSensorAngle) ?

If however you use the tilt sensor in mode 1 instead (TiltSensorTilt) the results will be the same in operation as WeDo 1 (actually you get the values 0-3-5-7-9, which can be scaled to 0-3-2-4-1 to match the normal Scratch tilt directions).

This TiltSensorTilt mode is also what Lego's own software uses...

To convert the tilt sensor to mode 1 simply write this hex data to characteristic 'Input Command' after the tilt sensor connection has been notified.

     (CONFIGURE) INPUT COMMAND
     00001563-1212-efde-1523-785feabcd123

     01 02 ch 22 01 01 00 00 00 02 01	where ch = channel, 01 or 02

Incidentally the similar command for motion sensor in distance cm is 

     01 02 ch 23 00 01 00 00 00 02 01

**Comment by ntlrsk** [comment]
@cpseager We'll review this decision and suggestion - thanks.

**Comment by cwillisf** [comment]
We discussed this and decided to make the changes described in #1062.
Thanks for the feedback!

**Comment by arvenil** [comment]
Hi @cpseager, @ntlrsk, @cwillisf,

I'm trying to figure out where is the code responsible for this (sending commands to Wedo2 hub) in scratch repos? 
Also @cpseager how did you know about command `01 02 ch 22 01 01 00 00 00 02 01`? Is there anywhere description of communication protocol for Wedo2 and BLE?

Could anyone point me into a right direction?

**Comment by cwillisf** [comment]
@arvenil, we use LEGO's SDK which is available to the public here:
https://education.lego.com/en-us/support/wedo-2/developer-kits

**Comment by cpseager** [comment]
@arvenil as I couldn't/didn't want to use the SDK in my use case (chrome/nw.js app talking RS232 via a BLED112 dongle to support any OS from Windows XP/Mac 10.6 upwards) I simply wrote a test app using the SDK and then sniffed/directly duplicated the actual packets. I have a list somewhere if you don't want to use the SDK.

**Comment by arvenil** [comment]
@cwillisf Ok, my bad. I was looking at lego sdk before, however I saw there only android/osx/windows8/ios sdk and somehow I've assumed for browser your are using javascript, not action script. So to confirm, you are using action script (windows8) sdk?

@cpseager That would be great. I was trying to follow lego SDK (mainly java/android), while this is doable it's really hard and frustrating as data packet is build by bunch of objects. Description of actual BLE protocol (e.g. what each byte does and to which characteristic send the whole packet) would be much better. I'm basically trying to hack/play/create my own sdk in language that is currently not supported by official sdk, so it's easier to also have the protocol documentation.

**Comment by cwillisf** [comment]
@arvenil we're using the Windows & OS X versions of the LEGO Device SDK through the Scratch Device Manager. Scratch uses a WebSocket connection to communicate with the Device Manager.

See here for user-oriented info about the Device Manager: https://scratch.mit.edu/wedo

The Device Manager is built using mostly JavaScript and I've intentionally avoided steps which would make it difficult to read the code. Feel free to dig through its code if that would be helpful :)

**Comment by cpseager** [comment]
@arvenil, see attached. It should give you enough info to switch on motors, change color etc.
[wedo2_summary.txt](https://github.com/LLK/scratch-flash/files/712493/wedo2_summary.txt)
