### ISSUE TITLE
LEGO WeDo 2.0 extension has no help

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-flash#1041]
![no-wedo2-help](https://cloud.githubusercontent.com/assets/9948030/13708414/e4016e6c-e784-11e5-807a-ef1deace2968.png)

Activating the dropdown menu for WeDo 2.0 and selecting About extension will link to this: https://cdn.scratch.mit.edu/scratchr2/static/help/en/ext/LEGO%20WeDo%202.0.html

..which doesn't exist.

**Comment by ntlrsk** [comment]
Thanks for reporting. This is a known issue and the fix is going out soon. For now, please see: 
https://scratch.mit.edu/projects/editor/?tip_bar=ext2

**Comment by cpseager** [comment]
BTW the offline 444.3 help link fails at a different position, it stops working here:

![captureoffline](https://cloud.githubusercontent.com/assets/7423187/13755006/0c3f5f7c-ea11-11e5-9a97-f88d4dac68ec.PNG)

**Comment by cwillisf** [comment]
Fixed in Offline v444.4
