### ISSUE TITLE
WeDo 2.0 motor blocks

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#1042]
1) 'motor on for' in English now uses 'seconds' rather than 'secs' and so doesn't translate using existing strings

![capturewedo2motor](https://cloud.githubusercontent.com/assets/7423187/13745536/7d6b3d18-e9e6-11e5-924c-2ce00eab7e87.PNG)

2) 'everything' is missing from WeDo 2.0 motor drop down list, so you can no longer switch 2 motors on/off within one block.

3) and finally a suggestion from an 8 year old...

"why don't they use 'this way, that way, other way' rather than 'this way, that way, reverse' ?"

**Comment by ntlrsk** [comment]
@cpseager Thanks for the feedback on the blocks - we'll look into these.

**Comment by cwillisf** [comment]
@cpseager, with regard to point #2: the "motor" option actually turns on all (both) motors, as opposed to the "motor A" and "motor B" options which turn on just one motor. This was true in the original WeDo extension as well; "everything" includes both motors and lights.

**Comment by cpseager** [comment]
@cwillisf originally WeDo 1 was just

     motor

Then it became this to support 2 motors

     motor
     motor A
     motor B
     all motors

This menu configuration is actually still shown on some of the out of date tips e.g.
     /templates/help/studio/tips/ext/wedo-set-direction.html


Then it evolved to this to add lights as well

     motor
     motor A
     motor B
     lights
     everything

I would still suggest that adding 'everything' or 'all motors' is easier to understand when, for instance, simultaneously reversing the direction of both motors to make a robot go the other way.

When PF2 lights are released the WeDo 2 electronics probably won't be able to tell which output device it actually is (I can't see Lego adding a microcontroller into the PF2 lights) so going for 'all motors' is probably fine long term.

Have you tried starting notifications on "00001526-1212-efde-1523-785feabcd123" to give a 'button' 0/1 reporter? Would be very nice to be able to write a sequence that only starts when the button on the WeDo is pressed!

**Comment by cwillisf** [comment]
We discussed this and came to a couple decisions:
- The motor menu will be adjusted as described in #1062 
- We decided not to add the WeDo 2.0's button as a reporter or hat block because we'd rather avoid the possibility of accidentally turning off or disconnecting the hub.
