### ISSUE TITLE
WeDo 2.0 commit has broken other extensions

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#1044]
@cwillisf the commit: 8d42822aeacb6704a1a0582ed598645d368ef8a2
changed the way it handled indexOf('.') and this has caused strange side effects for other extensions which now no longer work correctly e.g. as an example please see attached image where, because the reporter name contained a '.', the extension name, which never contained a '.', has now become corrupted.

![capturedeadextension](https://cloud.githubusercontent.com/assets/7423187/13750184/400608d4-e9fc-11e5-9c61-c442dc61a384.PNG)

**Comment by cpseager** [comment]
Example test file:

[test.zip](https://github.com/LLK/scratch-flash/files/172322/test.zip)

**Comment by cwillisf** [comment]
Yikes -- sorry about that. I'll fix that ASAP.

My current plan is to use a separator character that is unlikely to be typed into an extension name -- much less likely than `.` anyway. I'll have to experiment, but I have my eye on the Unicode "unit separator" character (U+001F)...

**Comment by cpseager** [comment]
Thanks, or just call 'WeDo 2.0' 'WeDo 2' and all your '.' problems go way! :-)

**Comment by Ev1lC** [comment]
Hi. Not sure if this is the right place but the commit didn't fix my issue.

The attached project opened fine under v443 - in v444.3 the blocks are displayed as "undefined" ::

[motions.zip](https://github.com/LLK/scratch-flash/files/185787/motions.zip)

Would really appreciate it if you could take a look.

**Comment by cpseager** [comment]
@Ev1lC It is the same issue but this commit is not actually live yet, neither 444.3 444.4 have this commit in them. Should be fixed soon.

**Comment by Ev1lC** [comment]
My apologies! Keep up the great work.

**Comment by cpseager** [comment]
Having looked at the json file inside the SB2 (which is just a zip if you want to look) I'm now not so sure it is the same issue, as you do not seem to be using '.' at all. However many extensions show strange behaviour at the moment so its hard to tell until the new fixes go live.

**Comment by Ev1lC** [comment]
I'll plough through the Scratch source over the Easter break and try to spot the problem. It may help. Is there quick a way to show all changes between two releases on github? I can do this in subversion, so I'm assuming you can do the same on github.
