### ISSUE TITLE
TypeError: Error #2007

### ISSUE THREAD

**Issue by bobbybee** [LLK/scratch-flash#1047]
The above error was found while trying to save my NES emulator. The sb2 for this project can be found here: https://backtick.town/~alyssa/NES.sb2

As a bit of backstory, I accidentally borked the project, and now I can't revert from my old copy through "Upload from my computer". It just get stuck at "Save now", with the error repeated in the console. 

Thoughts? (If nothing else, I'd appreciate if one of the admins get force-upload it to id 43692156, which is now broken and due to this error, unfixable -.-)

Thanks :-)
~Alyssa

**Comment by jwzimmer** [comment]
I can repro this, when trying to save the project I see TypeError: Error #2007 in the JavaScript Console.

Repro:
- Download the sb2 file from bobbybee
- Go to scratch.mit.edu and click Create
- Upload the file from the File menu
- Say yes to the dialogue box asking you if you want to discard the changes to the newly-created project
- The project itself seems okay: there are several scripts and sprites, and when you click a variable in Data it shows up on the project screen and displays a value
- Choose Save Now from the File menu
- Note that nothing seems to happen in the UI
- If you click on Save Now text in the upper right, nothing seems to happen in the UI either
- After trying to save, the page seems frozen: if you click on My Stuff or Scratch logo you don't leave the editor/ nothing seems to happen
- After trying to save, if you open the JavaScript console, you will see many instances of the TypeError: Error #2007 error. The console is basically a long list of that error, some project metadata, and "SWF saving project". It might be an infinite loop, I see the message continuing to come up even after about 5 - 10 minutes after trying save the project.

**Comment by bobbybee** [comment]
It's possible that the sb2 is corrupt. Actually, it's even quite likely to be honest.

**Comment by bobbybee** [comment]
The sb2 was corrupted (all the asset IDs were -1), apparently due to a bug in the converter. Manually fixed and the project works fine now :smile:
