### ISSUE TITLE
[Suggestion] Why variables can not be inserted into these blocks?

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#1050]
![image](https://cloud.githubusercontent.com/assets/8316018/13940171/01c1073e-f016-11e5-89fd-3981b646629b.png)

**Comment by lize777** [comment]
It it convenient in some complex project.

**Comment by liam4** [comment]
+1, searching around Google I couldn't find any answer.. People [have done it](https://scratch.mit.edu/projects/73570530/) for your convenience. I think it's been mentioned by the ST (or at least unofficially agreed on) that projects that use hacked blocks should clearly state that they used hacked blocks, because it can be confusing to try to figure out how the creator of the project got those blocks (FYI: the answer is editing the raw project JSON code :P).

On the other hand, if these weren't hacked blocks, we wouldn't need to worry about confusion like this..

**Comment by lize777** [comment]
@liam4 
Program core idea is enclose changes, so program needn't be changed when changed demand comes.
However, If I want to detect another key press event, I must add a script.
Hope to adopt this proposal.

**Comment by NoMod-Programming** [comment]
Couldn't this be confusing to some new scratchers?
>> I made a variable called "tab", and put it in the key sensing block, but when I press the "tab" key, nothing happens

**Comment by liam4** [comment]
Why would nothing happen when the tab key is pressed?

**Comment by NoMod-Programming** [comment]
I mean that a variable named "tab" with the default value of 0 is inserted. People might misunderstand that the variable is not the name of the key, but the value of the variable is the name of the key

**Comment by TheLogFather** [comment]
The "broadcast (var)" block already works just fine - you can drop a var into it in the standard editor.

You cannot drop a var into the "key pressed?" block in the standard editor, but it's possible to 'hack' it in via the JSON, and then all you need to do is put it into your backpack and you can drag it out into your own projects. It then works fine.

As for dropping a var into "when I receive" (and other similar hat blocks), it's quite possible to 'hack' it in via the JSON, as above. Unfortunately, there are some assumptions made in the current Scratch source code which prevent that from working correctly. However, it's not that hard to 'fix' the code to make such things work as expected (I have a version which does).

**Comment by Airhogs777** [comment]
I agree with all of the above, the frustration and confusion that these mostly-arbitrary restrictions create far outweighs the occasional bad code they stop from happening. Additionally, it's created a culture of "in-the-know" users who can easily do things that new users can't re-create. I say remove the variable restrictions.

Except for the "when I receive" block. I can understand why that doesn't work.

**Comment by TheLogFather** [comment]
Putting a variable into the "when I receive" hat block (and "when backdrop switches") works perfectly fine after a few changes to the Scratch source code. (Besides getting the actual script execution to work, it also needs a few minor fixes to prevent silly things going on when renaming a broadcast, and when highlighting senders/receivers.)

The only hat block that isn't so straightforward to have a var/expression placed into it is the "when loudness/timer/etc." hat block. (But even then, I think it'd be possible to do it with some work...)

(IIRC, the "when key pressed" hat block also needed some changes in the Scratch code in order for it to work correctly with a var hacked into it – I *think* it doesn't work correctly if you hack it in with the current version...?)
