### ISSUE TITLE
Offline: Projects saved with 'rR' block spec

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-flash#1051]
Because the offline editor's extension interface is asynchronous by nature, the offline editor needs to perform some trickery to simulate a synchronous reporter (`'r'`) block in an extension.

The current version of this trickery involves changing the block type internally to `'rR'`, which tells the editor to treat the reporter as asynchronous but to communicate with the extension in the `'r'`-block style. This code is here:
https://github.com/LLK/scratch-flash/commit/1fe8d3813cf14c33c30b4d3165564dde42a7474a#diff-b8ffd1b1d6e335abaeea8767edd6c819R205

Unfortunately, if a project with such a block is saved from the offline editor, the SB2 ends up including an `'rR'` block. Loading an SB2 with this sort of block into the online editor causes undesirable behavior -- that is, the reporter just doesn't work.

In my opinion, `'rR'` ending up in the SB2 is the bug, and broken reporters in the online editor are a symptom.

**Comment by cpseager** [comment]
rR also stops watcher checkbox appearing, would be nice to resolve that at same time?

https://github.com/LLK/scratch-flash/blob/master/src/scratch/PaletteBuilder.as#L506

**Comment by cwillisf** [comment]
Unfortunately, checkboxes / watchers in the offline editor is a much bigger issue... I've filed #1052 to make public some of our internal discussion on the issue.
