### ISSUE TITLE
Can't build using gradlew.bat build

### ISSUE THREAD

**Issue by BookOwl** [LLK/scratch-flash#1057]
When I run `gradlew.bat build`, I get this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'scratch-flash'.
> The following error occurred while executing this line:
  C:\Users\Matthew\.gradle\gradleFx\sdks\29c0f30dc9d07deae8899a18bc5a02eeff3b8afc\frameworks\downloads.xml:125: The following error occurred while executing this line:
  C:\Users\Matthew\.gradle\gradleFx\sdks\29c0f30dc9d07deae8899a18bc5a02eeff3b8afc\frameworks\downloads.xml:144: Redirection detected from https to http. Protocol switch unsafe, not allowed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED```

**Comment by BookOwl** [comment]
@thisandagain pls explain

**Comment by cwillisf** [comment]
There was a short time where some of the external servers hosting these files were misconfigured, but they've since fixed their configuration and it should be working now. @BookOwl or @bjskistad, could you try again and let me know if you're still having trouble?

**Comment by zktz** [comment]
It was still unsafe and not allowed.

**Comment by bjskistad** [comment]
@cwillsf I'm sorry, you referenced me. I don't remember what trouble I was having, I think I did open an issue though, could you please direct me to that issue if so?

**Comment by MegaApuTurkUltra** [comment]
This is happening for me too

**Comment by MegaApuTurkUltra** [comment]
FYI, @djdolphin has a solution for this https://scratch.mit.edu/discuss/topic/38970/

**Comment by cwillisf** [comment]
Unfortunately I don't think this one is under our control: it appears to be an intermittent server-side misconfiguration on servers that the Scratch Team doesn't have access to.

I think @djdolphin's / @Jonathan50's manual solution is the best we can hope for until and unless the misconfiguration gets fixed.

Here's that manual fix:
> If you get an error saying 
> `Redirection detected from https to http. Protocol switch unsafe, not allowed.`
> then manually download [OSMF_1.0.zip](https://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download) and put it in `<your home directory>/.gradle/gradleFx/sdks/<some number>/in`. (Thanks Jonathan50)
