### ISSUE TITLE
Cloud Variables - Invalid TCP request causes process to throw a fatal exception

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1061]
It's easy to see this happen if you're running a project that detects fallback polling (e.g. https://scratch.mit.edu/projects/96991584/) and you then use the cloud API to accidentally try to set any cloudvar, on ANY project, using ANY account, to an invalid value (i.e. to a string that's non-numerical).

ALL fast connections to cloud (i.e. port 531) from the same (external) IP address are terminated – even if the connections are from different machines (but they are behind a NAT, so they appear to the cloud server as the same IP).

Could this be part of the cause of #1001? Might it be even wider than just the same IP?
(Could it be just the NAT itself which drops them all for some reason? – Will try outside NAT tomorrow.)

**Comment by griffpatch** [comment]
Out of interest, did you try this outside of the NAT? - Only my slither.io project (https://scratch.mit.edu/projects/108566337/) is dropping everyones connections back to http fallback once every 15 to 30 minutes, but I have had reports from some people saying that scratch is reporting the 'you can only assign numbers to cloud vars' message and I was wondering if that was what might be causing the problem therefore? However, I do also remember you saying that the cloud server would periodically drop someone after so long a period anyhow?

**Comment by TheLogFather** [comment]
Yes, I did. It's actually really weird, and I don't understand it...

If I send a request from my laptop while away from home, to update a non-existent cloudvar on some random project, with an invalid value (i.e. text), from any account, it causes ALL of my custom cloud clients at home to drop connection (until they notice and re-establish).

I don't understand why it affects it like this for me. I mean, the project I send the invalid request to is unrelated to the ones used by the cloud clients, and I can send it from an account that's neither the one running the cloud clients, nor the owner of the projects. So that seemed to suggest any invalid request to anything from anyone would drop everyone everywhere.

However, I was also watching your slither.io cloud log, to see if there was any evidence of people getting disconnected soon after I made the invalid requests. But I didn't see any. (I even tried sending an invalid request to that project, and I still didn't see any evidence of anyone getting dropped – though it still drops my cloud clients on my other projects!)

Confused... :/

**Comment by griffpatch** [comment]
Well I find my connection to the fast cloud server is dropped back to http
fallback after just 10 mins of playing, or even straight away sometimes.
And this happens all the time. I do hope something could happen to help the
situation because it makes these projects seem very glitchy and like they
don't work :(. Such a shame.
On 26 May 2016 5:08 p.m., "Aka DadOfMrLog" <notifications@github.com> wrote:

Yes, I did. It's actually really weird, and I don't understand it...

If I send a request from my laptop while away from home, to update a
non-existent cloudvar on some random project, with an invalid value (i.e.
text), from any account, it causes ALL of my custom cloud clients at home
to drop connection (until they notice and re-establish).

I don't understand why it affects it like this for me. I mean, the project
I send the invalid request to is unrelated to the ones used by the cloud
clients, and I can send it from an account that's neither the one running
the cloud clients, nor the owner of the projects. So that seemed to suggest
any invalid request to anything from anyone would drop everyone everywhere.

However, I was also watching your slither.io cloud log, to see if there was
any evidence of people getting disconnected soon after I made the invalid
requests. But I didn't see any. (I even tried sending an invalid request to
that project, and I still didn't see any evidence of anyone getting dropped
– though it still drops my cloud clients on my other projects!)

Confused... :/

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/LLK/scratch-flash/issues/1061#issuecomment-221917465>

**Comment by TheLogFather** [comment]
Can you tell straight away when you're playing that the connection has dropped to polling?

How long does it take before the project notices? Does it give up almost straight away, or does it carry on trying to send the data as if nothing has happened? At what point does it give up?

If you want, I can send an invalid request at some fixed time while you're playing, and then we can see if you can tell...? (I can do that any time over the next half hour-ish, if you want...)

**Comment by griffpatch** [comment]
Sorry away from my pc at the moment...
You can tell quite quickly because all the other players disappear...
Because in http fallback mode it changes data too fast to receive any
updates from other players.

**Comment by TheLogFather** [comment]
Yes, but can I tell from the cloud log? If the project carries on sending stuff for quite a while, and doesn't really notice any problem, then it'd explain why I don't see evidence of anyone getting dropped.
But I though it does notice at some point? (A minute or two...?)

**Comment by griffpatch** [comment]
Yeah my project keeps sending data, but it drops back to sending it once
every second rather than ten times a second. Then if it makes contact it
goes back to 10 times a second then back to 1 until it gives up after 8 or
so cycles.

**Comment by TheLogFather** [comment]
OK, so the pattern I should see in the cloud log would be that after a couple of seconds or so (?) everyone should start to send far fewer changes. And then a second or two later, start sending lots again. And then repeat several more times. Until finally everyone who was connected would disappear? (Does it keep watching the changes of other players, even though it has 'given up' sending?)

**Comment by TheLogFather** [comment]
OK, I see from the log that you're playing now...
Apologies if everyone is now disconnecting the game, but I just sent an invalid request...
Let me know if you noticed anything!

**Comment by griffpatch** [comment]
Yep... that did it!

**Comment by TheLogFather** [comment]
Huh. Wow!

That's Very Bad. :(

**Comment by griffpatch** [comment]
Completely threw me out the game...

**Comment by griffpatch** [comment]
So... can you do this without using the API but within scratch itself?

**Comment by TheLogFather** [comment]
Yup, looking at the cloud log I can see a distinct decrease in the number of requests per second from each player.

I was using the API. I think that the client (i.e. project) checks the value before sending it...? (Might be wrong about that, in which case it'd mean anyone anywhere sending a bad value will break everyone's cloud connections.)

**Comment by griffpatch** [comment]
When you set a bad value using the API, does it appear on the log, I assume
not...?

**Comment by TheLogFather** [comment]
No, the server rejects it (and breaks your port 531 connection – and everyone else's, it seems...)

**Comment by griffpatch** [comment]
Seems ok on that score. I just set a letter and nothing happened to the
other players.

**Comment by griffpatch** [comment]
I wonder how often bad values get sent to the cloud server via the API...?
How many of the outages could be accounted for...?  Just it happens all the
time (every 10-15 mins on my game) so I assume there may be other things at
play? but it is everyone connected to the project that gets disconnected at
once so fits the bill. Games like scratcharia won't see any difference
because they work just fine in fallback mode.

**Comment by TheLogFather** [comment]
Well, I wondered if it might not just be stuff sent through the API, but any valid request that gets 'garbled' along the way somehow? Maybe 'cos someone's 'net connection gets cut off half way through sending some cloud data, so it never quite finishes correctly, or some such weird thing?

**Comment by griffpatch** [comment]
It'd be such a good idea to get this one solved as it might make cloud
games suddenly far more stable! I wonder who is the man to talk to these
days with regard to the cloud server!

**Comment by TheLogFather** [comment]
It's particularly an issue given that any old bot that's just created a brand new NS account could break every reasonably real-time cloud project everywhere for everyone as often as they like, and that it never even appears in the log, so can't be tracked so easily. And even if they get noticed and shut down, can just create a new bot account and do it all again straight away.
Seriously, how many emoti-faces can you pull for this... :o :( O_o :/

**Comment by rschamp** [comment]
Thanks for the additional info. We are currently working on QA for the deploy on Tuesday, but will look into this after the deploy for a hotfix.

**Comment by TheLogFather** [comment]
Thanks for that update.

I should note again that this is a specific instance of https://github.com/LLK/scratch-flash/issues/1001. We're speculating that this is probably at least one cause of that issue, but #1001 is a more general statement of the problem.

If it's any help, any time you want I can give a list of times over the last day or two where I see my cloud client has had to reconnect because it lost its connection.

E.g. in the last few hours:
1541UT, 1529UT, 1519UT, 1516UT, 1453UT, 1451UT, 1346UT(but that looks like something different?), 1333UT, 1307UT(that was down for almost whole minute, so maybe something different?), 1224UT, 1111UT, 0937UT, 0909UT, 0851UT, 0832UT, 0609UT...

That's all from the log for the custom cloud client that's connected with this cloud round-trip time project:
https://scratch.mit.edu/projects/96491582/

**Comment by TheLogFather** [comment]
Oh, hang on... the title change suggests it's just for a single client IP...

But when I tested this it looked like I could cause all (port 531) connections everywhere to drop.

Are you seeing something different @thisandagain?

**Comment by thisandagain** [comment]
What I'm seeing is a single process in the cluster throw which would cause any clients connected to that process to fail over to HTTP polling. Given the way that we load balance that would mean all clients sharing an `x-forwarded-for` would be attached to the same process and thus – fail over.

**Comment by TheLogFather** [comment]
Yes, OK, that's closer to how was thinking of it – everything connected to the server (of which there are several, which I'd wondered about) will lose connection, not just cloud clients belonging to one IP.
And it's because of an exception of the server process caused by the request (just the kind of thing I'd imagined would be happening).

So when we tested with griffpatch's slither.io above, we were lucky to get the same server?

Yet it always happens to all (three) of my cloud clients at the same time when I send a bad request. Does that mean that all clients from one IP will end up on the same server, even though they started up at very different times?

Also, it always happens to all of them even when I sent a request from somewhere completely different (i.e. totally different IP – different city, but same country). So is there some kind of allocation to specific servers for specific 'regions' of the world or IP address space?

**Comment by thisandagain** [comment]
Alright. This should now be resolved. Thanks for reporting and all the testing. @TheLogFather if you see this crop up again please let me know.

**Comment by TheLogFather** [comment]
Yep, that looks more robust now – not had a simultaneous dropout since 0332UT today, and sending invalid requests, even from the same IP, and/or the same project, no longer causes everything to drop. :)

(Also, a reminder about the Help@Scratch#43231/#41020 issue – might be worth sorting that out before it becomes widely known and starts getting abused...)

**Comment by thisandagain** [comment]
Thanks. I have that other issue on my radar but requires some major redesign of the system to resolve fully.

**Comment by TheLogFather** [comment]
OK, great.
Wouldn't the quickest first defence be to simply perform a server-side check for NS? That would greatly reduce the possibility of the worst abuse by bots.
