### ISSUE TITLE
Updating Wedo 2.0 Extension 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-flash#1062]
From the March 23, 2016 editor design meeting:

- Add "all motors" to the current {motor, motor A, motor B} drop-down menus.
- Change "seconds" to "secs" for localization and consistency with the rest of Scratch.
- The tilt-related blocks should be as follows:
  - when tilted {any, up, down, left, right}
  - tilted {up, down, left, right, any}? => Boolean value
  - tilt angle {up, down, left, right} => angle in degrees; up = -down, left = -right
- When adding and altering the blocks (especially reporters), make sure the order is consistent with other categories in the block palette.

**Comment by cwillisf** [comment]
This discussion came up in part due to #1040 and #1042

**Comment by cpseager** [comment]
Thank you.
