### ISSUE TITLE
445: Clone command does not work

### ISSUE THREAD

**Issue by perugini** [LLK/scratch-flash#1065]
Hi, 
after have upgraded to 445 I've lost clone command functionality.

It's seems strange enough, but same program just new Scratch offline editor release and nothing run - clone related.

With the new release I've created a simple one scratch using clone command and it's seems to run fine.

L

**Comment by thisandagain** [comment]
Hi @perugini. Sorry for the trouble. We released a hotfix to the offline editor last night to fix the issue. Please take a look and let us know if you are still experiencing any problems.
