### ISSUE TITLE
445 Load of Project with extension blocks is still broken - come up undefined

### ISSUE THREAD

**Issue by MrYsLab** [LLK/scratch-flash#1068]
If a new project is created, saved and reloaded, the blocks eventually come up properly. For project that were saved prior to 443, the blocks still come up undefined.

This is causing my users a great deal of angst. Please fix this ASAP.

**Comment by thisandagain** [comment]
Hi @MrYsLab can you please share a SB2 file that demonstrates the problem?

**Comment by MrYsLab** [comment]
Here is a [link](https://drive.google.com/file/d/0B4Qt0LRbWv31d1NseFZ3T0Q4VzQ/view?usp=sharing) to file that demonstrates the problem. The original project was saved with an older version of the editor. I added a single block and resaved using 445.1. As you can see the older information comes up undefined and the new block is defined.

**Comment by MrYsLab** [comment]
Installation of version 445.2 seems to have fixed the problem.
