### ISSUE TITLE
All reporter blocks of "operators" don't return any values on offline editor #445.

### ISSUE THREAD

**Issue by abee2** [LLK/scratch-flash#1069]
The title is all. It seems OK on online editor.

**Comment by lize777** [comment]
@ntlrsk This is a serious bug!

**Comment by thisandagain** [comment]
Hi folks, we released a hotfix last night to resolve this issue. Sorry for the inconvenience. Please take a look and let us know if you continue to experience issues.

**Comment by abee2** [comment]
Thank you for your quick response. I confirmed this bug is fixed with #445.1. However, automatic updater cannot detect this update. So I think Scratch Team should announce about this issue.

**Comment by thisandagain** [comment]
Scratch's auto-updater should be seeing this now.

**Comment by abee2** [comment]
I confirmed it. Thanks!
