### ISSUE TITLE
Change to extensionSeparator breaks saved .sb2 programs

### ISSUE THREAD

**Issue by davidjsherman** [LLK/scratch-flash#1070]
Changing the extension separator to \u001f in 8d149c6eb517101b7c64491556deb77bb35200bd (Scratch version 445) breaks saved .sb2 files created with previous versions. It is embarrassing to discover this in front of a class of ten-year-olds, after someone has kindly clicked on the update button. It is not really feasible to ask teachers and students to patch all of their saved programs.

The Scratch version is saved in the .sb2 file in `info.swfVersion` and could be used to infer the extension separator for backwards compatibility. Then the conversion process could simply be, open the old program, then resave it.

We observed this in offline Scratch. Since many of our elementary school classrooms may not use the Internet, and running a local Scratch X server is not within the means of most of our classes, offline Scratch remains a necessary cog in the machine.

On the left, a program in v430; on the right, the same program in v445.
![v430 versus v445](https://cloud.githubusercontent.com/assets/9472510/14376923/15594d60-fd6d-11e5-8db8-cccd097a87d6.png)

**Comment by cwillisf** [comment]
Here's an SB2 file to demonstrate the problem. I had to rename it to end with `.zip` in order to attach it here.
[ext-blocks-v444.4.zip](https://github.com/LLK/scratch-flash/files/210560/ext-blocks-v444.4.zip)

**Comment by davidjsherman** [comment]
Great, forgot to thank you at the time but I confirm this fixes our problem.
