### ISSUE TITLE
Copy / Pasting media library sounds results in frequency shift

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#1072]
Example:  
1. Start with a sprite with the "Pop" sound.  
2. Import the "Boing" sound from the sound library as a separate clip.
3. With the mouse, select the entirety of the "Boing" waveform and Ctrl-C to copy it
4. Click on the end of the "Pop" waveform and Ctrl-V to paste the "Boing" waveform to the end of it
5. Play the resulting composite waveform - you should note that the "Boing" sound frequency is different from the original.
6. You can do it the other way around as well, pasting the Pop to the Boing.

I have been told it does this with other sound file combinations as well, but I haven't experimented any further at this time.

**Comment by bjskistad** [comment]
Are you saying you want to be able to copy and paste sounds?

**Comment by Paddle2See** [comment]
You can currently copy and paste selected sections of a sound.  However, it sometimes results in a frequency shifted result.

**Comment by bjskistad** [comment]
Hmmm... That is strange. I guess I've never used that feature before.

What is the cause of the frequency shift? Do you know?

**Comment by chooper100** [comment]
Able to replicate this

Interesting that I didn't notice this before though...

**Comment by Tymewalk** [comment]
I asked someone about this before and they said it may have something to do with the sample rate.

Tried it from a song to the sound "pop" and it came out really distorted and slow.
