### ISSUE TITLE
Problem with  Chinese Block Font Size

### ISSUE THREAD

**Issue by beardad1975** [LLK/scratch-flash#1073]
The default english block font size  is  Ok . Like the following:

![](https://github.com/beardad1975/scratch_doc/blob/master/default_english_font.png?raw=true)

In China, Hong Kong and Taiwan . When teaching Scratch ,teachers use Chinese Language.  But the default font size is too small. Like the follwing:

![](https://github.com/beardad1975/scratch_doc/blob/master/default_chinese_font.png?raw=true)

  Teachers in Chinese World could only use the following solution.

![](https://github.com/beardad1975/scratch_doc/blob/master/current_solution.png?raw=true)

Yes!  Every Chinese tacaher, every chinese student  need to do this when we use scratch2 every time.  Shift + Click , over and over again.  Of course people are lazy in nature. So many students just skip this solution.  Causing problems like nearsightedness  or  using the wrong block.

This problem is a small one but quite annoying for Chinese Scratch Users. After reading the source code, I found somthing in [Translator.as(127) ](https://github.com/LLK/scratch-flash/blob/master/src/translation/Translator.as#L127) and  [Translator.as(44) ](https://github.com/LLK/scratch-flash/blob/master/src/translation/Translator.as#L44)  . A few code was  already added to make Chinese(zh_CN) font size a different default value than english. Then  I tried it in Scratch Offline and Online Editor , but the code didn't work. The chinese default font size is the same as english's.  Why?

After hard time building the SWF ( I don't quite know AS3  )  and testing,  I thought I found the answer.
See the following picture.

![](https://github.com/beardad1975/scratch_doc/blob/master/double_po_files.png?raw=true)

Yes! The po files for zh-cn and zh-tw chinese are doubled.The origin code in Translator.as, font12 array only has the value 'zh_CN', but no 'zh-ch' .  After I add all the 4 file names in font12 array(Translator.as), it just worked in my SWF.   Also I increase the default chinese size a little to make it suitable. 

![](https://github.com/beardad1975/scratch_doc/blob/master/Suggesting%20Chinese%20Default%20Font.png?raw=true)

This could solve the long default-font-size-problem for  Chinese both zh-ch and zh-tw.
( I believe I'm not the first reporter about this problem) 

So I sent a  [pull  request](https://github.com/LLK/scratch-flash/pull/1064)  to fix  this small but annoying problem.   Anybody could help the code merging or give me some other suggestions .
(I'm also a github newbie). Thank you .

**Comment by beardad1975** [comment]
#1064

**Comment by erichuang2013** [comment]
I have confirmed we do have font size issue in Scratch 2.0. Please consider to take this pull request to help students not to learn the tricky shift skill.

**Comment by thisandagain** [comment]
Resolved via #1064

**Comment by learnsite** [comment]
I think all language font size is 13,that can protect children's eyes

**Comment by liam4** [comment]
> I think all language font size is 13,that can protect children's eyes

*I* think that the language size setting should just be persistent. Then a parent or whoever can set the size of the font to whatever they want without worrying about their child/ren's eyes, because they know the font will always be big enough!
