### ISSUE TITLE
Chrome not rendering Arabic text right

### ISSUE THREAD

**Issue by adlogi** [LLK/scratch-flash#1075]
There's a problem with rendering Arabic (and Farsi) text on Chrome that persists regardless of the font size. The beginning of many words just don't show up. It wasn't like this before but I'm not sure when the problem started. Firefox renders the text well. For example:

![b1](https://cloud.githubusercontent.com/assets/2905644/14443642/3079ee54-0049-11e6-87e5-37aa2c9f86c8.png)

Chrome also adds colons in the blocks in the wrong place (an RTL thing?)

![b2](https://cloud.githubusercontent.com/assets/2905644/14443641/3078251a-0049-11e6-8308-06b4c1cf4212.png)

**Comment by Tymewalk** [comment]
Sounds like a problem with Chrome to me. Does Arabic render properly elsewhere with Chrome?

**Comment by adlogi** [comment]
Arabic seems fine outside the editor.

**Comment by thisandagain** [comment]
@cwillisf Adding this to your plate as it is related to the other L10N sizing issues you were exploring.

**Comment by cwillisf** [comment]
Looks like the Chromium team closed this as "wont-fix" a few months ago because they didn't have a repro case. I commented on the issue to offer our site as a repro case:
https://bugs.chromium.org/p/chromium/issues/detail?id=435195
