### ISSUE TITLE
How to compile source code of scratch ? and build scratch for my desktop pc by my own?

### ISSUE THREAD

**Issue by Maryam-Sonia** [LLK/scratch-flash#1078]
Kindly tell me i am working with it's source code and want to know that how can I build it in my pc ?

**Comment by liam4** [comment]
I'd suggest reading [this](https://scratch.mit.edu/discuss/topic/38970/).

**Comment by Maryam-Sonia** [comment]
Thank you for replying me but if I am using an IDE for compiling the source code then how can i do it?? which IDE i should use for ActionScript compilation? as before I was using Adobe FlashDevelop now I have installed FlashBuilder but the issue is same that is ;
After compiling succefully i cannot see the output ? where is the output window because it does not appear ? please if you can guide me..

**Comment by liam4** [comment]
I'm not sure how you'd do it with an IDE.. afaik all the Scratch devs use the command line.

**Comment by Maryam-Sonia** [comment]
but what is the use of shell script running tool when i am compiling it in IDE ?

**Comment by thisandagain** [comment]
Hi @Maryam-Sonia the majority of the Scratch Team uses the [IntelliJ IDEA IDE](https://www.jetbrains.com/idea/) when working with the `scratch-flash` codebase. Please refer to the `README.md` file for setup instructions.

**Comment by Maryam-Sonia** [comment]
Hi @thisandagain thank you for replying me. I will surely refer this.
