### ISSUE TITLE
The Offline Editor is not signed, leading to warnings from OS X and Windows

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-flash#1079]
Although the AIR package for the offline editor is signed using Adobe's tools, the executable is not signed at the operating system level. This makes installing and running the offline editor more painful than it should be and trains our users to ignore security prompts.

**Comment by liam4** [comment]
Fixed?

**Comment by cwillisf** [comment]
This didn't make it in time for this upcoming v447 release, but the v448 release will be digitally signed.
