### ISSUE TITLE
Enable drag-to-copy for Sprites

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1089]
Since we allow dragging to create a copy in the Backpack, it would seem to be consistent to allow it with Sprites as well.

Steps:
- Click on the backpack to open it.
- Click + drag a script or block into it.
- Click + drag the item you put into the backpack to the right, then release it.
- Note that a copy of the item should now appear next to your original backpack item.
- If you try this same procedure in the Sprite area, the Sprite will not be duplicated.

You can right-click on the Sprite and choose "duplicate" from the drop-down menu, so this does not impede functionality, but if a user gets used to dragging the items in the backpack, they might expect the same behaviour in the sprite area.

Version 445.2
scratch-flash: 2a019c6
scratch-flash-online: 015f4cc
Browser: Chrome Version 50.0.2661.86 (64-bit)

**Comment by TheLogFather** [comment]
It always felt to me as though the backpack behaviour was anomalous...?
