### ISSUE TITLE
Extended Sound Playing Blocks - Feature Request

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#1092]
Something I feel that would be useful and currently missing from Scratch is a block to begin playing back a sound from a given point.

Perhaps a block like this would do the trick?

```
Play Sound [name] from [seconds]
```

I'd also _really_ like a block like:

```
Play Sound [name] transposed by [semitones]
```

Just a thought! :)

Griffpatch

**Comment by TheLogFather** [comment]
Wow, really getting into the suggestions here today.. :)

Yup, again, requested many time in forums of course – and would be great to have! (I so wished for the first block in my "S.W.Ep.8 Vid-Player" project – so tedious splitting the soundtrack into 2s chunks...)

I think the second one has been requested in some form as a 'pitch effect' for sounds, and I quite like that idea – if a sprite/clone had a 'pitch effect' setting (just like it has a volume) then that would get applied to any sound it's currently playing, meaning you could dynamically change the pitch of sounds *while they are playing*. (Again, I so wished for this when I made my "pitch-bending attempt" project...)

**Comment by chooper100** [comment]
> Play Sound [name] from [seconds]

Nice, but I feel the naming is slightly ambiguous - some people could potentially think it means wait x seconds and then play the song.

> Play Sound [name] transposed by [semitones]

I'm not entirely sure how often this one would really be used. The naming isn't entirely clear when you consider that you can't see the parameter names in the blocks pallette but I guess that can be easily fixed:
`Play Sound [name] transposed by [number] semitones`

What I'd love to see is some block along the lines of
`Stop all sounds in this sprite`
