### ISSUE TITLE
Exhanced cursor key nudging in custume editor

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#1094]
Another fine feature in the costume editor would be to enhance the cursor key nudging to skip by x8 if shift is held down (I chose 8 because it would adhere to the pixel grid)

**Comment by chooper100** [comment]
If we are discussing improving the nudge feature, I think we also need to talk about the act that in bitmap currently you can nudge a selection by semi-pixels (which can be annoying when you are trying to line stuff up) even though it corrects itself onto the nearest pixel once you drop the selection
