### ISSUE TITLE
microphone recording not registering at first (Mac)

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1096]
I had a problem on my Mac recently where the Scratch Sound editor wouldn't record from the microphone in Chrome, even though microphone Input was responding in the Sound panel in System Preferences (and even after clicking "Allow" in Flash). 

I thought it was just my computer, but it happened on a Mac today at the Boys & Girls Club too.  Restarting Scratch (and/or Chrome) got it to work again.

Filing this issue though I haven't had a chance to try to reproduce yet. [Perhaps with Scratch open, trying to plug in an USB external microphone, choose it in Sys Prefs, and seeing if the Sound editor can record).

**Comment by jwzimmer** [comment]
I am able to use the (computer's) microphone to record new sounds on Scratch with Chrome and Safari. Project 107072124 has some sounds I recorded in both browsers.

@thisandagain Do you know if we have any USB external microphones that I could test with? Thanks.

**Comment by ntlrsk** [comment]
@jwzimmer The conference call speaker in the file drawer will work as a USB microphone. Thanks for checking it out.

**Comment by jwzimmer** [comment]
I am able to complete the following actions/ workflows when using an external USB microphone:
- Add new sounds when not signed in to Scratch.
- Those sounds are saved properly when I do sign in and I return to the project I started before signing in.
- Use those sounds in a script and save the script.
- Add new sounds when I am logged in as a New Scratcher.
- Add new sounds when I am logged in as an Admin/ Scratch Team Member (as my username).
- Use those sounds in a script.
- Add new sounds to an existing project.
- Add new sounds to a new project.
- Add new sounds in Safari and Chrome.

- I can also add new sounds without the external USB microphone (just using my Mac's built-in microphone) in Safari and Chrome.

The sounds play successfully through my headphones and through the computer's speakers.

**Comment by jwzimmer** [comment]
I can add new sounds with an external USB microphone and with the built-in microphone in Firefox as well.

I can add new sounds with an external USB microphone and with the built-in microphone in Chrome after newly-clearing my Chrome history.

**Comment by ntlrsk** [comment]
Thanks for checking this out so thoroughly @jwzimmer ! I guess we could close for now until we see again?

**Comment by ntlrsk** [comment]
Next time I will look to see if there's an error/exception in the browser.

**Comment by jwzimmer** [comment]
@ntlrsk No problem! I think closing for now makes sense, as does checking for errors in the browser if it's encountered again. I will also be keeping an eye out for it! : )
Thanks.

**Comment by jwzimmer** [comment]
Note: Just for clarity, this is being closed due to lack of repro. (If we see it again, we'll reopen.)
