### ISSUE TITLE
[Microworlds] do not display scroll bars in script pane in Microworlds view

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1097]
We think this may help avoid the pop-out look of the Script area in Microworlds. Will need to test it to make sure blocks don't go off screen without coming back.

![image](https://cloud.githubusercontent.com/assets/4721032/14915599/3f9cf79a-0de2-11e6-9b44-dbe39edfbbc8.png)

**Comment by bsb20** [comment]
Required changes to scratch-flash and scratch-flash-online:

https://github.com/LLK/scratch-flash-online/pull/274
https://github.com/LLK/scratch-flash/pull/1136
