### ISSUE TITLE
adding a backdrop to backpack sometimes not saving to backpack

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1098]
Dragging a backdrop into backpack - it appears, but when I open one of my other projects it's no longer in the backpack. 

However, if I make a change to that backdrop, then it does appear in the Backpack. 

Note: This is within a single tab of Scratch (with no other versions open).

I am able to reproduce from these steps:
1. Go to CeeBee's project:
https://scratch.mit.edu/projects/71968872/#editor
2. Click Backdrops tab. Drag "zig zag pattern" backdrop into Backpack.
3. Click My Stuff folder (top right of screen)
4. Open previously saved project  
5. Open backpack
The "zig zag pattern" doesn't appear in the Backpack for me.

**Comment by jwzimmer** [comment]
I was able to repro this following @ntlrsk's instructions. The backdrop doesn't appear to show up in my backpack when I am in the editor view of any of my projects. 

If I drag a block from one of my projects into my backpack, it is there when I access the backpack from another project, even if I didn't save the first project after altering the contents of the backpack. However, if I repeat these actions with a backdrop, it does not necessarily show up in the backpack from another project. Some of the behaviour is a little bit inconsistent, in that one of the backdrops I put in the backpack is now showing up, after opening and closing projects and backpacks for a while, but two others are not. But, following @ntlrsk's steps, I can consistently repro the issue as described.

Repro'd on Chrome Version 50.0.2661.94 (64-bit)
v446
scratch-flash: 3ed8b52
scratch-flash-online: 10bddb1
My Stuff page Site Version: 2.2.8_2016_04_28_11_49
