### ISSUE TITLE
make "go to random position" default menu item in palette

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1099]
make "go to [random position]" default value instead of "go to [mouse-pointer]"

since go to mouse-pointer doesn't do much unless in a forever loop
and go to random position is more often useful

(realizing that unfortunately this will disrupt some books and materials)

**Comment by thisandagain** [comment]
👍

**Comment by asweigart** [comment]
This would disrupt some books and materials. Also it is redundant: `go to x: pick random -240 to 240 y: pick random -180 to 180` does this.

However, I'd also say that it's not a common enough case. Many times when I want a sprite to move to a random place on the stage, going all the way to the end will often end up with half the sprite being off the stage and not visible. Or, I want to move the sprite randomly somewhere, but within a certain quadrant or half of the stage.

I'm conservative when it comes to adding new features to the editor. In this case, my recommendation is against a `go to [random position]` menu item.

**Comment by liam4** [comment]
> I'm conservative when it comes to adding new features to the editor. In this case, my recommendation is against a `go to [random position]` menu item.

So.. remove the `[random position]` dropdown menu item? I agree that it's redundant, but by removing it some newer projects that make use of it would be broken.

(for what it's worth, if I wanted a go-to-random-position block, I'd use a custom block - I think it'd be a good use case of custom blocks to the average Scratcher, were go-to-random-position not implemented.)

**Comment by asweigart** [comment]
Ah, my mistake. I didn't realize it had already been added.

**Comment by ntlrsk** [comment]
Hi @asweigart It's been added but inside the "go to mouse-pointer" block. We added it for new users because we found that inserting two "pick random" blocks within a "go to" block and knowing the x and y range to type in is cumbersome and not at all obvious.

**Comment by thisandagain** [comment]
@ntlrsk Is this something we should do in 3.0 or in your opinion should we prioritize a breaking change now?

**Comment by ntlrsk** [comment]
This can wait - thanks for checking and everyone's feedback.
