### ISSUE TITLE
Offline editor says "Save" while online says "Save now"

### ISSUE THREAD

**Issue by asweigart** [LLK/scratch-flash#1101]
In the offline editor, the menu items are "Save" and "Save as" while in the online editor the menu items are "Save now" and "Save as a copy". These should be made consistent.

If someone can point me to where the localization files are, I can submit a PR. I'm unable to find them by grepping through the repo.

**Comment by thisandagain** [comment]
@ntlrsk Any thoughts?

**Comment by ntlrsk** [comment]
I understand the desire for consistency, but the design team's thinking was to indicate that they do different things. For example, "Save as a copy" automatically renames and makes a new version online. In contrast, "Save as" offline acts just like "Download file to desktop" in the online editor. I realize it's not ideal, but may be important to flag that they're different.
