### ISSUE TITLE
Performance on Chromebooks

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1103]
As reported by Susan from SETC when using our Chromebooks:

When using the magic wand with the Chromebooks, half the time, the computers completely freeze up with photos.  We had to upload the photos several times before they would successfully be accepted by Scratch.

Then, once the photos were in Scratch, the magic wand was only functional some of the time.  The issue was that all of Scratch slowed to a crawl as soon as the photos uploaded.  We tried having one "fast computer" to edit the images and then put them in the backpack to be inserted through a remix, but that did not seem to help.  So about half the time, we had to resort to using the eraser and even that had lag times up to a minute for each stroke.  We tried making the photos very small before uploading, but that did not seem to help either.  So unless you use the library photos for the activity, it becomes almost impossible on the Chromebooks.  We also tried to decrease the size of the sound clips because we thought that might be a problem, but it did not seem to matter. 

Still, the youth had a LOT of fun with the activity.  The dance cards were really great, especially for youth who knew some Scratch already.

**Comment by ntlrsk** [comment]
Not sure if this can be solved - maybe just processor speed?

**Comment by griffpatch** [comment]
My core i7 pc running chrome often freezes up after each edit when working
with svg images. If I convert a full screen bitmap to svg then move it and
clone the bitmap to place them side by side then all edits have a second or
two delay, if I duplicate them up again I get a 4 or 5 second delay, it
gets worse and worse and can make life very difficult. And this is a very
fast pc. The graphics card however is very basic.

**Comment by thisandagain** [comment]
@ntlrsk This is one part processor speed and one part the Scratch technology stack. I don't see an easy solution to this in 2.0 but is most certainly related to some of the discussions we were having yesterday about the importance of support for lower-powered devices in general.
