### ISSUE TITLE
Problems compiling on Linux

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-flash#1104]
This is most likely something on my end, however, I'd still like to know how to fix it. Thanks :smile: 

**Steps**

  Downloaded the Flex 4.15.0 SDK from binaries.
  Added the 10.2 and 11.4 playerglobal.swc files into their proper locations (20.0 is also there.)
  Compiled Flex 4.15.0 successfully.
  Made a `local.properties` file which contained only `FLEX_HOME`.
  Cloned the latest commit as of this writing.
  Ran `ant`, and got this:

    Buildfile: .../scratch-flash/build.xml
    
    clean:
       [delete] Deleting directory .../scratch-flash/bin
    
    info:
         [echo] scratchFlashCommitID = e6df4f4-dirty
    
    compile-10.2:
        [mxmlc] Loading configuration file path_to_flex/frameworks/flex-config.xml
        [mxmlc] .../scratch-flash/src/scratch/ScratchStage.as(644): col: 19 Warning: Empty statement found where block of code expected. Did you type ';' accidentally?
        [mxmlc] 
        [mxmlc] 		if (Scratch.app.isIn3D) {
        [mxmlc] 		                ^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(89): col: 4 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			CModule.startAsync();
        [mxmlc] 			^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(398): col: 21 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			var imgPtr:int = CModule.malloc(workingData.length);
        [mxmlc] 			                 ^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(399): col: 26 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			var scribblePtr:int = CModule.malloc(workingData.length);
        [mxmlc] 			                      ^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(404): col: 4 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			CModule.writeBytes(imgPtr, workingData.length, workingData);
        [mxmlc] 			^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(405): col: 4 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			CModule.writeBytes(scribblePtr, scribbleData.length, scribbleData);
        [mxmlc] 			^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(410): col: 19 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			var func:int = CModule.getPublicSymbol("grabCut");
        [mxmlc] 			               ^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(412): col: 4 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			CModule.callI(func, args);
        [mxmlc] 			^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(451): col: 4 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			CModule.free(imgPtr);
        [mxmlc] 			^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(452): col: 4 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 			CModule.free(scribblePtr);
        [mxmlc] 			^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(417): col: 5 Error: Access of undefined property CModule.
        [mxmlc] 
        [mxmlc] 				CModule.readBytes(imgPtr, workingData.length, bmData);
        [mxmlc] 				^
        [mxmlc] 
        [mxmlc] .../scratch-flash/src/svgeditor/tools/BitmapBackgroundTool.as(22): col: 15 Error: Definition grabcut:CModule could not be found.
        [mxmlc] 
        [mxmlc] import grabcut.CModule;
        [mxmlc]               ^
        [mxmlc] 
    
    BUILD FAILED
    .../scratch-flash/build.xml:30: mxmlc task failed
    
    Total time: 36 seconds
    
Any idea what happened?

**Comment by Tymewalk** [comment]
I had problems building earlier due to me messing up the path to Flex.
Afterwards I re-cloned the entire thing and got the same error.

**Comment by TheLogFather** [comment]
See https://github.com/LLK/scratch-flash/issues/1011

**Comment by Tymewalk** [comment]
Thanks. I'm still having problems although it's due to something else, so I'll create a new issue for that.
