### ISSUE TITLE
Update README.md with new instructions

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-flash#1106]
I recently posted #1104 which had problems when compiling with `ant`.

I was told as per #1011 that you guys use `gradle` to build it now. However, README.md still says to use Ant.

This is really minor, although it can confuse anyone trying to build their own local copy.

EDIT: It's `./gradlew`, not `gradle`. #1107 was caused by this as well.

**Comment by kaschm** [comment]
Thanks! We just addressed this. Tracking in #1108
