### ISSUE TITLE
Sometimes uploads are truncated/ assets become corrupted (inconsistent)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1110]
The problem where corrupted assets caused projects to get stuck on loading/ load forever was fixed with [1085](https://github.com/LLK/scratch-flash/issues/1085), but the underlying cause of how those assets became corrupted is unknown.

This ticket is for documenting reports or incidences of corrupted assets, so hopefully we can figure out what is causing the assets to be corrupted.

=== User reported disappearance of 3 sprites and associated code ===

User reported via freshdesk ticket 47333 that in Project 108600921, 3 sprites disappeared (this may or may not be related to whatever caused the corruption of the assets in the projects in case #1085). The user did not have any idea why the sprites disappeared, but reported on Sunday night May 8th the project was fine, and on Monday May 9th the sprites had disappeared. 
I restored an earlier version of the project (the last one from Sunday night) to their My Stuff list as project ID 108998057.

**Comment by jwzimmer** [comment]
Projected loaded but all the code/ assets seemed to have disappeared, freshdesk ticket 47895.

**Comment by jwzimmer** [comment]
@cwillisf This may not be related, so feel free to remove, but I noticed a suspicious error on Sentry - I was just thinking that maybe some mismatch in timing between when the project is created and when it's edited could somehow cause corruption of the assets?

> DoesNotExist: Project matching query does not exist.
(8 additional frame(s) were not displayed)
...
  File "base_comments/views.py", line 46, in can_delete_comments_for_context
    return (self.get_deletion_type(comment_type, context_id, user) is not None)
  File "base_comments/views.py", line 50, in get_deletion_type
    return method(context_id, user)
  File "base_comments/views.py", line 53, in get_project_comment_deletion_type
    project = Project.objects.get(id=context_id)
  File "django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 334, in get
    self.model._meta.object_name

> https://scratch.mit.edu/site-api/comments/project/110269795/

> browser = Chrome 50.0; os = Windows 7; sentry:release = 2.2.8_2016_05_13_14_14

The project exists when I view it:
<img width="1230" alt="screen shot 2016-05-18 at 1 02 07 pm" src="https://cloud.githubusercontent.com/assets/1320456/15367892/fdf7204c-1cf8-11e6-9a24-9146e093c053.png">

**Comment by jwzimmer** [comment]
@cwillisf is there any chance this is related to: https://github.com/LLK/scratch-flash/issues/403?

**Comment by cwillisf** [comment]
@jwzimmer it's possible that this is related to #403... my guess is that we're seeing similar symptoms from the editor since the end result is similar (missing / bad costumes) but I think the underlying cause is different. The problems in #403 stemmed from the editor uploading data which didn't match the MD5 and/or file extension that the editor was claiming... the server now double-checks at least the MD5 and rejects an upload if it doesn't match.
Actually, we should double-check whether the truncated assets match the MD5 that the editor claims. That could help narrow down whether the truncation happens before or after the upload. Hmmmm...

**Comment by jwzimmer** [comment]
@cwillisf How do I check whether the truncated assets match the MD5 that the editor claims? Can I help with that? : )

**Comment by cwillisf** [comment]
I just put together a quick script and added it to our internal tools repository. It's called `check-asset-md5.sh` and there's a tiny bit of documentation at the top of the file. Feel free to move it if you can think of a better place for it to live :)

Anyway, if you watch a project load in the network tab of your browser, you'll see a bunch of things that end in `get/`. In some browsers you can type "assets" into a filter box to make this easier. They'll have URLs like `https://cdn.assets.scratch.mit.edu/internalapi/asset/09dc888b0b7df19f70d81588ae73420e.svg/get/`. If you want to double-check the server-side MD5 of such an asset, copy the `09dc888b0b7df19f70d81588ae73420e.svg` part from the middle and give it as an argument to `check-asset-md5.sh`.

Something like this (I faked these results but you get the idea):
```
$ ./check-asset-md5.sh 7e24c99c1b853e52f8e7f9004416fa34.png 09dc888b0b7df19f70d81588ae73420e.svg
7e24c99c1b853e52f8e7f9004416fa34.png: 7e24c99c1b853e52f8e7f9004416fa34 ok
09dc888b0b7df19f70d81588ae73420e.svg: 09dc888b0b7df19f70d81588ae73420e BAD
```

You can also feed the whole URL to `curl` and pipe the output through `md5sum` if you'd like... this might be quicker if you're doing a bunch of assets since you can copy the whole URL instead of grabbing a bit in the middle. Something like this:
```
$ curl "https://cdn.assets.scratch.mit.edu/internalapi/asset/09dc888b0b7df19f70d81588ae73420e.svg/get/" | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6635  100  6635    0     0  82423      0 --:--:-- --:--:-- --:--:-- 81913
09dc888b0b7df19f70d81588ae73420e  -
```

If the `09dc888b0b7df19f70d81588ae73420e` on the last line matches the corresponding part of the URL, then everything is OK. Otherwise, you've found a truncated or corrupted asset. That's basically what `check-asset-md5.sh` does, but it'll verify the MD5 for you.

**Comment by jwzimmer** [comment]
@cwillisf Okay, thank you. : )

I tried one of the original projects that were reported as unable to finish loading, and it worked (I saw a message saying one or more assets was unable to load, the rest of the project and scripts loaded). So that's good! I messaged the two users who had contacted us initially to tell them to try their projects, etc.

I got another issue in freshdesk (48539) from a user who reported their project was stuck on loading. They reported it on 5/21, so before we released the fix - I tried their project today, and it seems to be working, although with one version of it I did see the message about the corrupted assets: 112404338. (The project is unshared, so although I took a screenshot, I'm not going to put it in this case, since it's a public repo.) Including the project here in case it helps us figure out what was causing the original corruption issues. : )

**Comment by jwzimmer** [comment]
Project in freshdesk ticket 49353 could be related?
- Go to My Stuff
- Click on project ID 108737817 "See Inside"
- Note that you get frozen on full-screen view, but there is a tips window, and the project isn't fully loaded

**Comment by jwzimmer** [comment]
I'm moving this to the July milestone because we're kind of just adding to this case as evidence comes in, more than actively trying to repro it. @cwillisf Let me know if you don't think that's reasonable. : )

**Comment by jwzimmer** [comment]
Potentially relevant discussion on the forums: https://scratch.mit.edu/discuss/topic/205194/

**Comment by jwzimmer** [comment]
User reported various sprites & backdrops fail to load sometimes but will load other times:
> [This project] is pretty much my flagship project... However, I am having problems loading backgrounds, sounds, and costumes. When I load the project, some sprites and resources are just completely gone. The costumes and backdrops are blank, showing a size of 0x0. Normally, they load a little bit later. But recently, they haven't been loading in, and I can't tell whether or not they are loading in for other people. This is a major problem as many of the missing sprites are characters.

(See freshdesk ticket 51556)

I looked at the user's project, and noticed two assets seemed to have failed to load, sprite 19 and backdrop 12.

There was 1 404 error in the console. I also noticed one of the backdrops in my backpack had become a "question mark" again (I'm not sure when that happened).

<img width="1274" alt="screen shot 2016-07-12 at 3 49 52 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781476/81eaa4ac-4849-11e6-82a7-bd5aa116c4f4.png">
<img width="1279" alt="screen shot 2016-07-12 at 3 49 30 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781481/81ed9ae0-4849-11e6-845b-4bb800e71aac.png">
<img width="318" alt="screen shot 2016-07-12 at 3 49 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781480/81ece082-4849-11e6-9270-0b94cf0d719b.png">
<img width="1279" alt="screen shot 2016-07-12 at 3 48 29 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781478/81ec5e6e-4849-11e6-9f7a-55740ed5f44c.png">
<img width="571" alt="screen shot 2016-07-12 at 3 48 20 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781477/81ec23c2-4849-11e6-94a9-579f19563be8.png">
<img width="1047" alt="screen shot 2016-07-12 at 3 47 42 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781479/81eca11c-4849-11e6-8223-f69a232ce3e9.png">
<img width="218" alt="screen shot 2016-07-12 at 3 47 36 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781483/81f4d030-4849-11e6-95bf-2495bdac7769.png">
<img width="1280" alt="screen shot 2016-07-12 at 3 45 29 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781482/81f38d42-4849-11e6-87a2-069c421b0b29.png">
<img width="451" alt="screen shot 2016-07-12 at 3 44 31 pm" src="https://cloud.githubusercontent.com/assets/1320456/16781484/81f7768c-4849-11e6-921b-8e940e9f8825.png">

**Comment by jwzimmer** [comment]
@cwillisf: Backpack for my project 113240882 which has "backdrop 12" from the user's project 96409693 in it.

[{"type": "image", "name": "backdrop2", "md5": "61c7c21194ef0ef78ce3a6509b1aa237.png"}, {"width": 1, "md5": "cd21514d0531fdffb22204e0ec5ed84a.svg", "type": "image", "name": "backdrop12", "height": 1}]

**Comment by jwzimmer** [comment]
More "blank"-looking sprites:
https://scratch.mit.edu/projects/19204741/#editor
<img width="816" alt="screen shot 2016-07-19 at 4 36 54 am" src="https://cloud.githubusercontent.com/assets/1320456/16943594/758c528e-4d6a-11e6-917a-19aeb65765ba.png">

**Comment by thisandagain** [comment]
Moving to backlog and will track as part of the rollout for https://github.com/llk/scratch-projects

**Comment by jwzimmer** [comment]
From @ntlrsk:
> [User] reported that [their] project is missing assets - it looks blanked out. I had seen it earlier (probably a year ago) when it had a long song and a variety of other sprites:
[Ask me for the project ID, it is an unshared project.]
> Do you think it may be due to the asset/JSON limit change - or something else?

When I looked at the project, I noticed a blank "Costume backdrop12" just like in this project https://github.com/LLK/scratch-flash/issues/1110#issuecomment-232169147:
<img width="165" alt="screen shot 2016-08-18 at 1 44 26 pm" src="https://cloud.githubusercontent.com/assets/1320456/17784315/13f5e70e-654a-11e6-8e0c-8049b7d676f5.png">
When I dragged it out of the backpack, I saw it had 0x0 measurement:
<img width="156" alt="screen shot 2016-08-18 at 1 44 49 pm" src="https://cloud.githubusercontent.com/assets/1320456/17784316/14058b46-654a-11e6-924d-4b9c8228c84b.png">

**Comment by jwzimmer** [comment]
I tried to use @cwillisf's tool download_sb2.py to recover an earlier version of the project @ntlrsk reported in https://github.com/LLK/scratch-flash/issues/1110#issuecomment-240800978, but there was only 1 version in the version history, and when I uploaded that to my account on Scratch, it was the same blank version as is in the original unshared project.

The lack of version history reminds me of https://github.com/LLK/scratch-flash/issues/1148. (This account is not shared, however.)

**Comment by ntlrsk** [comment]
Thanks for investigating @jwzimmer ! It's too bad that the (unshared) project https://scratch.mit.edu/projects/112438908/ is missing - it's Mel King's original song project he's worked on over time.

**Comment by jwzimmer** [comment]
@ntlrsk I'm sorry we haven't recovered it... @cwillisf is there anything else we can do to recover the project(s)?

**Comment by cwillisf** [comment]
I'm very confused about how a project could end up with only one version in the version history according to `download_sb2.py`.

@thisandagain, do you have any guesses? That script just grabs all object versions in the `scratch2-projects` bucket with `Prefix=project_id`. It seems like the only way you could lose history there is either to change the project's ID number in our project database, disconnecting it from its existing history. I guess there's probably also a way to explicitly purge history from the bucket, but I expect that we probably don't use that...?

**Comment by jwzimmer** [comment]
@cwillisf it has happened at least a couple of times:
- This project had two versions, but they were both essentially blank projects https://github.com/LLK/scratch-flash/issues/1110#issuecomment-219458278
- With 114360338 from https://github.com/LLK/scratch-flash/issues/1148
- With 112438908 from @ntlrsk's comment

**Comment by jwzimmer** [comment]
Not sure if related, but missing data reported via freshdesk no. 55612:
> Dear Scratch Team, I'm hoping you can help me recover a project that I believe was corrupted by your web site. In the last week 28 sound recordings inside of two sprites and the backdrop were reduced to zero bytes. I can't think of anything I could have done to have caused to happen to all 13 recordings. I don't want to report a bug or a glitch. Because these were my only copy of these recordings, I'm asking you to look through your backups, snapshots, archives, or indexes to see if the original, non-corrupted, recordings can be found. My project is 104642026. The sprites with the corrupted sound recordings are Sprite1 and Sprite2. The last known date that this project was not corrupted was August 1. I would greatly appreciate it if you would forward my note to your IT department for their assistance in recovering these irreplaceable recordings. 

- User: [see freshdesk ticket]
- Operating System: MacOS Macintosh X 10.11.6
- Browser: Chrome 52.0.2743.116
- Flash Version: Flash 22.0 (release 0)

**Comment by jwzimmer** [comment]
Update re freshdesk 55612 (reported as new ticket 56035):
> The last known date that this project was not corrupted was 8/10 (I know I sent you this a few days ago, but then I realized I told you the wrong date).

I uploaded the largest & most recent version before 8/10/16 which was from 8/8/16 to the user's account as 119662825.

**Comment by jwzimmer** [comment]
I have not heard back from the reporting user for freshdesk no. 51556.

**Comment by jwzimmer** [comment]
A teacher reported student projects losing work in freshdesk no. 59179. It seems to be a shared account, so not sure if that could have contributed.
> I use Scratch with my students at school and today when we logged into our account to continue working all the students project were missing their sprites, they all had blank blue stages. The variables we had created were still there but no sprites so all the students code had gone! 

I asked for more info but have not heard back.

**Comment by jwzimmer** [comment]
Another report of this happening via freshdesk no. 59315:
> I went on my Mac to do my science project on Scratch, and I worked hard on it, but this morning, when I went to school and opened up a different computer, I pulled up my project and it was gone. All the backgrounds and scripts were totally deleted. But the thing is, the little clip on the front of the project, the thumbnail icon or whatever, showed a picture of a cat I drew when I last worked on the project, which proves that it didn't get totally deleted. However, even after I re-logged in, etc., the title (even though I changed it when I last worked on it) is still the same, and NOTHING is there. Is this a problem with Offline or something?
Please help, I have science today and my project is due. How do I fix this issue?

**Comment by jwzimmer** [comment]
Another example of projects getting `delbyusr` status without the user deleting them, and content going missing from the projects: https://github.com/LLK/scratchr2/issues/4167.

When I restored two of the projects (the two projects in the db that had `delbyusr` status for one of the users in that case), the teacher (reporting user) said that the student looked at the projects and they were not as she expected:
> That is not what the finished product looked like at all. The script is all jumbled and messed up [see other case for username]. She didn't erase this project because she was excited to show the class and then it was gone from her account. [See other case for username] had a simmilar problem with projects being gone.

**Comment by jwzimmer** [comment]
Example of project remaining unshared in My Stuff but all the work going missing from it (freshdesk no. 60400):
> I saved a scratch project in your systems called shimeji 1.0, and saved it, but the next day when I looked at it all of my work was gone, can you help because I spent a long time on it and I really, really want to have it back, and I guess your system had a problem because I saw the icon for my project but when I clicked it there was nothing there.... 

The project did have versions when I checked using the download_sb2 tool:
<img width="555" alt="screen shot 2016-10-20 at 10 54 35 am" src="https://cloud.githubusercontent.com/assets/1320456/19565568/3eaaf6a0-96b5-11e6-98b4-17d0e82862a2.png">

I uploaded the largest one as a new project for the user.

When I looked at the original project, the sprite was blank (asset corrupted) and there wasn't much scripting or any backdrops:
<img width="1096" alt="screen shot 2016-10-20 at 11 07 05 am" src="https://cloud.githubusercontent.com/assets/1320456/19565642/97a20b7c-96b5-11e6-9797-32a9d43df0a7.png">

**Comment by jwzimmer** [comment]
This user reported their student's work went missing (freshdesk no. 61145):
> I have a student working on a project and all the sprites that he created are now gone. Any suggestions on how to get it back?

**Comment by jwzimmer** [comment]
From freshdesk no. 65076:
A user wrote in describing accessing the project on two computers and on the computer that they had last used with an older version of the project, the new changes seeming to not exist. I was wondering if switching between the two computers could be causing the issue? The user asked the same question in a down-thread email.
> We have gone back and forth, working on their pc and on mine. 
The project is here: [133685718]
For the last two days, all the updates have been done on my PC. It was last used and updated around 8:20am PT on the morning of 12/03/2016. All the latest updates were in place at that time and the project looked good. 
Later this evening, my kids and I went back to their PC to view the project. It was the first time we had been back to their PC in several days. Upon opening it, the entire project seemed to revert back to how it was when we last looked at it there, with all the changes and updates we had made since then lost!!! We immediately tried to go back to my pc, but discovered that now, it too pulled back nothing but the old revision. (...)
> When it was ready, he was so excited to finally play it, he sprinted down to his machine to try it out for the first time, only to find that everything -the scoring system, his animations, the careful letter position, the dictionary lists...everything...had simply disappeared. (...)
> **An old, expired session shouldn't be able to overwrite more recent updates from a different machine.**

**Comment by jwzimmer** [comment]
Another example: freshdesk no. 64935.

**Comment by jwzimmer** [comment]
Another potential example: freshdesk no. 69529.

**Comment by jwzimmer** [comment]
Example project 140505888 from freshdesk no. 69529. (I think the projects may have been over or near the size limit?)

**Comment by jwzimmer** [comment]
Another potential example from freshdesk no. 68794, where it seems like switching between two computers may have caused the issue of an old version over-writing a new version (which we have seen before):
> I was working on a project for a really long time and it I also actively saved it (on Jan. 16 2017) but the next day, on a different computer that the one I had initially been working on, and all the progress was deleted, and it returned to an early save of the game (saved on Jan. 13 2017). What caused this and how can I save all the work I have done before?

**Comment by jwzimmer** [comment]
Another potential example from freshdesk no. 71036:
> I was working in a game on 2/6/17 and I saved it by pressing save. I went back to it today to put some finishing touches on it and it was all gone. What used to be 8 backdrops is now only 3 and what used to be 9 sprites is now 3. This is just the basis of what I did a week ago. This is for a school project and now I have to start all over.

**Comment by jwzimmer** [comment]
Another potential example from freshdesk no. 71176:
> I have been working on a school project witch is due tomorrow and i have logged in to my account to find the work i have done on the last two levels of my project is not longer there. I was unable to post on the discussion board this is why i am contacting you directly. I am hoping you can restore my lost work from 3pm GMT. my account name is (see ticket) and my project URL is (see ticket).

**Comment by jwzimmer** [comment]
Another example involving two computers from freshdesk no. 71524:
> I have been working feverishly on a scratch project in school. However, when I opened it yesterday, it had reverted back to one of the old versions. I have used the same computer to work on the project at home and school. Is there a way to restore my project? 

- Operating System: MacOS Macintosh X 10.11.6 
- Browser: Safari 9.1.2 
- Flash Version: Flash 24.0 (release 0)

**Comment by cwillisf** [comment]
The recent reports all seem to follow a particular trend: I was working on my project in two physical places and at some point my project reverted to a previous version. Freshdesk 71524 seems to be saying that they were using the same computer in both places, even.

For reference, the editor fetches a project JSON with a URL like this:
`https://cdn.projects.scratch.mit.edu/internalapi/project/${projectID}/get/${hash}`

The fact that the problem seems related to accessing the same project from multiple physical locations -- possibly even with the same computer -- makes me worry that this is a matter of different CDN nodes holding different, possibly stale versions of the project JSON. The editor tries to use a pseudo-cachebreaker token (`${hash}` above) to try to get around this problem but if that somehow fails then we'd be at the mercy of the CDN infrastructure.

Another possibility is related to the cachebreaker token itself. To generate this token, the editor hashes the `project_modifiedDate` supplied by the server. If the server supplies an incorrect (old) value, then the editor could reuse a hash which it used with an older version of the project and thus end up with a stale project JSON. I think this scenario is possible but less likely: I don't see why the server providing a stale `project_modifiedDate` would correlate with changing physical or network locations.

If the editor doesn't get a `project_modifiedDate` then it uses the hash of the current date & time. I don't think this is likely to cause problems.

@colbygk @thisandagain: any thoughts on the above?

**Comment by jwzimmer** [comment]
Potentially related? https://github.com/LLK/scratch-flash-online/issues/305

**Comment by thisandagain** [comment]
@cwillisf Both of these seem plausible to me (and in combination seem even more plausible).

Today, the project modified date is actually done via an asynchronous signal (this is fixed in the new project server) which can lead to a race condition which could cause stale a cache key.

If the cache key is stale (for any reason), then moving between physical locations could cause the user to move between CDN POP (https://www.fastly.com/network-map) locations which have different versions of the project JSON as we do not invalidate (purge) the existing project API or have a TTL.

The new project server should help resolve this by issuing a CDN purge on updates and more aggressively updating the modification stamp, but in the meantime I think I'd recommend the following:
- Double check our CDN configuration to make sure we have the backend connection limit set high enough
- Double check our CDN configuration to make sure we have "shielding" disabled for `cdn.projects.scratch.mit.edu`
- Double check our worker queue stats to make sure that project update signals are being triggered fast enough across the cluster

**Comment by jwzimmer** [comment]
Potentially related: https://github.com/LLK/scratch-flash/issues/1286

**Comment by cwillisf** [comment]
After some separate discussion with @jwzimmer, I'm removing the milestone to get this to triage to decide whether to implement @thisandagain's suggestions above and, if so, assign the work to someone.

**Comment by jwzimmer** [comment]
Another example: freshdesk no. 75936. The sprite & associated script disappeared from the project.

**Comment by jwzimmer** [comment]
Another example: freshdesk no. 77750:
> 154802780. Also, I'm not sure if this would make a difference but yesterday while I was working I opened the project on a friend's computer briefly, and it's possible I left the page open and it saved over it.

**Comment by jwzimmer** [comment]
An example with multiple computers involved, freshdesk no. 86200.

**Comment by jwzimmer** [comment]
An example of scripts & assets seemingly disappearing from a project: freshdesk no. 88650.

**Comment by jwzimmer-zz** [comment]
Potential examples:
- Freshdesk no. 105340
