### ISSUE TITLE
Uploading project sb2 file causes logout in editor

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-flash#1113]
Version: v446
OS: OSX 10.11.4
Browsers: Safari 9.1 (11601.5.17.1) and Chrome Version 50.0.2661.102 (64-bit)

Signed into account codubee, created new project, then attempting to upload a project .sb2 file: File→Upload
Select replace current project
Logged out of editor and unable to log back in.
Audio is also missing from uploaded project.

[![Signout issue on upload](https://img.youtube.com/vi/YWcGA-irNok/0.jpg)](https://www.youtube.com/watch?v=YWcGA-irNok)

**Comment by jwzimmer** [comment]
Trying to repro this issue - ongoing : )

Did not repro with:
- Sign in as jwzimmer1990
- Go to My Stuff
- Download an existing remix project as an sb2 file
- Go to Scratch homepage via logo in upper right
- Click on Create
- Upload sb2 file in editor
- Replace contents of current project
- Did not get signed out of editor, everything seemed as expected, sound Meow still worked

- Sign in using admintools as codubee
- Click on Create
- Upload sb2 file in editor (downloaded earlier today from jwzimmer1990)
- Replace contents of current project
- Did not get signed out of editor, everything seemed as expected, custom recorded sound still worked

- Sign in using admintools as codubee
- Click on Create
- Make a small project 1
- Download project 1
- Return to homepage
- Click on Create
- Make another small project 2
- Go to My Stuff
- Return to project 2
- Upload project 1
- Replace project 2 with project 1
- The uploaded project seems as expected, custom sound works (although it is displayed differently than it was when I first recorded it; stretched out twice as long)
<img width="1212" alt="screen shot 2016-05-16 at 10 20 37 am" src="https://cloud.githubusercontent.com/assets/1320456/15292281/5a851fc6-1b50-11e6-8e23-b215d1e20a96.png">
<img width="1170" alt="screen shot 2016-05-16 at 10 17 58 am" src="https://cloud.githubusercontent.com/assets/1320456/15292280/5a851698-1b50-11e6-8d24-0f821008e807.png">

**Comment by jwzimmer** [comment]
Could not (easily) repro in Safari either. Since I don't think this is a prio-high bug (given that it's not clearly happening often), I am not going to keep trying to repro this.

Safari Version 9.1 (11601.5.17.1)
- Signed into account codubee using admintools, 
- created new project via Create, 
- then attempted to upload a project .sb2 file: File→Upload (birthdaycat.sb2)
- Select replace current project
- Did not get logged out of editor - everything seemed fine.
