### ISSUE TITLE
Minimize assets in static/images/help 

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1115]
I will work with my team to make the animated gifs smaller in the help directory.

**Comment by kaschm** [comment]
@ntlrsk @juanita10 just wondering how you guys are doing with this? Will this be ready for the 23rd freeze date? thanks!

**Comment by ntlrsk** [comment]
I deleted a couple of the largest gifs for the last freeze, but we have more to go. Planning for Julio to work on it, so I changed to the following milestone - if that's OK.

**Comment by kaschm** [comment]
Sounds good, @ntlrsk. Thanks!

**Comment by ntlrsk** [comment]
@thisandagain Julio has dived into working on this and is making good progress. Do you have any guidelines for how small the gifs should be?

**Comment by thisandagain** [comment]
Follow-up from discussion in Slack and in-person:

- Hard to set a guideline for GIFs aside from "as small (and few) as possible". Just keep in mind that smaller = more accessible.
- We should use JPGs for any static (non-animated) images that have a large number of colors (e.g. photos)
- We should run all PNGs through an optimization algorithm. My favorite tool for this on Mac OS X is [ImageOptim](https://imageoptim.com/mac) which is free.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#3727

**Comment by juliomartin007** [comment]
Do you guys want the link for the folder that has everything I am working with?
If you want to check it out it's: https://drive.google.com/folderview?id=0B1C5rN_Rtha5eC16blJLakxyTHM&usp=sharing
