### ISSUE TITLE
extension boolean reporters not working offline

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#1117]
@cwillisf I'm not having any luck with the new Wedo2 tilt boolean reporter in 446 offline - should 'b' blocks get the isRequester treatment too?

https://github.com/LLK/scratch-flash/blob/a61593e5d7fbb17a243643c9fc769490d5aaaf9e/src/blocks/Block.as#L134

**Comment by cwillisf** [comment]
I think @cpseager is probably right: most likely Boolean reporters need to be converted to requesters in the offline editor. Built-in Boolean reporters should not be affected in the same way (see also #1067).

**Testing:** This can be tested with the WeDo 2.0 "tilted _ ?" block or the PicoBoard "sensor _?" block. Those are currently the only Boolean reporters in official extensions.

**Comment by jwzimmer** [comment]
**Repro'd!**

How I repro'd the tilted block not working correctly:
- Following directions on https://scratch.mit.edu/wedo
- Downloaded device manager from the Mac [App store](https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1084869222&mt=12)
- Upgraded to version 448 of scratch offline editor semi-manually (found https://github.com/LLK/scratch-flash-offline/issues/106)
- Following the steps in the Tips Window...
- Turned on Bluetooth
- I wasn't sure how to bring up the Scratch Device Manager (the icon didn't appear in my browser); I thought maybe I hadn't downloaded/ installed it correctly, but when I tried again from the scratch wedo page > open in app store, I got this:
<img width="781" alt="screen shot 2016-08-15 at 1 47 44 pm" src="https://cloud.githubusercontent.com/assets/1320456/17673481/51a87060-62ef-11e6-9906-0088f90559a2.png">
I don't know if that is the error message we're displaying for people who've already downloaded it or if something else is happening to cause it, but it's confusing...
- Searching for Scratch Device Manager in the Spotlight search bar brought the icon into my browser (Chrome) bar at the top right.
- The window with the wedo 2 and the Connect button opened
- I pressed the green button on the Wedo 2 and it paired with my computer
- I plugged in the tilted sensor
- I used two scripts to see if the tilted sensor would work:
<img width="420" alt="screen shot 2016-08-15 at 2 05 44 pm" src="https://cloud.githubusercontent.com/assets/1320456/17673973/771340da-62f1-11e6-874f-4d6d1d621473.png">
<img width="485" alt="screen shot 2016-08-15 at 2 05 30 pm" src="https://cloud.githubusercontent.com/assets/1320456/17673972/771128f4-62f1-11e6-8ffc-386d9660bb8f.png">
- The "When tilted any" hat block seemed to work as expected* (light changed every few seconds if I was tilting the sensor repeatedly, if I held it still and approximately level, it didn't change)
- The "if <tilted>" block did not work (nothing happened)

Steps to repro:
Use the Wedo 2 with the two scripts mentioned above.

*What to expect here was a bit confusing to me. I wasn't sure whether to expect the "when tilted any" block to kind of poll periodically, and if the sensor was tilted, to change the color, or to expect the color to change continuously while the block was tilted, or to maybe even expect it to change color if the block was tilted and in a new position from last time it was checked, or for the color to change when the block was in the motion of tilting, but when the block was still not to change color ("when tilted" could be interpreted as "when this is tilted" or "when this is being tilted")...
