### ISSUE TITLE
ArgumentError: Error #2015 - Project gets stuck on fullscreen view, no content, but tips window appears at the right

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1122]
In the JavaScript Console, @cwillisf and I both saw Error # 2015 repeated a lot of times (as long as the page was open, more error 2015's would appear).
On Sentry: https://app.getsentry.com/scratch-team/scratch-flash/issues/105167534/

In freshdesk ticket 49353, a user reported that their project does not load properly:

> The untitled 15 project is not loading properly. Can you please have a look at it as there was a long script and it now says it's empty.

Project ID is 108737817 (shared project).

Repro:
- Sign in as an admin
- Go to the project page directly via URL
- OR Go to the user's My Stuff page
- Click on the "See Inside" button for that project (Untitled 15)
- The project will load with a grey background and the tips window to the right side. You can open and close the tips window. The play and pause buttons don't seem to do anything.

I saw the project fail to load in Chrome Version 50.0.2661.102 (64-bit) (on a Mac). @cwillisf was able to repro the issue in IE 11 (on a Windows machine). The project loaded normally when I tried it in Safari (on a Mac) and when @cwillisf tried it in Edge and Chrome (on a Windows machine).

<img width="268" alt="screen shot 2016-06-03 at 2 56 48 pm" src="https://cloud.githubusercontent.com/assets/1320456/15790022/19a3fe5e-299d-11e6-8024-19ea796e5c84.png">

**Comment by jwzimmer** [comment]
I'm seeing this issue with another project, where the project gets stuck in full-screen mode with the tips window at the side, and otherwise won't load.
Project ID: 110776758

**Comment by jwzimmer** [comment]
@cwillisf Seems to be working now. I cannot repro in...
- Chrome 52 on Mac OS X El Capitan
- IE 11 on Win 7 VM
- Firefox 48 on Win 7 VM (although the editor is too small - known issue)
- Chrome 52 on Win 7 VM
- Firefox 48 on Mac OS X El Capitan

**Comment by yania** [comment]
I have the same problem with this Project 
https://scratch.mit.edu/projects/147511896/
In Windows 10, checked with Chrome and with Edge.
It is my son'sproject. The Project Works and suddenly start getting stucked this way.

**Comment by yania** [comment]
11:35:17 PM | err | TypeError: Error #1009
eval code (224) (1,7)
11:35:17 PM | err | TypeError: Error #1009
eval code (224) (1,7)
11:35:17 PM | err | TypeError: Error #1009
eval code (224) (1,7)
11:35:17 PM | err | TypeError: Error #1009
eval code (224) (1,7)
11:35:17 PM | err | TypeError: Error #1009
eval code (224) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:18 PM | err | TypeError: Error #1009
eval code (225) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:19 PM | err | TypeError: Error #1009
eval code (226) (1,7)
11:35:20 PM | err | TypeError: Error #1009
eval code (227) (1,7)
11:35:20 PM | err | TypeError: Error #1009
eval code (227) (1,7)
11:35:20 PM | err | TypeError: Error #1009
eval code (227) (1,7)
11:35:20 PM | err | TypeError: Error #1009
eval code (227) (1,7)
11:35:20 PM | err | TypeError: Error #1009
eval code (227) (1,7)
11:35:20 PM | err | TypeError: Error #1009
eval code (227) (1,7)
11:35:20 PM | err | TypeError: Error #1009
eval code (227) (1,7)

**Comment by yania** [comment]
Seems like infinite loop writing this "| err | TypeError: Error #1009
eval code (227) (1,7)" out to the console.
