### ISSUE TITLE
Gradle error while attempting to build

### ISSUE THREAD

**Issue by herohamp** [LLK/scratch-flash#1126]
- What went wrong:
  A problem occurred evaluating root project 'scratch-flash-master'.
  
  > Could not open no_buildscript class cache for script '/Users/hampton/Downloads/scratch-flash-master/scratch.gradle' (/Users/hampton/.gradle/caches/2.5/scripts/scratch_d4wpjxeqr8fjmx3b0fjlbgof3/DefaultScript/no_buildscript).
  > org/gradlefx/plugins/GradleFxPlugin : Unsupported major.minor version 51.0
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.212 secs

**Comment by liam4** [comment]
Downgrading to Java 7 fixed this for me, if I recall correctly.
