### ISSUE TITLE
Add `*.coding.me` to list of allowed domains for extensions

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-flash#1128]
`github.com` and `github.io` are blocked in China which results in Scratch Extensions not being available to a large number of our users. To work around this, we have a partner that would like to start porting some extensions over to Mandarin Chinese and hosting them via `coding.net` and their equivalent to `github.io` which is called `coding.me`.

[ExtensionManager.as](https://github.com/LLK/scratch-flash/blob/17e095682939f59163ee0a4806a71aa8603267fd/src/extensions/ExtensionManager.as)

/cc @cwillisf @kaschm

**Comment by kaschm** [comment]
:+1: this is great.
