### ISSUE TITLE
[microworlds] "Open in Scratch" button not opening consistently

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1129]
It's great to have the "Open in Scratch" button for the embedded microworlds projects.

So far it seems sometimes the 'Open in Scratch' button is working well for me, other times it isn't opening the project. Sometimes when logged in it prompts log in again. Other times it works fine.

Tried in Chrome and Safari and having similar issues. I haven't figured out consistently - not sure if it's related to server issues, so will try again tomorrow.  Thanks!

**Comment by jwzimmer** [comment]
Still trying to repro...

Microworlds pages:
- https://scratch.mit.edu/pathways/fashion/
- https://scratch.mit.edu/pathways/hiphop/

**Chrome Version 52.0.2743.82 (64-bit), Mac OS X El Capitan 10.11.6 (15G31)**
- Tried clicking the Open in Scratch button in fashion & hiphop projects while signed in as a teacher account; worked as expected (though kind of slow?)
- Clicked the button in fashion & hiphop while signed in as a mod (jwzimmer1990); worked as expected
- Clicked on button in fashion while signed out, pop-out asked me to sign in, I signed in as jwzimmer1990 and proceeded to my remix as expected
- I noticed if you click the button repeatedly, quickly, both the remix title comes up and a copy of that title... 
![out](https://cloud.githubusercontent.com/assets/1320456/17532021/a0f432b4-5e4c-11e6-8fbb-9dc8762c2c29.gif)

**Comment by ntlrsk** [comment]
Thanks @jwzimmer  "Open in Scratch" seems working well now for me too - so should we close this? Good point about not being warned that the changes aren't saved.

**Comment by jwzimmer** [comment]
As discussed with @ntlrsk, closing for lack of repro. : )

**Comment by jwzimmer** [comment]
Reopening because I didn't realize there are other microworlds than the two above, sorry about that...

**Comment by jwzimmer** [comment]
As discussed with @ntlrsk, closing in favor of https://github.com/LLK/scratch-www/issues/818. The open button in the two microworlds hosted on scratch (fashion and hiphop) seems to be working consistently. There is an issue with the button not working in www pages, which is addressed in https://github.com/LLK/scratch-www/issues/818.
