### ISSUE TITLE
Renaming of Lists

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1132]
Feature request from @AndersBillLinden, for consideration in Scratch 3.0.

Suggestion from https://github.com/LLK/scratch-flash/pull/640.

**Comment by AndersBillLinden** [comment]
https://github.com/LLK/scratch-flash/pull/640 is a pull request for functionality that implements this feature. How is that insufficient?

**Comment by jwzimmer** [comment]
@AndersBillLinden There's nothing insufficient with #640! We are not adding any new features to the scratch-flash repo right now, so we closed #640, but we want to make sure that the idea you're suggesting does get considered for our next major release, Scratch 3.0, so we created this case to keep track of your suggestion. Thank you! : )

**Comment by AndersBillLinden** [comment]
You closed the issue https://github.com/LLK/scratch-flash/issues/677 and opened this issue which is a copy of the other. What am I supposed to do now? Create a copy of my pull request?

**Comment by jwzimmer** [comment]
@AndersBillLinden Well, there's nothing more to do with this case, at this point. Eventually, the Scratch Team will go through all of these cases labelled "feature" in scratch-flash and decide what should get added as a new feature in Scratch 3.0.
If you want to work on submitting code to Scratch now, the best places to do that would be the repositories where we are actively developing new features... the scratch-blocks and scratch-vm repositories would be good places to check out. : )

**Comment by AndersBillLinden** [comment]
Sorry, you did not close that issue, my wrong. The person reporting it closed it.

**Comment by jwzimmer** [comment]
@AndersBillLinden No worries! Thanks for the time and effort you're putting into contributing to Scratch. : )
