### ISSUE TITLE
Wrong/Inconsistent costume order when using "Upload costume from file"

### ISSUE THREAD

**Issue by Tegmen** [LLK/scratch-flash#1134]
If you select multiple files in the file selector of "Upload costume from file", they get imported in a random (or at least inconsistent) order. 
For example import of a.png, b.png c.png might lead to a costume order b,c,a one time and a,c,b another time.
This behaviour is independent of OS (tried on Win 7, Win 10 and Ubuntu) and the way you select multiple files (shift-click or control-click).
IMO it would be best, if multiple files would get imported/ uploaded in alphanumeric order. This would make the creation of animations, fonts etc. much easier.

**Comment by griffpatch** [comment]
I second this! I was going to raise a lot for that very idea but didn't get
round to it

**Comment by Airhogs777** [comment]
I run into this all the time! I'd love to see this get fixed.

You may consider using [natural sort](https://en.wikipedia.org/wiki/Natural_sort_order) as well, it seems to be preferred for filenames

**Comment by griffpatch** [comment]
It would also be a lot easier to control the reordering of the costume
palette didn't scroll after dropping the costume you are repositioning. If
really wants to stay exactly where it was when you let go of the mouse.
