### ISSUE TITLE
Small editor (blocks, scripting area; everything except tips window) in Firefox & IE 11 on Windows OS

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1135]
**Repro**:
- Open Firefox in Windows (user reported the issue in Windows 10; I repro'd the issue in Windows 7 VM)
- Go to scratch.mit.edu
- Click Create
- (Or log in and choose a project from My Stuff, click See Inside)
- Note that the editor is tiny and squished looking, although the Tips Window is normal sized. The blocks and the scripting area, the backpack, the nav bar at the top; everything is small.
- There's also a small chunk of missing grey pixels in the top left of the Tips Window.

The size of the blocks and the other UI elements do make it pretty hard to use, so I think this could be prio-high (or prio-medium)?

Reported in freshdesk ticket 50388.

<img width="287" alt="screen shot 2016-06-13 at 5 23 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/16023713/135d1f02-318c-11e6-89fd-07856be9872f.png">
<img width="1279" alt="screen shot 2016-06-13 at 5 23 08 pm" src="https://cloud.githubusercontent.com/assets/1320456/16023716/1364d3be-318c-11e6-83db-67f8d4edb34b.png">
<img width="1277" alt="screen shot 2016-06-13 at 5 22 54 pm" src="https://cloud.githubusercontent.com/assets/1320456/16023715/1364c068-318c-11e6-9bef-5c1fbacefa68.png">
<img width="1278" alt="screen shot 2016-06-13 at 5 22 19 pm" src="https://cloud.githubusercontent.com/assets/1320456/16023714/135ff998-318c-11e6-8e63-5773cff765b5.png">

**Comment by jwzimmer** [comment]
The offline editor proportions also seem smaller in my windows VM (Win 7, IE 11):
<img width="1275" alt="screen shot 2016-06-22 at 3 08 03 pm" src="https://cloud.githubusercontent.com/assets/1320456/16279965/5ac08874-388b-11e6-9827-dfc9d640d68e.png">

Vs. the offline editor on my Mac OS X:
<img width="1279" alt="screen shot 2016-06-22 at 3 09 20 pm" src="https://cloud.githubusercontent.com/assets/1320456/16279964/5abfd104-388b-11e6-81fd-f7270e2d56ad.png">

**Comment by jwzimmer** [comment]
I also see the smaller editor in IE 11 on my Win 7 VM. If I zoom to about 200%, the editor looks "normal" in size.
100% in IE 11 on Win 7 VM (on my Mac):
<img width="1194" alt="screen shot 2016-07-11 at 5 14 26 pm" src="https://cloud.githubusercontent.com/assets/1320456/16747012/fdb11180-478a-11e6-9989-e26473c8502e.png">
200% in IE 11 on Win 7 VM (on my Mac):
<img width="1186" alt="screen shot 2016-07-11 at 5 14 08 pm" src="https://cloud.githubusercontent.com/assets/1320456/16747013/fdb73b64-478a-11e6-886b-7a8ec2c3108d.png">

**Comment by cwillisf** [comment]
My guess is that this is related to high-DPI displays, but I can't seem to repro it locally (Windows 10, high-DPI laptop).

@jwzimmer were you testing on a high-DPI display when you saw this?

My wild guess is that the "high-DPI" aspect isn't communicated through to the VM and it only hears that the display is high-resolution, but it certainly warrants further investigation.

**Comment by jwzimmer** [comment]
I was using:
[MacBook Pro (Retina, 13-inch, Early 2015)](https://support.apple.com/kb/sp715?locale=en_US)
13.3-inch (2560 x 1600)
Intel Iris Graphics 6100 1536 MB

**Comment by cwillisf** [comment]
@jwzimmer when you get the chance, could you check `window.devicePixelRatio` in a browser that's exhibiting this behavior? If it's 1 then we may not be able to do anything about it...
