### ISSUE TITLE
cloud data

### ISSUE THREAD

**Issue by edward789121** [LLK/scratch-flash#1138]
i am making a small mod of a scratch mod, can i have sum source to implement cloud data?

**Comment by thisandagain** [comment]
Hi @edward789121 thank you for your question. Our source code for cloud variables it not open source.

**Comment by edward789121** [comment]
ok!

**Comment by PolyEdge** [comment]
https://github.com/PolyEdge/scratchapi
https://github.com/trumank/scratch-api
