### ISSUE TITLE
Bitmap editor tool/image resolution mismatch

### ISSUE THREAD

**Issue by scratchteam** [LLK/scratch-flash#114]
<a href="https://github.com/griffpatch"><img src="https://avatars.githubusercontent.com/u/6737342?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [griffpatch](https://github.com/griffpatch)**
_Friday Feb 21, 2014 at 09:21 GMT_
_Originally opened as https://github.com/LLK/scratch-flash-common/issues/1346_

---

When editing images imported or converted to bitmap in the bitmap editor, the brush / eraser tools have a lower snap to pixel resolution than the image being edited? The same applies to the select (marquee) tool.

**Comment by 2jour** [comment]
@cwillisf was there a fix that went in for this iteration or was this fixed awhile back

**Comment by cwillisf** [comment]
Nothing in this iteration. If this comes up again we should look at #323 (linked above).
