### ISSUE TITLE
Pixelated text in online editor, looks like text from 1.4

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1140]
From freshdesk ticket 48539.

User reported that:
> I was working as usual, when the scrollbar wouldn't go somewhere. I was trying to refresh it, but it shared my project. I quickly unshared, and I tried to go into the editor. Suddenly, it wouldn't even go in!

(Meaning it was stuck on loading)
Then, after they experienced the above incident, in other projects (all their projects?) they noticed the text had changed to be pixelated and look like the old text from 1.4.

When I look at the user's project 112053635, I can see a screenshot of the pixelated text, but when I try to create a new variable or uncheck/ recheck an existing variable (e.g. Time), the block is not pixelated. I am not seeing any pixelated text, but the user still is. 

So we need to repro what circumstances they're seeing the pixelated text in/ what is happening. @cwillisf, I have no idea if this could be caused by https://github.com/LLK/scratch-flash/issues/1110 the asset corruption that caused the other stuck-on-loading projects or the fix to handling those errors?

Unshared project was stuck on loading (see the freshdesk ticket to see which project):
<img width="388" alt="screen shot 2016-06-15 at 2 53 30 pm" src="https://cloud.githubusercontent.com/assets/1320456/16093215/fc79ba56-3308-11e6-9adc-a2672ec0efdc.png">

Screenshot from user of pixelated text (in a shared project):
<img width="1085" alt="screen shot 2016-06-15 at 2 52 18 pm" src="https://cloud.githubusercontent.com/assets/1320456/16093168/d50d93ca-3308-11e6-9701-2181b2754d2b.png">

**Comment by cwillisf** [comment]
Regarding the pixelated text: I'm seeing this in Scratch in general (not just this project) when I use Chrome on my Windows 10 machine. I think it's a recent change to the version of Flash bundled in Chrome.

**Comment by jwzimmer** [comment]
There's a thread on Bugs & Glitches, a lot of people have encountered it, it looks like:
https://scratch.mit.edu/discuss/topic/204011/

Also, since you repro'd it, I'm going to remove the needs-repro label. : )

**Comment by cwillisf** [comment]
Initially I was thinking this should be a lower priority since it's only cosmetic, but if it's causing functionality problems then that's another story.
I saw in one of the Bugs & Glitches you linked that this may have started with 447.1 and not specifically with a Chrome Flash update. I'll look into that possibility... if that turns out to be the case, that may help explain what's going on and possibly even lead to a fix.

**Comment by cwillisf** [comment]
It looks like the Chrome team is working on this:
https://bugs.chromium.org/p/chromium/issues/detail?id=615375

**Comment by jwzimmer** [comment]
@cwillisf if it's not our bug, should we close this case? : )

**Comment by cwillisf** [comment]
Yeah, good point. I think closing this makes sense in this case since it looks like they're already working on it and there's nothing we can do in the mean time.
In other cases (#1075 for example) I think it makes sense to leave the issue open since we might be able to provide more information or otherwise expedite the fix...

**Comment by jwzimmer** [comment]
@cwillisf - I changed the milestone to June 23 instead of Backlog since backlog is like, unfinished stuff, and the time we spent on this case was during the June 23rd milestone... let me know if that's not how it should be categorized, though.  : )

**Comment by jwzimmer** [comment]
I responded to the threads [linked above](https://github.com/LLK/scratch-flash/issues/1140#issuecomment-226780653) to say that this appears to be a bug with Chrome and that the Chrome team seems to be looking into it.
