### ISSUE TITLE
Pen text block request

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#1142]
I think it would be worth considering adding a block to the pen category that renders text to the canvas.
- Positioning could use the current sprite location
- Size could be inferred from pen size perhaps (or a new set font size block)
- Font (if you want that) could come from a new block (set font), but you could default to the same font used in variable reporters?
- Colour would come from the current pen colour.

So then all you would need is: `text [hello world]`

A nice complement would be the reporter block: `<width of text [hello world]>`

Creating text engines while being a fun learning experience is past the skill of most basic scratchers, and operate too slowly for experienced scratchers. This could be used for many pen projects where any text output is required. There are many examples, but this project could work a lot faster with it: https://scratch.mit.edu/projects/113321949/

---

_I would point out that this would be even more useful if the pen layer was extended to allow us to either shift the pen layer to the front of the sprites, or draw to multiple pen layers ;) (just throwing these ideas out there)._

_One other text idea would be to add another variable reporter viewing mode (not just normal, large & slider) that is just the text without a background or border and perhaps centered instead of left aligned :) - of course empty strings would then prove to be a problem._

**Comment by thisandagain** [comment]
Thanks @griffpatch. Great timing. We are actively discussing options for "text" blocks for Scratch 3.0 and will keep this proposal in mind.

**Comment by griffpatch** [comment]
That's brilliant news. Is it worth me raising any other logs with feature
requests worth considering, or listing them briefly under a single log?

Things like closed polygons spring to mind?
And 'might' you consider that old idea of a checkbox in the sprite options
for 'allow off screen'? :) - Not having any natural way to get around that
is such a pain.
And lastly options to pause / stop particular sounds playing, or resume
from a specific point (in secs)

That sort of thing :)

**Comment by thisandagain** [comment]
Individual issues are best. Anything with the `feature` or `enhancement` (and of course bugs) labels are getting turned into design docs for discussion. Just let me know if you have anything else you think we should consider.

**Comment by thisandagain** [comment]
That said, we have those last two items already on the list!

**Comment by thisandagain** [comment]
Lastly, one thing that really helps is framing the feature or enhancement in terms of a use-case is really helpful for us. "I want to do this" is more helpful than "change x to do y".

**Comment by griffpatch** [comment]
Which part two? Specifically so I don't create duplicate loss? Thanks

**Comment by thisandagain** [comment]
- Considering ways to allow sprites to go "off screen"
- Reconsidering both the sound editor and sound blocks to allow more fine grained control over audio playback.

**Comment by joker314** [comment]
+ When sprites do go off screen, there should probably be a "reset to origin" button,

+ Feature request: pause/play sounds
