### ISSUE TITLE
Pen - Closed Polygons (suggested feature)

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#1143]
I might have suggested this before, but another feature that would extend the sort of projects creatable in scratch would be a closed filled polygon option in the pen tools. This would allow for much faster pen drawn games (not to mention 3d rendering).

I would imagine it would work akin to the pen down and up, but that at the last stage where you pen up it closes the polygon to the pen down location and draws it filled.

This could be done something like this:

```
set pen color [red]
go to 0,0
open polygon
go to 100,0
go to 50,100
close polygon [filled]
```

This would require two extra blocks, but might be less confusing than using the pen down and up and would save doing the extra drawing required before then drawing the pen lines. Also, you could then allow for things like:

```
set pen color [red]
go to 0,0
open polygon
go to 100,0
go to 50,100
close polygon [filled]
set pen color [blue]
close polygon [outline]
```

This might then draw a red polygon, and then outline it in blue. Although if allowing this kind of thing it might be better to reword the blocks to [define polygon] & [draw polygon [outline]]... maybe...

**Comment by Airhogs777** [comment]
This might be easier to understand as something more like a "fill" block that fills all connected areas of the same color.

**Comment by chooper100** [comment]
I think it has the potential to be slightly confusing with your implementation of filling a polygon and then another block drawing the outline.

(I would have expected the fill polygon block to reset the current polygon initially although you're implementation makes sense)

Anyway, I fear this might end up being one of the nice ideas that never gets implemented :(

**Comment by griffpatch** [comment]
I have played around with an alternative polygon filling idea, that is to draw a polygon like so:
```
go to x: (-50) y:(-50)
set pen color (66)
pen down
change y by (100)
change x by (100)
change y by (-100)
change x by (-100)
pen up and fill
```

The last block (the `pen up and fill`) closes the polygon and fills it. This requires all pen movements from the pen down to be recorded until a pen up or clear screen, etc is encountered. I don't think this is a very big overhead however. Also this also requires the outline of the polygon to be drawn beforehand using pen... which is a shame efficiency wise, but probably more understandable for Scratchers (and in reality still much faster that the mechanisms we are already using to draw polygons.)

To see this working in the Scratch Emulator go here: https://scratch.mit.edu/projects/113321949/
