### ISSUE TITLE
Pen Eraser - Feature Request

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#1145]
The pen layer is transparent, but the only way to remove what you have drawn is to clear the entire screen. This is drastic and slow if you then need to redraw everything, yet all you wanted to do was target a small area?

Thoughts:
- Add an eraser option to the pen drawing... Like drawing lines, except it draws setting the alpha channel to 0 and thus clearing the pen layer that it traverses over.
- Add a clear rectangle block like `clear to x: [x], y: [y]`. That clears a rectangular region between the current sprite location and the new x, y specified.  (in theory a fill rectangle to x,y would also be quite handy _grin_).
- A 3rd (and more generic option) would be to provide a clipping region block like `clip left [x] top [y] right [x2] bottom [y2]` which would then allow for the clear block to work as above but without any arguments, but has the added advantage that you can then also draw lines (and polygons / text if implemented) also clipped within a region. This would be amazingly useful for pen projects!!! But I understand that these kinds of features may be just too hard to understand for the target audience :(

**Comment by chooper100** [comment]
I think a "set pen to eraser" block would be the most intuitive here - I don't think many young scratchers would understand what "clip" means. It also gives people some more control over what they want to clear. However, I could see it needing some major reworking of the pen mechanics...

If you then combined this with #1143 then you could achieve the clear rectangle functionality you want with even more flexibility as well.
