### ISSUE TITLE
Dragging a backdrop into the backpack & refreshing causes it to be "zoomed in" - on scratchly

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1146]
Similar to https://github.com/LLK/scratchr2/issues/3720.

I set this as prio-high because (1) the backdrop loses the areas that aren't visible in the thumbnail when you drag it out of the backpack into a new project. Users can work around this (so I could maybe see an argument that this is prio-medium) by downloading and reuploading the backdrop but despite the workaround I think this issue non-trivially impedes the usefulness of the backpack re backdrops. (2) From talking to @cwillisf, it sounds like this may happen on production after deployment. However, if it doesn't happen on production, it's probably not prio-high.

**Repro:**
- Sign in on scratchly
- Go to a project
- Drag a backdrop with some pictures in it for scale into the backpack
- Refresh the page (or go to another project)
- Reopen the backpack
- Note that the image is larger/ re-centered; the bottom and right sides extend out of view. (It's like we zoomed in on the upper left quadrant.)
- When you drag backdrop out of the backpack into the project, it may be re-sized and have lost the edges that were off the edge of the screen (the bottom and right sides). It seems like this happens after... two refreshes? I'm not sure, I need to do more repro on it.

Noticed while testing https://github.com/LLK/scratch-flash-online/pull/272.

<img width="579" alt="screen shot 2016-06-17 at 4 27 46 pm" src="https://cloud.githubusercontent.com/assets/1320456/16164678/895b405c-34ad-11e6-8d65-140a6961fb51.png">
<img width="706" alt="screen shot 2016-06-17 at 5 10 22 pm" src="https://cloud.githubusercontent.com/assets/1320456/16164855/6a83eb92-34ae-11e6-8807-136c7cabf53e.png">

**You can see that the cut-off parts of the image aren't part of the backdrop anymore, even when you resize it**
<img width="1202" alt="screen shot 2016-06-17 at 5 27 03 pm" src="https://cloud.githubusercontent.com/assets/1320456/16165351/5890e068-34b1-11e6-8d49-e58d41f6f4cc.png">
<img width="1153" alt="screen shot 2016-06-17 at 5 32 41 pm" src="https://cloud.githubusercontent.com/assets/1320456/16165379/8c7f0788-34b1-11e6-88da-ffa2c5481ea1.png">

**Comment by jwzimmer** [comment]
Potentially blocking issue for https://github.com/LLK/scratch-flash-online/pull/272#issuecomment-226879521.

**Comment by jwzimmer** [comment]
Just to clarify, because I found this confusing when reading over these cases:
- https://github.com/LLK/scratch-flash-online/issues/277 is for the fact that the backdrops get bigger/ zoomed in when dragged **out** of the backpack
- This case is for the fact that the backdrops get bigger/ zoomed in when dragged **into** the backpack

**Comment by cwillisf** [comment]
Both of these issues are symptoms of the same problem in the code and should both be fixed by yesterday's changes (LLK/scratch-flash#1147 and LLK/scratch-flash-online#280). Sorry I missed closing this one when I merged those changes!
