### ISSUE TITLE
User unable to enter & submit answers to blocks after using block checkbox

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1151]
I'm not sure I understand what this issue is, but when trying to repro it hopefully it will become clearer.

User reported via freshdesk ticket 50377:

> I had been making a Webcam game, which needed the player to answer questions. But I, and other Scratchers found that typing and submitting answers wasn't quite working. I don't think it had to do with the coding, as it was happening for me in other games. It seemed that If I typed something in and clicked the blue tick button, I wouldn't be able to type in answers to any following questions. And, say if I was half way through a game, spotted a glitch and went to fix coding, it would mean that I would have to re-start the game from a certain point as I had clicked the screen to fix coding, which meant that I couldn't type anymore.
> 
> This is the one project which I remember having the bug, and is the project I originally spotted the bug in: 105777710. One of the users found trouble with it, but I'm not sure if it was his/her webcam, or the same glitch (the user was _see freshdesk ticket_)...

**Metadata:**
- User: _see freshdesk ticket_
- Operating System: Windows NT 10.0 
- Browser: Chrome 46.0.2486.0 
- Flash Version: Flash 21.0 (release 0)

**Comment by TheLogFather** [comment]
This is very likely due to their use of "set ghost effect to 100% / forever / go to front" in sprite 10.

This means there is an invisible sprite in front of the ask prompt the whole time, so it is impossible to click on the ask prompt to give it focus once that has been lost (since the click is 'eaten' by the invisible sprite).

**Comment by jwzimmer** [comment]
@TheLogFather Thanks for this theory, that is super helpful! : )

**Comment by TheLogFather** [comment]
I can replicate the problem simply by clicking on an "ask and wait" block, and then running that script.

Also, sprite16 does the same thing.

**Comment by jwzimmer** [comment]
@TheLogFather Great, thank you! : )
