### ISSUE TITLE
2D Lists (like 2D Arrays?)

### ISSUE THREAD

**Issue by Arinerron** [LLK/scratch-flash#1153]
Will there be 2-dimensional lists (like arrays) in Scratch? They'd be very useful for creating games, and would be a new learning opportunity and idea for lots Scratchers.

This is a List (3):

```
**List 1:**
apple
orange
kiwi
```

this is a 2D List (3x3):

```
**2D List 1:**
apple        grapefruit   grape
kiwi         orange       blueberry
bananna      lemon        huckleberry
```

This would be perfect for storing data like tiles and their locations in games, and could be used in lots of other projects.

**Comment by chooper100** [comment]
Whilst 2D lists would be good, if we're going down that route I'd much prefer a snap-style implementation with lists of lists (jagged arrays) for even greater flexibility :stuck_out_tongue:
