### ISSUE TITLE
Scratch offline 2.0 

### ISSUE THREAD

**Issue by elianabdelmajid** [LLK/scratch-flash#1155]
Hi

I just need some help to upload my own sprites files in my offline Scratch 2.0  via JSON files. 

Can someone help me to do it?

**Comment by thisandagain** [comment]
Hi @elianabdelmajid we use Github to track issues related to the development of Scratch itself. For questions on how to "hack" or use Scratch in new ways, please post questions to the "Advanced Topics" forum in Scratch:
https://scratch.mit.edu/discuss/31/
