### ISSUE TITLE
Zoom doesn't affect size of editor except for tip window - Firefox, Safari

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1161]
Changing the zoom setting also doesn't seem to effect the blocks in the editor (just the tips window):
![out](https://cloud.githubusercontent.com/assets/1320456/16746512/a4277f02-4788-11e6-99cf-47850ddda46d.gif)

Firefox 47.0.1, Mac, On Production

This also happens in Safari Version 9.1.1 (11601.6.17).

**Comment by jwzimmer** [comment]
IE 11 doesn't seem to have the issue where zooming doesn't affect block size or where zooming causes help to be incorrect; everything seems to work re IE 11 except that for the editor to look normal (in size) it has to be at about 200% zoom.

**Comment by ntlrsk** [comment]
@jwzimmer Good to document this. Zoom has never worked for Scratch 2.0 for the editor (except for tips which are HTML/Django versus Flash), and we had accepted that, so it would be good if there are ways to communicate that to Scratchers if/when it's causing issues.

**Comment by joker314** [comment]
The `onresize` event gets triggered when zoomed. I'm not sure if you want to, but if you did, you could use a hacky method to check if the page has been zoomed, and if so, pass a message to the flash player to zoom the blocks accordingly? Though I think that would just be unnecessary?
