### ISSUE TITLE
Hacked "When I Receive" block breaks broadcast blocks

### ISSUE THREAD

**Issue by NoMod-Programming** [LLK/scratch-flash#1162]
Due to the new "add to backpack" feature on the forums, hacked blocks are now possible for the average user. But this also adds problems. For example, add [this](https://scratch.mit.edu/discuss/post/2094796/) block to your backpack, and import it into scratch. You don't even need to change any of the values in the `join` block, just broadcast any message, and the broadcast block breaks. Due to the way that anyone can now import these blocks into scratch, it would be advisable to use `arg(` in order to evaluate it.

It's a one line fix for this block, by changing [line 584 of Interpreter.as](https://github.com/LLK/scratch-flash/blob/08d35a1edba3b39038b307050c37c51e83b0a6b6/src/interpreter/Interpreter.as#L584) from `if ((stack.op == "whenIReceive") && (stack.args[0].argValue.toLowerCase() == msg)) {` to `if ((stack.op == "whenIReceive") && ((arg(stack,0)).toLowerCase() == msg)) {`. I can't host a version right now, but I've tested it offline and it seems to work correctly.

**Comment by thisandagain** [comment]
We don't officially support "hacked" blocks so this is likely not something we will fix / resolve. The "Add to Backpack" feature may be something we should reconsider however.

/cc @rschamp @cwillisf

**Comment by TheLogFather** [comment]
With the above source change, it's no longer a 'hacked block'... problem solved! :D

Having said that, it's quite possible there are a couple of other changes would be needed to prevent exceptions, e.g. when showing the receiver block's dropdown menu and/or right/shift-click menu. But they're all straightforward enough.

TBH, I do think it's worth debating whether some of the constructs that currently require 'hacking' should be allowed in the editor itself. I think the behaviour of several of them are well enough defined and understandable to be worthwhile. (E.g. being able to drop an expression into left side of blue "_ of _" sensor block; into a "key _ pressed" boolean block; and even into a broadcast receiver, as in this case.)

**Comment by MegaApuTurkUltra** [comment]
I have to agree. Scratch in my opinion really has a problem with the "learning" curve being too high for making advanced projects. Yet you claim to have a "high ceiling." Some of the things LogFather is suggesting seem like easy changes, but have the potential to significantly lower the bar for what it takes for Scratchers to take their projects to the next level.

**Comment by quat1024** [comment]
After all you can do this *without* even having to use hacked JSON/"add to backpack", and it's even fully functional:

![](http://puu.sh/q7ac8.png)

So it's not too much of a stretch to say that you should be able to do this with broadcasts as well.

Whether it's *useful* or not is anyone's guess, but it sure is easier and more flexible to do this

![](http://puu.sh/q7aHw.png)

than this

![](http://puu.sh/q7aJd.png)

and the same applies to broadcasts.

**Comment by TheLogFather** [comment]
For the hacked 'when I receive' hat blocks, one thing I found was quite useful was using it to very easily target specific clones. (Some time ago, I made a version of Scratch which fixed this hacked receiver, as well as a few other things, so I could play with it.)

Being able to drop an expression into a receiver hat block means that you can use a local var in there, and then send a broadcast that only gets received by the clone(s) that has(/have) the local var set to the appropriate value. It felt somewhat more 'neat' than a clone ID local var.
