### ISSUE TITLE
My Class dropdown from Editor for Student Accounts goes to wrong URL

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1163]
(This wasn't tested prior to deploy because you would get signed out when you went to the editor on staging due to cookie issues.)

- Sign in as a student (tc2_student)
- Go to the editor
- Click on the dropdown by your username and choose "My Class"
- Note that the redirect URL is https://scratch.mit.edu/class/301/
- If you go elsewhere & click the dropdown from the navbar, the URL  for My Class will be https://scratch.mit.edu/classes/301/.

<img width="1074" alt="screen shot 2016-07-13 at 9 52 30 am" src="https://cloud.githubusercontent.com/assets/1320456/16805724/89cccab0-48df-11e6-95a6-c325c2371963.png">

Chrome, Production

**Comment by cwillisf** [comment]
@mewtaylor the editor just calls `JSredirectTo('myclasses')` in this situation, so I believe the fix will be in JS somewhere.

**Comment by mewtaylor** [comment]
@cwillisf thanks!
