### ISSUE TITLE
Dropdown menu from navbar opens behind tips window (very noticeable with languages other than English)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1164]
Chrome, Mac, on Production

@mewtaylor said this is an issue with layering of elements, since the tips window is an `iframe` on top of the editor, and potentially a complicated fix – because we’d be asking for the editor to simultaneously render both in front of and behind the `iframe`.

Steps to repro:
- Go to editor
- Click on the dropdown in the nav
- Note that when the language is set to English, the dropdown is more-or-less aligned with the tips window, but the shadow of the dropdown still goes behind the tips window
- Go to the homepage
- Change the language to another language, e.g. Asturian
- Go back to the editor
- Click on the dropdown in the nav
- Note that the dropdown is behind the tips window

<img width="173" alt="screen shot 2016-07-13 at 4 51 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/16824093/fcc5dde8-4936-11e6-8362-4b2f23ff455a.png">
<img width="183" alt="screen shot 2016-07-13 at 4 51 11 pm" src="https://cloud.githubusercontent.com/assets/1320456/16824092/fcc38d9a-4936-11e6-9f78-206ea564a309.png">
<img width="227" alt="screen shot 2016-07-13 at 4 50 41 pm" src="https://cloud.githubusercontent.com/assets/1320456/16824094/fcce4d02-4936-11e6-9a27-cbeb8168ee04.png">

**Comment by joker314** [comment]
Would making the dropdown an HTML element do the trick (while being easy enough to do?). That way you could set the z-index of the editor to be below the tips window to be below the dropdown?
