### ISSUE TITLE
Remove Khmer language

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1165]
Chrome, Mac, Production

Choose Khmer from the language dropdown on the homepage. Then go to the editor. Note that it looks like three kinds of script are being used for the blocks/ editor: English, Khmer, and another Asian language, potentially Japanese.

(I googled Khmer and Japanese to try and verify that the characters I'm seeing are from those two languages, but I do not know much about either language so I'm not 100% sure I'm describing this accurately.)

<img width="1277" alt="screen shot 2016-07-13 at 4 51 54 pm" src="https://cloud.githubusercontent.com/assets/1320456/16840615/a6a98a3c-49a3-11e6-8a3f-d9daa1155143.png">

**Comment by cwillisf** [comment]
This is an error in the translation file itself; the editor is just showing what's in the "km.po" file. My guess is that a translator accidentally uploaded a batch of strings to the wrong language.

**Comment by cwillisf** [comment]
@chrisgarrity are you the right person to handle this?

**Comment by chrisgarrity** [comment]
This file was corrupted between July and August 2013. Reloading the July 2013 file doesn't seem like a good idea. Also, there's no admin for Khmer on the pootle server. I can reach out to the two users that have made translations in Khmer, but I think they haven't been active for a long time because I think someone would have noticed the corrupted file.

In the meantime, I think we should remove khmer from the supported languages. As a result of the corruption the editor is essentially 0% translated.

**Comment by chrisgarrity** [comment]
@thisandagain @mewtaylor - Your thoughts? Is this a good reason to remove a language from the menu?

**Comment by thisandagain** [comment]
@chrisgarrity +1 on removing Khmer until we have an active / engaged translator for the language again.

**Comment by chrisgarrity** [comment]
I've contacted the Khmer translators and moved this into October iteration

**Comment by liam4** [comment]
On the topic of this..

I'm not sure how translation jobs are handled, but it might not be a terrible idea to add something along the lines of "Khmer Translator" to the openings..

**Comment by chrisgarrity** [comment]
@liam4 We actually have a couple of new translators for Khmer. They're students, so they're working on getting things translated, but it may take them a little while. When there's enough translated we can put Khmer back on the list. Thanks for your concern.

**Comment by liam4** [comment]
@chrisgarrity That's great! I don't know anybody who speaks Khmer personally, but I'm glad that there's people who are helping with getting it translated already.

**Comment by mewtaylor** [comment]
Removed in https://github.com/LLK/scratch-www/pull/973 – looking forward to getting it back on soon, thanks @chrisgarrity !
