### ISSUE TITLE
#1119 should initialise to _mouse_, not mouse-pointer

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1166]
This means that the "point towards mouse-pointer" block is not working when first dragged out from the block palette, until the menu item is selected again.

For example, see https://scratch.mit.edu/discuss/topic/208457/ and probably also https://scratch.mit.edu/discuss/topic/208622/
Was also reported in Bugs & Glitches forum here: https://scratch.mit.edu/discuss/topic/208762/

EDIT: The title doesn't create a reference, so adding this: #1119

**Comment by TheLogFather** [comment]
Enhancement? Isn't it more like a bug...? (I mean, at the moment, the block actually fails to work as it should, i.e. doesn't do anything, until the option is (re-)selected from the menu...)

**Comment by joker314** [comment]
So is #1179 correct?

**Comment by joker314** [comment]
So just to double check, `_mouse_` means the cursor, whereas `mouse-pointer` means a (usually nonexistant) sprite named `mouse-pointer` but it is impossible to tell this without viewing the JSON? I am curios then, what would happen if a user named a sprite `_mouse_`?

**Comment by TheLogFather** [comment]
IIRC, it used to just look for "mouse-pointer" (and "edge", and "Stage") in there. However, it was a reasonable thing to call a sprite "mouse-pointer" if you wanted to use it as some kind of cursor. But doing that caused things to break, so these special names were used instead, and (soon after) a restriction was added which means you cannot use any such name for a sprite.

Interestingly, there's still a bug with the blue "_ of _" sensor block left menu if you name a sprite "Stage"...

**Comment by david-sitsky** [comment]
I hope you fix this soon - I had a classroom of students who were following a scratch tutorial and we couldn't get past step 1 because of this very issue.  The workaround here works of course..

**Comment by TheLogFather** [comment]
This is regularly causing issues (even though easy to fix once someone actually complains about it), as evidenced in the forums even in the last day or so:
https://scratch.mit.edu/discuss/topic/215239/
https://scratch.mit.edu/discuss/topic/215146/

The patch, which has been ready for a while now (#1179), was simple and localised.
(Couldn't it have been included in the recent v449 release?)

**Comment by joker314** [comment]
Please review my PR whenever convinient (#1179). We were being taught Scratch, and the person sitting next to me experienced this bug. 

While that PR does do a lot, the only change that needs to be done is in Specs.as, the other stuff is optimisation and stuff
