### ISSUE TITLE
Misaligned fields in blocks with square fields

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1167]
Chrome Version 51.0.2704.106 (64-bit), Production

(~~If you look at the lower left corner & upper right corner of the square fields in some of the blocks, there are extra white pixels/ protrusions~~ --> whoops, nevermind, these are the frame around the field that have 3D shadow, not protrusions!)

The square fields seem to be closer to the bottom of the blocks than the top, rather than centered?

The single-digit entries in circular fields are slightly off-center, and the circular fields for numbers 2 digits or longer seem to be irregularly shaped (but it's hard to tell; I could be imagining that one).

<img width="326" alt="screen shot 2016-07-15 at 3 08 06 pm" src="https://cloud.githubusercontent.com/assets/1320456/16885734/02152ffc-4a9e-11e6-9e6e-1b866927a167.png">
<img width="414" alt="screen shot 2016-07-15 at 3 04 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/16885735/021a3268-4a9e-11e6-9a7e-0fb6bfdb903a.png">
<img width="180" alt="screen shot 2016-07-15 at 3 03 47 pm" src="https://cloud.githubusercontent.com/assets/1320456/16885736/0243531e-4a9e-11e6-9c3a-eee9b4ca4856.png">
<img width="169" alt="screen shot 2016-07-15 at 3 11 03 pm" src="https://cloud.githubusercontent.com/assets/1320456/16885812/624983fa-4a9e-11e6-8d4e-80eb2722a0c4.png">
<img width="184" alt="screen shot 2016-07-15 at 3 10 53 pm" src="https://cloud.githubusercontent.com/assets/1320456/16885813/624d8aa4-4a9e-11e6-84c4-cd9ca2d9ef98.png">
<img width="219" alt="screen shot 2016-07-15 at 3 12 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/16885849/9b4dc27e-4a9e-11e6-940c-e9b9830c50f6.png">

**Comment by kaschm** [comment]
This is the design of the blocks - going to close!
