### ISSUE TITLE
[CLOUD, HEADS UP] Cloud disconnecting about every 30s at the moment

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1168]
I also reported in forums (https://scratch.mit.edu/discuss/topic/208997/) but thought it'd be worth giving this exposure – hoping it can be fixed just by restarting some process somewhere!

Also see https://scratch.mit.edu/projects/96991584/ to test for fallback (which happens within ~30s all the time at the moment).

**Comment by TheLogFather** [comment]
Jusy FYI, here's a snippet from the log of one of my cloud clients (note the regular failure at roughly 30s intervals; all times are UTC)...

20:01:15.27:   ok  6673264
20:01:16.80:   ok  6673265
20:01:18.20:   ok  6673266
20:01:19.61:   ok  6673267
20:01:21.79: failed to get cloudvars for project 92748708?!
20:01:23.20: failed to get cloudvars for project 92748708?!
20:01:23.32: Session ok, just retrying cloud...
20:01:24.57: failed to get cloudvars for project 92748708?!
20:01:24.98:   ok  6673268
20:01:25.42:  Recorded failure at 20160715.200123
20:01:25.42:   ok  6673269
20:01:26.91:   ok  6673270
20:01:28.32:   ok  6673271
20:01:29.73:   ok  6673272
20:01:31.14:   ok  6673273
20:01:32.55:   ok  6673274
20:01:33.95:   ok  6673275
20:01:35.35:   ok  6673276
20:01:36.88:   ok  6673277
20:01:38.34:   ok  6673278
20:01:39.74:   ok  6673279
20:01:41.15:   ok  6673280
20:01:42.55:   ok  6673281
20:01:44.00:   ok  6673282
20:01:45.41:   ok  6673283
20:01:46.83:   ok  6673284
20:01:48.27:   ok  6673285
20:01:49.68:   ok  6673286
20:01:51.08:   ok  6673287
20:01:52.48:   ok  6673288
20:01:53.90:   ok  6673289
20:01:56.30: failed to get cloudvars for project 92748708?!
20:01:57.71: failed to get cloudvars for project 92748708?!
20:01:57.82: Session ok, just retrying cloud...
20:01:59.06: failed to get cloudvars for project 92748708?!
20:02:00.47:   ok  6673290
20:02:00.90:  Recorded failure at 20160715.200157
20:02:00.90:   ok  6673291
20:02:02.30:   ok  6673292
20:02:03.71:   ok  6673293
20:02:05.12:   ok  6673294
20:02:06.52:   ok  6673295
20:02:07.93:   ok  6673296
20:02:09.34:   ok  6673297
20:02:10.75:   ok  6673298
20:02:12.15:   ok  6673299
20:02:13.56:   ok  6673300
20:02:14.97:   ok  6673301
20:02:16.38:   ok  6673302
20:02:17.79:   ok  6673303
20:02:19.19:   ok  6673304
20:02:20.60:   ok  6673305
20:02:22.00:   ok  6673306
20:02:23.40:   ok  6673307
20:02:24.81:   ok  6673308
20:02:26.21:   ok  6673309
20:02:27.61:   ok  6673310
20:02:29.03:   ok  6673311
20:02:31.43: failed to get cloudvars for project 92748708?!
20:02:31.85: failed to get cloudvars for project 92748708?!
20:02:31.97: Session ok, just retrying cloud...
20:02:34.22: failed to get cloudvars for project 92748708?!
20:02:35.76: Session ok, just retrying cloud...
20:02:37.02:  Recorded failure from 20160715.200231 to 20160715.200235
20:02:37.02:   ok  6673312
20:02:37.52:   ok  6673313
20:02:38.92:   ok  6673314
20:02:40.39:   ok  6673315
20:02:41.88:   ok  6673316
20:02:43.29:   ok  6673317
20:02:44.70:   ok  6673318
20:02:46.14:   ok  6673319
20:02:47.56:   ok  6673320
20:02:48.96:   ok  6673321
20:02:50.37:   ok  6673322
20:02:51.91:   ok  6673323
20:02:53.31:   ok  6673324
20:02:54.71:   ok  6673325
20:02:56.19:   ok  6673326
20:02:57.60:   ok  6673327
20:02:59.00:   ok  6673328
20:03:00.41:   ok  6673329
20:03:01.90:   ok  6673330
20:03:03.31:   ok  6673331
20:03:04.72:   ok  6673332
20:03:05.51: failed to get cloudvars for project 92748708?!
20:03:06.99: failed to get cloudvars for project 92748708?!
20:03:07.10: Session ok, just retrying cloud...
20:03:08.35: failed to get cloudvars for project 92748708?!
20:03:09.75: failed to get cloudvars for project 92748708?!
20:03:09.86: Session ok, just retrying cloud...
20:03:11.12:  Recorded failure from 20160715.200307 to 20160715.200309
20:03:11.12:   ok  6673333
20:03:11.54:   ok  6673334
20:03:12.94:   ok  6673335
20:03:14.34:   ok  6673336
20:03:15.75:   ok  6673337
20:03:17.15:   ok  6673338
20:03:18.56:   ok  6673339
20:03:19.96:   ok  6673340
20:03:21.37:   ok  6673341
20:03:22.77:   ok  6673342
20:03:24.17:   ok  6673343
20:03:25.57:   ok  6673344
20:03:26.97:   ok  6673345
20:03:28.40:   ok  6673346
20:03:29.80:   ok  6673347
20:03:31.21:   ok  6673348
20:03:32.61:   ok  6673349
20:03:34.02:   ok  6673350
20:03:35.42:   ok  6673351
20:03:36.83:   ok  6673352
20:03:38.24:   ok  6673353
20:03:40.75: failed to get cloudvars for project 92748708?!
20:03:41.15: failed to get cloudvars for project 92748708?!
20:03:41.27: Session ok, just retrying cloud...
20:03:42.65: failed to get cloudvars for project 92748708?!
20:03:43.05: failed to get cloudvars for project 92748708?!
20:03:43.17: Session ok, just retrying cloud...
20:03:44.43: failed to get cloudvars for project 92748708?!
20:03:44.84:   ok  6673354
20:03:45.28:  Recorded failure from 20160715.200341 to 20160715.200343
20:03:45.28:   ok  6673355
20:03:46.68:   ok  6673356
20:03:48.08:   ok  6673357
20:03:49.48:   ok  6673358
20:03:50.88:   ok  6673359
20:03:52.29:   ok  6673360
20:03:53.73:   ok  6673361
20:03:55.18:   ok  6673362
20:03:56.58:   ok  6673363
20:03:57.97:   ok  6673364
20:03:59.38:   ok  6673365
20:04:00.79:   ok  6673366
20:04:02.19:   ok  6673367
20:04:03.59:   ok  6673368
20:04:04.99:   ok  6673369
20:04:06.39:   ok  6673370
20:04:07.79:   ok  6673371
20:04:09.22:   ok  6673372
20:04:10.65:   ok  6673373
20:04:12.05:   ok  6673374
20:04:13.46:   ok  6673375
20:04:14.87:   ok  6673376
20:04:15.37: failed to get cloudvars for project 92748708?!
20:04:15.77: failed to get cloudvars for project 92748708?!
20:04:15.89: Session ok, just retrying cloud...
20:04:18.16: failed to get cloudvars for project 92748708?!
20:04:18.57: failed to get cloudvars for project 92748708?!
20:04:18.69: Session ok, just retrying cloud...
20:04:20.38:   ok  6673377
20:04:20.80:  Recorded failure from 20160715.200415 to 20160715.200418
20:04:20.80:   ok  6673378
20:04:22.21:   ok  6673379
20:04:23.62:   ok  6673380
20:04:25.02:   ok  6673381
20:04:26.46:   ok  6673382
20:04:28.13:   ok  6673383
20:04:29.54:   ok  6673384
20:04:30.95:   ok  6673385
20:04:32.38:   ok  6673386
20:04:33.79:   ok  6673387
20:04:35.19:   ok  6673388
20:04:36.60:   ok  6673389
20:04:38.00:   ok  6673390
20:04:39.40:   ok  6673391
20:04:40.81:   ok  6673392
20:04:42.22:   ok  6673393
20:04:43.63:   ok  6673394
20:04:45.03:   ok  6673395
20:04:46.44:   ok  6673396
20:04:47.85:   ok  6673397
20:04:49.26:   ok  6673398
20:04:51.46: failed to get cloudvars for project 92748708?!
20:04:51.96: failed to get cloudvars for project 92748708?!
20:04:52.08: Session ok, just retrying cloud...
20:04:54.33: failed to get cloudvars for project 92748708?!
20:04:54.72: failed to get cloudvars for project 92748708?!
20:04:54.85: Session ok, just retrying cloud...
20:04:56.14:  Recorded failure from 20160715.200452 to 20160715.200454
20:04:56.14:   ok  6673399
20:04:56.55:   ok  6673400
20:04:57.98:   ok  6673401
20:04:59.38:   ok  6673402
20:05:00.78:   ok  6673403
20:05:02.19:   ok  6673404
20:05:03.59:   ok  6673405
20:05:05.07:   ok  6673406
20:05:06.47:   ok  6673407
20:05:07.88:   ok  6673408
20:05:09.28:   ok  6673409
20:05:10.78:   ok  6673410
20:05:12.19:   ok  6673411
20:05:13.60:   ok  6673412
20:05:15.01:   ok  6673413
20:05:16.41:   ok  6673414
20:05:17.82:   ok  6673415
20:05:19.23:   ok  6673416
20:05:20.64:   ok  6673417
20:05:22.06:   ok  6673418
20:05:23.46:   ok  6673419
20:05:24.87: failed to get cloudvars for project 92748708?!
20:05:25.27: failed to get cloudvars for project 92748708?!
20:05:25.38: Session ok, just retrying cloud...
20:05:26.64: failed to get cloudvars for project 92748708?!
20:05:27.04: failed to get cloudvars for project 92748708?!
20:05:27.19: Session ok, just retrying cloud...
20:05:28.45: failed to get cloudvars for project 92748708?!
20:05:28.86: failed to get cloudvars for project 92748708?!
20:05:28.99: Session ok, just retrying cloud...
20:05:32.37:  Recorded failure from 20160715.200525 to 20160715.200528
20:05:32.37:   ok  6673420
20:05:32.80:   ok  6673421
20:05:34.22:   ok  6673422
20:05:35.66:   ok  6673423
20:05:37.06:   ok  6673424
20:05:38.46:   ok  6673425
20:05:39.87:   ok  6673426
20:05:41.28:   ok  6673427
20:05:42.71:   ok  6673428
20:05:44.12:   ok  6673429
20:05:45.52:   ok  6673430
20:05:47.03:   ok  6673431
20:05:48.44:   ok  6673432
20:05:49.85:   ok  6673433
20:05:51.25:   ok  6673434
20:05:52.66:   ok  6673435
20:05:54.06:   ok  6673436
20:05:55.47:   ok  6673437
20:05:57.02:   ok  6673438
20:05:58.42:   ok  6673439
20:05:59.89:   ok  6673440
20:06:01.36: failed to get cloudvars for project 92748708?!
20:06:02.76: failed to get cloudvars for project 92748708?!
20:06:02.87: Session ok, just retrying cloud...
20:06:04.13: failed to get cloudvars for project 92748708?!
20:06:04.53: failed to get cloudvars for project 92748708?!
20:06:04.64: Session ok, just retrying cloud...
20:06:05.91:  Recorded failure from 20160715.200602 to 20160715.200604
20:06:05.91:   ok  6673441
20:06:06.33:   ok  6673442
20:06:07.74:   ok  6673443
20:06:09.14:   ok  6673444
20:06:10.54:   ok  6673445
20:06:11.94:   ok  6673446
20:06:13.34:   ok  6673447
20:06:14.76:   ok  6673448
20:06:16.25:   ok  6673449
20:06:17.65:   ok  6673450
20:06:19.05:   ok  6673451
20:06:20.50:   ok  6673452
20:06:22.11:   ok  6673453
20:06:23.65:   ok  6673454
20:06:25.05:   ok  6673455
20:06:26.46:   ok  6673456
20:06:27.87:   ok  6673457
20:06:29.27:   ok  6673458
20:06:30.68:   ok  6673459
20:06:32.09:   ok  6673460
20:06:33.49:   ok  6673461
20:06:34.90: failed to get cloudvars for project 92748708?!
20:06:35.30: failed to get cloudvars for project 92748708?!
20:06:35.43: Session ok, just retrying cloud...
20:06:36.70: failed to get cloudvars for project 92748708?!
20:06:38.19: failed to get cloudvars for project 92748708?!
20:06:38.31: Session ok, just retrying cloud...
20:06:40.60:  Recorded failure from 20160715.200635 to 20160715.200638
20:06:40.60:   ok  6673462
20:06:41.02:   ok  6673463
20:06:42.42:   ok  6673464
20:06:43.86:   ok  6673465
20:06:45.26:   ok  6673466
20:06:46.67:   ok  6673467
20:06:48.07:   ok  6673468
20:06:49.47:   ok  6673469
20:06:50.88:   ok  6673470
20:06:52.29:   ok  6673471
20:06:53.69:   ok  6673472
20:06:55.09:   ok  6673473
20:06:56.54:   ok  6673474
20:06:57.98:   ok  6673475
20:06:59.47:   ok  6673476
20:07:00.87:   ok  6673477
20:07:02.30:   ok  6673478
20:07:03.78:   ok  6673479
20:07:05.18:   ok  6673480
20:07:06.58:   ok  6673481
20:07:08.06:   ok  6673482
20:07:09.56:   ok  6673483
20:07:10.43: failed to get cloudvars for project 92748708?!
20:07:10.90: failed to get cloudvars for project 92748708?!
20:07:11.01: Session ok, just retrying cloud...
20:07:12.27: failed to get cloudvars for project 92748708?!
20:07:13.68: failed to get cloudvars for project 92748708?!
20:07:13.79: Session ok, just retrying cloud...
20:07:15.45:   ok  6673484
20:07:15.87:  Recorded failure from 20160715.200711 to 20160715.200713
20:07:15.87:   ok  6673485
20:07:17.30:   ok  6673486
20:07:18.81:   ok  6673487
20:07:20.21:   ok  6673488

**Comment by TheLogFather** [comment]
Still seeing this.

Also, cloud logs for many projects are looking distinctly sparse...

**Comment by CosmicWebServices** [comment]
@TheLogFather This may hurt one of the projects I am working on but maybe this is not a bug

**Comment by TheLogFather** [comment]
Seems to be something a little different going on now – like a 'short' failure ~20s after connecting, before the 'longer' failure about 10s later.

This is when it started appearing in the output log (~1310UTC):


13:09:38.60:   ok  6706175
13:09:40.05:   ok  6706176
13:09:41.46: failed to get cloudvars for project 92748708?!
13:09:41.86: failed to get cloudvars for project 92748708?!
13:09:41.97: Session ok, just retrying cloud...
13:09:43.23: failed to get cloudvars for project 92748708?!
13:09:43.63: failed to get cloudvars for project 92748708?!
13:09:43.74: Session ok, just retrying cloud...
13:09:45.00:  Recorded failure from 20160716.130941 to 20160716.130943
13:09:45.00:   ok  6706177
13:09:45.41:   ok  6706178
13:09:46.90:   ok  6706179
13:09:48.31:   ok  6706180
13:09:49.72:   ok  6706181
13:09:51.12:   ok  6706182
13:09:52.52:   ok  6706183
13:09:53.92:   ok  6706184
13:09:55.34:   ok  6706185
13:09:56.74:   ok  6706186
13:09:58.15:   ok  6706187
13:09:59.54:   ok  6706188
13:10:00.95:   ok  6706189
13:10:02.38:   ok  6706190
13:10:03.92:   ok  6706191
13:10:05.97: Session ok, just retrying cloud...
13:10:07.93: Session ok, just retrying cloud...
13:10:09.82: Session ok, just retrying cloud...
13:10:14.32:  Recorded failure from 20160716.131005 to 20160716.131009
13:10:14.32:   ok  6706192
13:10:14.76:   ok  6706193
13:10:16.16: failed to get cloudvars for project 92748708?!
13:10:16.56: failed to get cloudvars for project 92748708?!
13:10:16.68: Session ok, just retrying cloud...
13:10:18.13: failed to get cloudvars for project 92748708?!
13:10:18.52: failed to get cloudvars for project 92748708?!
13:10:18.63: Session ok, just retrying cloud...
13:10:19.88:  Recorded failure from 20160716.131016 to 20160716.131018
13:10:19.88:   ok  6706194
13:10:20.29:   ok  6706195
13:10:21.70:   ok  6706196
13:10:23.10:   ok  6706197
13:10:24.51:   ok  6706198
13:10:26.01:   ok  6706199
13:10:27.44:   ok  6706200
13:10:28.87:   ok  6706201
13:10:30.35:   ok  6706202
13:10:31.82:   ok  6706203
13:10:33.25:   ok  6706204
13:10:34.66:   ok  6706205
13:10:36.06:   ok  6706206
13:10:37.46:   ok  6706207
13:10:38.86:   ok  6706208
13:10:40.26:   ok  6706209
13:10:41.55: Session ok, just retrying cloud...
13:10:43.31: Session ok, just retrying cloud...
13:10:45.08: Session ok, just retrying cloud...
13:10:48.47:  Recorded failure from 20160716.131041 to 20160716.131045
13:10:48.47:   ok  6706210
13:10:48.89:   ok  6706211
13:10:50.30: failed to get cloudvars for project 92748708?!
13:10:50.70: failed to get cloudvars for project 92748708?!
13:10:50.83: Session ok, just retrying cloud...
13:10:52.10: failed to get cloudvars for project 92748708?!
13:10:52.50: failed to get cloudvars for project 92748708?!
13:10:52.61: Session ok, just retrying cloud...
13:10:53.87: failed to get cloudvars for project 92748708?!
13:10:54.27: failed to get cloudvars for project 92748708?!
13:10:54.39: Session ok, just retrying cloud...
13:10:57.76:  Recorded failure from 20160716.131050 to 20160716.131054
13:10:57.76:   ok  6706212
13:10:58.17:   ok  6706213
13:10:59.66:   ok  6706214
13:11:01.06:   ok  6706215
13:11:02.46:   ok  6706216
13:11:04.10:   ok  6706217
13:11:05.52:   ok  6706218
13:11:06.92:   ok  6706219
13:11:08.32:   ok  6706220
13:11:09.73:   ok  6706221
13:11:11.12:   ok  6706222
13:11:12.57:   ok  6706223
13:11:13.97:   ok  6706224
13:11:16.22: Session ok, just retrying cloud...
13:11:17.97: Session ok, just retrying cloud...
13:11:19.75: Session ok, just retrying cloud...
13:11:23.21:  Recorded failure from 20160716.131116 to 20160716.131119
13:11:23.21:   ok  6706225
13:11:23.65:   ok  6706226
13:11:25.06: failed to get cloudvars for project 92748708?!
13:11:25.46: failed to get cloudvars for project 92748708?!
13:11:25.58: Session ok, just retrying cloud...
13:11:26.84: failed to get cloudvars for project 92748708?!
13:11:27.35: failed to get cloudvars for project 92748708?!
13:11:27.46: Session ok, just retrying cloud...
13:11:28.70: failed to get cloudvars for project 92748708?!
13:11:29.11: failed to get cloudvars for project 92748708?!
13:11:29.23: Session ok, just retrying cloud...
13:11:32.69:  Recorded failure from 20160716.131125 to 20160716.131129
13:11:32.69:   ok  6706227
13:11:33.12:   ok  6706228
13:11:34.53:   ok  6706229
13:11:35.93:   ok  6706230
13:11:37.40:   ok  6706231
13:11:38.80:   ok  6706232
13:11:40.24:   ok  6706233
13:11:41.64:   ok  6706234
13:11:43.05:   ok  6706235
13:11:44.45:   ok  6706236
13:11:45.87:   ok  6706237
13:11:47.42:   ok  6706238
13:11:48.85:   ok  6706239
13:11:50.26:   ok  6706240
13:11:51.40: Session ok, just retrying cloud...
13:11:53.17: Session ok, just retrying cloud...
13:11:54.92: Session ok, just retrying cloud...
13:11:58.28:  Recorded failure from 20160716.131151 to 20160716.131154
13:11:58.29:   ok  6706241
13:11:58.69:   ok  6706242
13:12:00.09: failed to get cloudvars for project 92748708?!
13:12:00.49: failed to get cloudvars for project 92748708?!
13:12:00.60: Session ok, just retrying cloud...
13:12:01.86: failed to get cloudvars for project 92748708?!
13:12:02.39: failed to get cloudvars for project 92748708?!
13:12:02.50: Session ok, just retrying cloud...
13:12:03.75: failed to get cloudvars for project 92748708?!
13:12:04.16: failed to get cloudvars for project 92748708?!
13:12:04.29: Session ok, just retrying cloud...
13:12:07.64:  Recorded failure from 20160716.131200 to 20160716.131204
13:12:07.64:   ok  6706243
13:12:08.05:   ok  6706244
13:12:09.45:   ok  6706245
13:12:10.85:   ok  6706246
13:12:12.45:   ok  6706247
13:12:13.88:   ok  6706248

**Comment by joker314** [comment]
Interesting. On me and Icy's project bridgevar-js, we are taking advantage of Cloud Data, however, it appears it isn't working as of now, due to a Socket being closed while we are trying to pulse a cloud var at regular intervals. The pulse is every 50 secs so I can't pinpoint which, if any, of those two are the problem.

Thanks so much for looing into this @TheLogFather

**Comment by TheLogFather** [comment]
It's now gone back to disconnecting after 30 secs.

@joker314: If you're changing the pulse cloudvar after an interval of 50s, then it will always fail at the moment, since the cloud connection is only lasting 30s.

**Comment by TheLogFather** [comment]
Cloud is still misbehaving a lot (and the 'short' failure is back).

The cloud logs are clearly showing some oddities. For example, looking at https://scratch.mit.edu/cloudmonitor/96491582/ I see many gaps (it should increment the cloudvar every few seconds), as well as multiple entries. :/

**Comment by thisandagain** [comment]
Thanks. I'll take a look today.

**Comment by liam4** [comment]
June 23rd milestone..?

**Comment by CosmicWebServices** [comment]
yep

**Comment by thisandagain** [comment]
@TheLogFather This should now be resolved. Thank you for raising it.

**Comment by CosmicWebServices** [comment]
👏

**Comment by joker314** [comment]
Yay!

**Comment by TheLogFather** [comment]
👍

**Comment by bwbw223** [comment]
👏
