### ISSUE TITLE
Right mouse button/ right click does not work

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1181]
Reported via freshdesk no. 54172.

> The right mouse button seems to periodically not work while working on a project online. I've tried several browsers and am coming across the same problem. The issue is definitely not on my hardware or browser - Right clicking anything else (via the web or local) and the right mouse key works fine. 

Metadata: 
- User: (see freshdesk no. 54172)
- Operating System: Windows NT 10.0 
- Browser: Chrome 52.0.2743.82 
- Flash Version: Flash 22.0 (release 0)

**Comment by chooper100** [comment]
I feel that more information is needed before this can be reproduced.

For example, there are several issues with right click and it is not certain which one the user is describing:
- Right click bringing up browser flash context menu over scratch context menu
- Right clicking for variable watchers on the stage sometimes seems to miss them even when the mouse is over them (particularly noticed this when the watchers are in slider mode)
- Having a browser zoom at something not equal to 100%
- Right clicking scripts whilst in small screen mode with horizontal scroll sometimes misses them

Those are issues I've experienced at least but the workarounds are easy enough so they aren't particularly high priority

(There are probably documented issues for each of those but I can't be bothered to find them :stuck_out_tongue: )

**Comment by jwzimmer** [comment]
@chooper100 Thank you for this information, it's really helpful! : )

**Comment by jwzimmer** [comment]
I have not heard back from the reporting user for about 24 days, and the issue they reported is probably too vague for us to do much with without more information. However, the issues @chooper100 brings up should be repro'd and tracked (if they aren't already) so I'm not closing this case yet.

**Comment by jwzimmer** [comment]
Re the issues @chooper100 brought up:
- Right click bringing up browser flash context menu over scratch context menu
  - https://github.com/LLK/scratch-flash/issues/523
  - https://github.com/LLK/scratch-flash/issues/572
  - Getting the wrong menu: https://github.com/LLK/scratch-flash/issues/466
  - https://github.com/LLK/scratch-flash-offline/issues/110
- Right clicking for variable watchers on the stage sometimes seems to miss them even when the mouse is over them (particularly noticed this when the watchers are in slider mode)
  - Right click being "off" from where the mouse is: https://github.com/LLK/scratch-flash/issues/632
  - https://github.com/LLK/scratch-flash/issues/552
- Having a browser zoom at something not equal to 100%
  - https://github.com/LLK/scratch-flash/issues/1160
- Right clicking scripts whilst in small screen mode with horizontal scroll sometimes misses them

I opened a new case for "Right clicking scripts whilst in small screen mode with horizontal scroll sometimes misses them" since I didn't see a case that seemed like it could cover that issue --> https://github.com/LLK/scratch-flash/issues/1209.

So I think the known issues here are all now being tracked, and the original issue reported is too vague to repro. So I'm closing this case.
