### ISSUE TITLE
"Point towards" block consistently doesn't work in project

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-flash#1182]
In the first project, the <point towards mouse> block works as intended and the ladybug sprite continuously follows the mouse pointer. In the second project, the <point towards mouse> block doesn't work in the same way as the player sprite does not continuously follow the mouse pointer.

First:
https://scratch.mit.edu/projects/20683586/#editor

Second:
https://scratch.mit.edu/projects/117096711/#editor

The way to 'reset' the block is simply to pick the 'mouse-pointer' from the dropdown again in the second project, then it magically works again:
![screen shot 2016-08-08 at 5 38 07 pm](https://cloud.githubusercontent.com/assets/782228/17497322/50062974-5d8f-11e6-954e-c1046641f190.png)

**Comment by tmickel** [comment]
maybe the same as https://github.com/LLK/scratch-flash/issues/1166 ?

**Comment by kaschm** [comment]
Totally the same as https://github.com/LLK/scratch-flash/issues/1166. Closing.
