### ISSUE TITLE
Projects stopped working without any code being changed

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1183]
Reported via freshdesk no. 54744.

> Roughly 1 month ago these four projects of mine stopped working properly: 
An Eventful Adventure (the platformer part not working): 103794003
Avoid The Fire: 16201998
Avoid The Fire 2: 16840341
Avoid The Fire 3: 41537454
I haven't changed the code in any of those projects recently so I'm guessing it's an update to Scratch that has caused this problem. All projects use costume sizes larger than 480x360, I think this may have something to do with it... 
I'd appreciate it if you could look into it. 

Metadata: 
- User: (see shared projects or freshdesk ticket)
- Operating System: Windows NT 10.0 
- Browser: Chrome 52.0.2743.116 
- Flash Version: Flash 22.0 (release 0)

I don't know if there's any relation, but the sudden stop in working and the mention of large costumes reminded me of https://github.com/LLK/scratch-flash/issues/1177.

**Comment by TheLogFather** [comment]
Yup, very likely due to #1127 since they all have costumes wider than 2048 pixels.

See above link for more discussion of the problem, as well as https://scratch.mit.edu/discuss/topic/208322/.

**Comment by jwzimmer** [comment]
@TheLogFather Thank you!

**Comment by jwzimmer** [comment]
As discussed with @cwillisf, this issue was caused by https://github.com/LLK/scratch-flash/pull/1127. We are closing this issue since we're no longer supporting costumes/ sprites with sides > 2048 pixels. I emailed the reporting user via freshdesk to let them know.
