### ISSUE TITLE
User with large project is getting "network not connecting" error when trying to save

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1187]
Reported via freshdesk no. 55086. The project in question is unshared, so please see the freshdesk ticket or ask me for the project ID, username, etc.

Initial message:

> I am working on a Scratch project that is time sensitive, but anyways, I have tried to save a huge project multiple times (we're talking [3000+] scripts, [400+]\* sprites), but it doesn't matter where I try in terms of physical location. This particular project can't save and the saving part times out. It has not reached the 50 mb size limit, so I would like to know how I can save this project online.

Content from follow-up messages:

> What I see when I keep adding code is the image attached.
> The window keeps on prompting me repeatedly and the weird thing is, when I close the browser window to try to reopen it, the browser does not prompt me about whether I want to lose the changes without saving. 
> I tried downloading and attempting to open it up in the offline Scratch 2.0 editor, but it never works out. 
> I also tried fixing this project at a different IP location, but this issue keeps on appearing with this project. 

Image from user:
<img width="351" alt="screen shot 2016-08-16 at 4 49 44 pm" src="https://cloud.githubusercontent.com/assets/1320456/17715460/2b9a2830-63d2-11e6-897f-f57420b05210.png">

The project is about 14.5 MB. I was able to download it to my computer, then re-upload it to Scratch offline editor v 448 and Scratch website (unshared; then I deleted it). I was able to add scripts to it and save it on the website. It did take a long time to load in both places. While it was loading to the Scratch website, I saw both of these several times:
<img width="316" alt="screen shot 2016-08-16 at 4 40 21 pm" src="https://cloud.githubusercontent.com/assets/1320456/17715686/4f7f96da-63d3-11e6-97ce-7814f5dc8543.png">
<img width="444" alt="screen shot 2016-08-16 at 4 39 57 pm" src="https://cloud.githubusercontent.com/assets/1320456/17715687/4f85c4ba-63d3-11e6-8175-f2aa6e54d08c.png">
However, it did eventually load.

**I was using Chrome 52, Mac OS X El Capitan, Production to try to repro the issue.** 
The reporting user was using:
- Operating System: Windows 8.1 
- Browser: Chrome 52.0.2743.116 
- Flash Version: Flash 22.0 (release 0)

**Comment by chooper100** [comment]
I was under the impression that the size limit was just 10 MB (or was it that the json file had a limit of 10 MB and the total project with all the assets had to be less than 10 MB?)

If that is the case, try to find out the file size of the json alone (this is particularly significant if the user has any lists with 5000+ items as it is a known issue that list contents get duplicated internally - see #587 )

**Comment by jwzimmer** [comment]
@chooper100 I believe the user is getting the [50 MB limit from this page of the wiki](https://wiki.scratch.mit.edu/wiki/Project_Compression) or [this page](https://wiki.scratch.mit.edu/wiki/Is_there_a_file_size_limit_for_a_project%3F), etc.

**Comment by jwzimmer** [comment]
Another user reported getting "Server Error: No Response" when uploading an ~15 MB project file, via freshdesk no. 54970.

> I have recently worked on a big project, and as far as I know, here are big projects too. Although, there is one thing that annoys me. I had finished my project and every time I try to upload it, it fails. It says "Upload failed, Server error, no response". Of course I have tried uploading another projects, and it worked, the only thing I don't get is... this. It would be very nice if you had an answer to this, if not, I'll be continueing to upload the project.
> Also, is there a limit of space for the games? My game is around 15MB big and it always says this:
<img width="122" alt="screen shot 2016-08-17 at 10 04 56 am" src="https://cloud.githubusercontent.com/assets/1320456/17739171/3835055c-6462-11e6-879b-a2cced61d426.png">

- Operating System: Windows NT 10.0 
- Browser: Firefox 47.0 
- Flash Version: Flash 22.0 (release 0)

**Comment by cwillisf** [comment]
Regarding FreshDesk #55086:

I'm not sure what's going on here. The total project size is about 16 MB, or about 14 MB when compressed, so total project size isn't the problem. The project JSON is about 2.3 MB and otherwise the largest item in the project is a 360 KB sound, so it doesn't seem likely that they're hitting the asset size limit either. I was able to load, remix, edit, and resave the project without any errors, though the editor was definitely struggling with such a large project. I also saw some of the "not responding" messages you mentioned, @jwzimmer, but I didn't get the "Project not saved!" dialog.

Suggested next steps:
- Can we get more info about what sort of changes cause the problem?
- Are there any error messages in the browser's JavaScript console after the problem happens?

Regarding FreshDesk #54970:

This seems like a different problem to me, but it's hard to say from just this info. If we can get a project ID or an SB2 file I'd be happy to investigate further. I'd also be curious to know whether they see any error messages in their JS console.

**Comment by thisandagain** [comment]
> The project JSON is about 2.3 MB

I think that is the problem. We only accept project.json files that are less than 2 MB.

**Comment by cwillisf** [comment]
@thisandagain: wow, really? Is that new? I thought the JSON was subject to the 10 MB limit as well. For example: https://github.com/LLK/scratch-flash/issues/587#issuecomment-201415862

**Comment by jwzimmer** [comment]
@cwillisf, from the reporting user:
> I am not sure, but I think it may have to do with memory size. 
> I tried adding smaller scripts and shortening a list and saving worked.

**Comment by thisandagain** [comment]
@cwillisf I think we added that quite a long time ago to resolve issues with large JSON files causing the project upload server to choke while attempting to run `JSON.parse`.

**Comment by cwillisf** [comment]
@thisandagain ah, I think I remember hearing some of that discussion in meetings / standup.
@jwzimmer that seems consistent with @thisandagain's hypothesis: shrinking scripts and lists would directly decrease the size of the `project.json`.
Overall I think this basically means that FreshDesk 55086 is a vote for #1188.

**Comment by TheLogFather** [comment]
@thisandagain: 2MBytes seems unlikely (unless it's somehow compressed...?)
I have several projects with one or more variable values that contain way more data than that (e.g. as referenced above by @cwillisf), and they are included in the json.

**Comment by TheLogFather** [comment]
OK, just tried to create remixes of above projects, and neither of them would save.

I guess this means there could indeed be a 2MB limit, and that it was imposed fairly recently...?

:(

**Comment by thisandagain** [comment]
@cwillisf @jwzimmer Confirmed. We have a limit of 2.5 MB for the JSON body payload sent to the project upload server. This was implemented in January after we saw a spike in errors from the flash client and performance / scalability issues with the upload server's project parse method.

#### Current Implementation
https://github.com/LLK/scratch-file-upload-manager/commit/ddfd40c54e027cc3deb9d60ac75d6e54ac21b6ff

#### New Server Implementation (in testing)
https://github.com/LLK/scratch-projects/blob/develop/server.js#L21

**Comment by jwzimmer** [comment]
Closing this because the failure is due to the size of the project JSON, a limit we intentionally imposed. (I may open a new case for freshdesk no. 54970 after discussing with @cwillisf.) We need to communicate better to users what the size limits are and when they are encountering them in a project, and what steps they can take to remediate the issue (see #1188).

**Comment by TheLogFather** [comment]
Guess that means nobody can remix any such project, and any attempt to edit one (accidentally or otherwise) will result in failure to save. (Could it possibly even lead to project corruption under some circumstances?)

**Comment by jwzimmer** [comment]
(Reopening because there's still conversation happening on this issue, and I don't want to cut off anyone's questions.)

**Comment by TheLogFather** [comment]
(Oops! Sorry about that – came through as closed just as I was clicking the comment button...)

**Comment by jwzimmer** [comment]
(@TheLogFather No need to apologize, I don't want to close anything prematurely and your questions and input are great to have! : ) )

**Comment by TheLogFather** [comment]
Having said that (the extra edit to above comment), I have a feeling that what may happen sometimes is that the project just never stops showing the 'Saving...' text at top right, and the user eventually gives up and clicks away to a different page, thereby losing all changes.

Still, that's probably more related to the questions around showing some sensible warning/error message, and that's effectively already covered in other issues.

Still, it could be a bit odd that it seems there are (or were?) occasions when it doesn't (didn't?) show that 'network failure / failed to save' message/dialog, hence not giving any kind of clear chance for the user to save to local disk. (I'll have a go over the next few days and see if I can still get it to do that – it's possible it's only under specific circumstances it happens like that, if it still does at all?)

**Comment by jwzimmer** [comment]
@TheLogFather Sounds good. : )

**Comment by jwzimmer** [comment]
@cwillisf looking over this case again, I noticed that the user's project JSON was about 2.3 MB, but the limit seems to be 2.5 MB... sorry if this has already been covered, but wouldn't that make their project under the size limit? : \

**Comment by cwillisf** [comment]
My guess is that the 2.3 MB JSON is the largest one that successfully saved, then further modifications pushed it over the 2.5 MB limit and those versions failed to save. That said, 200 KB is kind of a lot of data to add to the JSON in one session. I wonder if there's a bit of [MB vs MiB](https://en.wikipedia.org/wiki/Mebibyte) going on here or something like that.

**Comment by jwzimmer** [comment]
@cwillisf Should we look into whether MB vs. Mebi is an issue, or further into this in general? If so, I can reopen (for the 3rd time lol). : )

**Comment by cwillisf** [comment]
@jwzimmer I just looked at the "current implementation" that @thisandagain linked to [earlier in this thread](#issuecomment-240710918), and it is indeed written as `2.5 * 1000 * 1000` bytes, meaning that a 2.3 MiB JSON is a little closer to the limit than I had thought. I don't think we have to do anything special for this other than to make sure that we use the same limit for the implementation of #1188.

**Comment by jwzimmer** [comment]
@cwillisf Hmm okay. So the current limit is 2.5*1000*1000 but the new limit (in testing) is 2.5*1024*1024, right... So our current theory is that the user's project was slightly more than 2.3*1024*1024 = 2411724.8 bytes,  enough more than 2.3 to push it over the 2500000 byte limit, but if it's less than 2621440 bytes, it will work again under the new implementation, is that right?

**Comment by cwillisf** [comment]
@jwzimmer Oops, I didn't notice that the new version implemented it differently. I think your description is accurate, yes... assuming that the changes they try / were trying to make put the JSON in between 2500000 and 2621440 bytes.

**Comment by jwzimmer** [comment]
@cwillisf Okay, cool, thanks. I think we're good to leave this closed then. We should make sure we're really clear with the unit of the limits in #1188. : )

**Comment by jwzimmer** [comment]
Note: got project (118472725) for freshdesk no. 54970. The user was eventually able to upload it to the website. The project (unzipped) is 15,816,655 bytes (16.3 MB on disk) for 199 items. The biggest individual asset is 2 MB (not over the 10 MB limit). Project json is 132 KB so not over 2.5 MB limit. Not sure why they would get Server Error: No Response. @cwillisf Since this info seems to indicate the project is not hitting any of the size limits, should we reopen? : \

**Comment by cwillisf** [comment]
@thisandagain do you have any idea why `assets` would return a 500 on asset set sometimes, but succeed later on what must be the same asset? Can we look up these uploads in the logs?
I have a copy of the project and can probably cause these errors again if necessary.
