### ISSUE TITLE
User reported getting "Server Error: No Response" when uploading an ~15 MB project file

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1189]
Another user reported getting "Server Error: No Response" when uploading an ~15 MB project file, via freshdesk no. 54970.

> I have recently worked on a big project, and as far as I know, here are big projects too. Although, there is one thing that annoys me. I had finished my project and every time I try to upload it, it fails. It says "Upload failed, Server error, no response". Of course I have tried uploading another projects, and it worked, the only thing I don't get is... this. It would be very nice if you had an answer to this, if not, I'll be continueing to upload the project.
> Also, is there a limit of space for the games? My game is around 15MB big and it always says this:
> <img width="122" alt="screen shot 2016-08-17 at 10 04 56 am" src="https://cloud.githubusercontent.com/assets/1320456/17739171/3835055c-6462-11e6-879b-a2cced61d426.png">
- Operating System: Windows NT 10.0 
- Browser: Firefox 47.0 
- Flash Version: Flash 22.0 (release 0)

(Moving this issue here from https://github.com/LLK/scratch-flash/issues/1187.)

**Comment by jwzimmer** [comment]
Maybe because the JSON was too large? @cwillisf

**Comment by jwzimmer** [comment]
(If it turns out this is related to size of the project at all, then it's related to https://github.com/LLK/scratch-flash/issues/1188, but it may not be related to the size.)

**Comment by thisandagain** [comment]
Would be great to get a copy of the project (SB2 file) they are trying to upload. My guess is this is the same as #1188.

**Comment by jwzimmer** [comment]
I have asked the user for a link to the project on scratch if they were able to upload it or the sb2 file from the offline editor. I will update this case if they respond.

**Comment by jwzimmer** [comment]
Looking into freshdesk no. 60252 which could be the same situation.

**Comment by jwzimmer** [comment]
I found another context which seems like a similar-enough situation with freshdesk no. 63380:
> I'm using the Scratch 2 offline editor and I'm trying to upload a project, but every time I try to upload the project, it always says 'Server error: No response'. I've also tried downloading the project and putting it on the website, but every time I try to do that, it always says it can't connect to the network. 
(...)
Yesterday, when I was trying to upload the project, it finally uploaded. Sorry if I wasted your time.

> - Operating System: Windows 8.1 
- Browser: Chrome 54.0.2840.71 
- Flash Version: Flash 23.0 (release 0)

The project is 131097817. It's about 21.1 MB when unzipped, and all its assets seem to be under the size limits. Largest asset is 3.6 MB, and project json is well under 2.5 MB.
