### ISSUE TITLE
Cloud appears to be very unreliable recently.

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1190]
Not getting any connection on any project a.t.m.

Here's my connection test project, which is currently showing zero for me (rather than one): https://scratch.mit.edu/projects/21501896/

I noticed a few hours ago that it was acting rather odd – empty cloud logs, and taking at least 3secs to respond on my round-trip ping-test project (and sometimes timing out after 5s): https://scratch.mit.edu/projects/96491582/

Should add that my custom cloud clients are also all failing to connect to cloud.

**Comment by TheLogFather** [comment]
Update: looks like the connection does eventually get through (connection test project cloudvar does change from one to zero eventually), but it takes about 10 secs or so – and the cloud logs are still empty for every project I've looked at...

**Comment by jwzimmer** [comment]
From @LiFaytheGoblin earlier today, another report of cloud variables not working properly:
> I now encountered the second project which clearly makes use of cloud variables but it says "no cloud variable activity" and also I can't change the cloud variable

/cc @cwillisf

**Comment by jwzimmer** [comment]
Repro'd by @cwillisf:
> huge delay, but eventually it works

**Comment by TheLogFather** [comment]
It was looking (mostly) better up until a few seconds ago (still had regular disconnects about every 20 secs, though).
But now it 's failing again, and I can't get a connection with https://scratch.mit.edu/projects/96991584/

**Comment by TheLogFather** [comment]
Cloud was back again for quite some time (apart from fairly regular slowdowns once or twice per minute which cause my custom cloud clients to think they've lost connection; also, still no cloud logs).

However, cloud is now almost completely failing again (from 1218UT).

**Comment by CosmicWebServices** [comment]
That happened to me yesterday I could not even create them

**Comment by TheLogFather** [comment]
Cloud was (mostly) back for several hours yesterday (from 1306UT), but it looks like the varserver has been down (as well as cloud logs still) since last night (2206UT), so my custom cloud clients are not working, 'cos they can't check if they successfully changed a cloudvar. :(

**Comment by TheLogFather** [comment]
Looks like cloudvars are working pretty well at the moment (just the occasional extra latency, and the source of that could be who knows where).

Cloud logs still not available though...

**Comment by CosmicWebServices** [comment]
Yeah... It 100% broke my cloud project now I have to make it again :(

**Comment by CosmicWebServices** [comment]
But it is mostly my fault

**Comment by CosmicWebServices** [comment]
by make it again I mean redo the cloud system

**Comment by thisandagain** [comment]
Assigning to @colbygk for investigation.

/cc @rschamp @cwillisf

**Comment by TheLogFather** [comment]
As I watch the logs from my custom cloud clients, I get the feeling that, after cloud is going well for a while, something starts to slowly degrade, until it eventually (effectively) fails.

Usually after incrementing the 'server heartbeat' cloudvar (if there was no other activity on cloudvars) my custom client waits (at least 0.3s) and checks the project's varserver URL several times to see if the change worked.

If all goes well, the change has nearly always made it through after the first 0.3s wait.

However, what I'm seeing at the moment is that, every so often, there's a longer delay – often having to wait 3 or 4 lots of 0.3s before the increment becomes visible.

"Every so often" starts off at something like every minute or two. But, over time, that gap between the longer waits decreases down to just a few seconds.

Sometimes, cloud then appears to fail almost completely (as happened at ~1649UT, and it's still effectively 'down' as of now, taking around a minute for a project to get the latest cloudvar values once it attempts to make its connection after first loading).

**Comment by CosmicWebServices** [comment]
Wow this is bad

**Comment by TheLogFather** [comment]
Looks like cloud is back again (as of 1840UT) – apart from the logs.

My logs are currently (as of ~1920UT) showing the long latency delays about every 30secs.

**Comment by TheLogFather** [comment]
Has something changed that fixed this?

Cloud has looked relatively stable for the last few hours (since 1807UT) – not even any (regular) latency spikes since 1912UT...

(Several rows of smileys go here...?)

**Comment by TheLogFather** [comment]
And cloud logs are back!!
(Another row of smileys...)

**Comment by CosmicWebServices** [comment]
YAY!
:) :)

**Comment by CosmicWebServices** [comment]
Wait it is down for me :(

**Comment by colbygk** [comment]
This was an issue I should have put more focus on after it was assigned to me 4 days ago. The cloud vars backend is experiencing a longer term issue that I'd rather not divulge in an open forum, since it has implications that could be used against it. We have some adjustments we can make the to host that is handling the vars to stabilize its operations for the time being.

It was bad luck that this coincided with a separate issue related to the monitoring of cloud vars. We have a plan to make that more robust as well that will go into effect before Monday.

For LLK future reference, this is related to ops issues 180, 182, 183, and 184. That's right, I used an oxford comma.

**Comment by colbygk** [comment]
```
[Fri Aug 26 15:35:55 2016] node[61189]: segfault at 2091abe00058 ip 00000000007ef478 sp 00007ffcf258cfd0 error 4 in nodejs[400000+854000]
```

**Comment by realmaster42** [comment]
The problem seems to be fixed, as I see 1... However it does take half a second to load.

**Comment by thisandagain** [comment]
Closing for now, though we realize we have some larger architectural work to do with Cloud Variables before this problem is fully resolved.
