### ISSUE TITLE
Users report problems accessing Editor: unable to use Create & See Inside buttons, asked to sign in again, 403 Forbidden error

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1191]
Reported via freshdesk no. 55934:

> I am a teacher who uses your website in my class. Starting around 2pm yesterday and continuing today your website would not load when my students selected the create button. The screen completely changed from its normal format and asked for the students to sign in again. Once the students had signed in an error occurred and it said Forbidden at the top of the screen. 
> Please let me know if this is an error with your website or if it is possibly an error with the network connection at my school or with my students computers or browsers. 
> Thank you for your help. PS I am emailing you from a students computer so you have their information. My username is [see freshdesk ticket]
- Username [see freshdesk ticket]
- Operating System: Windows 8.1 
- Browser: Chrome 52.0.2743.116 
- Flash Version: Flash 22.0 (release 0)

I am not seeing this in Chrome 52.0.2743.116 on Win 7 VM, or Chrome 52.0.2743.82 on Mac OS X.

**Comment by jwzimmer** [comment]
Discussed with @mewtaylor, this could be caused by https://github.com/LLK/scratch-www/issues/787.

I asked the user to please try, in order:
1) Go to https://scratch.mit.edu/discuss/ and click "Create" from the menu (nav bar) at the top of the page
2) Clear the browser's cache

(If 1 doesn't work as expected, then this user's problem isn't caused by the aforementioned issue.)

I will update the case if 1 doesn't work; if 2 works I'll close this case.

**Comment by jwzimmer** [comment]
Another report of issues with editor via freshdesk 55946, this one doesn't sound related to the www caching issue:
> Working the Create mode
> My students are not able to get to their Scripts Area because "Look Inside" will not open. This is not an isolated incident consequently I'm assuming the problem is on your end. Help . . . quickly please. 

Metadata: 
- User: None 
- Operating System: Windows 7 
- Browser: Microsoft Internet Explorer 11.0 
- Flash Version: Flash 22.0 (release 0)

**Comment by cwillisf** [comment]
I tried a variety of browsers (including IE 11) on both OS X and Windows and I haven't been able to reproduce either issue so far. I did notice that one of my browsers loaded the old editor at first, but it functioned correctly on the old version and again when I forced a refresh to get the latest version.

The only thing I can think of for 55934 is that the server returned a 403 with some part of the project save process that happens immediately after signing in through the editor. If the server returns 403 for any asset then the editor switches to a logged-out state and pops up a warning.

Regarding the "Look Inside" issue: it might be valuable to know what *does* happen when they the click "See Inside" button, and which version of the button they're using (Project page or My Stuff). For example, does it do nothing at all, or open an empty project, etc.? Also, does Create work?

The editor part of the "See Inside" process hasn't changed in a very long time... @mewtaylor, have there been changes to the Project or My Stuff pages recently that could affect "See Inside"?

**Comment by CosmicWebServices** [comment]
This happened to me I had to hard refresh to fix it

**Comment by jwzimmer** [comment]
Thanks @CosmicWebServices, your experience supports the original issue in this case being caused by the [www caching/ deploy issue](LLK/scratch-www#787), so that's helpful for us to know. : )

**Comment by CosmicWebServices** [comment]
np
