### ISSUE TITLE
User reported sound clips disappearing from projects

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1193]
Reported via freshdesk no. 57005:

> Hello there is a major glitch going around on scratch that i have noticed you see many people make music playing projects however these projects will sometimes have a 4 minute long sound file and yet have no audio the weird thing is is that so far ive only noticed it on music playing projects in fact i even made one and it was good for about a week before half the songs dissapeared this is it here 118351985 what is causing this and how is it fixed? 

Metadata: 
- User: (see project page or freshdesk ticket)
- Operating System: Windows 7 
- Browser: Firefox 48.0 
- Flash Version: Flash 22.0 (release 0)

**I'm wondering if the same issue that caused these sound clips to go missing is also what caused the missing sound clips from https://github.com/LLK/scratch-flash/issues/1110#issuecomment-242832383.**

**Comment by jwzimmer** [comment]
Looking at the version history for the project using @cwillisf's tool, it looks like the project was created and edited all on 8/15/16. The size increases like I would more or less expect it to as the user worked on the project... I don't see any sudden loss of size between subsequent versions...?
<img width="270" alt="screen shot 2016-09-08 at 11 40 15 am" src="https://cloud.githubusercontent.com/assets/1320456/18356071/57530192-75b9-11e6-83fd-183d591d2632.png">

**Comment by jwzimmer** [comment]
The last version of the project (using @cwillisf's tool) from 8/15/16 does have at least some of the missing sounds! (I have not checked to see if all of them are present.)
I uploaded the sb2 to my account as 120381774. Check MINEORES sound which exists in this project but not the current version of this project on the reporting user's account.

**Comment by jwzimmer** [comment]
Talking to @cwillisf about this: the file MINEORES can be downloaded from the project 118351985 via the editor and then played normally in another sound editor. So the file exists (in Scratch), but is not being completely loaded.

When looking at project 104642026 & 118351985, it turns out all the sounds use the same MD5 value:
<img width="397" alt="screen shot 2016-09-08 at 3 09 45 pm" src="https://cloud.githubusercontent.com/assets/1320456/18363075/7d287ed4-75d6-11e6-88cf-7188d759a5f8.png">

**Comment by jwzimmer** [comment]
Version aIP1kBPyQq6aBc8A8iHy3iORP78K8CEm of project 118351985 is the first version that is "bad" (missing sounds). It's the version after the one uploaded as project 120381774, which seems to be "good" (has at least some sounds present).

From the JSON for version aIP1kBPyQq6aBc8A8iHy3iORP78K8CEm:
`{
                    "soundName": "MINEORES",
                    "soundID": 1,
                    "md5": "b586745b98e94d7574f7f7b48d831e20.wav",
                    "sampleCount": 5841648,
                    "rate": 22050,
                    "format": "adpcm"
                }`

@cwillisf commented:
> the md5 is the "empty sound" one, but "sampleCount" is much larger than zero...
so somehow the editor thinks the sound isn't empty, but is calculating the "empty sound" MD5 anyway
that's valuable information already, though not really a complete picture yet

**Comment by jwzimmer** [comment]
Received another report of this via freshdesk no. 59196:
> I wanted to report that the sounds that were part of my project have disappeared. The file icon (placeholder) is still there and it still shows the correct amount of time that the sound used to take to play, but the graphic representation of the sound is gone and it will not play in my project or within the sound editor. Most of my sounds were uploaded so no big deal to replace them, but my sound called "intro" was recorded right into your interface and I never backed it up (my fault) by downloading it to my machine. Just wanted you to know that. Thank you. I am enjoying the experience otherwise.

I have asked the user for which project it was.

**Comment by jwzimmer** [comment]
I have not heard back from the user in freshdesk no. 55612 for about 2 months.

**Comment by jwzimmer** [comment]
Reported via freshdesk no. 68630:
> [140026443]
In my (see ticket) project, some of my sounds got deleted, and it has happened in some of my other projects. 
In the sound tab, it still says that the sounds are still there, but the audio got deleted. 
I refreshed the page many times, but the sounds didn't come back. 
The sounds are "Vanishing.mp3" and "The House of Leaves.mp3" in the Soundtrack sprite, and "Twirg Insuctualolas" in the Gobo Scratchcat sprite. 

Metadata: 
- User: (see ticket)
- Operating System: ChromeOS 8872.76.0 
- Browser: Chrome 55.0.2883.105 
- Flash Version: Flash 24.0 (release 0)

**Comment by jwzimmer** [comment]
Another example: 40881166 from freshdesk no. 76697:
> I checked a few days ago and they were all fine, but as soon as I re-shared the project they disappeared.

**Comment by cxw42** [comment]
Also, once yesterday and once today on 162523957 - in both cases re-uploading worked.  Same symptoms as noted above for 123706436 (2016/10/06 comment).  Windows 7, Chrome 58.0.3029.110 x64.

**Comment by cxw42** [comment]
Repro - opened 162523957 for the first time since my last comment, and the sound data is gone.  I left it that way - would you please take a look?  Thanks!

This project is private and has never been shared or remixed.  It only has one sprite, one backdrop, and one sound (a ~2min mp3 from freemusicarchive).  Definitely not size-limited :) . Let me know if any other detail would help, or if you'd like me to run a specific test.

**Comment by jwzimmer-zz** [comment]
This issue seems to still exist based on freshdesk no. 95002, per discussion with @cwillisf. Maybe https://github.com/LLK/scratch-flash/pull/1214 did not fix/ totally fix this issue.

Ideally we would have consistent repro steps for this issue. There are now several reports of this issue post-speculative-fix, from freshdesk as well as from @cxw42 (thanks, @cxw42!).
