### ISSUE TITLE
Name of project changes when you download an sb2 file as a new name

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1194]
Steps to repro:
- Open an existing project in the online editor with name X
- Click on File and choose Download to your computer
- Change the name value in Save As field to Y
- Click OK to download the file
- Note that the project name in the title field of the UI also changes to Y
- Go to the project page
- Note that the name of the project is still X
- Click See Inside
- Note that the project name in the title field is Y
- Go to My Stuff
- Note that the name of the project is still X

I would expect the name of the project **not** to be affected by saving the file under a new name. That's my first intuition. However, if we decide we prefer (or need) to change the project's name to the new name, we should change it everywhere at the same time, so that it doesn't show as having different names in different places. (As discussed with @cwillisf.)

Production, Chrome Version 52.0.2743.116 (64-bit), Mac OS X El Capitan 10.11.6 (15G31).

**Comment by chooper100** [comment]
Can reproduce

I presume this would also be a relatively simple fix?
(Even though it is only a minor inconvenience)

**Comment by kaschm** [comment]
Nice catch. We will address this in Scratch 3.0, which we are currently building.

**Comment by TheLogFather** [comment]
Yeah, this has been a bit of a niggle for me on numerous occasions.

The main problem I find is not, firstly, that it changes the title to the name, but rather that it can actually change 'bad' characters in the title (e.g. colon), which then ends up propagated *back* into the title 'cos it changes the title to the name. :/

**Comment by liam4** [comment]
> jwzimmer added the needs-discussion label

My input: when you download an image you uploaded to an image hosting site, does the image's name change to the downloaded file name? Nope! So why should a Scratch project behave differently?

Additionally, take a situation like this:

```
touch mydir/foo
cp mydir/foo baz
```

Now, will `mydir/foo` suddenly be `mydir/baz`? No, of course not. Copying or downloading a file/project to a new name shouldn't change the original file/project's name.
