### ISSUE TITLE
Inconsistent behavior with position sensing block

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-flash#1197]
The sensing block that returns {x position,y position, direction, costume #, ...} for other sprites does not include the current sprite as a valid data source.

That information is spread elsewhere, such as x position and y position under motion for the current sprite.

This is a little confusing and easy to stumble over.

**Comment by liam4** [comment]
This would be *awesome* to implement, if there's a "this sprite" option! Then you would be able to get the data of an arbitrary variable by variable name - handy for custom blocks, for example "square [var]":

![square var](https://cloud.githubusercontent.com/assets/9948030/18668581/9b2a9ac2-7f0c-11e6-852e-2386a21aa283.png)
