### ISSUE TITLE
Sprites can become more pixelated when their color is changed

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1198]
Production, Chrome Version 53.0.2785.116 (64-bit) and Mac OS X El Capitan 10.11.6 (15G1004)

Possible improvement we could make in Scratch 3.0: 
Currently, sprites can become more pixelated when their color is changed. It would be nice if that didn't happen, if nothing changed on recoloring except the colors.
See project 121999009.

@cwillisf said:

> I think it's a consequence of the way we do effects and the way we handle vector costumes. I don't think we're likely to change it in 2.0 but we can consider trying to improve it for 3.0

Screenshot showing the sprite with original color:
<img width="167" alt="screen shot 2016-09-20 at 3 14 02 pm" src="https://cloud.githubusercontent.com/assets/1320456/18685628/e95c4a76-7f46-11e6-8159-0cbe5fa9459e.png">

Screenshots showing the increase in pixelation with the color changed:
<img width="158" alt="screen shot 2016-09-20 at 3 16 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/18685629/e95cc866-7f46-11e6-9de2-a276ed834827.png">
<img width="193" alt="screen shot 2016-09-20 at 3 13 09 pm" src="https://cloud.githubusercontent.com/assets/1320456/18685630/e961011a-7f46-11e6-9fab-888b0e77de9e.png">

**Comment by jwzimmer** [comment]
Similar-looking issue with the pen tool:
<img width="233" alt="screen shot 2016-09-20 at 3 55 52 pm" src="https://cloud.githubusercontent.com/assets/1320456/18686723/ec884ff2-7f4a-11e6-82bc-8b944a61cc56.png">
<img width="427" alt="screen shot 2016-09-20 at 3 57 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/18686732/f60d0112-7f4a-11e6-92f9-5e89002e396b.png">

**Comment by TheLogFather** [comment]
Stage3D differences strike again... :)

Hit ctrl-M (cmd-shift-M on Mac, or just cmd-M in chrome) to toggle Stage3D.
