### ISSUE TITLE
Trying to save SVGs to a local file crashes the editor

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-flash#1200]
Steps to reproduce:
- Take any SVG drawn in Scratch. (Try the Scratch Cat or make a quick one)
- Right-click and use "save to local file".

The Abode Flash plugin crashes for me on Firefox 48. Strangely, this does not always happen, I reload the page and then it works as expected.

**Comment by chooper100** [comment]
Flash version and operation system?

Windows 10 and latest flash version here, never had any issues saving SVG files

**Comment by Tymewalk** [comment]
@chooper100 My browser / operating system: Ubuntu Linux, Firefox 48.0, Flash 11.2 (release 202)

Adobe cut support for Flash on Linux which really sucks 'cause I don't want to have to switch over to Chrome. :disappointed:

**Comment by kaschm** [comment]
Thanks for the report. We'll take a look - chances are, this is related to running Flash on Linux, which is no longer supported by Adobe and has various bugs that we can't control.

**Comment by thisandagain** [comment]
Unfortunately this appears to be a bug isolated to Flash on Linux which we don't have much control over. Moving to backlog to make sure we keep track of this for Scratch 3.0.
