### ISSUE TITLE
Users reported "Couldn't load plugin", out of date, unable to use Scratch

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1201]
Potentially related to https://github.com/LLK/scratch-flash/issues/1141.

Like we suspect with #1141, this could be totally outside our control. However, I think it may be worth tracking for now.
### From freshdesk no. 57765:

> So my laptop computer crashed a couple of days ago (9/15/16). I restored the device to a previous version (9/13/16) and it now works again, except whenever I go to a Scratch project on Chrome (my preferred browser for Scratch), it simply says "Couldn't load plugin." I checked the system requirements for Scratch, checked my computer, and found that the computer had automatically uninstalled the Adobe Flash Player plugin for unknown reasons. I proceeded to reinstall the Adobe Flash Player, but the problem still ensued. The weird thing is, when I tried loading a Scratch project in Microsoft Edge, it worked fine. 
> I very much enjoy using Scratch in my free time, and love seeing what people are inspired to make! Is there anything I can do to fix this issue? 
- User: (See freshdesk ticket)
- Operating System: Windows NT 10.0 
- Browser: Chrome 53.0.2785.116 
- Flash Version: Flash 23.0 (release 0)
### From freshdesk no. 57629:

> My son created 2 projects on his account today... When we try to open either project, we get an error message "Could not load plug-in". We tried to open other people's projects and we get the same message every time. How do we fix this? 

Metadata: 
- User: (See freshdesk ticket)
- Operating System: Windows Vista 
- Browser: Chrome 49.0.2623.112 
- Flash Version: Flash 23.0 (release 0)

**Comment by jwzimmer** [comment]
Preliminary google results, I just skimmed these: Issue with PepperFlash / https://bugs.chromium.org/p/chromium/issues/detail?id=572131 / https://productforums.google.com/forum/?#!topic/chrome/mxwrMGVA6FQ.
People seem to fix by doing something to PepperFlash or uninstalling + reinstalling Chrome, but it looks like the issue can return: https://productforums.google.com/forum/#!topic/chrome/VQEZ1I2APqw. Or maybe they can fix it by installing Canary: https://productforums.google.com/forum/#!topic/chrome/JYi4-QuUGag.

**Comment by jwzimmer** [comment]
In this freshdesk ticket, 56364, the user didn't mention the plug in, but was unable to load the projects:
> Every time I open the project page of ANY PROJECT, it doesn't load at all. Normally, it would have a blue loading bar and number of assets, but now it's only grey and didn't have numbers of asset underneath. What is going on here?

**Comment by unclej** [comment]
I am using my own version of scratch and I have found that the chrome browser v53 is crashing (complete crash - had to force quit on mac) intermittently for me on starting up scratch; it only reproduces for me on one machine.  I tried removing and reinstalling the browser with the same results. We haven't touched the scratch version code for months and so I concluded it was the browser update.  Sure enough when I went to canary the issue went away and it works great (v53 looks no good for scratch to me).

**Comment by jwzimmer** [comment]
@unclej Thanks, it's helpful to know the Canary solution worked for you 👍

**Comment by jwzimmer** [comment]
From freshdesk no. 58123:
> We are receiving a message that Adobe is out of date, but each time we download it and reopen the server Scratch continues to report the same problem. 

Metadata: 
- User: (see freshdesk ticket)
- Operating System: MacOS Macintosh X 10.11.6 
- Browser: Safari 9.1.3 
- Flash Version: Flash 22.0 (release 0)

**Comment by jwzimmer** [comment]
Another report of "can't load plugin" via freshdesk no. 59198:
> I have one computer in my lab that won't load Scratch. It has worked before but now gives the error message "can't load plugin". It doesn't say what plugin and I can't find any reference to technical specifications on the website.

Metadata: 
- User: None 
- Operating System: Windows NT 10.0 
- Browser: Chrome 53.0.2785.143 
- Flash Version: Flash 23.0 (release 0)

**Comment by cwillisf** [comment]
If they're receiving this message (possible with Freshdesk 58123) then it *should* just be a matter of clicking one of the links on that page, installing Flash, and restarting the browser. In some cases it might be difficult to tell whether the browser is fully shut down... to be 100% sure, they might want to restart the whole computer.
![image](https://cloud.githubusercontent.com/assets/7019101/19162281/1242084c-8bac-11e6-83a2-43769b639749.png)

**Comment by cwillisf** [comment]
The "Couldn't load plugin" message is a little trickier. I agree with @jwzimmer's implication in [this comment](https://github.com/LLK/scratch-flash/issues/1201#issuecomment-249019563) that it seems to be a bug in Chrome that can be triggered in a few different ways and is difficult to reliably work around.

I guess I would suggest that those seeing "Couldn't load plugin" should try to uninstall and reinstall Chrome, and if that doesn't work, they may need to use a browser other than Chrome.

It sounds like loading your user directory over a network connection is one of the causes of the "Couldn't load plugin" message. If you're not sure whether your user directory is loaded over a network connection, ask your network administrator. If you don't have a network administrator then you almost certainly are not loading your user directory this way.

**Comment by jwzimmer** [comment]
@cwillisf I can reply to the freshdesk tickets in this case with your advice. Thank you!

**Comment by jwzimmer** [comment]
@cwillisf, I sent the following to the freshdesk tickets in this case:
> Hello,
> We have looked into the issue you reported and similar sounding issues.
> **Re seeing the message "Couldn't load plugin":**
> We think this is a bug in Chrome that can be triggered in a few different ways and is difficult to reliably work around.
> We recommend if you are seeing "Couldn't load plugin" that you try to uninstall and reinstall Chrome, and if that doesn't work, you may need to use a browser other than Chrome.
> It sounds like loading your user directory over a network connection is one of the causes of the "Couldn't load plugin" message. If you're not sure whether your user directory is loaded over a network connection, ask your network administrator. If you don't have a network administrator then you almost certainly are not loading your user directory this way.
> **Re seeing the message "Oh no! We're having trouble displaying this Scratch Project... Visit this page to update Flash":**
> If you see this message, then we recommend you click one of the links on that page (or go to the Adobe website directly), install Flash, and restart the browser. In some cases it might be difficult to tell whether the browser is fully shut down. To be 100% sure, you might want to try restarting the whole computer.
> Thank you!
> Sincerely,
Julia
Scratch Team
