### ISSUE TITLE
Users report being unable to save projects

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1202]
Tracking users being unable to save projects.

### From freshdesk no. 58002:
> I work for [a school district]. One of our schools is currently using Scratch for a Gaming course. The teachers are unable to save projects on our network but can save them just fine at home. What could be the cause of this issue? 

Metadata: 
- User: None 
- Operating System: Windows NT 10.0 
- Browser: Chrome 53.0.2785.116 
- Flash Version: Flash 23.0 (release 0)

### From freshdesk no. 57741:
> I cannot save any of my projects online! I've tried reinstalling Chrome and Flash, and using a different Wi-Fi network, but it is not working. The Scratch window stops responding for about 10 seconds and gives the network not connecting error, but I can watch other scratch projects fine. 

[Update]
> Seems to work now. I had trouble saving projects with a specific sprite in my backpack. Apparently it had an issue and I removed it from the projects in the offline editor and it worked fine.
The projects in question were the projects in [see freshdesk ticket for studio].

Metadata: 
- User: (See freshdesk ticket)
- Operating System: Windows NT 10.0 
- Browser: Chrome 52.0.2743.116 
- Flash Version: Flash 23.0 (release 0)

I was wondering if these could be related to the issues where users ran into size limits, e.g. https://github.com/LLK/scratch-flash/issues/1172, https://github.com/LLK/scratch-flash/issues/1178, https://github.com/LLK/scratch-flash/issues/1189, https://github.com/LLK/scratch-flash/issues/1187, https://github.com/LLK/scratch-flash/issues/1188, or if it's a network connection issue, or if it could even have to do with the assets-becoming-corrupted issues, e.g. https://github.com/LLK/scratch-flash/issues/1085, https://github.com/LLK/scratch-flash/issues/1110 ...? I was thinking it could be size or asset corruption because the user from 57741 was able to save after removing a certain sprite. (Or they could have coincidentally removed the sprite after an unrelated transient connection issue was resolved.)

**Comment by jwzimmer** [comment]
This project 121280250 is giving me the network not connecting error when I try to remix it. I downloaded it and the unzipped size is 7,081,778 bytes (7.2 MB on disk) for 28 items. The largest asset is smaller than 10 MB but the project json is oversized (3.6 MB):
<img width="574" alt="screen shot 2016-09-23 at 10 57 59 am" src="https://cloud.githubusercontent.com/assets/1320456/18790410/ac2531bc-817c-11e6-8372-6edc2dc37a83.png">

The user had trouble uploading the project - they got server error: no response - but eventually they managed to upload it. They didn't see any warning about the data size limit. 

Since the oversize asset triggered server error: no response as well as the network not connecting error, it provides some support for the theory that that (something in project over size limit, even if project total size is not over 50 MB) is what happened in this case and the other cases where those errors were triggered.

**Comment by jwzimmer** [comment]
Re freshdesk no. 58002:
<img width="626" alt="screen shot 2016-09-27 at 4 30 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/18890589/c0314f6e-84cf-11e6-8bcf-df5719ea515b.png">
> That screenshot shows the issue we are experiencing when saving a project. Additionally the same message appears when an image is uploaded. When the message does not appear during an upload; the image is simply nowhere to be found.
 > What could be causing this issue? The teachers stated that this was not an issue last year during class. Our network connection is working with other sites and scratch.mit.edu was added to our educational area of web content.

I noticed this project looks like a "blank" project (meaning the kind created when you first click "Create"), so none of the parts of the project should be hitting a size limit. Hitting the size limit was my theory for why I saw the "network not connecting" error in https://github.com/LLK/scratch-flash/issues/1202#issuecomment-249217404. However that doesn't seem like a plausible explanation for what's happening with this user. I also noticed that the URL in the screenshot doesn't display a project ID... I don't know how that could happen under normal operations, seems like it has to be a bug. The only kind of similar thing I could think of was this issue https://github.com/LLK/scratchr2/issues/4087#issuecomment-249590192 where the project links in the Activity feed didn't contain the project ID at the end of the URL. But the context is pretty different.
^^ @cwillisf

**Comment by kaschm** [comment]
Sounds like this might be related to the size of the project - going to close for now, but we can reopen if we get more info from users.

**Comment by jwzimmer** [comment]
I don't think 58002 could be due to project size @kaschm, it looks like a blank new project. Sorry I didn't notice to point that out during Bug Triage.

The user got back to us with errors from the console:
<img width="719" alt="screen shot 2016-10-04 at 4 19 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/19090904/7916b11c-8a4e-11e6-9f14-64e290a552c5.png">

**Comment by cwillisf** [comment]
Based on those error messages, my guess is that their school network is blocking https://assets.scratch.mit.edu and possibly other parts of Scratch.

**Comment by jwzimmer** [comment]
Responding to user that we think 58002 is due to local connection issue. If more people report this issue, we can re-evaluate. 👍

**Comment by jwzimmer** [comment]
@cwillisf a user reported this via freshdesk no. 59211. Do these errors look like the same scenario, like their network is blocking assets.scratch.mit.edu as well?
<img width="592" alt="screen shot 2016-10-18 at 10 25 19 am" src="https://cloud.githubusercontent.com/assets/1320456/19482035/dc0336d6-951d-11e6-8b1e-eb6bb8aab2d1.png">

**Comment by cwillisf** [comment]
@jwzimmer yeah, that looks pretty similar. The fact that they got a 404 on a backpack item, while not necessarily a good sign, at least indicates that they were able to contact `scratch.mit.edu`. It looks like all attempts to contact `assets.scratch.mit.edu` timed out, though. Getting persistent timeouts like that usually suggests that the network is down or that the server is down or being blocked.

**Comment by jwzimmer** [comment]
@cwillisf Great, thanks, I will leave this case closed as probably due to local network configurations/ connection issues then. Thank you!
