### ISSUE TITLE
Forum search has no input field

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#1204]
When I try to search on the forum:

https://scratch.mit.edu/discuss/search/

I always get 0 results, because there is no input field to hand the search any keywords.

The search input field in the header will only search in projects and studios, so that's doesn't work for forum searches either.

**Comment by chooper100** [comment]
I think a better place for this kind of issue would be https://scratch.mit.edu/discuss/3/

Alternatively, you could try contacting the ST through https://scratch.mit.edu/contact-us/

This Github repo is just for the actual Scratch editor AFAIK

**Comment by gunchleoc** [comment]
I did contact the team per e-mail a good while ago and they advised me to use this bug tracker for any issues, because the website has no public bug tracker. One of your bug managers has then taken care of assigning the bugs where they belong.

I'm not fond of using the forums for this, they are too noisy for efficient bug management.

**Comment by thisandagain** [comment]
Hi folks,
We have a bug for this that we are tracking in our private repo for the forums. Thank you for the reminder.
