### ISSUE TITLE
[cloud] Raw cloud monitor "EOL" messages

### ISSUE THREAD

**Issue by PolyEdge** [LLK/scratch-flash#1205]
(I know this is probably related to #1190, but anyways, this isn't poor performance, it's an incorrect response from the server)

I haven't been able to isolate this problem, which seems to happen at an inconsistent rate, but it's really annoying, and most often renders the cloud monitor useless.

The raw cloud monitor API goes through phases of correctly returning the cloud history with a quick response time, and returning "EOL", after not responding for roughly 15 seconds.
![screenshot_1](https://cloud.githubusercontent.com/assets/13187260/19018476/7a9344ae-8820-11e6-8d4e-ffba7e01267b.png)

I'm talking about https://scratch.mit.edu/cloudmonitor/log/:id/

If you view it directly, you'll get EOL, which takes 15 seconds for the server to respond.
If you view it on the cloud monitor page, https://scratch.mit.edu/cloudmonitor/:id/ , you'll get a loading icon that takes 15 seconds and then says there's no cloud data activity, even though there's been activity in the last minute.

I do not know what EOL means. (End of line?) (End of log?)

Is this intentional or is it a bug?

**Comment by DrKat123** [comment]
According to Wikitionary:
>EOL
>
>1. End of line.
I don't think this is intentional though

**Comment by kaschm** [comment]
This has been fixed. Thanks.
