### ISSUE TITLE
 Right clicking scripts whilst in small screen mode with horizontal scroll sometimes misses them

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1209]
From @chooper100 in https://github.com/LLK/scratch-flash/issues/1181:

>  "Right clicking scripts whilst in small screen mode with horizontal scroll sometimes misses them"

**Comment by colbygk** [comment]
Bump: 
![out](https://user-images.githubusercontent.com/192393/28629074-5acb1e4e-71f4-11e7-8f12-73fe0cb2a11d.gif)
