### ISSUE TITLE
Alphabetize languages in editor the same way as language menu elsewhere on site

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1210]
Recently-ish we changed the order of the languages in the menu to be alphabetical by the name of the language (English is not at the top of the menu anymore). In the Editor, English is still at the top of the list. (There may be other differences in the order; I didn't check closely, but I didn't see any obvious diffs when I scanned it.)

I don't know if there was any design reason to keep English at the top of the menu in the Editor...? (Maybe a lot of people prefer to use their native language elsewhere on the site but still to code in English/ maybe the vast majority of users prefer English in the editor for whatever reason, and so we left it at the top of the list for convenience?) If so, we can close this. : )

Elsewhere on the website (e.g. homepage):
<img width="232" alt="screen shot 2016-10-06 at 5 22 42 pm" src="https://cloud.githubusercontent.com/assets/1320456/19171199/8cf7abe0-8be9-11e6-9c3c-ba23c207d77e.png">

Online editor (same as offline editor):
<img width="245" alt="screen shot 2016-10-06 at 5 20 22 pm" src="https://cloud.githubusercontent.com/assets/1320456/19171147/58e35ce6-8be9-11e6-8692-300dfd40b5ad.png">

Production, Chrome 53, Mac OS X El Capitan

**Comment by joker314** [comment]
Hmm, it seems to appear twice (once at the top, and once in its correct alphabetical position). I tried the same thing after changing the language on the homepage (to Russian), and it made no difference.

So perhaps the very first language in the list should match your selected language, for convenience? While still also appearing again in their correct position (so it appears twice).

And when joke languages are selected, like "Edible Scratch" it should put the very first option as it currently is, English.

**Comment by joker314** [comment]
Wait a second, it automatically switches to the language you have selected on the homepage. I still think that the top thing in the editor should match the language you select on the homepage, in case you want to change it in the editor but not on the website (e.g. when teaching somebody and you are bilingual). And then when you want to switch back it should be easy

**Comment by cwillisf** [comment]
I like @joker314's suggestion to make the first item in the editor match the language selected on the web site (if any). Beyond that, I agree with the issue title that the languages should be listed in the same order as on the rest of the site.

Does that make sense to others? Thoughts, especially @ntlrsk, @carljbowman, or @chrisgarrity?

Specific questions:
- Is it useful to have English at the top anyway? If there are many languages which have a good translation on the web site but less-complete translation of the editor, maybe a lot of people like to use English in the editor. Are there many languages in that situation?
- Should the language shown at the top (if any) also be shown in its usual location? My gut feeling is that it should be, in order to reduce the potential for confusion, but I'm interested in others' opinions.

**Comment by chrisgarrity** [comment]
@cwillisf I definitely agree that the languages should be in the same order in both places.

I'm not sure whether it makes sense to have the currently selected language at the top. If it's already selected, you don't need a shortcut to select it. However, on the website the menu shows the currently selected language and if you click on the dropdown it opens at the position of the currently selected item (e.g. with English there are things above and below the current selection). We can't really do that in the editor, so perhaps having the currently selected language at the top serves the purpose of letting you know what's selected.

Starting in the new year we are going to start requiring that the blocks and editor be 100% translated to get added (although that doesn't guarantee quality), and maintain 90% translated. So people should prefer to be in their own language in the editor.

**Comment by chrisgarrity** [comment]
Closing as this was fixed in https://github.com/LLK/scratch-flash/pull/1260
