### ISSUE TITLE
Editor, projects not loading on mobile devices, triggering update Flash message - Staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1213]
While trying to repro https://github.com/LLK/scratch-www/issues/831, I noticed that when using the Chrome (53) mobile device emulator, I am seeing the same message mentioned here (https://github.com/LLK/scratch-flash/issues/1201#issuecomment-252025929) on smaller screens. I am not seeing it on Staging with a regular-size browser window.

From clicking "Create" in navbar:
<img width="625" alt="screen shot 2016-10-13 at 11 30 57 am" src="https://cloud.githubusercontent.com/assets/1320456/19355700/4aec7532-9139-11e6-82fe-d73420e8b68d.png">

From clicking "Create" in navbar in regular-sized window:
<img width="571" alt="screen shot 2016-10-13 at 11 30 46 am" src="https://cloud.githubusercontent.com/assets/1320456/19355702/4b0c689c-9139-11e6-9b52-6119428c4d8d.png">

Looking at a project (I wouldn't expect this project to load, since it's an old project, but I would expect to see the normal "this project failed to load and the Scratch Team has been notified" message instead of the Flash message):
<img width="561" alt="screen shot 2016-10-13 at 11 38 43 am" src="https://cloud.githubusercontent.com/assets/1320456/19355823/bf766e26-9139-11e6-87c3-35c35d53b345.png">

With a new project which I would expect to load:
<img width="573" alt="screen shot 2016-10-13 at 11 47 36 am" src="https://cloud.githubusercontent.com/assets/1320456/19356175/ece24f14-913a-11e6-8a3b-a4786fc2903d.png">

That project does load in the regular window size (it took a while, but I'm connecting by VPN):
<img width="585" alt="screen shot 2016-10-13 at 11 48 36 am" src="https://cloud.githubusercontent.com/assets/1320456/19356213/0a33e528-913b-11e6-9843-e04eac21c7cc.png">
<img width="512" alt="screen shot 2016-10-13 at 11 47 02 am" src="https://cloud.githubusercontent.com/assets/1320456/19356212/0a115b7a-913b-11e6-907a-910c84e2c45a.png">

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratchr2/issues/4112
