### ISSUE TITLE
User reported cloud vars inconsistently treated as normal vars

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1215]
From freshdesk no. 60047:
> So I made a project where people can request for logos, using cloud variables. Now the problem is that occasionally some of them just gets converted to normal variables, and their values reset when I refresh the page. But they still have cloud variable attributes because when I rename it I still get the cloud symbol before the name. It just doesnt go to cloud log. Here is the project link if you want [see freshdesk ticket]

I wondered if this could be related to #1211?

Comment from @colbygk:
> Based on that one paragraph, it sounds to me like it's not so much that data is getting some how dropped for them, but that the editor itself is treating the variable differently or that the variable goes missing in the editor.
Perhaps there is some failure mode where if the cloud var server is not responding soon enough that the editor does something like dropping the var outright in the editor, but I don't think it would/should.. thoughts @cwillisf ?

**Comment by TheLogFather** [comment]
If the cloud server does not respond in time, then it's possible, under certain circumstances, that a newly created cloudvar can end up as a normal (global) var in a project. (It still has the cloud character at the start, of course.)
Given the recent cloud 'wobbles', I'd guess that might be what's happening...

**Comment by TheLogFather** [comment]
To elaborate, I _think_ the sequence of events might go something like this...
1) Cloud is acting up, taking about a minute or so to respond to requests;
2) User tries to create a new cloud variable;
3) Cloud does not (yet) respond, so variable is not (yet) created in the project;
4) The project gives up waiting, and doesn't create the cloudvar (dunno how long that timeout might be?)
5) After a minute or so, the cloudvar is eventually created as far as cloud server is concerned;
6) After cloud inactivity for some time (a few mins?), the port 531 connection gives up, and the project falls back to using https polling.

The key thing to note now is that if a project is using fallback polling, any cloudvars the server thinks _should_ exist in the cloud, but which are NOT in the project itself, _get instantly created in the project as normal global vars_ for some reason (and they have the cloud character in the name, of course).
See my fallback detector project for a demo of that: https://scratch.mit.edu/projects/96798133/

Therefore this now happens...
7) The finally-created cloudvar now appears in the project as a normal global var.

**Comment by thisandagain** [comment]
Most likely caused by #1211. Tracking further action(s) there.
