### ISSUE TITLE
Improve handling adding a list watcher to the stage when the list is very large

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1223]
The issue is that when a user has a project with a very large list being watched by a list watcher, the project may not be able to load (project page or editor). 

If the list takes a sufficiently long time to load, Flash kills the loading process as an "unresponsive script" well before it can complete, causing **error no. 1502** in the console.

This issue was reported via freshdesk no. 60427:

> Whenever I go onto my project it crashes my internet. It also won't load. Or it does load and keeps saying, "Plugin Stopped", it also has the reload button available. Can you help me? It just happens on my project called, [see ticket]. When I go on any other project it's fine. My dad said it's a website problem not an internet or computer problem. 

The project that isn't loading is 124673984.

I uploaded an older version of the project to their account and it does load (it has a shorter list).

@cwillisf was able to load the current version of the project (that isn't loading online) in the offline editor:

> it eventually finishes loading in the offline editor. It took about 90 seconds on my pretty-fast machine.

**Comment by CosmicWebServices** [comment]
This is a very common problem it happens to me all the time

**Comment by jwzimmer** [comment]
Good to know, @CosmicWebServices, thanks.

**Comment by algmwc5** [comment]
This also happens to me
Chrome 53.x, Windows 8.1
