### ISSUE TITLE
Input field bug

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-flash#1224]
Whenever you type into any input field before the last character, characters are deleted as you type.
I suck at explaining this, please refer to this diagram. (`|`=cursor)
`a|bc`
type "d"
`ad|c`
instead of
`ad|bc`

**Comment by Airhogs777** [comment]
Does your keyboard have an "insert" key? Try pressing it and see if that fixes it

**Comment by CatsAreFluffy** [comment]
It does and it did. Good to know.
