### ISSUE TITLE
Add Zulu language

### ISSUE THREAD

**Issue by EdwardGeneralov** [LLK/scratch-flash#1230]
Select language '''isiZulu''' blocks and editor completed,  the add file "zu.po" isiZulu the site scratch.mit.edu

**Comment by EdwardGeneralov** [comment]
Select language isiZulu to the languages menu

**Comment by EdwardGeneralov** [comment]
Add isiZulu to the languages menu, share user

**Comment by thisandagain** [comment]
Thanks @EdwardGeneralov we'll take a look.

**Comment by EdwardGeneralov** [comment]
See LLK/scratch-www/pull/1003

**Comment by EdwardGeneralov** [comment]
Merged LLK/scratch-www#1003

**Comment by chrisgarrity** [comment]
@EdwardGeneralov We're tracking this in the PR now, and currently testing the version to be deployed next week (where isiZulu is working great). So I'm closing this issue.
