### ISSUE TITLE
404 error in console when backpack has never had contents

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1231]
This is essentially a cosmetic issue according to @cwillisf.

To repro, open the console and use Create for an account where you have never put anything into the backpack. You should see a 404 error in the console. 

<img width="1064" alt="screen shot 2016-11-08 at 3 29 54 pm" src="https://cloud.githubusercontent.com/assets/1320456/20116649/17c91470-a5cb-11e6-8e73-a9745599bfa8.png">

**Comment by algmwc5** [comment]
This issue happened to me too
![screenshot](https://cloud.githubusercontent.com/assets/15071615/20131708/c5df88ca-a691-11e6-8d11-09734507dc13.png)
Offtopic, but what is the recaptcha.js for?

**Comment by liam4** [comment]
https://www.google.com/recaptcha/intro/index.html

For logging in when you've failed too many times, afaik, as well as signing up. (I think.)
