### ISSUE TITLE
User apparently logged out in editor - 404s for their project's assets in the console

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1232]
Reported via freshdesk no. 61213. At first @cwillisf & I thought the user's school network might be blocking the assets server, but that doesn't seem to be the case. I was able to repro similar messages to what the user is seeing in the console, errors like:
```
cdn.assets.scratch.mit.edu/:1 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/[id].png/get/ 404 (Not Found)
```

The user initially reported the issue as:
> Since Wednesday I have had issues with right clicking on the online editor. I had a solution, if I used the offline editor then Upload it onto the online editor at the end of the day. However since yesterday when I upload it, it thinks I'm logged out but if I go out of the editor I'm logged in. So now I can't upload to the online version and need help. Thanks! 

We asked them to try clearing their cache and cookies (since this reminded me of the issue we saw with cookies on Staging a while ago where the editor would appear to think the user was signed out), and discussed with them the possibility that the assets server was blocked and got back:
> I don't think this is the case I did what you said and still it didn't work so I decided to use another network (my friends) I explained to him and tried. It didn't work, so we reset his cache and restarted. It didn't work even after that. I don't know what's happening!

@cwillisf said of this issue:
> I've verified that those assets really don't exist on the assets CDN
> ... the editor is supposed to save all assets and then, once all assets have been successfully saved, save the project itself
> but based on those error messages, it looks like this person is loading a project which references assets that haven't been saved, somehow
> which suggests to me that either the editor is really messing up the "save assets first and then the project" or the assets server is saying "yep, OK got it" but then somehow failing to actually save the asset properly
> they don't have permission to load their own project or something like that

When I log in as the user and load the project (My Stuff > See Inside) in the editor, I see the following in the console:
```
3:39:18 PM | inf | Refresh Object {isPrivate: true, id: "123366794", owner: [see freshdesk ticket], user: [see freshdesk ticket]}
VM1439:1 03:39:18 PM | inf | SWF Initialized Object {version: "v451"}
cdn.assets.scratch.mit.edu/:1 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/d3eed1bf215bdf802554a5f8360b6126.png/get/ 404 (Not Found)
cdn.assets.scratch.mit.edu/:1 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/c11859d8b328ee61792a8445220a0a27.png/get/ 404 (Not Found)
cdn.assets.scratch.mit.edu/:1 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/91a2180d2c680e34be6b58f04ec5636c.png/get/ 404 (Not Found)
cdn.assets.scratch.mit.edu/:1 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/9dca6562ea6d51b5147ab5fe2a63e2e7.png/get/ 404 (Not Found)
cdn.assets.scratch.mit.edu/:1 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/5ffadf6d425468e02033d58c174b9100.png/get/ 404 (Not Found)
VM1440:1 03:39:26 PM | wrn | Failed server request Object {data: null, url: "https://cdn.assets.scratch.mit.edu/internalapi/asset/d3eed1bf215bdf802554a5f8360b6126.png/get/", event: Object}
VM1441:1 03:39:26 PM | wrn | MediaInfoOnline failed to set thumbnail Object {md5: "d3eed1bf215bdf802554a5f8360b6126.png"}
cdn.assets.scratch.mit.edu/:1 GET https://cdn.assets.scratch.mit.edu/internalapi/asset/dcc247f33bdfeffe3fb4c232e78e748c.png/get/ 404 (Not Found)
VM1442:1 03:39:32 PM | wrn | Failed server request Object {data: null, url: "https://cdn.assets.scratch.mit.edu/internalapi/asset/c11859d8b328ee61792a8445220a0a27.png/get/", event: Object}
VM1443:1 03:39:32 PM | wrn | MediaInfoOnline failed to set thumbnail Object {md5: "c11859d8b328ee61792a8445220a0a27.png"}
VM1444:1 03:39:32 PM | wrn | Failed server request Object {data: null, url: "https://cdn.assets.scratch.mit.edu/internalapi/asset/91a2180d2c680e34be6b58f04ec5636c.png/get/", event: Object}
VM1445:1 03:39:32 PM | wrn | MediaInfoOnline failed to set thumbnail Object {md5: "91a2180d2c680e34be6b58f04ec5636c.png"}
VM1446:1 03:39:32 PM | wrn | Failed server request Object {data: null, url: "https://cdn.assets.scratch.mit.edu/internalapi/asset/9dca6562ea6d51b5147ab5fe2a63e2e7.png/get/", event: Object}
VM1447:1 03:39:32 PM | wrn | MediaInfoOnline failed to set thumbnail Object {md5: "9dca6562ea6d51b5147ab5fe2a63e2e7.png"}
VM1448:1 03:39:32 PM | wrn | Failed server request Object {data: null, url: "https://cdn.assets.scratch.mit.edu/internalapi/asset/5ffadf6d425468e02033d58c174b9100.png/get/", event: Object}
VM1449:1 03:39:32 PM | wrn | MediaInfoOnline failed to set thumbnail Object {md5: "5ffadf6d425468e02033d58c174b9100.png"}
VM1450:1 03:39:32 PM | wrn | Failed server request Object {data: null, url: "https://cdn.assets.scratch.mit.edu/internalapi/asset/dcc247f33bdfeffe3fb4c232e78e748c.png/get/", event: Object}
VM1451:1 03:39:32 PM | wrn | MediaInfoOnline failed to set thumbnail Object {md5: "dcc247f33bdfeffe3fb4c232e78e748c.png"}
```
When I access the same project the same way while logged in as an admin, I don't see error messages.

**Comment by jwzimmer** [comment]
The 404 errors seem to be from backpack items (via @cwillisf).

**Comment by cwillisf** [comment]
Yep - I now believe that all of the 404s (and corresponding `failed to set thumbnail` messages) are from backpack items. That explains why they don't appear when the project is loaded from an admin account.

@jwzimmer contacted the person to ask them to delete the offending items from their backpack and see if that improves the situation. So far neither of us has been able to reproduce or even identify the actual problem, though.

**Comment by jwzimmer** [comment]
@cwillisf the user looks like they're consistently getting the project ID printed after the set of object attributes/ info... why is that? 

(I believe we saw it with their backpack 404s as well, but not the ones I saw when I logged in as the user, but I could be misremembering that?)

Response from the user:
> I tried but it didn’t work. I then reset all data on firefox but it didn’t work. Then I reinstalled firefox but it didn’t work.
Also this is the console code 
```
unreachable code after return statement[Learn More]save_actions.js:6:4
05:29:36 PM | inf | Refresh Object { isPrivate: true, id: "123366794", owner: [see freshdesk ticket], user: [see freshdesk ticket] }123366794
05:29:36 PM | inf | SWF Initialized Object { version: "v451" }123366794
05:30:43 PM | inf | SWF saving project Object { owner: [see freshdesk ticket], title: [see freshdesk ticket], id: "123366794" }123366794
05:31:06 PM | inf | Refresh Object { isPrivate: true, id: "123366794", owner: [see freshdesk ticket], user: [see freshdesk ticket] }123366794
05:31:06 PM | wrn | Failed server request Object { url: "https://assets.scratch.mit.edu/inte…", data: Object, event: Object }123366794
```
> I got some more code when I deleted all my backpack
```
unreachable code after return statement[Learn More]save_actions.js:6:4
08:06:01 PM | inf | Refresh Object { isPrivate: true, id: "123366794", owner: [see freshdesk ticket], user: [see freshdesk ticket] }123366794
08:06:01 PM | inf | SWF Initialized Object { version: "v451" }123366794
08:06:02 PM | inf | Refresh Object { isPrivate: true, id: "123366794", owner: [see freshdesk ticket], user: [see freshdesk ticket] }123366794
08:07:38 PM | inf | SWF saving project Object { owner: [see freshdesk ticket], title: [see freshdesk ticket], id: "123366794" }123366794
unreachable code after return statement[Learn More]save_actions.js:6:4
08:08:01 PM | inf | Refresh Object { isPrivate: true, id: "123366794", owner: [see freshdesk ticket], user: [see freshdesk ticket] }123366794
08:08:01 PM | wrn | Failed server request Object { url: "https://assets.scratch.mit.edu/inte…", data: Object, event: Object }123366794
```

**Comment by cwillisf** [comment]
Good(?) news: I managed to reproduce this issue locally!

I used:
- Windows 10.0.14393
- Firefox ESR 45.5.0
- Flash 23,0,0,207 (NPAPI)

Here's what I did. Some details might be unnecessary, but here goes:
1. Have a somewhat slow Internet connection (roughly 8 Mbps download, 1 Mbps upload)
2. Download the SB2 from the Freshdesk ticket
3. Log in with a non-admin account
4. Go to My Stuff
5. Click "+ New Project"
6. Click "File" then "Upload from your computer"
7. Pick the SB2 you downloaded from the Freshdesk ticket
8. Watch the progress bar (and the network window!) for a few minutes

Over time it seemed like asset uploads were gradually slowing down, and eventually I got a 403 from the server. At that point, the editor responded to the 403 as designed: it acted like I had signed out and informed me that I needed to sign in to save.

**Comment by jwzimmer** [comment]
@cwillisf the user from freshdesk no. 61213 reported they are no longer running into this error - they're no longer getting the sign out / network not connected message when uploading. (Post your fix in scratch-flash-online no. 293.) 👍
