### ISSUE TITLE
Grey overlay behind Sign In dialogue box only covers Tips Window - IE 11 on Win 7 VM

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1234]
Staging & Production, IE 11.0.9600.18499 on Win 7 VM

When you click the Sign In link from the editor, it opens a dialogue box, and the rest of the editor & tips window should be greyed out behind it. In IE 11 on a Win 7 VM however, only the Tips Window gets greyed out/ is covered by the overlay. The rest of the editor shows up as usual.

**The overlay effect in IE 11**

<img width="1108" alt="screen shot 2016-11-16 at 10 15 46 am" src="https://cloud.githubusercontent.com/assets/1320456/20353168/df4cf756-abe7-11e6-9717-2ee74a9e959e.png">

**The overlay effect in Chrome**

<img width="1030" alt="screen shot 2016-11-16 at 10 19 27 am" src="https://cloud.githubusercontent.com/assets/1320456/20353169/df523e0a-abe7-11e6-9a68-bfed8da04de1.png">

**Comment by chooper100** [comment]
I could not reproduce this with IE 11, Edge or Chrome on Windows 10.
Is this a bug exclusive to Windows 7?

@jwzimmer You said you were on a Windows 7 VM - does that mean that on your main OS you don't see the issue in IE?

**Comment by jwzimmer** [comment]
@chooper100 - I am using IE 11 on a Windows 7 VM on my Mac OS 10.11. I don't have IE on my Mac directly. It could be an IE version-specific bug, or a Win 7-specific bug, or even a bug that exists in my VM but not elsewhere. We will need to figure that out. : ) Thanks for your help.

**Comment by CosmicWebServices** [comment]
issue 1234 :Horray:
