### ISSUE TITLE
Costume sometimes gets "stuck" when sprite is hidden and there is a stamping tick loop

### ISSUE THREAD

**Issue by as-com** [LLK/scratch-flash#1237]
Safari 10.0.1, OS X 10.11.6, Flash 23.0.0.207
Project: https://scratch.mit.edu/projects/131747216/

Expected behavior:
- Hair animates smoothly
- Hair returns to "normal" state after clicking
- Hair matches the sprite corral

Actual behavior:
- Hair does not animate smoothly
- Hair does not return to normal position on the stage

I may be doing something horribly wrong, but this is certainly not expected.

**Comment by TheLogFather** [comment]
I'm not seeing any problem with the costume getting 'stuck' when I click. Only with it being too large to fit within the costume editor (so getting clipped on the right as soon as I look at the costume in editor).

Does it still get stuck for you if you redesign the costumes to fit within the costume editor frame?

For reference, I'm still back in the dark ages using much older Safari (7.1.8) and OSX (10.9.5), but I'm using Flash 23.0, and I see it looking fine on both Firefox and Chrome (until I look at costume in editor and it gets clipped).

**Comment by as-com** [comment]
@TheLogFather This is what happens for me: https://cloudup.com/cWT-KfItnPN

**Comment by TheLogFather** [comment]
Huh, weird... nope, definitely don't see that happen. Always ends up back at the expected costume for me, in every browser I've tried. (Have you checked with other browsers?)
Does it still happen if you're not running it through the tick broadcast from Stage (i.e. if you clear and stamp directly within the sprite's "showframe" custom block script)?
