### ISSUE TITLE
Recording new sounds - sounds not saved - from smoke testing

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1239]
Safari 9.1.3, Mac OS 10.11, Staging

- Project Editor (Safari)
  - Created project 1000014367 to test
  - Tried to add a sound by recording a new sound
  - After recording, size was still 0
  - Went to project page
  - Returned to editor > sounds tab
  - Recorded sounds not there

**Staging - The recorded sounds:**

<img width="599" alt="screen shot 2016-11-22 at 1 24 07 pm" src="https://cloud.githubusercontent.com/assets/1320456/20536510/66543aa6-b0b7-11e6-8da6-8bc44acaed59.png">
<img width="593" alt="screen shot 2016-11-22 at 1 24 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/20536509/66522ea0-b0b7-11e6-9164-d01af4cb2f04.png">

**Staging - After returning to editor:**

<img width="624" alt="screen shot 2016-11-22 at 1 24 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/20536508/664b4f7c-b0b7-11e6-9225-5c4809faf2ea.png">

It looks like that on Production (Chrome), the time also stays at 0 (if you click record, then click record (so two new sounds) then go back and add sound to each) for the clips (until you refresh the page I think). However, the clips did get saved on Production when I went editor -> project page -> editor, whereas on Staging they didn't.

**Production - Time stays at 0 at first**

<img width="663" alt="screen shot 2016-11-22 at 1 32 59 pm" src="https://cloud.githubusercontent.com/assets/1320456/20536776/6eae00be-b0b8-11e6-8f18-0d25aa4af188.png">
<img width="981" alt="screen shot 2016-11-22 at 1 32 49 pm" src="https://cloud.githubusercontent.com/assets/1320456/20536775/6eadd332-b0b8-11e6-90c0-484153d4afb2.png">

**Production - After refresh, clips are still there, and times have been updated**

<img width="815" alt="screen shot 2016-11-22 at 1 33 15 pm" src="https://cloud.githubusercontent.com/assets/1320456/20536774/6eacf9a8-b0b8-11e6-9c98-64956c5bb744.png">

/cc @cwillisf

**Comment by jwzimmer** [comment]
Tried to repro in Chrome, clips were saved.
Tried to repro in Safari, clips were saved.

**Comment by jwzimmer** [comment]
I tried to repro this several times. @cwillisf looked at all the sound-related code that had changed in this iteration, and found one part that could affect saving:
> this commit in particular could affect saving sounds... I still believe it's correct and that it should, if anything, fix problems related to saving sounds, but it's possible that I missed something and there's a case where it's harmful.
https://github.com/LLK/scratch-flash/commit/86be65b284951f17b0a0e44adf238fd7b62adbfa

Since we couldn't repro this and are confident in the changes made to sounds in this iteration, we are not considering this a blocker for release. We're going to attempt to repro this at some point post-deploy. 👍

**Comment by algmwc5** [comment]
I believe this has been reported on the Bugs and Glitches subforum, now I just need to dig trough the topics to see which one it is

**Comment by thisandagain** [comment]
@cwillisf Would it be helpful to ask @jwzimmer to repro this?

**Comment by cwillisf** [comment]
@thisandagain (& @jwzimmer) yeah, trying to repro this now would be very helpful. If there's info in Bugs and Glitches that might help repro then that could be valuable too.

**Comment by jwzimmer** [comment]
Seems like this could potentially be related to https://github.com/LLK/scratch-flash/issues/1255?
