### ISSUE TITLE
Recent change to limit list watcher size breaks appearance of some projects

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1240]
See https://github.com/LLK/scratch-flash/commit/ddf692d5bb86229a553c8fe36b218fbfb6ab198a#commitcomment-19712681
(See PR #1229)

**Comment by griffpatch** [comment]
You know... just keeping lists 'exactly where you left them' between saves
and exports and imports would be an amazing feature :) - They still grow my
a few pixels at each save or so causing layouts to slowly creep off
position :)

**Comment by TheLogFather** [comment]
Yeah, https://github.com/LLK/scratch-flash/issues/883 does cause the need for some list watcher management here & there...

**Comment by liam4** [comment]
And so they were broken. 💔
