### ISSUE TITLE
[Lo-Prio, Cloud] Cloud time is slow by ~30 secs

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1243]
Consequently, the cloud log shows "30 seconds ago" for something that has only just changed.

**Comment by TheLogFather** [comment]
(Furthermore, looks like cloud started to go down ~2hrs ago, and is now non-functional...)

**Comment by CosmicWebServices** [comment]
:(

**Comment by TheLogFather** [comment]
Looks like cloud is *almost* fully working at the moment...

Projects seem to able to read and change cloudvars just fine, and the API can make changes just fine. Also, the cloud log looks good now (changes have correct time).

But the varserver URL for projects is failing – i.e. trying to get the JSON for a project's cloudvar values through its ID with https://scratch.mit.edu/varserver/[PROJECTID]
