### ISSUE TITLE
Public Procedures

### ISSUE THREAD

**Issue by DanFessler** [LLK/scratch-flash#1244]
I've read through the Global Procedures thread, and this idea relates heavily to it, but is not only different enough to warrant its own topic, but also I feel is a much simpler ask to implement.

Instead of marking procedures as global, it might make most sense to have a toggle to make them "public" and access these public procedures from any other sprite/stage with a new block which can select the sprite/procedure from a drop-down.  This would function in the very same way the drop-downs of the "[var] of [sprite]" block works.  Being public, the code would execute on the sprite it is defined on, and therefore doesn't need any new notion of UI to accommodate for where they live.

Mockup:
![scratch_globalblocks](https://cloud.githubusercontent.com/assets/1312084/20687054/db39218a-b56f-11e6-882b-777ed9d6aa8f.png)
the parameter slots would change to reflect the selected procedure from the list.  Perhaps truncate the inputs when viewed in the "more blocks" panel

The biggest open question would be if the call would execute on only the base sprite, or also its clones.  To be honest, I'd be happy with either, but I think the best solution would be to have it called on all clones.  That way, you could filter out which specific clone to apply it to in the block definition if you so wanted by supplying a cloneID variable or some similar method.

**Comment by TheLogFather** [comment]
If all clones execute it then wouldn't that be pretty similar to extending the broadcast mechanism to include parameters? (So a receiver block has the option to become extended with extra parameters in a way that looks & works roughly like the parameters of a custom block, and then the corresponding broadcast block has slots to drop expressions into, just like the custom block callers.)

I wonder if that might be the most intuitive way to implement such a thing? (Though it does raise the question of the confusion over differences between broadcasts vs custom blocks, i.e. starting a new thread vs running within the current thread – but it could be argued that potential confusion already exists, though not in such a stark way...?)

**Comment by DanFessler** [comment]
You're right that syntactically it would nearly be identical, but I think that as soon as you start dealing with parameters, the concept of "broadcasts" loses meaning.  Right now, I'm definitely hacking this sort of behavior through broadcasts and global variables, but if these public custom blocks existed I'd imagine a much cleaner paradigm where broadcasts are generally called across sprites to maintain code-flow (update broadcasts, render broadcasts, etc), and public procedures would be for more specific tasks that require variable input conditions.  The end result, in my mind, would be much less confusing than overloading broadcasts.

**Comment by LFP6** [comment]
I'd be all for broadcasts with parameters. Bypasses the confusion and complication of "stacks". The benefit I'd find of this approach is that you know exactly where the script is located, and it's limited to just that sprite. That's what I'd like to see most, second being execution per clone-type, and the third being this implementation.

Honestly I'd like to see an option of having an individual script or an entire workspace not being connected to a particular sprite, and being able to "include" it. Would this be confusing in the existing Scratch paradigm? I'm imagining something like the existing "browser" for sounds and costumes, could even use this to split up the code on one sprite. Could be called "roles" or something similar?

**Comment by liam4** [comment]
And of course, context menu -> define would work lovely with this.

**Comment by DanFessler** [comment]
On second thought, @TheLogFather, there is one complication I overlooked when dealing with custom blocks.  They don't have a pure name string and can have parameters mixed in, or even no text labels at all.  Representing this via a drop-down is problematic and would take some clever UI rework.

I'll try to think of ways to solve the UI in a simple manner, but if I can't, broadcasts on the other hand don't have any of these problems.  They have pure string names and might be a better fit to extend this behavior - even if it means losing the sprite-specific function call.
