### ISSUE TITLE
Say doesn't work correctly in fullscreen

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-flash#1251]
The last line of text can disappear, the textbox can be the wrong size, etc.

**Comment by TheLogFather** [comment]
Yeah, this has been a longstanding issue that pops up from time to time...
I've only seen it mentioned occasionally in the forums, so I've wondered if it only happens on Macs?
I've also wondered if it's what was meant by https://github.com/LLK/scratch-flash/issues/1034...?

**Comment by DanFessler** [comment]
@CatsAreFluffy can you provide information on what operating system and browser you're using and provide an example project that shows the issue?
