### ISSUE TITLE
About scratch Add an extension

### ISSUE THREAD

**Issue by jiangzhixiao** [LLK/scratch-flash#1253]
i pull a copy of scratch-flash,then import the code , complier and run with flashbuilder.everything goes well.
but when i click the  Add an Extension button,select a PicoBoard or LEGO WeDo 1.0 or  LEGO WeDo 2.0,then i click  “OK” button, a strange thing happend. **no block was loaded** 
 can anyone tell me ,what's the problem of this.thanks all
1、run by FlashBuilder
![image](https://cloud.githubusercontent.com/assets/7273487/21166537/15dc94c0-c1e1-11e6-86e2-e3b288759bec.png)
2、run By Scratch 2 Offline Editor
![image](https://cloud.githubusercontent.com/assets/7273487/21166600/815523b6-c1e1-11e6-83fd-c8406414c1c5.png)

**Comment by liam4** [comment]
I imagine the extension scripts are stored separately from scratch-flash (like all the other pieces of media [costumes, sounds, backdrops]), though it's a little surprising that the names are still in the list.

**Comment by thisandagain** [comment]
@cwillisf @jwzimmer Could this be related to the offline editor bug you just patched?

**Comment by cwillisf** [comment]
There are two pieces which may be missing, depending on how you're loading the editor.

First off, the editor must be given a host name and path to use when loading extensions. This is handled by the [`getOfficialExtensionURL` function in `Server.as`](https://github.com/LLK/scratch-flash/blob/de0bd0220aa1d821664092ebddfcb6ca75bb8930/src/util/Server.as#L95). You can see how ScratchX supplies these configuration values by looking at [`urlOverrides` in `scratchx.js`](https://github.com/LLK/scratchx/blob/ed239eb0f03cdedc0fe773af461659f43019d71a/js/scratchx.js#L90).

If you have that configuration data in place, the next problem you might run into is that the editor expects to be hosted by a browser, and it uses that browser to load the extension JavaScript files. If you're trying to run the editor SWF outside of a browser then it might not be able to do this. Take a look at the [`loadExternalJS` call in `ExtensionManager.as`](https://github.com/LLK/scratch-flash/blob/abac440f1f34932679bd001d96de2315be7020ee/src/extensions/ExtensionManager.as#L173) for more details.

**Comment by drew345** [comment]
I have exactly the same problem as the OP here. After adding PicoBlock or LEGO WeDo extensions, the extension names show up but there are now blocks in the drawers.
I have done no modifications to the source code at all . I downloaded and compiled based on the instructions here:  https://scratch.mit.edu/discuss/topic/38970/?page=1 (New Way)
I try running the Scratch.swf file in browsers (firefox, chrome, explorer) and in an swf player (Swiff Player) . In all cases the Extension names load with no blocks exactly as shown above. 
I have my own hardware and extension that I want to load, but of course want to get the default extensions working first.
- Should I run the swf file in another way other than browser windows or swf players?
- Should I download the blocks from another place first and manually put then someplace in the source code?
Thanks so much! Andrew

**Comment by cwillisf** [comment]
@drew345 my guess is that either your `urlOverrides` aren't being set correctly or you're missing some of the Scratch extension framework JavaScript files (see [here](https://github.com/LLK/scratchx/tree/gh-pages/scratch_extensions)). If you can, I would try to verify that `loadExternalJS` is attempting to load the correct URL to help narrow down the problem.
