### ISSUE TITLE
PepperFlashPlayer.plugin: 0x77052 is not a valid resource ID.

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1257]
**TL;DR** Previously-unencountered error in console, seems suspicious, not much else known. Don't know if this is a regression.

I ran into this error yesterday afternoon while in the editor; Staging, Chrome 55, Mac OS El Capitan.

@cwillisf said:
> I've never seen that error before
I've never seen an error of that format before
judging from a couple of web searches it seems like it might be related to recording audio

<img width="1038" alt="screen shot 2016-12-16 at 10 13 53 pm" src="https://cloud.githubusercontent.com/assets/1320456/21284040/7fd4000e-c3dd-11e6-9050-e22ab0efe9ad.png">

**Comment by yifengteng** [comment]
你好！我也遇到了这个问题，做一个录音的时候，你的问题解决了吗，求助。

**Comment by yifengteng** [comment]
Hello there! I have encountered this problem, do a recording time, your problem is solved, help.

**Comment by zoofox** [comment]
> Hello there! I have encountered this problem, do a recording time, your problem is solved, help.
Hi, i run into this problem too,have u resolved it?
