### ISSUE TITLE
CloudVars - Latest version of Flash blocks port 531. Player not falling back to polling(?) so ALL cloud projects get 'stuck' when connecting.

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1261]
See https://forums.adobe.com/thread/2261853, note final answer (and that 531 is in list):

> While updates to the official documentation are forthcoming, I can confirm that we've expanded the list of blocked ports to include the following:
>  
> 1, 7, 9, 11, 13, 15, 17, 19, 21, 22, 23, 25, 37, 42, 43, 53, 77, 79, 87, 95, 101, 102, 103, 104, 109, 110, 111, 113, 115, 117, 119, 123, 135, 139, 143, 179, 389, 465, 512, 513, 514, 515, 526, 530, **531**, 532, 540, 556, 563, 587, 601, 636, 993, 995, 1720, 1723, 2049, 3659, 4045, 5060, 6000, 6566, 6665, 6666, 6667, 6668, and 6669.
>  
> To resolve this issue, our recommendation would be to modify your content and corresponding socket server to use a port that's not included in the list above.

Shouldn't the Scratch player eventually fall back to polling, though? Or does it just not expect an exception, so ends up dealing with it in the wrong way...?

I suspect this is the source of all the problems users have started having with cloud-enabled projects failing to connect to the cloud server.

**Comment by TheLogFather** [comment]
Some references in forums:
https://scratch.mit.edu/discuss/topic/234150/
https://scratch.mit.edu/discuss/topic/232550/
https://scratch.mit.edu/discuss/topic/234746/
https://scratch.mit.edu/discuss/topic/234672/
https://scratch.mit.edu/discuss/topic/234648/
And many of the most recent posts in https://scratch.mit.edu/discuss/topic/12949/

**Comment by thisandagain** [comment]
@cwillisf Could you investigate?

**Comment by TheLogFather** [comment]
Just to give an update on some experimenting...

I updated to Flash 24.0.0.194 this morning, and cloud immediately stopped connecting for all cloud projects (as expected).

If I uninstall Flash, and then re-install 24.0.0.186, cloud projects works fine.

Also, if I add the line "EnableInsecureSocketPorts=1" to Flash's mms.cfg file then cloud also works fine for 24.0.0.194. (In particular, I can add the line temporarily just before loading the project, and then remove it again once connected to cloud.)

Hope that's useful in some way!

**Comment by cwillisf** [comment]
Good info -- thanks, @TheLogFather!
That led me to what I think might be a reasonable fix, if we want to re-enable socket connections to the cloud server at some point. Here's the relevant info: http://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7c60.html#WS5b3ccc516d4fbf351e63e3d118a9b90204-7c63

I'm also about to open a pull request for a change that makes the editor properly fall back to HTTP when this happens...

**Comment by TheLogFather** [comment]
OK, good to hear a fix is in the works! :)

(BTW, this is closed now, but the issue isn't fixed AFAICT – do you expect it to be working right now, or is the fix yet to be deployed?)

**Comment by TheLogFather** [comment]
OK, I see 453.1, and that looks to have fixed it. :)

**Comment by LFP6** [comment]
We ran into this issue with a project I'm involved in, and just changed the port we're using. From what I remember, we already have a Flash policy file, but when you try to connect to a blocked port, it won't even request it.

**Comment by TheLogFather** [comment]
@cwillisf:
Did this change also somehow fix the issue with cloudvars not seeing remote updates when being changed regularly locally by a project? (i.e. #976)

I'm no longer seeing the top cloudvar get 'stuck' when I run https://scratch.mit.edu/projects/92748708/...

**Comment by cwillisf** [comment]
@LFP6 that's disappointing... but good to know. Thanks!

**Comment by cwillisf** [comment]
@TheLogFather I did fix a place where sometimes the HTTP fallback code was throwing an exception but I wouldn't have expected that to fix #976. I'll take another look and see if I missed something; if #976 is fixed then I'd like to know why :)
