### ISSUE TITLE
Error: Calling JSeditorReady() failed.

### ISSUE THREAD

**Issue by elorenn** [LLK/scratch-flash#1265]
This issue appears on my console every time I load the page my Scratch project is embedded onto. How can I fix/get rid of this error? 

"Error: Calling JSeditorReady() failed"

**Comment by thisandagain** [comment]
@elorenn Is the error causing the project to not load or not work properly?

**Comment by wangwanzhong** [comment]
i have the same problem.

I embed scratch.swf into html on remote webserver , chrome will raise warnning : 09:36:58 AM | wrn | SWF Error: Calling JSeditorReady() failed. and can not display right,  

While it works right when i open scratch.swf on my loca filesystem with url file://scratch.swf in chrome

**Comment by kelthzuard** [comment]
try add "var flashvars = {extensionDevMode:'true'}",the error: Calling JSeditorReady() failed may not be the reason for your failed loding.

**Comment by rschamp** [comment]
@wangwanzhong Do you have a link so we could see the error ourselves? Alternatively, could you post the html with the swf embedded?  Usually this error comes from another fatal javascript error happening during the embed process.

**Comment by QinJhonny** [comment]
same problem here.
my html code :

    <object type="application/x-shockwave-flash" data="Scratch.swf" width="100%" height="100%" id="scratch" style="visibility: visible;">
        <param name="allowscriptaccess" value="always">
        <param name="allowfullscreen" value="true">
        <param name="wmode" value="direct">
        <param name="menu" value="false">
    </object>

</html>
I open the html file directly works fine,while I open it on remote webserver the browser raises warning '06:47:45 PM | wrn | SWF Error: Calling JSeditorReady() failed.'.   the 'Scratch.swf' I built myself from the latest commit

**Comment by cwillisf** [comment]
The `JSeditorReady` function itself isn't critical to the editor, but to get rid of this warning you'll need to put one on your web page and have it return a "truthy" value. Something like this should work:
```js
function JSeditorReady() {
  return true;
}
```

The Scratch 2.0 editor calls this function once the editor is done with its initialization process, so if you have anything on your web page that you'd like to do at that point you can trigger it here.

**Comment by thammaknot** [comment]
Did anyone figure out a solution to this?
I also have this problem.

Steps to reproduce & symptoms:

1. downloaded and built scratch from this repo.
2. embedded it on an HTML page (minimal code)

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <title>Scratch Editor</title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>

        <script type="text/javascript">
         swfobject.embedSWF("scratch.swf", "scratch-editor", "1000", "700", "10.2.0");
        </script>

    </head>
    <body>
        <div id="scratch-editor">
            <p>Flash is not supported.</p>
        </div>
    </body>
</html>

3. Opening up this HTML page on local machine works fine (whole editor showed up). No JSeditorReady() error.

4. However, trying to access this via a remote server, only the stage will be display; no editor; no blocks. JSeditorReady() error (as mentioned above) occurred.

**Comment by thammaknot** [comment]
And this is even after following @cwillisf's comment to put in JSeditorReady() function on the page. It didn't help.

**Comment by ghost** [comment]
I met the same issue, can anybody help to explain how to fix it, many thanks.

**Comment by thammaknot** [comment]
Hi moxuanchen,

I recently solved this issue. The jseditorready() error was indeed not critical to setting up Scratch 2.0.

What is the real issue you're observing?

**Comment by emorenis** [comment]
Hi @thammaknot Please post how did you solve it. It may help other people get on the right track.

Thank you!

**Comment by thammaknot** [comment]
If you really want to get rid of the jseditorready() error, you can define that function somewhere in Javascript (could be right in your HTML file).

The point though was that, in my case, the jseditorready() error was just a red herring. It was not the cause of any further issue. It was just an annoying console error. The cause of my real issue (which is not related to this issue) was something else.
