### ISSUE TITLE
[Cloud] IE/Edge caching varserver response can revert cloud data for a project to older values

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1267]
See conversation with ZZ9PluralZAlpha on https://scratch.mit.edu/projects/141195887/
(The project only increases the cloudvar, yet when ZZ9 went to it again, its value was back to the previous value seen when last visiting the project. On increasing the value, it obviously sent the *old* increased value to cloud, hence losing all more recent increases over the minutes since previous visit.)

See also topic https://scratch.mit.edu/discuss/topic/235998/

Without knowing yet exactly what mechanism is causing the caching (if that's what it is), it's hard to be sure how to fix it. But maybe adding a random/dated query string onto the end of the varserver request might ensure it doesn't get cached?

**Comment by TheLogFather** [comment]
More info...

ZZ9 tried from a different computer at a library, and encountered the same problem.
That seems at odds with the idea of a caching issue, since it's a different 'net connection on a different computer. (But it was also using old IE on old Win7, so maybe there's an issue with such a set up?)

Or could it be account-specific somehow? The only other vague evidence for that is another user @andallfor who appeared to have the same problem when I examined the cloud log for my test project.
Since these two both have very similar sign-up times (~8 months ago) they also both have very similar userids (starting with "16"). But how that could cause a problem is really beyond me... :/

**Comment by TheLogFather** [comment]
I'm also seeing another (Scratcher959) appears to have the same issue (according to logs).

**Comment by thisandagain** [comment]
We don't have any type of caching in front of cloud vars so it isn't that, but rather I would guess within the client itself.

**Comment by TheLogFather** [comment]
Yes, I wasn't expecting it would be any kind of Scratch-related cache. Perhaps more to do with some kind of proxy which is placing its own cache between the user and the Scratch website?
(Although the fact it's happening for specific users, perhaps even no matter the system they use, given ZZ9's attempt at a library [which is only a single other test, unfortunately], does seem rather odd – that there could, maybe just, be something account-related which is somehow preventing the latest value getting through? Seems really unlikely, but I'm thrashing about for ideas...)

Is there a way for a Scratch Team member to sign in with the identity of a chosen other user for a short time? If so, would it be possible to take a look at the above test project while signed in as ZZ9'? You wouldn't even need to change anything or run it as ZZ9'. Just change the cloudvar value from any other account, and see if you can see the change from where you're signed in as ZZ9'.

**Comment by TheLogFather** [comment]
Found another user experiencing the same problem: BunnyTales.

**Comment by TheLogFather** [comment]
Looks like LBMCompany also has the same issue.

Is this just IE being way more aggressive with caching...?
A quick search turns up loads of comments about it:
http://stackoverflow.com/questions/6115342/json-is-being-cached-incorrectly
https://dzone.com/articles/output-caching-aspnet-mvc
http://www.greenvilleweb.us/how-to-web-design/problem-with-ie-9-caching-ajax-get-request/
https://meta.discourse.org/t/aggressive-caching-in-ie-11/18514
etc... etc...
(Most of the results are in the context of jQuery/AJAX.)

If it is to do with this, I think my original suggestion (just add a changing query string to the varserver requests) may well fix it...?

**Comment by TheLogFather** [comment]
Confirmation that the problem is browser-specific...

ZZ9 has successfully made & seen changes to cloudvars using both Chrome & Firefox.

But when trying with IE and Edge, they both continue to show the caching issue.

**Comment by TheLogFather** [comment]
I'm seeing more and more users having this issue on various of my cloud projects. (I can tell from the pattern of entries in the logs – the failure to acquire the cloud locks, 'cos the project never sees the changed lock value 'stick' for more than about a second.)

If adding a query string to the request does work around this issue, then isn't that a fix which could be rolled out very quickly? (Or maybe the query string thing doesn't fix it...?)

**Comment by TheLogFather** [comment]
Continuing to see entries in cloud logs which suggest this issue remains.
(Was hoping v454 might've included a fix.)
