### ISSUE TITLE
(Vertical) Gradient issues with horizontal and vertical lines

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-flash#1271]
All of the following shape strokes/lines have the same gradient (top -> down, black -> blue):

![](https://cloud.githubusercontent.com/assets/9948030/22450541/bc6997d0-e73d-11e6-9b4b-c475e968448c.png)

(..except the rectangle, oops, but you get the point.)

[Here's the SVG image.](https://gist.github.com/liam4/0d40c72c567708dbd37968b4bb232b48) (Strangely enough, the native Chrome SVG renderer doesn't even draw the lines at all..)

Surprisingly, Scratch doesn't seem to want to render the gradients on those lines at all.

* Rotating the vertical line does [*not*](http://i.imgur.com/GnzwLGg.png) fix the issue (it still renders without a gradient).
* Horizontal lines [don't want to render a vertical gradient](http://i.imgur.com/v2v8Vwp.png), but they'll [draw horizontal gradients fine](http://i.imgur.com/dKshNim.png). Radial gradients [don't work on horizontal or vertical lines](http://i.imgur.com/eWpWNNS.png) at all.
* On diagonal lines, [all gradients work](http://i.imgur.com/B85iXJD.png).
* Rotating a horizontal line with a gradient 90° (so it appears vertical) will not render its horizontal (seen as "vertical") gradient, just like vertical-line+vertical-gradient; rotating lines [generally effects the gradient badly all around](http://i.imgur.com/eeSo1QR.png).
* I found it interesting that rectangles, which have 90° vertical lines, render vertical (and all) gradients properly (see the first, embedded picture).

I'd imagine these are all somewhat related to the gradient problem..

Browser/OS: Google Chrome 55.0.2883.95 on macOS Sierra (10.12).

**Comment by liam4** [comment]
As a workaround, you can just *slightly* adjust the tip of the line so that it's no longer truly a vertical line, but rather a bent path to which the gradient will apply properly to.

![](https://cloud.githubusercontent.com/assets/9948030/22450895/62a2c4e4-e740-11e6-88af-4d090f51e2e0.png)

**Comment by towerofnix** [comment]
These seem to render properly [in Scratch 3.0](https://llk.github.io/scratch-gui/develop/#196307470) (although only once I go into the paint editor and make any change, e.g. moving the background rectangle a little). So, fixed? 🙃
