### ISSUE TITLE
Sprite image copyright issue and how to import Sprite library images?

### ISSUE THREAD

**Issue by Taeyang-Choi** [LLK/scratch-flash#1275]
Hello!

I make a scratch mod using flash builder.
when I run scratch app, it's not here default Cat sprite and Sprite Library is empty!!
so I've investigated about this problem (keyword: how to import sprite image, no default sprite image, media library is empty, etc ...)
and I've found that empty library is intentional and Cat sprite image haven't to use because copyright

then can't I use All other images except cat image for copyright?
For example Amon, Anna, Bat1, Bat2, Bear1, Beetle, etc ...

And If I have own sprite image instead of Cat sprite image,
How to import default Sprite Image and media library?

**Comment by algmwc5** [comment]
I remember adding the sprites before, I'll try to find it

**Comment by algmwc5** [comment]
cc @mrcomputer1

**Comment by thisandagain** [comment]
Hi @Taeyang-Choi. Assets in the Scratch sprite, sound, and backdrop libraries are not open source. If you would like to make your own project based on a fork of Scratch you will need to source and/or produce your own assets.

**Comment by liam4** [comment]
@thisandagain Yes, but I think they're asking for information on *how* to use the assets that they made:

> And If I have own sprite image instead of Cat sprite image,
> How to import default Sprite Image and media library?

I think they probably meant to say "import *to* the default media library".

You could read it in any way, but I've found very little actual documentation on adding images to a sprite library, which leads me to imagine they just don't know how to use their own images in the media library.

**Comment by beitaz** [comment]
@towerofnix Can you give me some idea？

> How to import default Sprite Image and media library?

**Comment by towerofnix** [comment]
@beitaz There isn't really a simple way. In fact, I've never changed the costume library; but here's some pointers anyways:

* [`MediaLibrary.viewLibrary`](https://github.com/LLK/scratch-flash/blob/35b6a84bfd508c17105d6bf68cd0962a5c8c94a0/src/ui/media/MediaLibrary.as#L286-L325) is the function used to view any media library.
* viewLibrary uses the [`Server.getMediaLibrary`](https://github.com/LLK/scratch-flash/blob/develop/src/util/Server.as#L270-L273) function to get the list of entries.
* getMediaLibrary uses [`Server.getCdnStaticSiteURL`](https://github.com/LLK/scratch-flash/blob/develop/src/util/Server.as#L90-L92) to decide the URL to fetch the list from. If you want to change what domain that uses (perhaps to your own domain), I recommend you add code to [`Server.setDefaultURLs`](https://github.com/LLK/scratch-flash/blob/develop/src/util/Server.as#L69). For example, you could add `URLs.siteCdnPrefix = 'http://example.com'; URLs.staticFiles = '/static';` to make Scratch fetch the URL `http://example.com/static/medialibraries/costumeLibrary.json`. (Of course, you should change `http://example.com` to your own domain; while you're testing, that could just be `http://localhost:8000`, or wherever you're serving your Scratch SWF from.)
* You can look at https://cdn.scratch.mit.edu/scratchr2/static/medialibraries/costumeLibrary.json to write your own `costumeLibrary.json` file. (There are also `soundLibrary.json`, `spriteLibrary.json`, and `backdropLibrary.json` files.
* The images themselves are imported using [`ProjectIO.fetchImage`](https://github.com/LLK/scratch-flash/blob/9fbac92ef3d09ceca0c0782f8a08deaa79e4df69/src/util/ProjectIO.as#L411-L446). This, in turn, calls [`Server.getAsset`](https://github.com/LLK/scratch-flash/blob/9fbac92ef3d09ceca0c0782f8a08deaa79e4df69/src/util/Server.as#L261-L268). Again, this uses some URL strings which you will need to supply in `Server.setDefaultURLs` - in this case, `URLs.assetCdnPrefix` and `URLs.internalAPI`. I suggest you read this function's code so you know how these strings are used.

I have not tested *any* of this; all this is just what I've guessed from browsing the source code for scratch-flash.

(You'll be glad to know that it will be a bit easier to add assets to the media library in Scratch 3.0 - the principle of setting up your own CDN URLs is basically the same, but you can just edit the various files in the [`libraries`](https://github.com/LLK/scratch-gui/tree/develop/src/lib/libraries) folder to add assets. Or even easier, if you know how to get the MD5 of an asset in one of your own online Scratch projects (i.e. by reading the project's source file), you can add that MD5 right into the library file just like that.)
