### ISSUE TITLE
Custom block boolean parameter can be sent 'bad' value after editing spec

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1276]
As follows:
1) Create custom block `test (num)` where 'num' is a numerical input.
2) Create variable "var" and attach `set var to (num)` under definition.
3) Drag custom block caller into editing pane, and click on it.

Result: all fine so far: default value in caller is 1, so variable 'var' ends up as 1.

4) Edit custom block spec so it has a boolean instead of (num), i.e. to become `test <bool>`
5) Change the 'set var' block to `set var to <bool>`, so we see what 'bool' is.
6) Note caller now says `test < >`, so the boolean param is blank (which corresponds to false).
7) Click on caller.

Result: variable 'var' still gets set to 1 – but it should now be "false".
(Note that the boolean parameter 'bool' is supposed to be false, given the blank slot in the caller, but actually has the value 1. And that means in a boolean test it will equate to true – i.e. it'll end up doing completely the opposite of what you're expecting it to do.)

----

Examining the JSON shows what's happening:
`                [79.5, 93.5, [["call", "test %b", 1]]],`
The value of the param being passed into it is still one, from before the spec was changed (and we can make it send text too, if the first param was a string input, rather than numerical, before it was changed to boolean) – but, of course, that's not shown in the boolean param slot in the caller, since it only shows block expressions dropped into it.

----

It's easy to work around in the editor just by dropping something into the caller's boolean param slot (and then removing it) – but it had me really confused for a while in a project I was working on, 'cos I just couldn't understand how it could possibly be acting like the boolean param used in the custom block script was true when its corresponding caller slot was blank!

**Comment by TheLogFather** [comment]
Made a bit of a fun project to demo how Scratch can use this to defy logic itself:
https://scratch.mit.edu/projects/147618731/
:)

(Interestingly, it's kinda related to what was just happening with the "not" block problem in #1284, which is why I managed to get to the bottom of that so quickly...)

**Comment by milad-mehri** [comment]
Nice!
