### ISSUE TITLE
If a clone is deleted while it is being dragged, you can't drag anything ever again

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-flash#1280]
Repro case: https://scratch.mit.edu/projects/145728222/

**Comment by cwillisf** [comment]
When you get to `GestureHandler`'s `drop()` method with a clone that has already been removed, this line throws:
```as3
carriedObj.parent.removeChild(carriedObj);
```

The reason it throws is that `carriedObj.parent` is null -- the clone has already been removed from its parent. It's easy enough to add a check for that, but unfortunately that just moves the problem around. You end up with an orphaned clone on the stage and some really strange behavior around it. I have a feeling that a proper fix wouldn't be too terribly complex, but it'll be more than just adding a check for null :)
