### ISSUE TITLE
Missing assets.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-flash#1286]
The assets are missing from https://scratch.mit.edu/projects/10000098/#editor

console errors:
<img width="793" alt="screen shot 2017-03-03 at 3 04 27 pm" src="https://cloud.githubusercontent.com/assets/399209/23567161/f62c2ef8-0022-11e7-9d1e-91a937fcf00e.png">

**Comment by morantsur** [comment]
Another example:
https://scratch.mit.edu/projects/16616427/#editor

![image](https://cloud.githubusercontent.com/assets/15109618/23567251/70cafa0e-0023-11e7-9a3d-4cc6d1aca2dc.png)

**Comment by jwzimmer** [comment]
Tracking in https://github.com/LLK/scratch-ops/issues/245.
