### ISSUE TITLE
Scratch's boolean operators applied to strings give 'unexpected' results (low-prio, but has very simple fix)

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1288]
If a string is accidentally sent into a boolean custom block parameter, it's possible to get non-sensical results from Scratch (see http://scratch.mit.edu/projects/147618731 ).

This is related to https://github.com/LLK/scratch-flash/issues/1276 (and was also touched on in https://github.com/LLK/scratch-flash/pull/1284#issuecomment-282865943 ).

However, the fix is very simple...
Change the not operator in Primitives.as ([line 58](https://github.com/LLK/scratch-flash/blob/develop/src/primitives/Primitives.as#L58)) to return ````!interp.boolarg(b,0)````, instead of ````!interp.arg(b,0)````.

----

I have to admit that I'm a bit bemused that the "or" and "and" operator primitives seem to be working fine with both string "true" and string "false", as well as string "1" and string "0", even though they are also using "interp.arg"...

It seems as though ActionScript considers ("true" && "true") is true, and ("true" && "false") is false, yet it still considers that !"false" is false. (And similarly !"0" is false even though ("1" && "1") is true, and ("1" && "0") is false.) :/

EDIT: what I wrote above was wrong. See my next comment below. ("true" && "false") actually gives "true", but it's ("false" && "true") that gives "false". Similarly ("1" && "0") gives "1", while ("0" && "1") gives "0".

Since that behaviour seems a bit 'quirky', I'm wondering if it's a good idea to rely on it, and maybe the other boolean operators should also be changed to use interp.boolarg instead of interp.arg?

**Comment by CosmicWebServices** [comment]
https://github.com/LLK/scratch-flash/pull/1289

**Comment by TheLogFather** [comment]
For completeness, I did some further experimenting with strings in boolean expressions.

It seems the way ActionScript deals with strings is as follows:
````(str1 || str2)```` gives str1, unless one of the strings is empty
````(str1 && str2)```` gives str2, unless one of the strings is empty
````!str```` gives false, unless str is empty

In particular, these mean that Scratch gives the following:
````<"false" or "true">```` is "false" (a string)
````<"true and "false">```` is "true" (a string)
````<"0" or "1">```` is "0" (a string)
````<"1" and "0">```` is "1" (a string)
````<not "false">```` is false (a boolean)
````<not "0">```` is false (a boolean)

The last two are the original title of this issue, but the others are also 'unexpected'.

They are all 'fixed' by switching "interp.arg" to "interp.boolarg" for these logical operators in Primitives.as.

In particular, Scratch currently returns a string value for the AND and OR operators if both inputs are non-empty strings. Switching to 'boolarg' means the return value is always boolean.
