### ISSUE TITLE
Picoboard Browser Support

### ISSUE THREAD

**Issue by michaelcaplan** [LLK/scratch-flash#1293]
Hi There,

I'm looking for some advice. My understanding is that with NPAPI being removed in Chrome an Firefox, options for using the Picoboard with any contemporary browser are currently nil (IE seems to not work for me either). I gather that the only option is to use the AIR based Scratch 2 Offline Editor.

I'm trying to find the source for the original NPAPI plugins to see if I can hack together a solution that will work with contemporary firefox and chrome.

Any pointers?

Thanks,

Mike

**Comment by cpseager** [comment]
The Chrome extension already works ok as it is not NPAPI based, but does not work with firefox as it is a Chrome only extension.

![capturepicoboard](https://cloud.githubusercontent.com/assets/7423187/24079692/91e5e082-0c85-11e7-9d6f-3bd7da61035c.PNG)

**Comment by michaelcaplan** [comment]
Well then!  I am happily mistaken about the state of support in Chrome!  

To be sure, are you aware of the state in Firefox and IE and Edge?  I thought that the recent removal of NPAPI in Firefox ment that the picoboard is dead in that browser.  Never had luck with IE.

**Comment by thisandagain** [comment]
@michaelcaplan We are. We'll be addressing inconsistent browser support for extensions more thoroughly in Scratch 3.0 via the Scratch Device Manager.
