### ISSUE TITLE
List Watcher Grows on Drag

### ISSUE THREAD

**Issue by Airhogs777** [LLK/scratch-flash#1297]
When the editor is in small stage view, sometimes dragging a list watcher causes it to double in size. This only appears to happen when 3D rendering is on

![out](https://cloud.githubusercontent.com/assets/2879020/24842767/29eaaafa-1d59-11e7-818a-ee633d591d4c.gif)
latest Chrome, OSX 10.12.1

**Comment by TheLogFather** [comment]
Duplicate of #958

**Comment by Airhogs777** [comment]
Oops my bad, I only looked for list watchers when looking for dupes
