### ISSUE TITLE
Cloud monitor logs currently unavailable?

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1298]
Unable to see any cloud data history on any cloud-enabled project – just get the spinning blue thingy...
(Is anyone managing to see any cloud logs?)

**Comment by thisandagain** [comment]
@colbygk @rschamp This may be some more fallout from the power outage this morning.

**Comment by TheLogFather** [comment]
OK, looks like it's working now, going back to ~20mins ago.
(Everything before that is now gone, I'd guess...?)
