### ISSUE TITLE
https://github.com/LLK/scratch-flash/issues/782

### ISSUE THREAD

**Issue by Johnlon** [LLK/scratch-flash#1300]
How can I comment on issue 782?

I wanted to add this ...

There a lot of discussion here but has anyone put together a structured and comprehensive list of the challenges that would need either to be addressed or just written off and accepted as consequences?

Potential solutions can then be measured against that score card.

We should probably also accept that no solution will likely be perfect and apply the 80/20 rule here.

What's the simplest thing that will avoid the cost/effort of maintaining masses of cut and paste without introducing excessive complexity, **for most use cases**.

It would seem that the treatment given to variables that can be local/global or "cloud" present a precedent/guide here.

-- 

My own starter ....

How to represent the new concept visually?
NB Don't use the word "global" on the UI - use "shared".
Use the same "all sprites" / "this sprite" definition scheme as used for variables.

What to do with refs to Shared Blocks when exporting a sprite with a ref to a "Shared block"?
Resolve the problem away by providing the option of converting any shared scripts during export into sprite local scripts, or alternatively just accept the hassle that any ref to shared blocks will be dangling refs and provide a scheme in the tool to repair those refs by adding the missing "shared blocks".
Anyway isn't the basic requirement to be at least consistent to what happens when one exports a script that refers to a global var - what's the min requirement here?

How to avoid naming collisions?
Well what happens if I attempt to create a global var that would eclipse a local var? 
I get a message saying that the var name is already in use - so do the same with shared scripts.

Shared blocks would need an implicit parameter - ie the Sprite at the site of use.
It would seem that in order for shared blocks to be useful one would need such blocks to support an implicit parameter type of "Sprite".
All sub blocks used within the shared block would be implicitly applied to the scope of the sprite at the site of use.

Also ...

Re "ntlrsk commented on Jul 12, 2015"
"A possible workaround (which would be a simple addition to the current model) is to be able to right-click on a define script (e.g., "define dance") and update all the define scripts with the same name in any other sprite. They would still be local definitions (and thus easy to see and change) but at least a way to update them all so they're the same. Thoughts?"
This is a sensible compromise but what happens when we have two sprites with accidentally similar block names?
So allow the user to select which sprites to copy/apply the change to - this is still better than the current approach as it simplifies the cut and paste effort.
This doesn't get rid of the horrible anti-pattern of cut and paste but it does make that approach more practical/scalable.

**Comment by thisandagain** [comment]
@Johnlon We are not accepting any new features in Scratch 2.0. Issue #782 was closed for discussion while we weigh options and priorities.
