### ISSUE TITLE
Character encoding issues in costume editor

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#1303]
When writing text in the costume editor, the wrong character encoding is used. This happens both in the vector and bitmap modes.

In the screenshot below, I am trying to replace "PLUTO" with "Plùto", which gives me a pretty Cyrillic character instead of the ù.

![scratch-encoding](https://cloud.githubusercontent.com/assets/4095570/25737786/92642454-3171-11e7-811b-42358821b096.PNG)

OS: Windows 7, German langue, Scottish Gaelic locale
Browser: Firefox 53.0 (32-bit), Scottish Gaelic language, Shockwave Flash 25.0.0.148

**Comment by maxiostro** [comment]
Also, in the costume editor the letter Ñ can't be used in some fonts, it is replaced by a C. Also, there aren't available the letters á, é, í, ó, ú, Á, É, Í and Ú (frequently used in Spanish). All this characters belongs to the Spanish language. Add UTF-8 to the costumes editor.
