### ISSUE TITLE
Saving a costume to file omits file extension

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#1306]
To reproduce:

* Right-click on a costume
* Choose the save to file option
* Enter a filename without extension and save

This will create a file without extension, which is a problem for Windows users. The editor should automatically add the png/svg file extensions if they haven't been specified by the user, avoiding accidentally creating duplicate file endings like `.png.png` or `.PNG.png` in the process.

**Comment by cwillisf** [comment]
Unfortunately this is a limitation of Flash: depending on the version of Flash you're using the dialog may or may not enforce the file extension. We're providing Flash as much information as we can through the current API.

For example, this is what it looks like on my system. If I just type in "foo" (with no extension) and click "Save" then I end up with "foo.svg" in this case.

![image](https://cloud.githubusercontent.com/assets/7019101/25874975/f6de7690-34c9-11e7-9dc9-46d25c69efc5.png)
