### ISSUE TITLE
[low-prio] Inconsistent treatment of case in broadcast names

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1309]
Probably worth having this noted somewhere, to ensure it's dealt with eventually...

See https://scratch.mit.edu/discuss/post/2218655/

**Comment by cwillisf** [comment]
Ah, thanks @TheLogFather!

Copied from the forum post:
> Triggering of the receiver script itself is not case sensitive – you can broadcast message “A” and receive it as “a”.
> Also, you cannot rename to a different cased version of a name that already exists, so rename is also case insensitive when it checks for pre-existing names.
> 
> However, it does allow you to *create* a different cased version of an existing name, and they are shown as two separate names in the dropdown list.
> 
> Also, ‘show receivers’ for a particular message will find sprites/stage that has/have different cased versions of the same name, while ‘show senders’ does not.
