### ISSUE TITLE
Feature idea: "move to center and show" menu option for sprites

### ISSUE THREAD

**Issue by asweigart** [LLK/scratch-flash#1310]
While Scratch does a good job making sure that sprites don't move off the side of the stage, sometimes in the programming classes I teach the students will still "lose" their sprites. Either a tiny bit of the sprite is visible on the side of the stage, or they've hidden it.

For now, I tell them to add a "go to x 0 y 0" and "show" block to their sprites temporarily and then run them. However, it would be much more convenient if there was a menu option added to the Sprites Area called "move to center and show" (or something similar) that would do this for them. The students would then be able to find their sprites without changing the code.

I've attached a demo screenshot of what this could look like:

![centerandshow](https://cloud.githubusercontent.com/assets/52220/26029819/90f25c3e-37f3-11e7-95bc-f1d1d77e0ee4.png)

**Comment by jwzimmer** [comment]
Thank you for the suggestion @asweigart! We labelled this "feature" and are backlogging it for consideration as we develop Scratch 3.0.
