### ISSUE TITLE
[Translation] Strings for translations are sorted alphabetically, robbing them of their context

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#1311]
I would like to revise my translations for the musical instruments, because I have just done some terminology work on a music-related project. However, I can't find them easily, because translations are sorted alphabetically in the .po file. This means that I would have to scroll slowly through all the entries and look at them very carefully so I won't miss any of them. This is too much work, so it's not gonna happen any time soon.

It's also a hindrance for new translations, because important context information is eliminated.

Please sort by source file occurrence if possible at all.

**Comment by chrisgarrity** [comment]
@gunchleoc, thanks for the feedback. We probably won't get to this for the current editor as we're focusing on the next version of Scratch (3.0). However, we're in the process of thinking about translation for the new version, and this is definitely something we'll keep in mind.

**Comment by gunchleoc** [comment]
If you're using *xgettext* to pick up the strings, just remove the `-s` or `--sort-output` option and run it again and then call `tx push -s` - this doesn't need any big code changes at all.

Since Scratch is used in the schools, I think correct terminology is important. I estimate that going through the file like it is would take about an hour, while changing and running the xgettext command should take about 5 minutes ;)

**Comment by chrisgarrity** [comment]
Since the 2.0 editor has been frozen for years we're not even generating new po files for the editor at all, and there's no documentation of how the file was generated originally. I know it's frustrating, but it's definitely going to take me more than 5 minutes to figure out who, if anyone, currently on the team knows how the file was generated, and then figure out how to regenerate it.

**Comment by gunchleoc** [comment]
I grepped the project now and no xgettext, so you're right, it's not that trivial :(

**Comment by chrisgarrity** [comment]
I had the same instinct - it should be easy - sadly that wasn't the case. On the plus side I'm definitely thinking about these ergonomic factors for the Scratch 3.0 translation.

**Comment by gunchleoc** [comment]
Since you have this in mind now, Let's close this as won't fix.

Too bad the original developer didn't create any documentation for this - another thing to keep in mind.
