### ISSUE TITLE
How to build it in Flash Builder？

### ISSUE THREAD

**Issue by scris** [LLK/scratch-flash#1313]
Someone built it in Flash Builder.
But I don't know how to build it in Adobe Flash Builder.
If I want to do that,what should I do?

**Comment by cwillisf** [comment]
Hi @scris! The scratch-flash repository is set up to build using `ant` or `gradle`; building with Flash Builder is not supported. I'm sure there's a way to do it but I don't know the details.

For instructions on building with `gradle`, see the repository's README:
https://github.com/LLK/scratch-flash/#readme
