### ISSUE TITLE
[low-prio] Bizarre failure of equality test (ActionScript cast of string to Number?)

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1315]
Certain long strings of digits (e.g. one followed by >1252 zeros) can end up apparently being equal to zero. (One followed by only 1252 zeros is not equal to zero.)

Test project here: https://scratch.mit.edu/projects/159326497/

More info here: https://scratch.mit.edu/discuss/post/2635896/

Some thoughts on what might be happening: https://scratch.mit.edu/discuss/post/2649207/

Note that "1.0000... _[total of 1253 zeros]_" is also equal to zero.

**Comment by chooper100** [comment]
At least this issue doesn't occur in Scratch 3:
https://llk.github.io/scratch-gui/#159326497
