### ISSUE TITLE
New feature: Numeric line width indicator

### ISSUE THREAD

**Issue by asweigart** [LLK/scratch-flash#1319]
As a teacher, I sometimes have to instruct (or write out instructions) for the students to draw lines of a certain width. It'd be helpful if the line width slider had a numeric indicator for the current width. Then instead of telling them "slide the line width slider mostly to the right but not all the way" I could say "slide the line width slider to 24".

This is, of course, a low priority suggestion.

**Comment by rschamp** [comment]
Moved to LLK/scratch-gui#430
