### ISSUE TITLE
Quick feature request about cloud data

### ISSUE THREAD

**Issue by encloinc** [LLK/scratch-flash#1320]
I recently came up with the idea of a secondary cloud data server reserved for people who need the fast performance on their projects (Its gonna send and accept cloud data requests at websocket speed). I will personally host this server free of charge, but I need the ST to make a small experimental feature to change the server the project is listening to. Is this possible?

**Comment by ModernFeelGames** [comment]
That would be very cool. Please implement that scratch.

**Comment by MooShoe** [comment]
I'll help pay for the servers.

**Comment by encloinc** [comment]
Perfect!

**Comment by ModernFeelGames** [comment]
Im sure MIT owns servers...

**Comment by rschamp** [comment]
@encloinc We're going to have a new cloud data infrastructure Very Soon™ which will use websockets, so keep an eye on cloud data in the next couple of months!

@MooShoe Thanks for the offer! https://secure.donationpay.org/scratchfoundation/
