### ISSUE TITLE
Slovak translation is missing translated strings.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-flash#1322]
![Screen Shot 2017-06-13 at 9.08.30 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/bafa1e50-873d-40e5-ab2a-1c2b2f6098f2/Screen+Shot+2017-06-13+at+9.08.30+AM.png)

In Transifex the glide string is translated:
kĺž sa %n s na x:%n y:%n﻿
https://www.transifex.com/llk/scratch-legacy/translate/#sk/editor-full/103105521?q=glide

In scratchr2_translations the string is translated (updated 11 days ago):
https://github.com/LLK/scratchr2_translations/blob/master/legacy/editor/static/locale/sk.po

But it's not translated in either the online or offline editor.

**Comment by cwillisf** [comment]
The locale files used by the editor have `%ns` in them instead of `%n s`, which is causing the editor to reject the string:
https://github.com/LLK/scratchr2/blob/develop/static/locale/sk.po

**Comment by chrisgarrity** [comment]
Yes, it looks like someone fixed the %ns about 11 days ago - but we didn't pick up the corrections.

**Comment by thisandagain** [comment]
For some reason this wasn't resolved in the translation deploy on Tuesday. Marking as "prio-critical" and assigning for investigation.

**Comment by rschamp** [comment]
Fixed with the deploy today.
