### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by scris** [LLK/scratch-flash#1325]
Would like to ask a question: I use the source to export a SWF, and then I embed it into the page (yes, i used swfobject), then i tried to let swf be able to use my language pack (.po), how can I do?Thanks.

**Comment by CosmicWebServices** [comment]
Try asking this in the advanced Forums on scratch that might be of better use for you.

**Comment by chooper100** [comment]
As the forums have now been removed from the top navigation, here is a direct link for you:
https://scratch.mit.edu/discuss/31/

**Comment by scris** [comment]
@CosmicWebServices @chooper100  Oh I know how to do,thanks.
