### ISSUE TITLE
Cloud has 'vanished'...?!

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1326]
Can't connect to any varserver URL.
No cloud monitor link on cloud-enabled projects.
Can't create cloud variables (no option available in 'New Variable' dialog).

May be related to site outage a few hours ago...?

**Comment by rschamp** [comment]
Hi @TheLogFather, yes it's related to the site outage. We are working to restore service to the cloud data system, but it may not be back until tomorrow at the earliest. Sorry for the inconvenience.

/cc @colbygk @thisandagain

**Comment by rschamp** [comment]
@TheLogFather This should be fixed now.
