### ISSUE TITLE
The window was all white

### ISSUE THREAD

**Issue by abc2237512422** [LLK/scratch-flash#1327]
My Scratch couldn't work,it didn't display properly. The window was white.Press it no response.Why is this so?How can I solve it?
Thanks.

**Comment by christan1029** [comment]
What browser are you using? Does this issue persist even after a refresh?

**Comment by abc2237512422** [comment]
Forgot to say, there was the offline version of the problem,sorry.

**Comment by christan1029** [comment]
Make sure your Adobe Air is updated to the latest version. Also, make sure your documents folder is accessible. 

https://scratch.mit.edu/discuss/topic/80744

This user had the same issue. "I had the “my documents” folder in the registry set to a location that didn't exist yet."

**Comment by abc2237512422** [comment]
I installed the Adobe Air.The issue is solved.Thank you.

**Comment by rschamp** [comment]
Thanks for posting the solution @abc2237512422
