### ISSUE TITLE
Drum sounds continue playing their sample well after beat time in block ends

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1328]
In particular, in drum sounds with long samples (such as "Crash Cymbal" and especially "Conga") this can mean you reach the limit of 32 sounds being played at once (which is the Flash sound channel limit).

See this topic: https://scratch.mit.edu/discuss/topic/270330/
And related project: https://scratch.mit.edu/projects/168821897/

See this post for discussion about the cause (and how to work around it with "stop all sounds"):
https://scratch.mit.edu/discuss/post/2726426/

It might be nice if it were possible for Scratch to prioritise sound channels a bit – for example, if a new channel is requested, and there are already 32, then it looks to see which one has been running longest (or is nearest to ending?) and 'kills' it.

In particular, though, it seems a bit odd that the "Conga" drum sample is so long.
Could it be shortened in some way?

**Comment by DevanWolf** [comment]
Maybe set drum length to 8 or 4 seconds on the source code.
