### ISSUE TITLE
Don't write russian letter(Localization)

### ISSUE THREAD

**Issue by SimaDuck** [LLK/scratch-flash#1330]
Don't write russian letter in editor(Paint)

**Comment by rschamp** [comment]
Can you elaborate?

**Comment by SimaDuck** [comment]
It is impossible to write the Russian text, no font supports it

28 июля 2017 г. 17:36 пользователь "Ray Schamp" <notifications@github.com>
написал:

**Comment by cwillisf** [comment]
Thanks @SimaDuck! Unfortunately, this is a tricky problem to solve in Scratch 2.0. If you'd like, you can join in the ongoing discussion regarding non-Latin fonts in the paint editor here: #231
