### ISSUE TITLE
Use HTML5 Player

### ISSUE THREAD

**Issue by SimaDuck** [LLK/scratch-flash#1331]
Why do not you use HTML5 to view the project? And for editing, you could switch to Flash 
This will add a bit more speed OR phosphorus player

**Comment by CosmicWebServices** [comment]
Flash is not truly dying until late 2020 but development of Scratch 3 is HTML5 (see scratch-gui repo). Development of an HTML5 player for the current scratch was canceled but there is an incomplete repo for it. Until then there is no point.

**Comment by SimaDuck** [comment]
I say that you can use it on the site, because with HTML5 it's faster. Flash it develops like HTML.

**Comment by CosmicWebServices** [comment]
Not really Flash has it's own language and requires Flash player one cannot simply run it it HTML5

**Comment by OctoPenguin** [comment]
Flash is dying in 2020. Scratch 3.0 will include an HTML5 player.

**Comment by thisandagain** [comment]
We are currently working on Scratch 3.0 which is HTML5 based. The prior HTML5 player was never feature complete and had issues which lead us to discontinue development. If you are interested in our work on Scratch 3.0 I recommend taking a look at our current progress here: https://github.com/llk/scratch-gui
