### ISSUE TITLE
Is this the full Scrath Offline Editor?

### ISSUE THREAD

**Issue by OctoPenguin** [LLK/scratch-flash#1332]
I'm working on a project that will port the Scratch Offline Editor _away_ from the Adobe Integrated Framework for Linux functionality. Is this the full editor or is there proprietary code we don't know about?

**Comment by thisandagain** [comment]
Yes, this is the full editor. If you are interested in our work on Scratch 3.0 I recommend taking a look at our current progress here: https://github.com/llk/scratch-gui
