### ISSUE TITLE
[Cloud] Rare failure causes cloudvar reset to zero?

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1333]
Over the years, I've heard occasional mention of cloudvars getting reset to zero for no apparent reason, right after seeing the message about cloudvars only being able to store numerical values – even though the values placed in the cloudvar were always meant to be numerical.

Previously I've tended to put it down to some potential error in the scripting when constructing the cloudvar (and that may still often be the case).

However, I just had it happen in one of my own projects, even though what it does is pretty simple (add a digit to the end of the cloudvar): https://scratch.mit.edu/projects/24934494/

Also, the user reported exactly what happened (just clicked the cat to add the digit, as instructed):
https://scratch.mit.edu/projects/24934494/#comments-80000206

The entry in the cloud log reports the user (@Kooldude183) set "long cloudvar" to zero on Mon, 31 Jul 2017 01:46:58 +0000 (followed by a couple of entries for other cloudvars that don't really make that much sense to me).

It also shows the same user had successfully added a digit to the long cloudvar a couple of seconds before the failed attempt.

If there is some kind of occasional glitch in the cloud system, then perhaps it could be worth looking in more detail at your own internal server logs (given above provides an exact time for the event) to see if there might be some clues about this issue...?

[BTW, I just realised github comments changes all letters following the @ symbol to lower case.
E.g. "@" followed by "DadOfMrLog" –> @DadOfMrLog.
Doesn't really matter, I guess, but curious anyway...
Ah... interesting... looks like it's for users that don't exist in github. So @TheLogFather works fine, and even gets changed to bold and turned into a link. That makes sense, but still not clear why non-existent usernames should end up lower...]

**Comment by thisandagain** [comment]
We are in the middle of testing the next version of the cloud vars server. We'll check this during our testing process.

**Comment by TheLogFather** [comment]
I guess this is partially covered by #1348, since the cloudvar gets reset to zero when the client(?) spuriously detects an attempt to set to a non-numeric value.
In that case, the problem is with the client itself actually sending zero as the value, rather than just ignoring it and leaving the current value intact.
(Though it still doesn't explain why the client thinks the value is not numerical...)
