### ISSUE TITLE
Duplicate costume size error

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-flash#1342]
I will quote Scratch user armageddon6 here:
>I have not been able to find any previous postings on this issue so hope someone can help me out.
>
>I am just about to complete a project and the last 3 sprites I need to create require and alternate state which i wanted to achieve with an additional costume. My project is 6.7mb in size completely but when I try duplicate a costume on an existing sprite i get the following message:
>
>Adding that media asset would put this project over the size limit by 57054 KB
>Please remove some costumes, backdrops, or sounds before adding additional media.
>OK
>
>A 6.7mb file will increase in size by at least 57mb just by duplicating a costume?
>
>The thing is I can duplicate the sprite many many times without any issue or messages. The same sprite I am trying to duplicate the costume on.
>
>Any ideas? It is all that is holding me back.

(Original post: https://scratch.mit.edu/discuss/post/2786688/)

**Comment by jwzimmer** [comment]
Hi @Kenny2github, armageddon6 wrote to us via the contact us page, so I will respond to them there. We think we have figured out what is going on - a combination of https://github.com/LLK/scratch-flash/issues/1347 and the fact that their project used a lot of identical assets that are de-duped when the project was saved locally as an sb2 file (causing the file size to be under the size limit) but do exist as separate copies in memory when the project is running in the Scratch editor (causing the project to be over the size limit). Thanks!
