### ISSUE TITLE
What is the password from the Developer Mode?

### ISSUE THREAD

**Issue by SimaDuck** [LLK/scratch-flash#1343]
And why the password?

**Comment by thisandagain** [comment]
@SimaDuck can you please clarify your question?

**Comment by SimaDuck** [comment]
Well, in the editor, you press Shift on "Edit" and in the "Developer mode"

**Comment by SimaDuck** [comment]
Well, in the editor, you press Shift on "Edit" and in the "Developer mode"

**Comment by SimaDuck** [comment]
Well, in the editor, you press Shift on "Edit" and in the "Developer mode"

**Comment by SimaDuck** [comment]
Well, in the editor, you press Shift on "Edit" and in the "Developer mode"

**Comment by towerofnix** [comment]
Are you certain you're not using a mod of Scratch 1.4? I know many Scratch 1.4 mods added a "password" to stop people from getting into the developer mode easily, but I don't think any official Scratch versions did (1.4 or 2.0 -- this repository, scratch-flash, is about 2.0, by the way).

**Comment by thisandagain** [comment]
That feature is not included in any of the currently supported versions of Scratch (1.4, 2.0, or 3.0 pre-alpha).
