### ISSUE TITLE
[website] Text overflow on credits page

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#1344]
The contributor lists don't fit on the cretis page, because line breaks are being blocked.

![scratch-credits-string-overflow](https://user-images.githubusercontent.com/4095570/29519732-56b577c8-8676-11e7-9df2-01b1c50d8980.PNG)

My browser / operating system: Windows 7, Firefox 55.0, Flash 26.0 (release 0)

Posting this here so I won't have to bother with image hosting for the screenshot ;)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-www#1470
