### ISSUE TITLE
Dropdowns & inputs missing values when editor set to Spanish

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1346]
Reported via freshdesk no. 89126:
> I can not program from the web because the web editor does not work and all the refillable blocks, their letters are blank instead of their original color

They also attached a video (see ticket).

I think the language shown is Spanish; I asked the reporting user and will update if that is not correct.

I have not verified if this is specific to the online editor only or if it also occurs in the offline editor.

<img width="534" alt="screen shot 2017-08-23 at 3 31 52 pm" src="https://user-images.githubusercontent.com/1320456/29634921-6521413a-8819-11e7-826a-e265a3a1530f.png">

When I view the editor in Spanish (Chrome 60, Mac OS El Capitan, Production), the values are not missing from the dropdowns/ input fields, but I have asked the user for their OS/ Browser so we can try it there.
<img width="247" alt="screen shot 2017-08-23 at 3 41 55 pm" src="https://user-images.githubusercontent.com/1320456/29635034-c69b79b2-8819-11e7-8cea-4a5bf6cd2935.png">

**Comment by jwzimmer** [comment]
Reporting user responded with their metadata:
> My operating system is windows 10, with version 1703
> My browser is firefox, with version 55.0.2 (32-bit)
> And the scratch language I have defined is Spanish (Spain)

I will try to repro using this info.

**Comment by jwzimmer** [comment]
I'm not seeing this issue in Win 7 VM + Firefox 55.0.3 (latest) and language set to Spanish.

**Comment by naradi** [comment]
I recall having a similar problem, on windows 7 with Firefox, but it turned out to be connectivity problems in my case. It may be advisable to request information as to how long the user has experienced this error.

**Comment by jwzimmer** [comment]
Thanks @naradi 👍

**Comment by Kenny2github** [comment]
From the screenshot it looks like the problem is simply that all the text is white instead of some being dark-colored (like inputs and sprite names are white instead of dark). Could that be related?

**Comment by chrisgarrity** [comment]
It does look like it could be an issue with white text on a white background, but this is in the flash editor, so I think that's less likely. We had a similar problem with the language selector in scratch-gui on windows, but that UI is HTML.

**Comment by Kenny2github** [comment]
Yeah I know about that issue (I fixed it :P).

Look how the sprites and category names also have white text - normally that should be dark.

**Comment by jwzimmer** [comment]
The reporting user replied with diagnostic info.
