### ISSUE TITLE
Cloud variables are reset to 0 when attempting to set to non-number value

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-flash#1348]
### Expected behavior
When you try to set a cloud variable to (let's say a string) it should just say "Currently, only numbers are supported in cloud variables" and do nothing to the value.
### Actual behavior
When you try to set it to a string it pops up the message and sets it to 0 instead.
### Steps to Reproduce
1. Set a cloud variable to a non-zero number.
2. Try to set it to a string.
3. The popup appears and the value is set to 0.
### Operating System and Browser
Chromium 57.0.2987.98 Flash N/A (on Raspbian Desktop) Operating system Raspbian Jessie Pixel Desktop

**Comment by thisandagain** [comment]
Hi @Kenny2github is this issue with the new cloud variables system or the existing production version? See: https://github.com/LLK/scratch-flash/issues/1211#issuecomment-324073462

**Comment by jwzimmer** [comment]
This occurs with or without `?newcloud` in the URL (so, in both old & new systems). (Repro'd on Production, Chrome, Mac OS El Capitan.)

**Comment by Kenny2github** [comment]
@thisandagain I tested this on the existing production version - but noting @jwzimmer's comment above this seems to be unrelated to platform or cloud system.

**Comment by colbygk** [comment]
This is behavior that is in both the old and new cloud data. There is a warning message about "Currently, only numbers can be stored in Cloud variables" when setting a variable to a non-number and it does indeed set the value of the variable to zero instead of leaving it at its current value. I'm refiling this against that repo (which is currently private).

**Comment by TheLogFather** [comment]
I'm not surprised it's both old & new, since it looks to me as though it's the client that sends the zero to cloud when it 'decides' the new value is non-numerical.
It's a fix in the client, rather than in the cloud system itself, I think...

**Comment by colbygk** [comment]
Moved to LLK/scratch-flash-online#325
