### ISSUE TITLE
Monitor checkmarks in state mismatching what's displaying on stage

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1350]
The monitor checkmarks in the block palette appear to be unchecked, but the monitors are being displayed on stage.

On Staging or Production if you re-upload/ view this project: 147084704 (Chrome, Mac OS El Capitan). 

To **repro**, view that project and go to the Sensing tab. Note "video motion on this sprite" and "current minute" don't have checks in their boxes.

<img width="1193" alt="screen shot 2017-08-28 at 3 58 23 pm" src="https://user-images.githubusercontent.com/1320456/29791170-0898c344-8c0a-11e7-8434-3eca3a01da88.png">

**Comment by naradi** [comment]
Just for a sanity check, the error persists after you press the green flag, correct?

**Comment by jwzimmer** [comment]
@naradi Yes, it does. The issue goes away if you check the boxes/ uncheck them - they'll return to working as usual.

**Comment by Kenny2github** [comment]
@jwzimmer:
This issue, I think, is present for any reporter block with a dropdown that has a checkbox.

For "current [time v]":
1. Change the dropdown to "minute" and check the box. The watcher for "minute" will appear on stage.
2. Change the dropdown to "hour" and click the checkbox again. The checkbox *will remain checked* and the "hour" watcher will appear on stage.
3. Click the checkbox again. The checkbox *will become unchecked* and the "hour" watcher will disappear from the stage.
4. Change the dropdown to "minute". The "minute" dropdown will remain on stage and *the checkbox will still be unchecked*. This is where, I think, you're seeing this inconsistency.
5. If you then click the checkbox again, it will *remain unchecked* and the "minute" watcher will disappear.

For "video [motion v] on [something v]" it's essentially the same - replace cases "minute" and "hour" above with "this sprite" and "stage".

Does this clear it up?

**Comment by jwzimmer** [comment]
Thanks @Kenny2github, that's very helpful! 👍

**Comment by TheLogFather** [comment]
This is effectively a duplicate of https://github.com/LLK/scratch-flash/issues/1125

**Comment by jwzimmer** [comment]
Thanks @TheLogFather, closing this to track in #1125.
