### ISSUE TITLE
Sprite name reporter

### ISSUE THREAD

**Issue by PiotrGrochowski** [LLK/scratch-flash#1354]
It may seem funny, but there is no way to use sprite names as values. That means we can't say sprite name, or get the third letter for example.

**Comment by towerofnix** [comment]
I think the most graceful way to make this possible would be to add a `myself` option to the second input in the ![attribute of](https://user-images.githubusercontent.com/9948030/29980199-18c02740-8f1f-11e7-8623-171987bfc47d.png) block, and add a `name` option to the first input; then you could do something like this:

![letter 3 of name of myself](https://user-images.githubusercontent.com/9948030/29980226-3a7bdb04-8f1f-11e7-9b63-061dc23d8794.png)

**Comment by PiotrGrochowski** [comment]
This can be useful if you have a lot of sprites with number in it, and you want a script that easily copies to all of them.
