### ISSUE TITLE
Cloud is down –v457 trying to use websockets now?

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1355]
I'm getting no connection to cloud for any cloud-enabled project (_without_ the "?newcloud").

The "Connecting to cloud data server..." window appears for a long time (much longer than usual), eventually disappearing, but then no values from cloud in cloudvars (only in-project values).

The console log in Safari shows the following:

    [Error] WebSocket network error: The operation couldn’t be completed. Operation timed out
    [Error] Websocket closed, code:1006 reason: [Error] TypeError: Scratch.FlashApp.ASobj.ASonCloudDataClose is not a function. (In 'Scratch.FlashApp.ASobj.ASonCloudDataClose()', 'Scratch.FlashApp.ASobj.ASonCloudDataClose' is undefined)

And in Firefox:

    "11:33:45 AM | inf | Connecting to cloud data server" Object { server: "clouddata.scratch.mit.edu" } 172591974
    Firefox can't establish a connection to the server at wss://cloud.scratch.mit.edu/. project_base.js:1
    TypeError: Scratch.FlashApp.ASobj.ASonCloudDataClose is not a function project_base.js:1
    "Websocket error: [object Event]" project_base.js:1
    JScloudDataConnect/this.cloudDataConnection.onerror() project_base.js:1
    "11:34:05 AM | wrn | Connection Error for Cloud Data Server" 172591974
    "Websocket closed, code:1006 reason: " project_base.js:1
    JScloudDataConnect/this.cloudDataConnection.onclose()

Is this new with the v457 update? Is that set to only try to use the new websockets connection? (But it goes wrong because it's trying to connect to clouddata.scratch.mit.edu instead of varserver2.scratch.mit.edu like it does with "?newcloud" in the URL?)

**Comment by thisandagain** [comment]
Sorry about that! Resolved (HT @rschamp @cwillisf @colbygk)

**Comment by TheLogFather** [comment]
Ah, OK, great – downgraded back to 456 I see...
