### ISSUE TITLE
Shift issue

### ISSUE THREAD

**Issue by PiotrGrochowski** [LLK/scratch-flash#1363]
On my EE remake (https://scratch.mit.edu/projects/168423636), shift-click is supposed to erase. However, it acts like a standard click. Inside, it acts like a right click. Happens in IE and MF. In offline 2.0, it works, but still acts as a right click.

**Comment by towerofnix** [comment]
I'm pretty sure the shift key can no longer be detected by Scratch 2.0, as of #1345. You'll have to check for a different key being pressed while dragging.

**Comment by griffpatch** [comment]
You can still detect shift using a hacked block as before, but instead of a
value of 0, you need to look for 16. There's a working project on my
@griffpatch_tutor account.

**Comment by PiotrGrochowski** [comment]
But I can't change that, I'm banned!

**Comment by PiotrGrochowski** [comment]
IE means Internet Explorer
MF means Mozilla Firefox

**Comment by towerofnix** [comment]
I mean, I don't think it's too big of a breaking change, considering it's a not-so-well-known hack.. it's too bad you can't do anything about it because that account is banned, but it seems okay to not take into account the very, *very* small number of projects which will be broken by this and cannot be fixed because the creator is banned or inactive. If you have access to another Scratch account (assuming you've already dealt with this ban, and you're not allowed to use that account but you're permitted to use other accounts) maybe you could remix the project with the fix?

**Comment by PiotrGrochowski** [comment]
My original account is piotrgrochowski (haven't found the ban reason), and all other my accounts are also banned for being alts. Making an account is a short-term solution as it will be banned sooner or later.

**Comment by towerofnix** [comment]
Then the only solution is to look for and deal with the ban reason and update the project when you regain the account (or another one).

**Comment by PiotrGrochowski** [comment]
Most users are banned from Scratch. A ban is permanent. I don't think I can regain an account long term.

**Comment by towerofnix** [comment]
Most users are not banned from Scratch. In fact, [I can name 250,000 users who were active in September.](https://scratch.mit.edu/statistics/) I can also say that virtually all Scratchers I personally know who got banned were also later unbanned after contacting the Scratch Team. No reason to "not think" you can regain an account long term; assuming you personally think it's fair or right for you to have a Scratch account, you should give contacting them a shot.

However, a lot of people *used* to use Scratch and don't anymore. Some projects of these people used the shift sensing hack, so those projects are broken until somebody else creates a remix.

**Comment by PiotrGrochowski** [comment]
You are lying. Most users are banned from Scratch. And I could never get unbanned by any way from contacting. Therefore a ban is permanent.

**Comment by thisandagain** [comment]
This has gotten extremely off-topic so I am going to lock this issue.

To help resolve this, let's use some facts: of the 21.5M users on Scratch only 120,391 of them have ever been banned (either temporary or permanent). That works out to roughly 0.056% of all users. That is a long ways away from "most" (e.g. greater than 50%).

**Comment by thisandagain** [comment]
Tracking in GH-1361
