### ISSUE TITLE
Javascript injection of block color files

### ISSUE THREAD

**Issue by ZenithRogue** [LLK/scratch-flash#1367]
It would be a nice feature to be able to inject a .color file into any active project using javascript. Currently (AFAIK) the only way to load them is via the hidden menu.  I have a userscript that could really use this feature.

**Comment by thisandagain** [comment]
Thanks for the suggestion @NitroCipher. We are no longer accepting new features for Scratch 2.0, but Scratch 3.0's blocks can be styled with user stylesheet / userscripts.

**Comment by ZenithRogue** [comment]
I already wrote a userscript to style 3.0 =P
