### ISSUE TITLE
Support import of OGG files

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-flash#1368]
Can you add support to .OGG files?

**Comment by Kenny2github** [comment]
Scratch 2.0 is in maintenance mode as the Scratch Team need to devote their time to Scratch 3.0. Feature requests and bug reports will not be considered unless they are labeled `prio-high` or above.

**Comment by ghost** [comment]
oh

**Comment by thisandagain** [comment]
Hi @TheRealPiggyWiggy. We are exploring supporting OGG as a sound format in Scratch 3.0. As @Kenny2github mentioned we are not adding any new features to Scratch 2.0 and only resolving issues that are labeled `prio-critical`. Thanks!
