### ISSUE TITLE
Get cloud variables over HTTP

### ISSUE THREAD

**Issue by trumank** [LLK/scratch-flash#1369]
The old /varserver/:id endpoint only returns data from before the transition to the new cloud infrastructure. Is there (or will there be) a way to get cloud data over HTTP again?

**Comment by Kenny2github** [comment]
ooh, good question. I believe thanks to the integrity of the new infrastructure, the cloud system doesn't fall back to HTTP at all anymore.

Please note, however, that Scratch 2.0 is now in maintenance mode as the Scratch Team focuses their efforts on Scratch 3.0 and the Scratch website. Only issues labeled `prio-high` will be addressed before the first alpha release of Scratch 3.0.

**Comment by thisandagain** [comment]
Hi @trumank. No, the new cloud data system only supports secure web sockets (WSS). We do not have any plans to support HTTPS long polling.

**Comment by trumank** [comment]
Specifically, I was wondering how I could get current cloud data (either by via websockets or HTTP) without having to authenticate as a Scratch user. If only websockets are supported, is there a way to get the state without having to send a scratch session token?
