### ISSUE TITLE
the initial open source don't have the Block help part. How to find it

### ISSUE THREAD

**Issue by XXyueliang** [LLK/scratch-flash#1370]
![snip20171206_3](https://user-images.githubusercontent.com/29173407/33650871-b7d08f08-da9e-11e7-8b23-67d9f3e1298b.png
![snip20171206_5](https://user-images.githubusercontent.com/29173407/33651117-a6f85dfe-da9f-11e7-961e-988e1712950f.png)

)

**Comment by Kenny2github** [comment]
`scratch-flash` does not contain all components of the Scratch editor - it is simply the base for all of them. That part of the editor is managed by a different repository.

**Comment by XXyueliang** [comment]
Can you tell me where can find it

**Comment by Kenny2github** [comment]
@XXyueliang unfortunately no, since it's probably in a private repository (a repository that is not available for the general public to see)

**Comment by XXyueliang** [comment]
ok, thank you very much

**Comment by thisandagain** [comment]
Block help and "tips" (the right hand bar) are not included in our open source codebase for Scratch 2.0.
