### ISSUE TITLE
no sound in offline editor on ubuntu 16.04

### ISSUE THREAD

**Issue by notklaatu** [LLK/scratch-flash#1371]
Using the offline editor in a classroom without Internet access on Ubuntu 16.04 (x64).

Sound works on the computers fine (I get sound in Firefox, system settings, and so on), it's only Scratch 2.0 Offline Editor that lacks sound. I'm assuming it's a Flash issue..?

I have adobe-flashplugin installed.

I have also tried:

    pasuspender -- /opt/"Scratch 2"/bin/"Scratch 2" 

but this has no affect.

I can't seem to get any kind of error out of Scratch 2 Offline Editor to provide more helpful information for you, but I'm willing to try if you give me a hint about extracting useful info from it.

Any ideas?

**Comment by thisandagain** [comment]
This is unfortunately an issue with Adobe AIR / Flash on Linux which is no longer maintained.
