### ISSUE TITLE
How to capture the click event of close button?

### ISSUE THREAD

**Issue by XXyueliang** [LLK/scratch-flash#1372]
![snip20171206_6](https://user-images.githubusercontent.com/29173407/33661977-12701160-dac5-11e7-9f77-79cd227cb832.png)

**Comment by thisandagain** [comment]
https://stackoverflow.com/questions/7440667/how-to-detect-window-closing-event-in-air-application-and-how-to-prevent

**Comment by XXyueliang** [comment]
thank you very very much!
I have solved this problem with your help
