### ISSUE TITLE
Flash end of life in 2020

### ISSUE THREAD

**Issue by Kiza** [LLK/scratch-flash#1373]
Flash will be end of life in 2020.

Is there a plan to migrate Scratch to other technology like HTML5?

Reference, 
https://theblog.adobe.com/adobe-flash-update/

> stop updating and distributing the Flash Player at the end of 2020

**Comment by rschamp** [comment]
Yes, follow our progress on Scratch 3.0 here! https://github.com/LLK/scratch-gui

**Comment by Kiza** [comment]
Cool. 
Thanks. 

Somehow just found similar information in Raspberry Pi forum. 

https://www.raspberrypi.org/forums/viewtopic.php?t=189127
