### ISSUE TITLE
Why my app can not open sb2 project?

### ISSUE THREAD

**Issue by XXyueliang** [LLK/scratch-flash#1375]
![snip20171226_7](https://user-images.githubusercontent.com/29173407/34348747-bf62d9de-ea47-11e7-99e6-743f7a0cd180.png)
![snip20171226_9](https://user-images.githubusercontent.com/29173407/34348752-c722041a-ea47-11e7-973e-4b2d1ce124fb.png)
![snip20171226_10](https://user-images.githubusercontent.com/29173407/34348754-c93c479c-ea47-11e7-8682-784c0f4d4243.png)

**Comment by thisandagain** [comment]
I'm a little unsure as to what you are asking. What is "LINXCODER"? That is not an application that we support.
