### ISSUE TITLE
I'm afraid many fonts are copyvio

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-flash#1376]
This program has some fonts under SIL-OFL, but it cannot be used under GPL.
https://www.gnu.org/licenses/license-list.html.en#SILOFL
According to the page, SIL-OFL is "incompatible with the GNU GPL".

These are OFL Fonts.

* Donegal
* Gloria
* Mystery

Apache License 2.0 is ONLY compatible with GPLv3, but scratch-flash is GPLv2.
https://www.gnu.org/licenses/license-list.html.en#apache2
That is Apache License Fonts.
* Marker

Helvetica is copyrighted.
So all the fonts except Scratch violate the license.

**Comment by apple502j** [comment]
(Scratch Topic https://scratch.mit.edu/discuss/post/2936091/ )

**Comment by thisandagain** [comment]
This was all run by MIT's intellectual property office prior to release, but I'll investigate it again. In either case, we will be handling this differently for Scratch 3.0.
