### ISSUE TITLE
Scratch 2.0 v458.0.1 cannot share and update

### ISSUE THREAD

**Issue by corporateanon** [LLK/scratch-flash#1378]
Approximately in December, 2017, i started to experience connectivity problem with Scratch 2.0.

When i try to share a project to the website, the message is: **Server error: No response**

When i try to check for updates, the message is: **Could not retrieve version information from server**

No log messages, when running from console.

**OS**: Ubuntu 16.04.3 LTS

Scratch is installed with Adobe Air.

![](http://pix.toile-libre.org/upload/original/1515247041.png)

![](http://pix.toile-libre.org/upload/original/1515246882.png)

**Comment by thisandagain** [comment]
@corporateanon Sorry to hear that! We haven't gotten any reports of this elsewhere so I'm curious what the issue may be. If you go to https://scratch.mit.edu what do you see?

**Comment by corporateanon** [comment]
@thisandagain The site opens normally.

What i also noticed:

1) I sniffed the traffic with wireshark, when i was trying to update scratch, but no requests were seen at all.
2) The error appears too quickly (no delay between button click and error dialog) - it looks like it does not even try to connect the update host. 

Could you show me the examples of HTTP requests Scratch makes to check for updates? So that i could  reproduce them with `curl` and see if my network provider does not block.

**Comment by MansyrevAY** [comment]
Its October 2018, I faced same problem. Site opens without problems as well.

**Version of scratch:** v456.04
**OS:** Windows 7 6.1.7601
