### ISSUE TITLE
Size block doesn't set size to 100% when used after setting size to intermediate value

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-flash#1379]
Reported via https://scratch.mit.edu/discuss/topic/289589/?page=1#post-2967039:

> So, out of no where, the sprite changes size (always smaller)
When you click the [size] block, it says the size of the current sprite.
When you click a number higher than the current number (witch is usually ranges from 60 to 90) It just goes back to the default number. 
For example. the size says 60, when the ‘set size to 100’ is used in the script, or is clicked in the looks section. Sometimes the number changes, but is always in the same range. But when you try to set the size to a number lower than the current size, it works. 

> This is an example of the glitch - https://scratch.mit.edu/projects/198755410/ -  it occurs in Sprite 2 and 3...

**Comment by jwzimmer-zz** [comment]
Workaround and explanation from the discussion thread (https://scratch.mit.edu/discuss/topic/289589/?page=1#post-2972546), via @TheLogFather and neeb132:
> (neeb132) This is no glitch, Scratch just can't handle sprites being WAY bigger than the display area, so it automatically changes the size back to what it can handle.
> (TheLogFather) As neeb132 said above, when you set a sprite's size, Scratch will limit the size to make it (mostly) fit within the stage.
> You have costumes that are somewhat larger than the stage, so when you set size while the sprite is set to such a costume then it will be limited.
> If you want to switch to an oversize costume, and you want to set its size to go beyond the size of stage, then there is a ‘trick’ you can use…
> When setting the size, Scratch only limits it for the *current* costume. It doesn't limit it when switching to a large costume. That means you can do the following:
> 1) Switch to a small costume (you have a number of 1x1 size costumes)
> 2) Set the size to what you want the large costume to have
> 3) Switch to the oversize costume

**Comment by jwzimmer-zz** [comment]
So it sounds like this may not be a bug, but there may be a question of what behaviour we want to implement in 3.0 - do we want to keep what sounds like the current 2.0 behaviour of keeping the max size of the current costume within the stage, or do we want to e.g. allow the same size range for all costumes (0 - 100%) and allow costumes to extend outside the visible stage area/ look like they do so?

**Comment by TheLogFather** [comment]
For completeness, I'll note that Scratch also currently applies a *lower* size limit too, i.e. it prevents a costume from becoming too small.

Just like the upper limit, this can also be slightly annoying to have to work around occasionally (applying the same kind of trick) – see my "BatCave3D techniques demo" project, for example (https://scratch.mit.edu/projects/146240126/), where the "Monster" sprites have to start off very small and grow as they come closer.

I'd be tempted to consider whether the limits could be relaxed a bit, both ways, but I can imagine that changing the behaviour has the potential to break a few projects (visually, at least).

And there's also the issue that allowing a costume to become very large can lead to slowdown when it gets manipulated in various ways (e.g. rotations, and then having to work out pixels for touching/stamping, etc.). –OTOH, perhaps Scratch 3 handles that better...?
