### ISSUE TITLE
the app generated using the open source code of scratch2.0 on git can not open sb2 project directly

### ISSUE THREAD

**Issue by XXyueliang** [LLK/scratch-flash#1381]
![snip20180201_15](https://user-images.githubusercontent.com/29173407/35667994-a6b57f28-076a-11e8-9be5-09595c031764.png)
![snip20180201_8](https://user-images.githubusercontent.com/29173407/35668026-c49039a2-076a-11e8-9895-7a059f740ad1.png)
![snip20180201_10](https://user-images.githubusercontent.com/29173407/35668028-c6ef5048-076a-11e8-8930-4c61e69b79a1.png)
![snip20180201_13](https://user-images.githubusercontent.com/29173407/35668032-c8c15542-076a-11e8-8b8d-83ad87d7cc4c.png)
![snip20180201_14](https://user-images.githubusercontent.com/29173407/35668035-caee2ec6-076a-11e8-8ff2-a43c3ecdb526.png)

**Comment by XXyueliang** [comment]
what should I do? How to solve this problem? Any help Will be appreciated.

**Comment by towerofnix** [comment]
This is definitely interesting - the behavior is the same as when I run a compiled Scratch.swf with `flashplayer` from the command line. Flash simply doesn't have permission to read files offline. (So I wonder how the actual Scratch 2.0 app works....) A simple solution is to serve the SWF on an HTTP server, but that means you can't give out the mod as a native app.

**Comment by thisandagain** [comment]
@xxyueliang You'll need to write your own "wrapper" layer to build and distribute the scratch-flash code as a standalone app. Sorry we can't be more help with this.
