### ISSUE TITLE
On Mobile, when on a profile page, the sign-out button changes.

### ISSUE THREAD

**Issue by PatheticMustan** [LLK/scratch-flash#1382]
![5f765b38-5549-4619-9321-3316b5b53442](https://user-images.githubusercontent.com/35382971/35774402-18a41662-093c-11e8-85cc-d1a4594a5cbf.jpeg)
Here is a photo of the sign-out button on the main page,

![bd9d07ba-9845-47f5-964d-04a096ed2697](https://user-images.githubusercontent.com/35382971/35774404-30e589a4-093c-11e8-97ff-4eec8651919e.jpeg)
and here is the button when on a profile page.

**Comment by Kenny2github** [comment]
This is because the main page is in [scratch-www](https://github.com/LLK/scratch-www) while the profile pages are in [scratchr2](https://github.com/LLK/scratchr2) (private repository so it 404s).

**Comment by thisandagain** [comment]
Will resolve this when the profile page is migrated to [scratch-www](https://github.com/llk/scratch-www).
