### ISSUE TITLE
Security Disclosure

### ISSUE THREAD

**Issue by encloinc** [LLK/scratch-flash#1384]

**Comment by towerofnix** [comment]
Aren't you better off using contact us, so you can more safely (or at least, more confidentially) share details? (Telling thisandagain the ticket number on his profile after can also help you get a response sooner.)

**Comment by thisandagain** [comment]
Closed and locked due to the sensitive nature of this issue. In the future please send an email to `help@scratch.mit.edu` for security related issues.
