### ISSUE TITLE
Unable to type into text fields

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-flash#1386]
What should happen:
Users should be able to change the value of text inputs, such as the name of sprites, by selecting the text field of the sprite and typing a new value. Other values includes move blocks. 

What is actually happening:
The user can select the text fields but typing does not send values to the text field.  It's like the keyboard isn't plugged in when typing.

How to reproduce:
NEEDS REPRO

Using Firefox on Windows 10 (user sees it on multiple computers.
Ticket 107795 from freshdesk (https://mitscratch.freshdesk.com/helpdesk/tickets/107795)
user: zac.adams

**Comment by neadlak** [comment]
Also getting this on firefox on windows 10. I have to leave the tab and come back to be able to write to text fields.
