### ISSUE TITLE
firefox doesn't give warning if flash not installed when you click create

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-flash#1387]
If you open firefox and don't have flash installed and navigate to scratch.mit.edu and then click create it should tell you that flash is not installed at least.

Actual behavior:
When you click create it loads a new page that is blank.  Nothing loads.

![firefoxNoFlashCreate.png](https://codetreeusercontent.s3.amazonaws.com/uploads/b3f917fc-1e8b-476c-a0d6-59c6c00acd2f/firefoxNoFlashCreate.png)
![firefoxNoFlashProjectPage.png](https://codetreeusercontent.s3.amazonaws.com/uploads/b3f917fc-1e8b-476c-a0d6-59c6c00acd2f/firefoxNoFlashProjectPage.png)

If you have flash installed it will give a dialogue to open it:
![flashInstalledNotUsedYet.png](https://codetreeusercontent.s3.amazonaws.com/uploads/45fffc96-43dc-454d-b5bc-c804de51e442/flashInstalledNotUsedYet.png)

![flashInstalledAllow.png](https://codetreeusercontent.s3.amazonaws.com/uploads/45fffc96-43dc-454d-b5bc-c804de51e442/flashInstalledAllow.png)

Reproduction steps:
*Launch firefox without flash installed.
*Navigate to scratch.mit.edu
*Click Create in the top bar
*Note the lack of content on the page.

A similar thing happens on the project page, but it's only the project that doesn't load, the rest of the page loads just fine.

Colby linked me to Firefoxe's roadmap to flash end of life, which might be relevant here.
https://blog.mozilla.org/futurereleases/2017/07/25/firefox-roadmap-flash-end-life/!

**Comment by nixerus** [comment]
As far as I know, Firefox doesn't come packaged with flash. It's generally up to the user to download Flash Player to be able to use the site. This isn't really a bug..

**Comment by Kenny2github** [comment]
@netxdaguy the problem is that Scratch doesn't give any *indication* that the user doesn't have Flash. Normally there's a "whoops! you don't have Flash" message, but on Firefox this is apparently not the case.
