### ISSUE TITLE
Bring up cloud data limit to 1024 characters

### ISSUE THREAD

**Issue by encloinc** [LLK/scratch-flash#1388]
I know the reason for the scaledown was to relive stress on the servers, however i think 128 characters might be a little to limiting. 10240 was definitely too much, but 1024 should be ok no? I would really appreciate it if the limit could be brought up to 1024 (this wouldn't be enough for cloud chat rooms which is what you are trying to avoid but would be for simple multiplayer games where you cant to stream your x and y position to the other clients). Thankyou and please consider this.

**Comment by thisandagain** [comment]
The old limit was 1024. We will review, but at this time we have no plans to increase the limit.

**Comment by encloinc** [comment]
the old limit was 10240 i believe
