### ISSUE TITLE
Tan of 90 lets sprites go past normal position limits

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-flash#1389]
Discussed with @cwillisf, reported by user -Handle-. If you use tan(90) for sprite position, the value will be a very large number and the sprite will not appear within the visible part of the stage.

Repro: https://scratch.mit.edu/projects/212387052/#editor

<img width="237" alt="screen shot 2018-03-27 at 9 45 51 am" src="https://user-images.githubusercontent.com/1320456/37971339-b0c905ee-31a3-11e8-92b8-db3ad314f66b.png">

@cwillisf said:
- Google's built-in calculator gives the same result for tan(90), https://www.google.com/search?q=tan+90+degrees
- Apparently it [returns that value specifically] because `Math.pi` in Flash (and in JavaScript, and a number of other places) is represented the same way, with a 64-bit floating point number (standard IEEE 754 format), which is imprecise enough that the common way of implementing `tan` gives a result that's really big but not actually infinity (`inf`). It could also be related to converting from degrees to radians.
- I'm not sure why it lets you go past the normal limits, though

**Comment by Kenny2github** [comment]
`tan(x)` where `x` is 90 technically should have the same result as `x/0`, i.e. `NaN`. However, values of `x` approaching 90 should get progressively larger (e.g. `tan(89) ~= 57.3` but `tan(89.99) ~=5730`).

**Comment by TheLogFather** [comment]
I've come across this numerous times, and it's probably worth noting that it has nothing to do with tan, specifically – it's all to do with the large numbers.

I've always suspected this issue comes down to rounding errors when performing the calculations on such large values (i.e. maths operations on x & y in function keepOnStage() in ScratchSprite.as) – the final values still end up outside the expected range (i.e. not within screen limits).

**Comment by TheLogFather** [comment]
I think a fairly quick-n-easy fix might be to assume that the dimensions of the sprite will not exceed some suitably large value (a million pixels?), and then check if the x and/or y positions do exceed this by somewhat more (positively or negatively). If so, then bound the co-ordinate without any reference to the actual supplied x and/or y (i.e. using only the sprite's bounding box, along with the sign(s) of the relevant x/y co-ord(s) to tell which screen edge to bound it on).
