### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by luofei614** [LLK/scratch-flash#1391]
show this error：

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileFlex'.
> Could not resolve all dependencies for configuration ':external'.
   > Could not resolve macromedia.com:playerglobal:10_2.
     Required by:
         :scratch-flash:1.0-SNAPSHOT
      > Could not resolve macromedia.com:playerglobal:10_2.
         > Could not parse Ivy file http://fpdownload.macromedia.com/get/flashplayer/installers/archive/playerglobal/playerglobal10_2.xml
            > The markup in the document preceding the root element must be well-formed.

**Comment by afety** [comment]
I also got this failure
System: Ubunto 16.04 LTS
Gradle: 4.6

Error: 
```
:compileFlex FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileFlex'.
> Could not resolve all dependencies for configuration ':external'.
   > Could not resolve macromedia.com:playerglobal:11_6.
     Required by:
         :scratch-flash:1.0-SNAPSHOT
      > Could not resolve macromedia.com:playerglobal:11_6.
         > Failed to download SHA1 for resource 'http://fpdownload.macromedia.com/get/flashplayer/installers/archive/playerglobal/playerglobal11_6.xml'.
            > For input string: "<!"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by moneygohome** [comment]
same failure. 
could anyone please advise?

**Comment by dadede999** [comment]
same error

**Comment by royqh1979** [comment]
me too

**Comment by royqh1979** [comment]
tried manually download , and got 404 error

**Comment by royqh1979** [comment]
Seems that it's because macromedia.com is wrong CDNed in some country.  I tried to download http://fpdownload.macromedia.com/get/flashplayer/installers/archive/playerglobal/playerglobal11_6.swc by using a proxy, put the downloaded swc file in my own http server, and changed scratch.gradle file:
` 
    ivy { 
      name 'Player Globals'
        artifactPattern 'http://royqh.net/[module][revision].[ext]'
    }`
And then build ok.

**Comment by wweiradio** [comment]
@royqh1979  thank you for the information. 
Now the build is OK,  and got the Scratch.swf how to proceed to get the windows installation binary of scratch offline editor.

**Comment by standup-jb** [comment]
I alsob build failure ,The error message as blow :

Execution failed for task ':compileFlex'.
> java.lang.Exception: mxmlc execution failed: Apache Flex Compiler (mxmlc)
  Version 4.15.0 build 20160104
  Copyright 2016 The Apache Software Foundation.
  command line: 错误: 无法打开“libs/osmf.swc”
 
  使用“mxmlc -help”可获得有关如何使用命令行的信息。



* Try:
Is there anyone can help solve this error
