### ISSUE TITLE
gradlew build failed

### ISSUE THREAD

**Issue by royqh1979** [LLK/scratch-flash#1394]
I'm using windows 7 , JDK 8, Grade 4.7 and Apache Flex SDK 4.15;
When I tried to build by running ".\gradlew build -P11.6", I got the following error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileFlex'.
> Could not resolve all dependencies for configuration ':external'.
   > Could not resolve macromedia.com:playerglobal:11_6.
     Required by:
         :scratch-flash:1.0-SNAPSHOT
      > Could not resolve macromedia.com:playerglobal:11_6.
         > Failed to download SHA1 for resource 'http://fpdownload.macromedia.co
m/get/flashplayer/installers/archive/playerglobal/playerglobal11_6.xml'.
            > For input string: "<!"`

Then I tried to download http://fpdownload.macromedia.com/get/flashplayer/installers/archive/playerglobal/playerglobal11_6.xml manually,  and got a 404 error.

Seems the depenecy is broken

**Comment by power-coding** [comment]
No one know this issue?
