### ISSUE TITLE
Sprite Library is Empty

### ISSUE THREAD

**Issue by emorenis** [LLK/scratch-flash#1395]
Hi, 

I realized from other posts that Sprite Library is empty by design to not violate copyright.

Can you please advise what is the structure for Sprite Library folder (folder name, subfolders, sprite file format) and if it is needs to be compiled into flash file or it can sit side by side with it.

Greatly appreciate your response.

Thank you,
Egor

**Comment by thisandagain** [comment]
Hi @emorenis. The assets are in a flat directory of MD5 hashes plus a file extension (e.g. "005f2dd99f1f3e22a377296b7ba2445a.json").

**Comment by emorenis** [comment]
Thank you. What is the name of default directory?

Egor

**Comment by thisandagain** [comment]
It is in the `src/media` directory.

**Comment by emorenis** [comment]
Thank you
