### ISSUE TITLE
Since PR #1396, the "timer" block no longer gets updated correctly during non-refresh loops

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1397]
See https://github.com/LLK/scratch-flash/pull/1396#issuecomment-396726678 for more discussion...

**Comment by AmazingMech2418** [comment]
Maybe there could be another block called "turbo timer" that is like the original timer block, but unlike the new updated timer block, would work in non-refresh loops.

**Comment by towerofnix** [comment]
@amazinigmech2418 That's a fine idea, but I think older projects would still be broken. And there's no need for such a block in 3.0, which is written in JavaScript and therefore doesn't have this host of Flash-30 issues at all.

**Comment by AmazingMech2418** [comment]
@towerofnix I meant a new block in 2.0. It would also automatically convert all previous uses of the timer block to turbo timer.

**Comment by towerofnix** [comment]
@amazinigmech2418 Wouldn't it be better to just change the function of the timer block itself, then? Since all timer blocks would be turned to turbo timer blocks.

**Comment by AmazingMech2418** [comment]
@towerofnix Sure, but why did the ST make the original PR then?

**Comment by TheLogFather** [comment]
@amazinigmech2418: The initial PR comment gives the explanation: https://github.com/LLK/scratch-flash/pull/1396#issue-194058103

BTW, might be worth me noting here that this timer issue breaks projects that try to do speed tests – e.g. all(?) the ones in my speed tests studio https://scratch.mit.edu/studios/795672/

**Comment by towerofnix** [comment]
@amazinigmech2418 ^ Yep; The PR was to address issues with other slowdown issues (as described there). It *inadvertently* broke the timer block in no-screen-refresh custom blocks, which is what this issue is tracking/describing.

**Comment by AmazingMech2418** [comment]
The check frequency needs to be brought back to the original for it to work...
