### ISSUE TITLE
Not able to set cloud variables to regular variables.

### ISSUE THREAD

**Issue by Fuzzychicken17** [LLK/scratch-flash#1400]
In the process of creating an MMO game I have come across one problem. If you want to set a cloud variable to say "bot x" it will be blocked for fear of letters without even checking to see that it contains a letter. I think that is the problem at least. If you have a solution or I am just plain wrong please tell me.

**Comment by towerofnix** [comment]
Hmm, weird. I just tried the script "set bot x to 12345, set my cloud variable to bot x" and it worked.

Are you absolutely certain that "bot x" is a number (i.e. only contains number digits)? Does "set cloud variable to (0 + bot x)" work? Also, importantly, does the message "Currently, only numbers can be stored in Cloud variables" message show up when "set my cloud variable to bot x" runs? (If it doesn't, there might be some other issue.)

**Comment by Fuzzychicken17** [comment]
I've tried 0+var but it still doesn't work. I'm using the join block so that might be causing some problems, I'm using a system I often use called letter check, basically it says "set cloud variables to letter check of save (Put together list digit by digit based on cloud variable) (Save is a bunch of joined variables including one cloud variable)(change letter check by one). Sorry if I'm blathering or it doesn't make any sense.

**Comment by Fuzzychicken17** [comment]
OK I fixed it i was using coords and one value was negative. FIXED!!!
