### ISSUE TITLE
Stage3D causes excessive GPU usage

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#1402]
...even without any scripts running.

Steps to reproduce:
1. create new project
2. delete cat sprite (just so we know it's not specifically to do with a sprite)
3. watch GPU usage for browser/Flash, and see it's low
4. drag "set/change color effect" block into scripting area
5. watch GPU usage go up
6. change block from "color" to "brightness" effect
7. watch GPU usage go down

This happens for me on Mac in Safari, FF & Chrome.

Not checked Windows(/Linux).

**Comment by Kenny2github** [comment]
Windows 10, Chrome 68, CPU Intel(R) Core(TM) i3-4012Y CPU @ 1.50GHz, GPU Intel(R) HD Graphics Family

Following those steps, I saw no significant change in CPU usage (remaining around ~20%) with or without the graphic effect block. However, my *GPU* usage shot from ~2% to ~30% when I dragged the effect block in, then dropped back down to ~2% when I dragged it out.

**Comment by TheLogFather** [comment]
Hmmm, interesting, you're right...

I should've noticed I was actually using the activity monitor app set to show "Energy impact" rather than specifically monitoring CPU.

–That's probably why I didn't notice this usage before (I usually use "top" in terminal).
