### ISSUE TITLE
A suggestion about colour seleter in draw character 

### ISSUE THREAD

**Issue by 2439905184** [LLK/scratch-flash#1403]
advise  you  add HSV mode in colour seleter(picker).if I want to draw ,it's hard to chose a colour.能不能加入像绘画软件PS那样的HSV颜色选择器的功能。或者在以后的新版本中添加这个功能，非常小的一个功能。

**Comment by towerofnix** [comment]
Scratch 3.0 has this feature:

!["Color", "Saturation", and "Brightness" sliders](https://user-images.githubusercontent.com/9948030/45264059-8f34a780-b40c-11e8-863e-85628d20342f.png)

Scratch 3.0 will be released in January 2019.
