### ISSUE TITLE
Is Linux support going?

### ISSUE THREAD

**Issue by bowstones** [LLK/scratch-flash#1405]
You can't download Scratch 2.0 for Linux anymore. Is there a reason for this, and will there be Scratch 3.0 for Linux?

**Comment by towerofnix** [comment]
See LLK/scratch-www#1886:

>Unfortunately Adobe stopped supporting Adobe AIR on Linux platforms in 2011. We have continued to provide a version of the Scratch 2.0 Offline Editor since then, but unfortunately more recent versions of Ubuntu and other major distributions of Linux have completely broken AIR compatibility to the point where we need to drop support. Our hope is that the Scratch 3.0 Offline Editor will be able to more sustainably support Linux (via Electron) in the future.
