### ISSUE TITLE
Support for supplemental non-English fonts in paint editor

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#231]
Currently, the Paint Editor supports only a small number of fonts - all limited to English characters.  This leaves some of our non-English using Scratchers with very limited and cumbersome options. Here is an example of a procedure that one of our Russian users has developed for importing Cyrillic vector text into the Paint Editor as SVG paths.  You don't have to speak Russian to see that the 14-step process is not for beginners:

http://scratch.mit.edu/discuss/topic/33253/

Realizing that every new font added to the Paint Editor increases the size of the SWF,  and there are very many character sets in use in the world, I'm wondering if there is a way to perhaps simplify the importation of supplementary fonts into a project (as vector paths) rather than making new fonts a permanent feature of the SWF.

**Comment by Scimonster** [comment]
Yes, please find a solution to this! I conduct a Scratch class in Hebrew,
and constantly get thrown by the fact that the paint editor doesn't support
it.

On Wednesday, January 7, 2015, ntlrsk <notifications@github.com> wrote:

> Reopened #231 <https://github.com/LLK/scratch-flash/issues/231>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LLK/scratch-flash/issues/231#event-215485531>.
>


-- 
Sent from Gmail Mobile

**Comment by ntlrsk** [comment]
We are now revisiting these various options and will update with the plan to address this very soon (hopefully by the end of this week).

**Comment by dimon4ezzz** [comment]
Maybe we can use “Text Layout Framework”?! Quote: “We've been dealing with the same issue in Arabic for years. Flash and non-Latin letters don't always play well together. There is a new component out called Text Layout Framework for CS4 that is supposed to play better with foreign languages.”

http://help.adobe.com/ru_RU/as3/dev/WSb2ba3b1aad8a27b0-1b8898a412218ad3df9-8000.html

**Comment by kaschm** [comment]
Thanks for the tip, @dimon4ezzz ! We'll update with a plan soon.

**Comment by Gromko** [comment]
A year has passed - nothing has changed, non-Latin characters in scratch - in the distant future

**Comment by ntlrsk** [comment]
We have worked out a new plan. First, it is important to understand that there is a problem with adding non-English fonts because the Scratch editor (SWF) file grows in size with each font. So the proposed plan is to add an option to use a System font, which would include all fonts on the user's computer. It would turn that text into bitmap after editing, so that the project can be viewed by others without that font. The interface details will need to be worked out.

**Comment by Gromko** [comment]
This is an excellent plan - when will its implementation?

**Comment by ntlrsk** [comment]
The interface for choosing fonts within Scratch seems like it is tricky to figure out, since some people have so many fonts on their machine. Anyone have any suggestions for the interface for choosing a local system font within the image editor?

**Comment by freakshow1217** [comment]
A year has apparently pasted, still no resolution? Is anyone able to start a pull request because the Scratch Team isn't going to help?

**Comment by liam4** [comment]
Perhaps, the first time a non-implemented-as-it-is-now character is pressed, Scratch downloads the charset font for that character? When somebody then opens the project Scratch goes through the vector text and loads the required fonts?

Just an idea. :P

**Comment by Scimonster** [comment]
Or it downloads the fonts according to the language the interface is in at
the beginning.
If i use the interface in Hebrew (for example), i expect to be able to type
in Hebrew.
It's not a perfect solution, but definitely would be an improvement.

On Tuesday, January 26, 2016, Liam <notifications@github.com> wrote:

> Perhaps, the first time a non-implemented-as-it-is-now character is
> pressed, Scratch downloads the charset font for that character? When
> somebody then opens the project Scratch goes through the vector text and
> loads the required fonts?
>
> Just an idea. :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LLK/scratch-flash/issues/231#issuecomment-175008090>.
>


-- 
Sent from Gmail Mobile

**Comment by liam4** [comment]
But what if somebody shares a project with Hebrew text in it? Then a person viewing the project can't see the properly rendered text.

**Comment by Scimonster** [comment]
So maybe it also has to be saved per project.

On Tuesday, January 26, 2016, Liam <notifications@github.com> wrote:

> But what if somebody shares a project with Hebrew text in it? Then a
> person viewing the project can't see the properly rendered text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LLK/scratch-flash/issues/231#issuecomment-175066134>.
>


-- 
Sent from Gmail Mobile

**Comment by chrisgarrity** [comment]
Another request for a font that supports polish characters (looks like open-sans would do it). https://mitscratch.freshdesk.com/helpdesk/tickets/50986
