### ISSUE TITLE
Hat blocks not supported by http extensions

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#233]
Sorry this turned into a bit of an essay! 
However it does show the thought process behind the latest pull request made (#234), which provides a full solution to this issue.

Hat Blocks not Supported in Http Extensions

Hat blocks are an important feature of extensions and are already supported/used by the WedO/PicoBoard javascript extensions.
However they are not currently supported by http extensions and are not even mentioned at all in the draft http documentation.

Hat blocks are easy in javascript, as we simply write a custom function that returns true/false as required for each hat.

However in http it does not at first appear so easy to implement, as we can only get the current values from the /poll response. Therefore it requires looking at how we can process hat blocks in a slightly different way.

Hat types can be split into two groups - predefined and customisable:

Type 1

Predefined hats (for example picoboard 'when button Pressed') simply require a true/false response. So it is quite simple to include a matching custom response within the reply to the http /poll .
The extension server is then responsible for determining whether the event is currently true or not.

Exactly the same response can be used as already works for existing 'b' boolean reporters e.g.

```
[ "h", "when %m.booleanSensor", "getSensorBooleanValue", "button-pressed" ],
[ "b", "sensor %m.booleanSensor ?", "getSensorBooleanValue", "button-pressed" ], 
```

which will both look for this same reply in the polled response

```
getSensorBooleanValue/button-pressed true
```

Type 2

Customisable hats generally have a trigger threshold that can be changed

e.g. WeDo 'when distance < 20'

These are much harder to use directly with a polled response, as they would need to look for a polled response of 

```
op_name/distance/&lt;/20 true
```

and the last part of the phrase will change significantly whenever the operator and threshold values are changed

However it should also be observed that the vast majority of hats are based upon existing reporter values, which Scratch actually already knows the value of via it's regular polling.

'distance' and 'tilt' on the Wedo are two obvious examples, as are 'slider' or 'resistance-A' on the PicoBoard.

Therefore it is proposed that Scratch can recognise a special generic http op 'whenHttpHat'  that can be used within hat block processing to compare an existing reporter value with a threshold value. Note the existing Scratch source already includes hints to (unused) legacy hardware-specific equivalents such as WeDo's 'whenTiltIs' etc. What we propose here is very similar, but is now a generic op, not a hardware device specific op.

This covers the vast majority of http hat requirements without any extra work at all within the extension, as Scratch itself calculates the hat's true/false condition from the three arguments supplied alongside 'whenHttpHat' (reporterName-operator-thresholdValue)

The comparison can then be numeric (>, <, == , !=) to a specified target number
or can be string comparison based (e.g. ==, != to 'true'/'false' or any other custom string as required)

This 'whenHttpHat' op needs to be part of the internal core Scratch source code and hence always available to all http extensions.

This special op is hard coded into the startEdgeTriggeredHats function within ScratchRuntime.as in exactly the same way as the other existing internal special ops (e.g. 'whenSensorGreaterThan' which is used for loudness/timer/video motion)

Therefore the hat would be defined in the s2e file as follows:

```
[ "r", "distance", "distance" ],
[ "h", "when %m.sensor %m.lessMore %n", "whenHttpHat", "distance", "<", 20 ],
```

When processed the hat block now simply looks for the reporter value of args[0](in this case), and then does the maths internally.
So the reply in the http polled response from the extension server is simply

```
distance 50
```

and this is actually all that is required for both the reporter block and the hat block to function correctly.

Hence adding hats to http extensions then becomes quite simple.

**Comment by srikar0896** [comment]
By the poll response we can update the value of sensors,but how can we achieve the main purpose of hat blocks which is to start a script,for example this is my js extension 

![image](https://user-images.githubusercontent.com/17567875/35845902-63a4b860-0b3a-11e8-9863-3af5b3cb743d.png)

which will continuously request the helper app for the value of analog sensor and it will start the script whenever the condition satisfies(helper app returns true if that condition satisfies).But I want to achieve the same functionality with HTTP extension,but when i try the same with HTTP extension,no matter what all the hat blocks in that extension are starting the next blocks in that stack in my case what ever the value of analog sensor the bot moves right

**Comment by cpseager** [comment]
Custom hats just don't work with http at all. Instead you have to workaround this by using a green flag hat and then a 'wait until custom_value > 50' block.
