### ISSUE TITLE
Create MSI package for offline editor

### ISSUE THREAD

**Issue by SpeakkVisually** [LLK/scratch-flash#245]
A number of educators and IT folks have requested an MSI version of the Scratch 2.0 Offline Editor. Manually installing 400 copies of Scratch is kind of a bummer.

**Comment by dfuhrmann** [comment]
This discussion was closed but I can't find an MSI Installer for Scratch2 Offline Editor. Is it hidden somewhere or wasn't it released yet?

**Comment by kaschm** [comment]
@neurodude, @dfuhrmann - we just added a page (http://llk.github.io/scratch-msi/) that hosts an MSI created by github community member @cpseager ... a big thank you to him!

**Comment by cpseager** [comment]
@cwillisf I was going to update the offline MSI again with a new PR but no longer seem to have access to that repo?

**Comment by thisandagain** [comment]
Sorry about that @cpseager. You should now have access again. Please just send me an email if you need anything else.

**Comment by tigattack** [comment]
Sorry to revive an ancient thread guys, but are there any plans for a Scratch 3 MSI?

**Comment by Kenny2github** [comment]
@tigattack That is best opened as an issue on [LLK/scratch-desktop](https://github.com/LLK/scratch-desktop) instead.

**Comment by cwillisf** [comment]
@tigattack @Kenny2github
see LLK/scratch-desktop#35 :)

**Comment by tigattack** [comment]
Cheers @cwillisf, following that issue. Good to see it's part of a planned milestone! Very hopeful.
