### ISSUE TITLE
Large pen sizes don't work

### ISSUE THREAD

**Issue by nathan** [LLK/scratch-flash#360]
Pen size is limited to numbers less than 256. This looks like a [Flash limitation](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Graphics.html#lineStyle%28%29), so it might not be worth fixing, but I've made projects in the past that use larger pen sizes than that.

**Comment by chooper100** [comment]
I know this is a (very) old issue, but can anyone confirm whether this limitation will be removed in Scratch 3?

(Since it seems we are switching to html5 canvas based rendering)

**Comment by tmickel** [comment]
@chooper100 We are tracking the question here: https://github.com/LLK/scratch-vm/issues/97
