### ISSUE TITLE
Make blocking HTTP reporters use the polling mechanism

### ISSUE THREAD

**Issue by nathan** [LLK/scratch-flash#369]
Currently, blocking HTTP reporters (`R`-type blocks in HTTP extensions) send an HTTP request and wait for its response; when the request finishes, execution continues, using the response as the value for the reporter.

However, it would be more consistent (and help to reduce the number of concurrent requests) if they instead sent a request which terminated quickly and checked its status via the `poll` command. The documentation [suggests](http://wiki.scratch.mit.edu/w/images/ExtensionsDoc.HTTP-9-11.pdf#page=6) the following:

```
_result 7639 82
```

(where `7639` is a request ID and `82` is the result of the operation.) This seems like the opposite of `_busy`, though: `_busy` must be sent with every poll response until the command should terminate, whereas `_result` must be sent with only a single poll response when the reporter should terminate.

**Comment by la10736** [comment]
There is a way to track the story of that feature? I would like to know when is complete or contribute to it if you are too busy to implement it.

**Comment by la10736** [comment]
I would like implement this feature. Are you in the middle of something or you are not looking at it now?
