### ISSUE TITLE
Variable watchers always in front of sprites

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#385]
This issues was brought to my attention by Boltbait on his Chess project

http://scratch.mit.edu/projects/2737104/

where you can see that the "Ply" variable is in front of the title screen, despite a "go to front" block on the title screen.  Dragging the title screen sprite manually in the editor also does not move it in front of the variable for very long - as soon as you release the sprite with the mouse, the variable jumps in front of it.

I remixed the Chess project and removed all the sprites except one, all the variables except one, all the lists except one, etc.  This isolation project is here

http://scratch.mit.edu/projects/24759729

It also shows the behavior - although at times it has gone away during this narrowing process so that I had to start over.  I've looked at the JSON file of this project and I don't see anything unusual other than a Comments section that seems to contain comments added by the author - there's nothing visible in the project though (that I have found).  There is also a rather large History section.

Newly created projects do not seem to have this problem - so I'm thinking there is something weird about this particular project.  Consequently, I've tagged it as low priority since it is only impacting a small population so far as we know.

**Comment by tjvr** [comment]
@kaschm Did this discussion move somewhere else, or was it decided not to do this?

**Comment by nathan** [comment]
@tjvr the 3d player still does this, but I don't know what the plan is for the future. Unless they start rendering watchers in 3d with the sprites, it's probably here to stay.
