### ISSUE TITLE
Disappearing assets – data collection

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#403]
This issue is to be used to collect information on reports of missing assets (costumes, sprites, sounds, scripts) in an effort to see a pattern and hopefully fix the cause or causes.

Here is one I came across today that reports a large loss of data

http://scratch.mit.edu/discuss/post/385608/

interestingly, the person also reports that the assets appear to be missing from remixes as well (see two posts below).

There is another report at the top of this topic as well

http://scratch.mit.edu/discuss/post/384158/

**Comment by 2jour** [comment]
We are closing this issue.  If you notice specific issues with regards to data loss then please log a separate issue. We take data loss issues very seriously and it helps us troubleshoot if they are logged separately.
