### ISSUE TITLE
Importing SVG files ignores text

### ISSUE THREAD

**Issue by CraftedCart** [LLK/scratch-flash#411]
**When importing .SVG files, text is not imported**
Test done with SVG file created using Inkscape - File saved as Inkscape SVG - Font was Century Gothic

**Comment by 2jour** [comment]
@cwillisf  can you update based on editor meeting ?

**Comment by cwillisf** [comment]
The current plan is to import the text but switch the font to one of the Scratch fonts. This means that the text will still be editable as text in the SVG editor, including by another user after a remix.
