### ISSUE TITLE
Closing tab on new project as it is saving results in "project not loading" message

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#431]
If you close out the project editor tab on your browser as it is saving a new project for the first time, when you subsequently try to load the project, you will get the "project not loading" message.  

Probably the tab should not allow itself to be closed while the save is progressing?

Original report in the forums

http://scratch.mit.edu/discuss/topic/48120

**Comment by cwillisf** [comment]
The last several changes to the labels and assignment of this issue were made accidentally.
That said, I believe this was fixed a while ago... we should confirm that and close this issue.
