### ISSUE TITLE
Variable watchers overflow stage in 3D

### ISSUE THREAD

**Issue by nathan** [LLK/scratch-flash#452]
When a variable watcher goes outside the bounds of the Stage, it isn't properly clipped in the 3D renderer.

![screen shot 2014-08-13 at 15 24 25](https://cloud.githubusercontent.com/assets/1578238/3911246/77a51ea6-231f-11e4-9674-d5a9d4593f61.png)

http://scratch.mit.edu/projects/25551259/#editor

**Comment by 2jour** [comment]
fixed in #660
