### ISSUE TITLE
"when [loudness v] > (reporter block)" hat event block causes the project to not run

### ISSUE THREAD

**Issue by DevanWolf** [LLK/scratch-flash#468]
When you try to run the project with a variable or reporter in a "when [ v] > ()" block, it won't work!
There's something about the way Scratch deals with variables in these event blocks that means it gets confused when a project is first run (curiously, it's fine if you've run the project beforehand *without* the variable in there, and then you put the variable there and run it - my guess would be that something internal is not getting initialised before this event trigger starts getting checked).
Example: http://scratch.mit.edu/projects/20324557

**Comment by cwillisf** [comment]
Fixed by @TheLogFather with #913
