### ISSUE TITLE
"stop this script" inside non-refresh custom block can cause strange behaviour

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#475]
Here's a demo project: http://scratch.mit.edu/projects/25912556/

What I think is happening is that the interpreter gets confused about its repeat loops when it reaches "stop this script" while still within the repeat loop. This means the subsequent repeat loop doesn't get executed correctly.

It's something I've noticed a few times before (over a year ago!), but never tried to pin it down. Here's a couple of references in the forums:
http://scratch.mit.edu/discuss/post/148124/
http://scratch.mit.edu/discuss/post/82330/
http://scratch.mit.edu/discuss/topic/50378/

Here's a project where it happened, and I talk about it in the comments:
http://scratch.mit.edu/projects/15648803/

**Comment by griffpatch** [comment]
Can I ask whether this also will fix the issue that when you exit out of a custom block with 'without refresh' ticked using the stop this script block, that the 'run without refresh' is not disabled, so the parent script continues running without refresh?

**Comment by MegaApuTurkUltra** [comment]
@griffpatch that's the issue I'm having as well. Can this please be fixed soon?

**Comment by TheLogFather** [comment]
@sclements: this glitch has been hanging around for quite some time now, and can cause all sorts of problems for Scratchers.

Can you outline how you got to see the exception you mentioned? -I'll have a go at tracking it down if I can see where it's actually happening...

**Comment by TheLogFather** [comment]
Yes! :)
