### ISSUE TITLE
Adobe Flash microphone / camera security dialog cannot be dismissed

### ISSUE THREAD

**Issue by lightnin** [LLK/scratch-flash#491]
Saw another case of this in the wild while running a workshop this past weekend -- didn't have time to reproduce or get details, but it was FF on an older MacBook.

This is often a known flash bug - so it may follow / change with successive Flash versions. However, here is s a past instance of this bug that turned out to be caused by our remix nagifier overlay, which was covering the dialog and preventing the click from reaching it, IIRC.
https://github.com/LLK/scratch-flash/issues/423

(Yes - this means that this bug can be caused by our site and Adobe, but I'm still putting it in scratch-flash b/c that seems like the best place.)

Let's aggregate data on this problem when it appears (and it seems to always appear) here. @Paddle2See This is a very tough one, and it might be a good one to get the community to help nail down.

**Comment by 2jour** [comment]
Thanks for sending this workaround. We will put it on our workaround page. If we notice this issue again, we will reopen this.
