### ISSUE TITLE
Very thin sprites do not scale

### ISSUE THREAD

**Issue by gtoal** [LLK/scratch-flash#502]
I wanted to write a program that would take an image and render it isometrically on the wall of a maze (actually I wanted to create a walk-through art gallery).  I carved a 360x240 image up into vertical strips and was planning to display them with appropriate vertical scaling in a trapezoid to give the impression of a rectangle that was being viewed from off to one side with perspective.
Unfortunately the thin sprites would not scale - they always stamped at 100%.  After eliminating the most likely cause (bugs in my code) I was forced to the conclusion that Scratch has a plotting bug.  Please see project http://scratch.mit.edu/projects/26992347/ and the code in it.  The only difference between the two examples in the demo is a costume change - the code is identical.  The first example does not scale vertically; the second example with a wider sprite scales correctly.

**Comment by nathan** [comment]
You're hitting the `1` case in https://github.com/LLK/scratch-flash/blob/f9885de88083f34437b9427c6ae25d60be054b13/src/scratch/ScratchSprite.as#L250—i.e., the minimum width of a sprite is the smaller of 5 pixels and the unscaled width of its costume.

**Comment by gtoal** [comment]
If the width of the unscaled sprite is 1 pixel, then by that logic the
minimum width would also be 1 pixel, but the problem I reported was that it
was scaled out of existence entirely!

There's a workaround that involves switching to another costume and back,
but the workaround is clearly taking advantage of a caching bug somewhere
and not something you would want to rely on.

Thanks for the pointer to the area of the source where this happens.  I'll
have a look at it.


Graham

**Comment by nathan** [comment]
> the problem I reported was that it was scaled out of existence entirely!

No, the problem you reported was that the sprites' minimum scale was 100%.

> the thin sprites would not scale - they always stamped at 100%

**Comment by gtoal** [comment]
You're right - I was thinking of a related problem.  This was the one where
the workaround was to make the sprite wider but with the added section set
to transparent...

thanks,

G
