### ISSUE TITLE
Tips window should remember html page when it autocloses

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#503]
The Tips window used to remember what step it was on and reopen to that step after autoclosing (for example when adding a sprite). But it now forgets its place -- it goes back to the home (All Tips) page which means people doing tutorials lose their place.

**Comment by jwzimmer** [comment]
It seems like this user is reporting this issue (via freshdesk 58787):
> Hi I wonder if you could help me. I’m currently teaching the children how to create the games in the tips section which come up on the right hand side of the screen. When the children make the scripts, the instructions disappear and they always have to go back into it from the tips menu, then bring up the list of where they were and then click them for the instructions to continue. Is there a way of keeping the instructions on the right hand side of the screen, or at least one click only away from what they are doing?

I have asked them for more information (OS + browser version, student username, any errors, if they're using the online editor and what version appears in the editor).
