### ISSUE TITLE
File open/save as dialogs - filters & default folder

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#525]
1) Default folder in Online/Offline version save/open dialogs is not consistent:

1.1) 'File>Open / Upload' is always forced to Documents
1.2) 'File>Save As / Download' is always forced to Desktop instead
1.3) 'File>Import experimental HTTP extension' remembers last folder used

The first two should at least be the same, probably Documents?

2) File extension filters are not currently used in Offline version dialogs, making it harder to locate Scratch project files. However the online version 'upload/download from computer' does use filters. This directly relates to #307 (but here for the offline version).

2.1) 'File>Open' uses 

```
 All files (*.*)
```

would be more user friendly with

```
 var filter0:FileFilter = new FileFilter('Scratch Projects', '*.sb;*.sb2');
 var filter1:FileFilter = new FileFilter('Scratch 2 Projects (*.sb2)', '*.sb2');
 var filter2:FileFilter = new FileFilter('Scratch 1.4 Projects (*.sb)', '*.sb');
```

2.2) 'File>Save As' uses 

```
 All files (*.*)
```

would be more user friendly with

```
 var filter0:FileFilter = new FileFilter('Scratch 2 Projects (*.sb2)', '*.sb2');
```

2.3) 'File>Import experimental HTTP extension' uses

```
 All files (*.*)
```

would be better with

```
 var filter0:FileFilter = new FileFilter('Scratch 2 Extension (*.s2e)', '*.s2e');
```

**Comment by ntlrsk** [comment]
I agree that these would be good changes and will add them to our developers priority list.

**Comment by arnauldvm** [comment]
IMHO, the default folder should be configurable.
E.g. by a property defined in some kind of configuration file (? $HOME/.scratch or something similar ?)
