### ISSUE TITLE
clicking with grow tool on vector shape should grow it (rather than select it)

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#526]
Right now if you draw a vector shape (e.g., oval or rectangle) and then click on it with the grow tool it selects the object rather than making it grow. (Same with the shrink tool, I think it should shrink rather than select.)

![image](https://cloud.githubusercontent.com/assets/4721032/4894201/6ea2ba3a-63ce-11e4-895e-2adc0a94e145.png)

**Comment by ntlrsk** [comment]
I still find this gets in my way when using the vector image editor.

**Comment by sclements** [comment]
This bug is harder to track down than I assumed.

**Comment by ntlrsk** [comment]
I figured out that it's only for ungrouped shapes that it selects. Grouped shapes do what's expected, which is to grow or shrink. To reproduce, ungroup the cat. Click on an ungrouped part of the cat, and it selects instead of grows.

![image](https://cloud.githubusercontent.com/assets/4721032/10482124/b958eb2e-7243-11e5-89ac-46d57ad09291.png)

**Comment by bsb20** [comment]
Fixed in [1006](https://github.com/LLK/scratch-flash/pull/1006)
