### ISSUE TITLE
add rotate 45 tool to image editor (like in 1.4)

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#528]
In the image editor, a rotate 45 degrees tool (that used to be in the Scratch 1.4) is really needed to help with imported photos (the current rotate isn't easy enough to access in bitmap editor, nor in the vector when the photo is large). 

We would need to ask @carljbowman  to create an icon - like this:
![image](https://cloud.githubusercontent.com/assets/4721032/4908100/092ac44c-6467-11e4-8dc2-1f8f355684bb.png)
(One clockwise, one counter-clockwise). 

Optional: In Scratch 1.4, holding shift + the rotate tool popped up a window for typing in the number of degrees. This would be great but not necessary now (could be an add on later).

**Comment by ntlrsk** [comment]
@carljbowman @bsb20  @thisandagain  - Eric  @SpeakkVisually  said this tool would be very useful to overcome the other stumbling block for people wanting to use magic wand tool - importing photos from cell phone that are at the wrong angle.

**Comment by griffpatch** [comment]
This would be awesome!

**Comment by ntlrsk** [comment]
I suggest putting the rotate tool where the crop tool is now, since the crop tool usually grayed out (the crop tool could just appear in the bitmap tools when something is selected). 
![image](https://cloud.githubusercontent.com/assets/4721032/13987201/c7afd38c-f0dc-11e5-82ff-125d315fca14.png)

**Comment by griffpatch** [comment]
Of course just holding ctrl or shift while dragging the rotation handle
would equally work well too...

**Comment by ntlrsk** [comment]
@griffpatch Yes, though in bitmap that only works after selecting the whole image, so the rotate tool is much easier to explain and help beginners use.

**Comment by griffpatch** [comment]
Agreed, I think a dedicated button is also an excellent idea.
