### ISSUE TITLE
Auto-loading an sb2 project does not work with version from github

### ISSUE THREAD

**Issue by demesos** [LLK/scratch-flash#550]
While the online scratch.swf accepts a project link given in the flashvars, this functionality seems to be missing for this version in Github. if possible please add this functionality or give a hint how to load sb2 files from a webserver on start-up. 

Such a feature would enable further use of this project for teaching (see http://scratch.mit.edu/discuss/topic/38970/?page=8#post-561364)

**Comment by NoMod-Programming** [comment]
It's been two years. Any progress on this?
