### ISSUE TITLE
Right-click on list in Data pane shows other list names in menu

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#552]
Just a little oddity I suddenly noticed...

You can also choose one of the other names, and it (temporarily) changes the name of the list! :)

**Comment by TheLogFather** [comment]
BTW, does this still 'needs-info', or is it clear now...?

**Comment by 2jour** [comment]
Sorry for the delay @TheLogFather . Thanks for bringing this to our attention .
