### ISSUE TITLE
[3D} Stage3D: Colour effect not always applied to stamp

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#553]
Might as well flag this here, to ensure it's 'in the system'...

[strike]The brightness effect hasn't worked for stamps under Stage3D for some time (see here for an example: http://scratch.mit.edu/projects/25638006/ -note comments inside project).[/strike]
EDIT: Forget the line above! -brightness is working now... :D

I think the colour effect stamp glitch with Stage3D might be new - see reports on forums:
http://scratch.mit.edu/discuss/topic/66900/
http://scratch.mit.edu/discuss/topic/66610/
This project is a good demo: http://scratch.mit.edu/projects/26985184/
Adding the blocks "set color effect to 100 / wait (0) secs" right after GF makes it work as expected.

-Could be related to https://github.com/LLK/scratch-flash/commit/d67464ea068c6d41f81f6f455d36211d2683e3f6 ...?

**Comment by cwillisf** [comment]
Looks like this was fixed by the recent 3D changes.
@2jour please reopen if you find that it's not fixed, but it works for me now.

**Comment by TheLogFather** [comment]
Yup, fixed. :)
