### ISSUE TITLE
Context menu not working Firefox Ubuntu

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#572]
OS Ubuntu 14.04
Browser Firefox 
1. Go to scratch.mit.edu and click create
2. Right click anywhere on editor and you do not get context menu

http://scratch.mit.edu/discuss/topic/74128/

**Comment by 2jour** [comment]
@kaschm let me know if @cwillisf has time for this

**Comment by 2jour** [comment]
workaround shift-click

**Comment by jwzimmer** [comment]
We think https://github.com/LLK/scratch-flash-offline/issues/110 is a special case of this issue. Closed #110 in favor of aggregating here.
