### ISSUE TITLE
Booleans that wait (Extensions)

### ISSUE THREAD

**Issue by Felizolinha** [LLK/scratch-flash#575]
Reporters and command blocks are able to do this, but booleans aren't. This is a must-have feature in Scratch Extensions.

**Comment by kaschm** [comment]
@cwillisf marking you as assignee so you can keep track of this one! thanks @Felizolinha for submitting.

**Comment by la10736** [comment]
I like that feature.... If you need some help I can try to see to implement it. Let me know if you are interested
