### ISSUE TITLE
HTTPS URL to project displays editor features in the project player

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#578]
If you access a project using

https://scratch.mit.edu/projects/31550804/

Rather than 

scratch.mit.edu/projects/31550804/

you get a bizarre combination of editor features showing in the project player, including an editable title and portions of the blocks pallet.  Apparently this is happening fairly frequently as we currently have three forum topics reporting it 

http://scratch.mit.edu/discuss/topic/74742/
http://scratch.mit.edu/discuss/topic/75142
http://scratch.mit.edu/discuss/topic/75836

**Comment by 2jour** [comment]
@cwillisf have you seen this?

**Comment by 2jour** [comment]
This may be fixed in the next iteration

**Comment by 2jour** [comment]
Tested able to see projects using https and looks the same as in http 

OS : osx 10.10
Browser Chrome
