### ISSUE TITLE
Duplicating rectangle blocks

### ISSUE THREAD

**Issue by Felizolinha** [LLK/scratch-flash#580]
If you duplicate a rectangle block (blocks with invalid block types become it), it becomes the basic command block. (Tested with Javascript Extensions)

**Comment by 2jour** [comment]
@Felizolinha could i get some steps to reproduce issue ? Thanks :)

**Comment by Felizolinha** [comment]
Create a block exactly like that `['l', '%s', '', 'Rectangle Block']`.
I found out it is more specific that I thought, it doesn't happen to all the rectangle blocks, maybe it only happens if the block doesn't have a function assigned to it (didn't test it) or doesn't do anything.

**Comment by Felizolinha** [comment]
![l glitch](https://cloud.githubusercontent.com/assets/5050667/5733871/6026b740-9b91-11e4-9b41-eed062682eab.gif)

**Comment by 2jour** [comment]
Thank you @Felizolinha
