### ISSUE TITLE
Support for Cyrillic characters in the text tool

### ISSUE THREAD

**Issue by Gromko** [LLK/scratch-flash#581]
Need support Cyrillic text tools for the graphic editor. 
Font Helvetica-Bold already has the necessary character image, and it is embedded in Scratch. 

Cyrillic - a few million new users in Eastern Europe.

Please do not reject our request, it is the same as https://github.com/LLK/scratch-flash/issues/54 and https://github.com/LLK/scratch-flash/issues/231 (closed)

**Comment by 2jour** [comment]
Thank you.  We have reopened the issue #231 and we will continue the thread there.
