### ISSUE TITLE
1080 Hip Hop Sprite Thumbnail missing

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#583]
OS : mac osx 10.10
Browser : Firefox

Server: 2.0.87

1080 hip hop sprite thumbnail is missing 

also in offline, the name is different 1080 dance

marking this as high since we probably need this for our workshops

**Comment by 2jour** [comment]
@cwillisf i think this may just require a rebuild of swf :) for offline and online

**Comment by ntlrsk** [comment]
@rschamp @mewtaylor the thumbnails for the newly revised sprites are missing in the online editor, but the sprites are there once you select them. The missing bitmap thumbnails for sprites are: 
- 1080 Hip-Hop (formerly named 1080 Dance)
- CM Hip-Hop (formerly CM Dance)
- D-Money Hip-Hop (formerly D-Money Dance)
- Jouvi Hip-Hop (formerly Jouvinator Dance)
- LB Hip-Hop (new sprite)
- Nina Hip-Hop (formerly Nina Dance)
 -SL Hip-Hop (formerly SL Dance)

**Comment by 2jour** [comment]
@ntlrsk sprites are there . However, CM Hip-Hop and SL Hip Hop do not have costumes chain*

@cwillisf ping me when there is an offline build that includes the new sprites

**Comment by 2jour** [comment]
closing this issue . Verified in offline editor windows and mac OS X 10.10

@ntlrsk if you notice any issues reopen bug
