### ISSUE TITLE
Choosing "New costume" for newer bitmaps results in oversized image

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#584]
Choosing one of the newer bitmap costumes from the Media Library results in an oversized costume (so its head is chopped off). To reproduce, click "New Costume" in Costume tab and choose Catherine or any of the Hip-Hop sprites:
![image](https://cloud.githubusercontent.com/assets/4721032/5696558/26ad3d6c-99a3-11e4-861c-16957625e36d.png)

**Comment by ntlrsk** [comment]
Note: This is on production as well as the staging server.

**Comment by ntlrsk** [comment]
Ah, I see that the image size numbers in the mediaLib file for those sprites are large. I wonder if we can just change them - without changing the md5?

**Comment by 2jour** [comment]
@ntlsk, @cwillisf  i just imported the images and they look good.. are you still noticing an issue.

**Comment by 2jour** [comment]
@ntlsk @cwillisf sorry still see issue :)

**Comment by cwillisf** [comment]
@ntlrsk the numbers in mediaLibrary.json reflect the actual size of the image. I opened a few of the files and it looks like they were scaled up -- each "pixel" in the original image is actually 4 pixels in the image file. Was that intentional?

**Comment by ntlrsk** [comment]
@cwillisf That's how it automatically uploaded -- that's why I'm thinking it has something to do with the uploading process.

**Comment by ntlrsk** [comment]
I mean the numbers are automatically generated by the "Media Lib - media" script in the Edit menu.

**Comment by ntlrsk** [comment]
New solution has been discussed and will be implemented - costumes will be generated from sprites rather than from mediaLib.json file. For now the oversized costumes will be removed from the costume library.
