### ISSUE TITLE
cloud variable stalling issue

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#585]
Cloud variables can get stuck. When length reaches the 10000 char limit they turn gray in the visualised version and cannot be changed any longer, not even to reset. At least, the value doesn't get set on the server or something so when you come back to the project it has reset to how it was before again.

Deletion of the cloud variable also fails as it just gets re-created automatically, showing as a cloud variable but not functioning as one?

**Comment by TheLogFather** [comment]
I can't say I've seen long cloud variables get 'stuck' like this (the grey happens for all vars, of course, when the watcher reaches a certain number of pixels across, probably 65536 or something - it's even more funky if you're on a machine with a rather old version of Flash).

Do you mean the var doesn't change any more on the server, but still changes 'locally'? Or can it not even be changed locally? (Even by the owner project...?) But it's fine for non-cloud vars?

There does appear to be a limit of 65535 characters imposed when showing the cloud log - anything longer doesn't show up in there (though it does all still work correctly, just doesn't appear in log), but this sounds like something far worse than just not appearing in the log... Do you have an example project you can share (or maybe upload an sb2 here)?

**Comment by griffpatch** [comment]
Hey, the project is this one: http://scratch.mit.edu/projects/12785898/

However, on trying to debug it to answer your questions I struck upon a
reference to the old cloud variable name that I thought I had completely
removed traces of...  So I removed it and lo I was then able to delete the
original cloud variable!  I think the problem with not being able to set it
to might be related to the way you are disconnected from the cloud variable
server as soon as you look inside and update things (like trying to set
cloud variables manually? - Is that right?). So whenever I try to debug
them I end up being disconnected and things go downhill from there! I wish
there was some indicator on the scratch player to highlight when you are
connected or not! :)

So, for now, the project is ok again... I won't be able to replicate the
issue until it occurs again, but perhaps my newest work around will always
fix things - what I do is set up an in game key combination combined with
the user name block being me, that means I can reset the cloud variable
without looking inside and disconnecting from the server...  I guess that's
it really?

Don't you find the best way to solve your own issue is to raise a log for
it ;) - Then the answer finds you almost instantly *grin*.

Still wish strings could be over 10k in size... you don't get many
usernames and achievements stored in 10k especially when you need to encode
as numeric :(

Griffpatch

**Comment by 2jour** [comment]
Thank you for submitting this. We will consider this improvement in the future

**Comment by kaschm** [comment]
@griffpatch - we are going to close this one since you already opened another issue. Thanks.
