### ISSUE TITLE
Sometimes the picoboard and WeDo don't work when both plugged in

### ISSUE THREAD

**Issue by sclements** [LLK/scratch-flash#586]
According to a few users (E.g. http://scratch.mit.edu/users/grokblah/#comments-6707344), order matters when using the Picoboard and WeDo with Scratch at the same time. This seems to be a bug in the browser plugin.

**Comment by cpseager** [comment]
You can sometimes tell when this happens as the WeDo LED goes black, which in theory isn't a possible color...

![blackled](https://cloud.githubusercontent.com/assets/7423187/5728768/e5e93bfa-9b64-11e4-855e-fcad0db5882c.PNG)
