### ISSUE TITLE
Clone costume shouldn't be editable

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#589]
This causes some grief from time to time...

Selecting a clone in the player window means the editor is 'switched' into that clone. The costumes tab now has costumes that belong to that clone, rather than the original sprite. That means any edits made to the costumes, including even whole new costumes, are lost as soon as the project is restarted (or stop clicked), since the clones all get deleted (along with their edited/added costumes) - though it's maybe worth noting that if the costumes tab is still open, you still see the now non-existent clone's costumes...

When a clone is selected, the editor should still get its costumes from the original sprite, not the clone. (And should those edits then get propagated to the clones, so they are seen within the project window...? -otherwise I can imagine some will be confused that the costume visible on-screen still looks the same.)

Some forum links to where this has led to loss of costume edits:
http://scratch.mit.edu/discuss/topic/82062/
http://scratch.mit.edu/discuss/topic/52825/
http://scratch.mit.edu/discuss/topic/60114/
http://scratch.mit.edu/discuss/topic/49612/

**Comment by 2jour** [comment]
1. click on http://scratch.mit.edu/projects/45377546/ and remix
2. Play project
3. move the cat that is behind (this is the clone and by moving it you are selecting it)
4. Go to costume tab of cat
5. duplicate a costume and colour the cat green
6. Click on green flag

Expected: Cat should be green but it takes on costume1

Thanks @TheLogFather for logging this issue :)

**Comment by TheLogFather** [comment]
Also expected: your duplicate costume (now green) is still there - but it's gone!

**Comment by cpseager** [comment]
In that example click on the stage icon bottom left (so stage is selected rather than a sprite).

Double click on the clone cat - nothing happens.
Double click on the sprite1 cat - it gets selected.

So is the bug simply that the click'n'drag of the clone accidentally 'selects' the clone, whereas it should not change the selection at all (to match the double click behaviour). 

If the clone can't stay selected you cannot then edit its properties either.

**Comment by TheLogFather** [comment]
Yes, the bug would go away if clones did not get selected.

I'd point out, though, that being able to select a clone actually does have a rather useful side-effect, namely, the ability to directly interrogate the value of sprite-only variables for a clone (rather than the original sprite).

Without this the only way to do it is by creating a little broadcast receive script that's targeted to a specific clone (via a local clone id variable), which then either uses "say" so you can see the value, or puts the value into a global that you can interrogate.

Still, the potential costume/edit loss needs to be fixed, so if it's by entirely preventing clone selection, then so be it...
