### ISSUE TITLE
Music gets stuck when user changes computer's date/time

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#590]
Bit of a rare & low-priority issue, but thought it'd be worth bringing up while I remember so it's 'in the system'...

Since the music playback on Scratch depends on AS's built-in getTimer, and that depends on the machine's date/time settings, it's possible to mess up playback badly if you happen to change the time on your computer for some reason (e.g. if you're temporarily in a different time-zone and you change local time manually, rather than via shifting time-zone).

It's also worth noting that Scratch's "timer" uses this, too, so it's possible to see a negative value for the timer by setting your computer's clock back in time by an hour or so. :)

I wonder if it's worth adding a little check, at least to see if AS's getTimer has gone backwards (also if jumped forwards by an unlikely amount?), and so add some kind of offset of the previous known 'correct' value...?

**Comment by 2jour** [comment]
@TheLogFather While I am playing music , I change timezone ahead and behind and I did not notice the song getting stuck. The timer looked ok too. Please let me know if I missed any steps. I am using this project to repro http://scratch.mit.edu/projects/45315046

**Comment by TheLogFather** [comment]
Change the actual time, not timezone (as in OP: "change local time manually, rather than via shifting time-zone").

I'm on Macs, so I guess it's also vaguely possible you won't see this issue if getTimer is implemented differently in Flash on other OSes...

**Comment by 2jour** [comment]
server:  scratch.mit.edu
Browser: safari
OS: mac osx 10.10

1. Play this project http://scratch.mit.edu/projects/45523664/
2. Manually set OS time to 1 hour behind.. Timer is set to negative

@TheLogFather  I did not see music being halted only timer being set to negative

**Comment by TheLogFather** [comment]
I think the sound issue only happens if the project is more intensive.
Try adding another script like this: "when GF clicked / set count to 0 / forever / change count by 1 /"
That loop should run at full speed, since it has no screen-updating block in it, so it will hopefully be intensive enough (if not, make a non-refresh block that repeats for a million, or something, and put that into the forever loop instead...)
