### ISSUE TITLE
Offline Editor:  Can't exit editor unless you save project

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#594]
OS: mac osx 10.10
1. Open offline editor
2. Create a project
3. Click the close 'x' icon

A dialog appears to save your work but the editor does not exit which causes confusion to user:

Expected: When you click the close X button ,  editor should close after the save dialog . 

Workaround: Save project and then close .

**Comment by cwillisf** [comment]
This is because the `exportProjectToFile()` call in `saveProjectAndThen()` in Scratch.as doesn't actually clear the `saveNeeded` flag as suggested by the comment. Maybe `exportProjectToFile()` should support a callback, in which case `saveProjectAndThen()` could simply forward its callback.
