### ISSUE TITLE
some changes in image editor not updating

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#598]
Some edits in the paint editor don't seem to be setting the "dirty bit."

For example, "send to back" button: To reproduce: create a new backdrop. In the Vector editor, draw a circle. Then draw a rectangle about the full size of the stage. Send the rectangle all the way to the back. It updates the Stage thumbnails but not on the actual Stage.

**Comment by ntlrsk** [comment]
Typing vector text also does not update on the Stage for a long while...

**Comment by 2jour** [comment]
@ntlrsk I am using this project to recreate issue http://scratch.mit.edu/projects/45528884/. 

I drew circle and then square but sending square back a layer shows on stage.. am i doing something wrong? I also see text appear on stage as I type the letter in the paint editor.

if you save work and then refresh screen do you see the changes on the stage? I am wondering if there is a workaround for this issue

**Comment by 2jour** [comment]
1. remix http://scratch.mit.edu/projects/45551294/
2. go to backdrops and click on backdrop4 
3. in vector paint editor, draw a square , you will see this on the stage. When you click on the Back Layer button ,  a few times, the stage does not get updated only the thumbnail.
4. Type "Hello there" , the stage does not get updated with text only thumbnail.

Expected: any changes you do in the paint editor should reflect almost immediately on the stage:

Workaround:  Save work and refresh screen

**Comment by 2jour** [comment]
still an issue
