### ISSUE TITLE
SCRATCH::allow3d, why and how in FlashDevelop?

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#599]
SCRATCH::allow3d is causing me trouble to open the project in FlashDevelop.
Now, the question arises, why disallow 3d? Is there anyone with a gfx card without 3d?
Can the use of that macro be removed entirely in the project?
Is there anyone that knows how to setup such a macro in flash develop?
I do not think it can make any use of build.xml, but I am nore sure...

**Comment by sclements** [comment]
In the Project Properties, Compiler Options tab, you can populate the "Compiler Constants" list. You should set SCRATCH::allow3d to true there. I hope that helps.
That setting controls whether to compile Scratch with 3d rendering or not. Flash 11 and later versions support the 3d rendering. We compile Scratch twice; once for Flash without 3d and once for those with 3d support.

**Comment by AndersBillLinden** [comment]
Thanks for the fast reply! Isnt flash 11 so old that we could assume 3d support in the player? Just a thought that you may ignore if you wish :)
