### ISSUE TITLE
should be able to fill default white backdrop in Vector mode

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#601]
The default backdrop in Vector mode is a white selectable rectangle. It should be able to be filled with a color. (If you delete it and replace it with one you draw yourself then you can fill it.)

**Comment by TheLogFather** [comment]
Isn't that really a converted bitmap, though? In which case, vector really has no idea (without doing various checks) that it's effectively a white-filled no-outline rect. I guess there are several possible ways to 'fix' it... One could even include the possibility of allowing flood-fill to apply to bitmap-based elements of vector costumes, which would be quite neat.

**Comment by 2jour** [comment]
1. Login to online editor
2. Create backdrop
3. Choose convert to vector
4. Choose fill 

Fill does nothing

Workaround: Create a rectangle and then fill
