### ISSUE TITLE
Cloud does not work in embedded projects

### ISSUE THREAD

**Issue by Felizolinha** [LLK/scratch-flash#602]
When you are **logged in** and use any project with cloud enabled in embed format, **none** of the changes you make to the cloud are saved.

**Comment by 2jour** [comment]
able to reproduce 
http://scratch.mit.edu/projects/49519628/ changes cloud variable
http://scratch.mit.edu/projects/embed/49519628/ cloud variable value not persistent

@sayamindu is this design intent?

**Comment by sayamindu** [comment]
No - it's a bug. I'll take a look at it early next week.

On Wed, Feb 25, 2015 at 9:48 AM, 2jour <notifications@github.com> wrote:

> able to reproduce
> http://scratch.mit.edu/projects/49519628/ changes cloud variable
> http://scratch.mit.edu/projects/embed/49519628/ cloud variable value not
> persistent
>
> @sayamindu <https://github.com/sayamindu> is this design intent?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LLK/scratch-flash/issues/602#issuecomment-75972072>.
>



-- 
Sayamindu Dasgupta
[http://sayamindu.randomink.org/ramblings]

**Comment by TheLogFather** [comment]
Any chance we could also have ye olde http://scratch.mit.edu/discuss/post/123518/ sorted while you're looking at issues with tokens? -It really makes it pretty hard to test relatively complex cloud projects the way it is at the moment...
