### ISSUE TITLE
Javascript Extensions can't be executed on /projects/embed/

### ISSUE THREAD

**Issue by Felizolinha** [LLK/scratch-flash#603]
ScratchExtensions isn't defined in these pages.
Example:
- Open http://scratch.mit.edu/projects/embed/21778760/?autostart=false
- Open the javascript console.
- Try to call ScratchExtensions.

**Comment by 2jour** [comment]
@cwillisf can you take a look at this one if you have time?

**Comment by 2jour** [comment]
Can repro

**Comment by 2jour** [comment]
@kaschm @cwillisf should this be fixed for this iteration?

**Comment by cwillisf** [comment]
It looks like one reason this happens is because the embed page doesn't include the JS files necessary to support extensions.
@rschamp is there a reasonable way for scratchr2/templates/projects/embed.html to include the {% compressed_js 'project_base' %} that editor.html has, or something like it?

**Comment by rschamp** [comment]
@cwillisf Yes. And this issue should be moved to scratchr2.

**Comment by kaschm** [comment]
Moved to scratchr2, https://github.com/LLK/scratchr2/issues/2564
