### ISSUE TITLE
Sprite library preview only shows number of costumes first time selecting

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#604]
When you enter the online version of Scratch and select a sprite in the Sprite library, the preview tells you how many costumes there are. On subsequent selecting of sprites in the Sprite library, that info no longer shows. 

Showing number first time:
![image](https://cloud.githubusercontent.com/assets/4721032/5990136/fea779bc-a970-11e4-8a79-13873eaed887.png)

Subsequently doesn't show them:
![image](https://cloud.githubusercontent.com/assets/4721032/5990138/11547e0c-a971-11e4-8b4e-570ca5073544.png)

**Comment by 2jour** [comment]
Browser: chrome
OS : mac osx 10.10
server: scratch.mit.edu

1. login to scratch.mit.edu
2. Click create
3. Choose Sprite
4. Select Bear2  notice he has 2 costumes
5. Choose Sprite again
6. Select Bear2 and notice no costume number

Expected: costume number appears when we select a sprite
