### ISSUE TITLE
"Edit block colors" is a broken and possibly useless functionality

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#609]
"Edit block colors" (a menu alternative found in the scratch menu and under "Edit") is a functionality that pops up a dialog where there are sliders to change colors of the block categories.

What it will provide is a way to make those categories less recognizable because they will not always have one defined color. The user can change them to his/hers favorite color. They can all be colored the same if the user wishes.

The dialog to change the colors has some buttons that are not easily recognizable as such. The color picker uses three sliders which is a way of picking a color that I think most people would not prefer. The dialog is tall because the sliders are vertical which also fees inconvenient.

Changes in color does not affect those blocks that are already forming a program. If addional blocks in that category are laid out they will have the new color, but old blocks will still use the old color.

How useful is the functionality of changing category colors?

**Comment by ntlrsk** [comment]
Good questions. Actually this was only designed for Scratch Team when we were deciding on what color to make the blocks for Scratch 2. Probably it should be removed - though it's possible when adding extensions or at some other point we may need to reconsider colors, but could always be added back in later.

**Comment by Felizolinha** [comment]
I don't think it should be removed, it's a cool feature, but it needs to be improved. The colors do not save with the project, which is currently what really makes it almost useless. They should also be only shown to the author of the project, to avoid confusion.

I believe the best option would be to save the color configurations in the user's account, and apply it client-side to every project he visits. This would require a "Reset to Default" button in case the user wants to revert these changes.

The input boxes could also support changing values by using the up arrow and down arrow keys, it would improve quite a lot the UX.

**Comment by AndersBillLinden** [comment]
Should all the parameters of the application have settings dialogs then so the developers can test some things out, you think?

**Comment by ntlrsk** [comment]
Thank you both for your ideas! Currently, we are focusing our development efforts on making it easier for new scratchers to create projects. This feature is lower priority than some of the other things we'd like to incorporate first. For this particular ticket, I am going to move this suggestion onto our suggestions roadmap and close the issue.

**Comment by bobbybee** [comment]
@ntlrsk If this was implemented, would you accept pull requests?
