### ISSUE TITLE
Say block floating-point formatting could do with improvements – preferably to show same as variable watcher

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#613]
Some examples to try...

In the following, set the variable to the expression given, and then say it - i.e. "say (var)":
set var to ( (1e-4) / (10) )  <--- fine, gives 0.00001, same as var watcher
set var to ( (1e-5) / (10) )  <---- gives lots of places (note var watcher rounds the expected error)
set var to ( (1e8) \* (10) )  <--- gives 1000000000, same as var watcher
set var to ( (1e9) \* (10) )  <--- gives 10000000000.00 (why the decimal? Lost accuracy somewhere?)
set var to ( (1e300) \* (10) ) <--- fun!
set var to ( (0.0045678) \* (10) )  <--- such rounding...
set var to ( (0.00045678) \* (10) )  <--- but not now...

Is there any reason why "say" should show a different format to what's shown in a variable's watcher?

**Comment by 2jour** [comment]
Created a project to illustrate issue

http://scratch.mit.edu/projects/46489312/

**Comment by Dylan5797** [comment]
With red sprite...
set colour effect to (10^308) = green
set colour effect to join (10^308) "" = yellow
:stuck_out_tongue_winking_eye:
