### ISSUE TITLE
Variable watchers show "Infinity" before the variable actually has value "Infinity" (also for x/y positions)

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#614]
Should be a pretty low-prio  issue, but might as well throw it in here while I remember...

Try this:  set var to ( (1e153) \* (1e153) )
(or any other expression to get a large value beyond ~1.8e+302)

The watcher shows "Infinity", but the variable itself still has the expected value.

E.g. click on it in the editor pane to see its value, or use it in a mathematical expression, or take a look at ( letter (1) of (var) ), etc...

**Comment by 2jour** [comment]
@TheLogFather :) interesting find.

I made a project that highlights this issue http://scratch.mit.edu/projects/46489312/

**Comment by TheLogFather** [comment]
Yup, that shows both this and the other 'say' format issue quite nicely :)

**Comment by TheLogFather** [comment]
It occurred to me that, since the max double is ~10^308, and the min value that shows infinity is ~10^302, and the watcher is set to show 6 places after the point, then could it be that AS's 'toFixed' function actually multiplies the number by 10^N (where N is number of places required) to turn it into an int, and then format that...?
Of course, multiplying 2*10^302 by 10^6 will push it past the double limit...

**Comment by TheLogFather** [comment]
Just tested this and I see that the limit at which it shows Infinity does get higher if I change Watchers.as to show 3 places rather than 6.
I guess a workaround would be to test if the abs(value) is higher than some limit (10^302), and then tweak it in some way if so. (Could divide by 10^6, and then fix up the last two characters afterwards?)
Bit of a pain, though...
