### ISSUE TITLE
Mouse Down Lag (in chrome)

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#615]
Mouse Down events (in chrome on win7) appear to cause an unusual amount of lag on projects with a large number of sprites/clones. The lag only occurs on the mouse down, not during or on the mouse up.

Single clicking on the below is hard to notice, but click click clicking causes the project to stutter and you miss most frames of the animation: http://scratch.mit.edu/projects/45187680/

This is also an issue when running embedded, so appears sadly not to be related to jquery this time.

Testing in IE, the issue is not as pronounced, jitter is still visible on mouse down, but the animation still continues between clicks, whereas in chrome, most of the animation never appears and is skipped over.

**Comment by griffpatch** [comment]
I also note that the issue is exaggerated manyfold by Chrome's built in scratch player. If you use adobe's flash player then there is a small delay on clicking, but the project is not held up. I wouldn't be surprised then if this issue was to mainly manifest itself on windows chrome PCs. It's worth noting that google chrome is attempting to phase out the use of external flash players... that's why I'm not using the built in player again now, and probably why this is now causing me issues.

**Comment by griffpatch** [comment]
A good test for this is DadOfMrLogs lag project: http://scratch.mit.edu/projects/10125047/

In both the embedded and non-embed the project just freezes when clicking on my win 7 core i7 laptop again using chrome. I notice that the list size drops in half and the frame number goes spasmodic, going up in 1's then skipping a lot then going up a little, etc... JQuery trick has no effect.

**Comment by TheLogFather** [comment]
Is it definitely happening on mouse *down*, not mouse up? -I've always had a problem with mouse up on Firefox (for intensive projects, and only on the actual project page, not embedded).

Safari, however, has a quite different problem, with key-repeats taking too long to get dealt with under intensive projects (i.e. they act as if you're still holding down the key long after you've let go). Embedded makes no difference in that case.

**Comment by griffpatch** [comment]
Yes... the initial mouse down is definitely the root cause, although mouse
up also has a 'small' effect.

**Comment by andrewjcole** [comment]
Happens on Linux version of Chrome too.

**Comment by MrFlash67** [comment]
Mac 10.10, Chrome 40.0.2214.111, happens to me, too.

**Comment by 2jour** [comment]
Browser : Safari
OS: mac osx 10.10

Thanks for bring this to our attention @griffpatch . I see this even more pronounced on safari :) where safari freezes and can't be shut down if you click many times.

http://scratch.mit.edu/projects/45187680/ and http://scratch.mit.edu/projects/45187680/

**Comment by andrewjcole** [comment]
For more reference, it does it on Opera a fair bit, too. 

Windows Vista, Opera 27.0.1689.76, Flash 16.0 (release 0)

**Comment by 2jour** [comment]
Currently investigating

**Comment by griffpatch** [comment]
Awesome!

**Comment by sclements** [comment]
I just tracked this down! We're using jQuery 1.7.2 and in the Chrome profiler you can clearly see that jQuery is causing the lag when handling events. Upgrading to 1.11.2 removed the lag. I'll see if we can upgrade next week.

**Comment by griffpatch** [comment]
Oh my, that would be awesome! Well done tracking it down!

**Comment by sclements** [comment]
In case you're interested, here are the graphs from Chrome.
Current jQuery:
![image](https://cloud.githubusercontent.com/assets/874656/6987352/6de025d2-da03-11e4-8be9-c17e998f540c.png)

Upgraded jQuery:
![image](https://cloud.githubusercontent.com/assets/874656/6987362/82bae01e-da03-11e4-9925-195153f37fcf.png)

**Comment by rschamp** [comment]
This is closed because I merged the fix in another repo, but the fix will be deployed next week.

**Comment by 2jour** [comment]
@sclements reopening issue .. still see lag

**Comment by sclements** [comment]
okay, so the bug should stay open and we'll need to move the editor into an iframe to isolate it from any javascript libraries which could be (and are) adding event listeners. it'll be a fairly big change because it will affect all of the editor / js communication and we'll have to resize the iframe when the editor goes full screen.

**Comment by as-com** [comment]
@sclements Will this change break any of our extensions?

**Comment by sclements** [comment]
@as-com We would make it a friendly (same-domain with full DOM access) iframe so it shouldn't act differently in regards to the extension and Scratch communication. However, we'd have to decide if the extensions are in the iframe or not. In the iframe they would work exactly the same as today but not be able to affect the surrounding webpage (creating visible elements around the player). I haven't seen anyone doing that type of thing though so I don't think it matters if we put the extension into the iframe too.

**Comment by as-com** [comment]
@sclements I've seen several other extensions require jQuery and interact with the page in amazing ways. (Just search on the forums.) I think it's necessary to make the extensions run on the main page, not inside the iframe.

**Comment by 2jour** [comment]
Move to Rally ? @kaschm

**Comment by as-com** [comment]
You could try switching to Zepto, if that doesn't cause these issues. Try doing this, though it might be a bit ugly:
```html
<script>
if ("__proto__" in {}) {
    var usingZepto = true;
    document.write("<script src='/path/to/zepto-custom-build.min.js'><\/script>");
} else {
    var usingZepto = false;
    document.write("<script src='//cdn.jsdelivr.net/jquery/1.11.2/jquery.min.js'><\/script>");
}
</script>
<script>
// You must use a separate <script> tag!
if (usingZepto) {
    window.jQuery = Zepto;
}
</script>
```
Notes:
- You will need to create a custom build of Zepto to support all your fancy effects and whatnot: http://github.e-sites.nl/zeptobuilder/
- There may be incompatibilities between Zepto and your existing code, though it might work fine.
- You should use jsDelivr. Seriously, they are awesome.
