### ISSUE TITLE
Blocks palette width scaling

### ISSUE THREAD

**Issue by mactro** [LLK/scratch-flash#616]
When creating custom blocks, loading extensions, or changing language its easy to encounter blocks that are too wide to be visible entirely in the palette. It can be especially annoying when you have two block with similar name beginnings but different endings. It would be nice if we had ability to change palette width or at least to scroll it with horizontal slider, just like you can scroll scripts area.

**Comment by TheLogFather** [comment]
The palette area already scrolls horizontally (e.g. if you drag a block towards its left edge - I use that occasionally to see which custom block is which). It's just the scrollbar that's missing...
