### ISSUE TITLE
Escaping a block drag operation?

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#626]
In the scripts panel, dragging blocks is not always succeeding. Maybe you dragged the wrong block and now you sit and watch it being moved away from a place where you actually wanted it. It would maybe be a good thing to be able to escape the drag operation with the escape key?

**Comment by Scimonster** [comment]
I support this. Good idea.
I've needed this more than once.

On Wednesday, February 11, 2015, Anders Lindén <notifications@github.com>
wrote:

> In the scripts panel, dragging blocks is not always succeeding. Maybe you
> dragged the wrong block and now you sit and watch it being moved away from
> a place where you actually wanted it. It would maybe be a good thing to be
> able to escape the drag operation with the escape key?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LLK/scratch-flash/issues/626>.
>


-- 
Sent from Gmail Mobile

**Comment by AndersBillLinden** [comment]
Implemented this in https://github.com/LLK/scratch-flash/pull/717

**Comment by 2jour** [comment]
Closing issue. Thanks @AndersBillLinden
