### ISSUE TITLE
ScratchExtensions.unregister() requires manual block removal

### ISSUE THREAD

**Issue by Felizolinha** [LLK/scratch-flash#629]
The "Not Loaded" warning isn't the best way to handle this function I believe, it would be much better if it at least had a boolean parameter that allowed you to choose if you just want to unload the extension or also remove it's blocks from the list.
Adding a bunch of extensions into only one category is a mess, it would be really useful to have a way to programmatically remove the blocks from the More Blocks list like it does when you click on the extension's name.

**Comment by 2jour** [comment]
@cwillisf if you have time, could you look at this ?
