### ISSUE TITLE
Right click is way off on Linux

### ISSUE THREAD

**Issue by andrewjcole** [LLK/scratch-flash#632]
When right clicking anything in the editor using Chrome on Linux, the right click is really off as shown here: http://scratch.mit.edu/discuss/topic/90950/

**Comment by Scimonster** [comment]
I confirm this bug.

~Sci

**Comment by 2jour** [comment]
Can't reproduce with linux distro on sauce but can reproduce with 

OS: Ubuntu 14.04.1 via vmware
Browser: Chrome 40
Server: scratch.mit.edu
1. Go to Create
2. Right click on stage : Context menu far from where you clicked
3. Right click on sprite: Not able to get context menu for Ubuntu OS

**Comment by markroth8** [comment]
I don't have it with me right now, but last time I checked (about a week ago) I saw the same behavior on Chromebook.

**Comment by andrewjcole** [comment]
Hmmm... now it's off the the right.

**Comment by andrewjcole** [comment]
It is never off for me in Windows Vista/Chrome.

**Comment by jwzimmer** [comment]
Similar-sounding issue reported by @chooper100 in https://github.com/LLK/scratch-flash/issues/1181:
> Right clicking for variable watchers on the stage sometimes seems to miss them even when the mouse is over them (particularly noticed this when the watchers are in slider mode)

**Comment by isiahmeadows** [comment]
Can repro on Windows 10 + Google Chrome as well. It's consistently ~100px left, ~25px up from the cursor.

**Comment by Kenny2github** [comment]
It only happens to me on Windows 7 (school computers use windows 7, happens there; home computers use windows 10 and 8, nothing happens).
Also, it seems to only happen after using the editor for a long time.
