### ISSUE TITLE
The block of 'floatNumber = n' should be modified

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#647]
When green flag clicked, the sprite will not say 'hello' because of float number:
![image](https://cloud.githubusercontent.com/assets/8316018/6370367/82674e36-bd2a-11e4-8f4f-f06cbd20cf31.png)

To modify this, we should modify '=' function:
![baidushurufa_2015-2-25_20-21-6](https://cloud.githubusercontent.com/assets/8316018/6370626/6db162da-bd2d-11e4-8f52-0a8c7c0e1e07.png)

After that, the sprite say 'hello':
![2](https://cloud.githubusercontent.com/assets/8316018/6370628/75a88644-bd2d-11e4-9cc0-2ba42773eb32.png)

**Comment by AndersBillLinden** [comment]
You can't compare floating point numbers like integers. You have to use < and > instead. In your code, you put a < block instead of hte = block and compare var with 10000 using that block.

http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by lize777** [comment]
@AndersBillLinden  I know what you mean. I am a Chinese Scratch teacher now and a programer before, however, many teachers are not know what is float and interger. So they will wonder why 1/3=0.33 is false. So I think this modify is intuitive and good at Scratch beginners.

**Comment by AndersBillLinden** [comment]
We can't change how IEEE floating point numbers are stored. In binary. There is no exact representation of the number 0.2 using binals (binary digits).

**Comment by lize777** [comment]
@AndersBillLinden I understand how float number convert to binary and we can't change standard, so I suggest that we can do something on the layer of software : )

**Comment by AndersBillLinden** [comment]
If you want to step from a number A to another number B using a step of 0.2, you can always step from the number thats 10 times A to the number 10 times B, using a step of 2 and then in each step calculate the current value/10.

**Comment by lize777** [comment]
![image](https://cloud.githubusercontent.com/assets/8316018/6376586/c5c9eb5a-bd59-11e4-93b2-938eaf4a55e8.png)
@AndersBillLinden

**Comment by Felizolinha** [comment]
@lize777 Just a correction, 1/3 is not equal to 0.33 even in decimal :x It would be too imprecise to consider that. I suggest editing your example to use values like 1/10 and 0.1.
