### ISSUE TITLE
There are lots of wrong Chinese translation. Please update it.

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#648]
Scratch / local / zh-cn.po.

line 185 & 186
-----------------
wrong
msgid "join %s %s"
msgstr "将 %s 加到 %s 的后面"

right
msgid "join %s %s"
msgstr "连接 %s %s"

line 212 & 213
-----------------
wrong
msgid "mouse down?"
msgstr "鼠标下移？"

right
msgid "mouse down?"
msgstr "鼠标按下？"

line 478 & 479
-----------------
wrong
msgid "when Stage clicked"
msgstr ""

right
msgid "when Stage clicked"
msgstr "当舞台被点击时"

**Comment by 2jour** [comment]
@ntlrsk can you take a look when you get the chance?

**Comment by lize777** [comment]
Scratch has growing effect in China, so right translation is vital. So please udpate it, especially line 185 & 186(This is absolutly wrong).

**Comment by cpseager** [comment]
@lize777 
You can submit any corrections here, and add any of the missing ones as well!
http://translate.scratch.mit.edu/

e.g. 'when Stage Clicked' is here:
http://translate.scratch.mit.edu/zh_CN/blocks/translate/blocks.po#unit=427158

**Comment by lize777** [comment]
@cpseager I have correct many of translation on this website.
e.g.
![1](https://cloud.githubusercontent.com/assets/8316018/6377058/b689e066-bd5c-11e4-8ae5-c5abeaec7040.png)

However, it seems to nobody there.
So I directly suggest to Scratch developers.

**Comment by ntlrsk** [comment]
@lize777 Thank you for letting us know. We are contacting the administrator of Chinese to accept the suggestions you have submitted.

**Comment by ntlrsk** [comment]
@lize777 I accepted the change for line 185 & 186 连接 %s %s - thank you for pointing out the previous incorrect translation

**Comment by 2jour** [comment]
@ntlrsk, @kaschm said you were looking into it.

**Comment by ntlrsk** [comment]
I already have approved these earlier and they should appear in the release next Thursday or Friday.

**Comment by ntlrsk** [comment]
We also have arranged for an educator and translator collaborating with our group to go through the remaining suggestions. @lize777 Thank you for your contributions!

**Comment by lize777** [comment]
@ntlrsk Not at all. I enjoyed it.
