### ISSUE TITLE
Broadcast - Trim event names

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#650]
![image](https://cloud.githubusercontent.com/assets/8316018/6386047/dfb459c0-bdad-11e4-806d-fb47e9f53edd.png)

I think 'a' is equal to '(space)a(space)'. So it is time to trim when we input a new message.
![image](https://cloud.githubusercontent.com/assets/8316018/6386614/acbacfdc-bdb6-11e4-8bd7-2f8b3d8acee4.png)

**Comment by AndersBillLinden** [comment]
My suggestion is that all variable-, list- and broadcast names should be trimmed.
