### ISSUE TITLE
The center point of custome often auto-modified when I first click Customes tab.

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#656]
This bug exists offline editor, and exists in lots of Scratch versions(include v432).

For example, the real center point is here:
![image](https://cloud.githubusercontent.com/assets/8316018/6482985/f348ef48-c2a6-11e4-898e-cc95a5149d40.png)

However, when I open a project and when I first (only first) click Customes tab, the center point sometime is auto-modified!
![image](https://cloud.githubusercontent.com/assets/8316018/6483084/d9ac7d10-c2a7-11e4-898e-1631906e086b.png)

Please fix this bug, it is very very annoying!

**Comment by 2jour** [comment]
Hi @lize777 ,

Would you be able to include a link to the sb2.. I am having trouble reproducing ..

**Comment by lize777** [comment]
@2jour This is a universal problem, not a special sb2 file.
