### ISSUE TITLE
Crop Causes Duplicate

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#658]
scratch.mit.edu/discuss/topic/95778/

Browser: Chrome
OS: mac os x 10.10
server: 2.0.94
1. Go to Editor
2. Go to costumes and crop scratch
3. You will notice that if you move cropped image , there is a duplicate underneath.

**Comment by 2jour** [comment]
@kaschm why was v434 removed? Our update introduced this.

**Comment by kaschm** [comment]
@2jour - considering workload, we went through the list of issues and isolated the ones that are most important for the next release. let's chat offline.
