### ISSUE TITLE
List Variable Takes Over  Script Area : Green Flag Disappears

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#660]
I can't even remix this :(!!!! I have not been able to repro.  According to discussion, it has to do with stage3d .However you can probably debug with this test case

This project has no green flag. If you click 'See Inside' you only see list
http://scratch.mit.edu/projects/26787508/

**Comment by 2jour** [comment]
Able to repro part way
In Editor
1. add a sprite with (when green flag clicked) (change colour) block
2. Create a list variable and resize it to the size of the whole screen .
3. click green flag and the list takes over the whole screen. It is hard to to modify blocks or anything in script area

http://scratch.mit.edu/projects/51071828/

**Comment by TheLogFather** [comment]
As mentioned in the discussion topic, this a dup of #452.
