### ISSUE TITLE
Linux Vector Images: Cannot Edit in Bitmap Mode

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#662]
OS : Linux (sauce linux) , (in forum used Ubuntu)
Browser: Firefox 36

Create
Choose sprite vector heart
Click on costume tab for vector heart
Heart sprite disappears and the editor is in a weird state

Please see https://github.com/LLK/scratch-flash-online/issues/111 for more details

I think this  may be it  LLK/scratch-flash@57dadab

**Comment by Sonickyle27** [comment]
Seems to not happen in Chrome's pepperflash.
When I use Firefox, whenever I click on a bitmap costume it is completely wiped out with no way to recover the image. It's like I've clicked the clear button.

**Comment by 2jour** [comment]
Its currently under investigation. I will mention your findings with regards to chrome on the discussion board http://scratch.mit.edu/discuss/topic/95810/ ..  This may help someone find an alternative solution on Linux.

**Comment by 2jour** [comment]
Fixed for v433a
