### ISSUE TITLE
C-Blocks in Scratch Extensions

### ISSUE THREAD

**Issue by kvackkvack** [LLK/scratch-flash#667]
When making my Scratch extension, I noticed that when making a C-block the code inside won't run.
I posted a discussion page on this issue ( http://scratch.mit.edu/discuss/topic/97118/?page=1 ), and on there we came to the conclusion that C-blocks are unimplemented and just don't work. If this is true, I would suggest that this is implemented as fast as possible since many current Scratch extensions use these without anything working. Thanks!

**Comment by 2jour** [comment]
@cwillisf should this be implemented for this iteration in lieu of the extension work you are doing?
