### ISSUE TITLE
Some backdrop costumes get cut off

### ISSUE THREAD

**Issue by sclements** [LLK/scratch-flash#672]
If you add a new backdrop costume from the media library and select the baseball-field it looks OK at first. Looking in the costume editor you can see that it's cut off and if you switch costumes and come back to it then it will be cut off in the player as well:
![image](https://cloud.githubusercontent.com/assets/874656/6693645/1bc545d2-cc9a-11e4-92ac-ae604a2be0fa.png)

**Comment by AndersBillLinden** [comment]
I have tried to address this bug in my branch https://github.com/AndersBillLinden/scratch-flash/tree/fix-cutoff-backdrops. I have only tried this fix in the offline editor and the baseball image loads as it should (other images also do). Loading a project with that baseball backdrop has also been tested.

**Comment by 2jour** [comment]
Is this the only background or are there others?

**Comment by 2jour** [comment]
looks like only baseball background is impacted downgrading to prio-medium.. if this affects more backgrounds will change to prig-high

**Comment by sclements** [comment]
We should be able to simply check the dimensions to determine the bitmap resolution (1x vs 2x) since backdrop bitmaps will always be either 480x360 or 960x720.

**Comment by 2jour** [comment]
This exists for offline editor v437
