### ISSUE TITLE
Suggestion: WeDo should use active braking

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-flash#674]
@cpseager has suggested (see https://github.com/LLK/scratch-flash/issues/673#issuecomment-82687074 and https://github.com/LLK/scratch-flash/issues/499#issuecomment-76519599) that the WeDo extension should use active braking, where the motor actively stops rotating immediately when it turns "off". Currently, the motor coasts to a stop.

@ntlrsk do you have thoughts on this from a design perspective? Should we allow both kinds of stopping? Perhaps we could have a "Hit the brakes!!!" block, maybe with better text... ;)

@cpseager or others, feel free to share your thoughts too, of course.

**Comment by cwillisf** [comment]
Active braking is one potential fix for #673 -- another is in [this comment](https://github.com/LLK/scratch-flash/issues/673#issuecomment-82952192). The appropriate fix depends on whether we're using active braking or not.

**Comment by ntlrsk** [comment]
@cpseager Glad you understood what the issue was! Do you think it will act very differently if the turn onfor block uses active braking?

**Comment by cpseager** [comment]
@ntlrsk Some Wedo Lego models that need positional accuracy can benefit from active braking - the 'fairground ride / ferris wheel' is a good example.

https://education.lego.com/en-us/lesi/support/product-support/wedo/wedo-base-set-9580/building-instructions

For others such as the 'sailing boat' it doesn't really make any difference, but in these cases active braking does no harm. So generally I think being able to use active braking would be a good improvement.

I've already written a demo replacement wedo js plugin that has an 'motor braking on/off' extra block that I can share so you can try it out for yourself, but I first need to wait until #499 fix is available in the next offline release to make sure my demo is working correctly. You could then demo it and decide whether to enable it permanently (or make it available as an extra new block).

@cwillisf Active braking does stop the ID working completely. So the approach I took was to active brake (128) for a while - e.g. 200 ms, and then switch back to 0.

**Comment by ntlrsk** [comment]
@cpseager Thanks for explaining that, and the fix you're suggesting sounds great.

Integrating it in makes the most sense (rather than adding an active breaking block).

Question: Does turn motor off do active breaking?

**Comment by cpseager** [comment]
@ntlrsk Nothing currently active brakes, but 'motor off' could.
