### ISSUE TITLE
renaming lists

### ISSUE THREAD

**Issue by sp00py** [LLK/scratch-flash#677]
you can rename variables, but not lists. this seems inconsistent.

**Comment by AndersBillLinden** [comment]
https://github.com/LLK/scratch-flash/pull/640

**Comment by sp00py** [comment]
@AndersBillLinden ah I should've looked. Sorry!

**Comment by AndersBillLinden** [comment]
No problem, I need your help to push that change!

**Comment by sp00py** [comment]
Oh, then OK! :)
