### ISSUE TITLE
Crop Button Not Inactive If No Selection

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#680]
OS : any
Browser: any

1. Go to editor
2. Go to costume editor and use the bitmap editing tools
3. Click on the crop button and nothing happens

Expected: Crop Button is inactive until a selection has been made.

**Comment by sclements** [comment]
Perhaps we need to better communicate with the user. The code always crops the bitmap and only keeps the smallest bitmap that holds the visible pixels. Here is the code:
https://github.com/LLK/scratch-flash/blob/master/src/svgeditor/BitmapEdit.as#L217
