### ISSUE TITLE
Offline Editor does not support HiDPI displays

### ISSUE THREAD

**Issue by as-com** [LLK/scratch-flash#683]
On my Retina MacBook Pro, the offline editor looks disgustingly pixelated, while the online editor does support retina displays and scales the editor accordingly. The pixelation makes editing projects offline unpleasant.

**Comment by ntlrsk** [comment]
@as-com I can confirm that. I somehow hadn't noticed that until you just mentioned it.

**Comment by cpseager** [comment]
Try adding

       <requestedDisplayResolution>high</requestedDisplayResolution>
to the < initialWindow > section in application.xml

**Comment by 2jour** [comment]
Did you notice a difference @as-com ? I didn't see a difference using requestedDisplayResolution

**Comment by as-com** [comment]
@2jour Adding `<requestedDisplayResolution>high</requestedDisplayResolution>` to the `<initialWindow>` section in application.xml did not seem to do anything. It's still pixelated.
