### ISSUE TITLE
New Chinese Translations Not Showing Up In Editor

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#684]
For example, in Operators, the join block should say: 连接 __ __  but still shows the old text: "将 _ 加到 _ 的后面"

More importantly, “Add an Extension” and the LEGO WeDo blocks are showing just English. We are planning to base our workshop on using those blocks. 

I see there are errors in the Javascript console (attached) - do you think it is because of that? Note that those errors also seem to be calling from an earlier version of the translations (before %m.motor was added).

**Comment by 2jour** [comment]
Can I close @cwillisf ? @mewtaylor ?

**Comment by cwillisf** [comment]
Yep -- fixed with LLK/scratchr2@dc6822d and LLK/scratch-flash-offline@f3bffae
