### ISSUE TITLE
User Variables (aka personal cloud variables)

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#689]
This is a feature request, and one that will no doubt need some serious work to support, but I think it's worth raising as a change request so as not to get lost in the forums of scratch forever!

See: https://scratch.mit.edu/discuss/topic/15299/?page=1

Put simply it would be a personal cloud variable for the logged in user that is saved and read like a normal cloud variable, only it is saved for them only, and each user sees only their own variable value.

This would put a lot less strain on the cloud server in terms of users writing loads of data to a single variable just to get and put a small amount of data in it...  and it would make larger scale per player saving in games possible.

Please consider!

Many thanks,

griffpatch

**Comment by ealgase** [comment]
I like this idea.  You should still be able to make cloud variables, too.

**Comment by griffpatch** [comment]
Sure...  We definitly need cloud variables to stay the same as well, so
you'd just need a fourth option when creating variables.

"For all Sprites", "For this sprite only", "Cloud variable", "User/Personal
cloud variable?"

**Comment by MegaApuTurkUltra** [comment]
1. Another (more recent) discussion: https://scratch.mit.edu/discuss/topic/87548
2. @djdolphin's extension: http://scratch.mit.edu/discuss/topic/65698/

I've been supporting this for a while.

**Comment by sayamindu** [comment]
This may be easier with an extension that uses localstorage. Does that address the use-case? (it will be tied to a browser though, rather than a user)

**Comment by griffpatch** [comment]
I don't think so because it's primary use is to allow users to continue a
game where they left off. If implemented then it would allow for scratch
projects to be designed that support far more depth and replay value. It's
a feature that has been requested in a number of similar forms for many
years and would be wanted by everyday scratches to allow them to play
scratch games. I've been asked for per player saving for two years now by
literally hundreds of scratches and I've had to say I can't do it in
scratch! That seems a shame and perhaps a reason to think about including
it?

Thanks, griffpatch

**Comment by griffpatch** [comment]
Actually just to be clear, I would support the local storage idea, that
would work especially if the Web browser sports shared local storage across
computers like I think chrome does? However I suspect on school computers
that this would not be a workable solution?

Am I right in saying that a scratch extension would not work naively for
all scratches without installing the extension, or is it actually something
that you can add and then players automatically make use of it?

**Comment by griffpatch** [comment]
Ok, so I read up on extensions :) and yes! We could indeed write an
extension for this. However am I right in thinking that you can't write
extensions unless you are invited to the development program? Also
extensions are not made available until they are fully vetted and
accepted... I have to say I got exited when I saw the javascript interfaces
and thought of all the things I could do with them  ;) any idea whether I
can get on the Dev program? :)

**Comment by MegaApuTurkUltra** [comment]
@griffpatch:
1) You don't need to make an extension. One already exists: http://scratch.mit.edu/discuss/topic/65698/
2) I've tried to get into the dev group. It's been months since the ST told me they would do something, yet nothing's happened.

**Comment by ealgase** [comment]
You can't join the dev group, but you can code extensions without being in it: http://ealgase.github.io/Scratch-Boost

**Comment by Iwotastic** [comment]
This would be a good idea

> 1) You don't need to make an extension. One already exists: http://scratch.mit.edu/discuss/topic/65698/

Or [this one](http://Iwotastic.github.io/Scratch-Boost).

**Comment by 2jour** [comment]
@kaschm assigning to you .. since this is something that may be added to rally.

**Comment by aianmoo16** [comment]
support

**Comment by liam4** [comment]
Support.

**Comment by TypicalHog** [comment]
Support!
