### ISSUE TITLE
[Translation][Website] Outdated tip: "Currently there is one extension available"

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#696]
The following tip is outdated, because we now have 2 extensions:

    Currently there is one extension available:<br>
    <a href=“../../ext/wedo”>LEGO WeDo</a>

*templates/info/help/studio/tips/blocks/add-an-extension.html:22*

Translation file: *django.po*

Also reported on the forum: https://scratch.mit.edu/discuss/topic/102968/

**Comment by 2jour** [comment]
creating sub issue

**Comment by ntlrsk** [comment]
Updated and will go out with next content push - thanks.
