### ISSUE TITLE
Offline 'file overwrite' prompt incorrectly formatted

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#701]
The offline version has a strangely formatted warning about overwriting an existing file when using 'Save as'...

![saveaswarning](https://cloud.githubusercontent.com/assets/7423187/7013084/6068bf24-dcae-11e4-8bb3-139cb9905d73.JPG)

**Comment by 2jour** [comment]
@cpseager what version of air do you have?

**Comment by gunchleoc** [comment]
I can reproduce this

Windows 7
Adobe Air 17.0.0.124

Also, the string isn't localized.

**Comment by cpseager** [comment]
@2jour 17.0.0.124 on Windows 7

**Comment by 2jour** [comment]
Thanks :)

**Comment by 2jour** [comment]
Yes can repro :) @cpseager
