### ISSUE TITLE
[Translation][Website] Country stats needs plitting and plural forms

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#703]
The following list items need individual translations with proper plural forms:

```
            <li class="data"><span class="value">%(projects)s</span> projects shared,</li>
            <li class="data"><span class="value">%(users)s</span> users registered,</li>
            <li class="data"><span class="value">%(comments)s</span> comments posted,</li>
            <li>&hellip;and growing!</li>
```

_templates/stats/country.html:12_

```
            <li class="data"><span class="value">%(projects)s</span> projects shared,</li>
            <li class="data"><span class="value">%(users)s</span> users registered,</li>
            <li class="data"><span class="value">%(comments)s</span> comments posted,</li>
            <li class="data"><span class="value">%(studios)s</span> studios created</li>
            <li>&hellip;and growing!</li>
```

templates/stats/index.html:12

It is no problem for my language, because I expect numbers to be >= 20, but the Slavic languages have some interesting modulus stuff going on. e.g. Russian:

```
nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);
```

Also, the studios are missing from the first list. Is this on purpose?

**Comment by 2jour** [comment]
created sub issue

**Comment by gunchleoc** [comment]
Found another string that needs a plural form:

    Sorry, you have to wait %d seconds between posts.

djangobb_forum/forms.py:130 djangobb_forum/forms.py:134

**Comment by gunchleoc** [comment]
And some more:

    Found %i posts.
djangobb_forum/views.py:297

    Found %i topics.
djangobb_forum/views.py:301

**Comment by gunchleoc** [comment]
And another one - it also contains a typo (allows => allowed)

    (%(count)s answers allows.)
djangobb_forum/templates/djangobb_forum/topic.html:43

**Comment by gunchleoc** [comment]
And another one:

     posts

djangobb_forum/templates/djangobb_forum/topic.html:105

Needs to be (in 1 string fetched as plural form):

    %i post
    %i posts
