### ISSUE TITLE
[Translation][Website] Change "gallery"/"galleries" to "studio"/"studios"

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#704]
Some dross left over after the renaming:

```
You do not own any galleries. <a href=>Create one!</a>
```

_templates/studio/includes/galleries_list.html:26_

```
You do not have any galleries
```

_templates/studio/includes/gallery_list.html:37_

Best grep the .po file to make sure I didn't miss any.

**Comment by 2jour** [comment]
created sub issue
