### ISSUE TITLE
I can't send the same request more than once using extensions

### ISSUE THREAD

**Issue by rodrig0lima** [LLK/scratch-flash#706]
I'm part of a project and we need to use Scratch with the s2a_fm extension. The problem is: i upload the extension I need, and watch the prompt for the log of requests. When I use the online version of Scratch I can make the number of requests of the same type I want, repeating the command already sent to Arduino, but when I use this version I can't, I click to execute the project and it doesn't do anything. 

Here is an image of the prompt, receiving only once the command I want: 
![erro](https://cloud.githubusercontent.com/assets/7308811/7057761/aa311160-de2f-11e4-9920-3aa400789595.png)

I try to make the same request again and it doesn't receive anything, probably because the scratch didn't send anything. I try to send different kind of requests and it does receive, but i need to repeat requests for this project using this version of Scratch. Is there anything i can make to solve it? We need the solution as soon as possible, if you guys could help we would be thankful.

**Comment by 2jour** [comment]
Hi @rodrig0lima,  have you tried logging an issue with the group who created s2a_fm at https://github.com/MrYsLab/s2a_fm?

**Comment by rodrig0lima** [comment]
I used the scratch online and even the offline to test it and I didn't have this issue, I don't this this is a problem with that extension, because it is receiveing the requests from the other versions of Scratch. But I'll report this issue and I want to know if is there a known issue that may cause this with this extension.

**Comment by rodrig0lima** [comment]
Here is an example of the s2a_fm working well unsing the Scratch offline:
![erro2](https://cloud.githubusercontent.com/assets/7308811/7058388/831da0d6-de37-11e4-8ad0-ac02b31e808d.png)
There you can see the same request over and over, and when I try with this version i can't get it. I tried to look for a solution in the code, but I couldn't find, I was looking for some statement that blocks repeated requests or something like that. Is there a block for repeated commands/requests that will be send to the extension?

**Comment by 2jour** [comment]
Hi @rodriglima

We need some more information so that we can help you. Could we have the version of Scratch where you notice the failure?  You can find the version number at the top left corner on the stage. The current offline editor version is v434a. 

We also need to know where in the interface between s2a_FM and scratch its failing. You can look at the following documents 

 * http://llk.github.io/scratch-extension-docs/
 * http://wiki.scratch.mit.edu/wiki/HTTP_Extension#HTTP_Extensions 

However, I think its easier to contact @MrYsLab, the author of s2a_fm. @MrYsLab would probably know existing limitations and may also suggest where scratch is failing.

**Comment by MrYsLab** [comment]
Hi @rodriglima,
Could you please file an issue at https://github.com/MrYsLab/s2a_fm? I am not sure if I understand the problem you are reporting, so could you please provide a screen shot of the Scratch scipt?

Also, how are you running the Scratch script? It is hard to tell what your script looks like from the screen-shot. Do you run in a Scratch loop, or are you starting the script over and over again and setting the value of the pin manually?

**Comment by rodrig0lima** [comment]
First thing: Sorry for english mistakes, I'm trying my best.
Hi @2jour, I was using the scratch-flash v433 but it is also noticed in the version i just downloaded: v435. I haven't modifed the Scratch source code.
Here is some prints and tests that may help finding where in the interface is the issue.
And Hi @MrYsLab  I'm running the same Scratch code in the prints. I tried both ways, setting the value of the pin manually and inside a loop. Both ways it accepts only once some kind of request. (E.G.: Using this version of Scratch If I turn a led on and off I can't turn it on again, even in a Scratch loop. And when it occurs i have to restart the Scratch-flash).

I tested once more the issue, I just downloaded the latest version of scratch-flash and I'll run the first test 3 times. 1st with scratch-flash v435, 2nd with Scratch Offline (v434)(https://scratch.mit.edu/scratch2download/) and 3rd with Scratch online (ttps://scratch.mit.edu/projects/editor/). For the tests i'm running the same Scratch code, with debug on and i'll print the variable cmd_list inside the s2a_fm code, which will print every request Scratch does. Here is how i'm printing the request for tests x.1
![moment of print](https://cloud.githubusercontent.com/assets/7308811/7123725/80b57582-e1fa-11e4-9aba-de662435f686.png)
For second tests (x.2) I'll only use the debugmode of s2a_fm, I will not print cmd_list anymore.
![noprint](https://cloud.githubusercontent.com/assets/7308811/7123839/5d09788a-e1fb-11e4-8881-61cc114c4ef7.png)

Test 1.1 - Scratch-flash, printing request
![scratch-flash-teste1](https://cloud.githubusercontent.com/assets/7308811/7123832/4b4401c4-e1fb-11e4-9c5e-da9815ad5b88.png)
It doesn't make anymore requests, compare with the other versions below.
Test 1.2 Scratch-flash, without "print cmd_list"
![scratch-flash-teste2](https://cloud.githubusercontent.com/assets/7308811/7123850/69a79e46-e1fb-11e4-85a9-faa160964d5a.png)
You can see that the time is going on and it doesn't send requests anymore.

Test 2.1 Scratch Offline, printing requests
![scratch-offline-teste1](https://cloud.githubusercontent.com/assets/7308811/7123903/b742c1a8-e1fb-11e4-9405-a4e24f0a69ea.png)
As you can see, it sends a lot of polls as soon as it is connected. 
![scratch-offline-teste1-1](https://cloud.githubusercontent.com/assets/7308811/7123919/d80e542e-e1fb-11e4-80fe-9de2598d94f1.png)
Test 2.2 Scratch Offline, without "print cmd_list"
![scratch-offline-teste2](https://cloud.githubusercontent.com/assets/7308811/7123951/17250612-e1fc-11e4-9f28-6a88ed38cf89.png)

Test 3.1 Scratch Online, printing requests
![scratch-online-test1](https://cloud.githubusercontent.com/assets/7308811/7123973/33ae1ce2-e1fc-11e4-9ec6-176386442230.png)
![scratch-online-test1-1](https://cloud.githubusercontent.com/assets/7308811/7123979/380a347e-e1fc-11e4-8217-62f2650ca699.png)
Test 3.1 Scratch Online, without "print cmd_list"
![scratch-online-test2](https://cloud.githubusercontent.com/assets/7308811/7123983/4acbebf2-e1fc-11e4-97eb-d0a9c86c7f39.png)

**Comment by rodrig0lima** [comment]
Funny part is that if I try to use another port (make another kind of request) it works. But if I try to use the same port of arduino (make the same kind of request) it doesn't work. 
Here is the main Example:
![teste](https://cloud.githubusercontent.com/assets/7308811/7124286/2c6f65b0-e1fe-11e4-97b3-08ccfec3ac25.png)

**Comment by MrYsLab** [comment]
@rodrig0lima From the s2a_fm debug statements in you screen shots, I would tend to agree with you that the Scratch build has a bug. The s2a_fm interface to scratch is pretty simple, and if the debugs do not show a command appearing, it is most likely Scratch is not sending them. Have you tried building version 434a, which is the latest official off-line version? I have never built the Scratch SWF version, but if it creates the same file as the file that is provided as part of the official off-line download, it should work the same.

Sorry if I could not be of more help.  but if I can answer any questions about s2a_fm to help you solve the issue, please let me know and I will be happy to do so.

**Comment by rodrig0lima** [comment]
Hello again @2jour, I would like to know how do you run the scratch-flash that you just built, I ran it on basic flash players, do you run in a specific way or you just open it? I think that this may influence the way the scratch send requests. 
And does this version of scratch can open extensions in a browser? I tried once and didn't have success, and I saw some issues reports about it, is there a correct way to do this?
Thanks for the help.

**Comment by rodrig0lima** [comment]
@MrYsLab Thanks for the attention in my issue, the scratch off-line version comes with an executable, you run it and then you can use the scratch version. But when you build a scratch-flash version, you have a .swf file to execute, and I think that my issue may be caused by the way I'm running it. I'm looking for some ways to run it on a browser but I can't t even open the extensions on the built version (not even the s2a_fm), so I can't test if the problem is with the way I am running the scratch-flash.
If you guys have any information to help me I would be thankful.

**Comment by MrYsLab** [comment]
@rodrig0lima Currently s2a_fm works only with the off-line version of Scratch, and xi works only with the on-line version. The Scratch off-line version does not use a web browser. You might want to look at Snap! https://github.com/jmoenig/Snap--Build-Your-Own-Blocks. This uses a browser, but can be run directly from your PC without a web server. Creating extensions is quite easy and s2a_fm already supports Snap! if you want to look at an example.

Good luck!

**Comment by 2jour** [comment]
@rodrig0lima sorry for the delay .. 

has @MrYsLab comments been helpful are you still stuck?

**Comment by 2jour** [comment]
We are closing this issue. If you have an issue, please let us know
