### ISSUE TITLE
[3D] Adding colour block changes the direction of sprite

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#708]
server: Production
Reporter: MegaApuTurkUltra
1. go to this project https://scratch.mit.edu/projects/56441274/
2. add set colour effect block and dog will point in direction 90
3. take away block and dog will point in direction -90

can not repro with other sprites.. not sure why

**Comment by 2jour** [comment]
Marking as medium since I am unsure how many cases are impacted by this.

**Comment by djdolphin** [comment]
I played around with this, and it looks like this is what causes the bug:
1. Switch the sprite to a bitmap costume.
2. Set its rotation style to left-right and point it in the direction -90.
3. Add a color effect block.
It doesn't happen if steps 2 and 3 are switched.

**Comment by 2jour** [comment]
Thanks @djdolphin :)!!!

**Comment by TheLogFather** [comment]
It will happen in a newly-loaded project if the sprite was facing left when saved.

Here is a simple project that clearly demonstrates the problem:
https://scratch.mit.edu/projects/152407373/
