### ISSUE TITLE
Consistency of touching behaviour for hidden sprite

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#709]
This is something that comes up from time to time (I know it kinda surprised me when I first met it).
For example, recently: https://scratch.mit.edu/discuss/topic/104672/

Just thought it might be useful to flag it up for some discussion amongst the team to come to a clear resolution over expected behaviour. (Maybe it already has been discussed...?)

An example project for "touching mouse-pointer" from when I first met it (and thought it was a bug): https://scratch.mit.edu/projects/20212721/

The immediate intuition for this block is that it's asking the question "is the mouse-pointer touching the sprite?", to which we would most likely want to answer false for a hidden sprite. However, the block is potentially asking the question "am I being touched by the mouse-pointer?", and the answer to that question really depends on how the sprite sees _itself_ - does it consider itself to exist in a space that can contain the mouse-pointer, even when hidden?

It appears that the answer to the above question is currently  "yes", since "touching mouse-pointer" can be true for a hidden sprite, as can "touching edge" (though that doesn't feel so unintuitive as the mouse-pointer case).

However, note that the "touching sprite" sensor block _doesn't_ behave in this 'non-symmetric' way - a hidden sprite will not consider itself to be touching a non-hidden sprite that's overlapping its space, just as the non-hidden sprite clearly cannot 'see' the hidden sprite.

This behaviour seems inconsistent, hence the reason for raising this issue...

**Comment by 2jour** [comment]
Thanks @TheLogFather  :)

**Comment by cslaviero** [comment]
May I add my 2 cents to the discussion? When I tested the Improved Drag and Drop project ( https://scratch.mit.edu/projects/21512101/ ) @TheLogFather mentions on the editor and after dragging the dragon (pun intended?) and releasing it, nothing happened. Only after I clicked it, it fell to the ground. On the project page the dragon falls right after I release it. Is this inconsistent behavior intended to be like this? Although this is unrelated to the "hidden sprite" issue, I believe it is related to the consistency of a script

**Comment by TheLogFather** [comment]
Also, a hidden sprite can detect when it is touching colours - including colours of other sprites (visible ones) that it cannot currently detect via its "touching sprite" sensor.

Here's a project I've made that helps to demonstrate all of this:
https://scratch.mit.edu/projects/56442484/

**Comment by TheLogFather** [comment]
@cslaviero:
While in the editor, sprites are always draggable. That means the dragging is being done by Scratch itself, not the script, and that interferes with the scripted drag, unfortunately.
It's one of the things that can be a tad annoying when trying to test things in the editor...

The simplest way to make a sprite draggable in the player is to check that option for that sprite. That way you get the same behaviour in the editor and player.
Unfortunately, that also brings in a few possibly unwanted extra 'features' - for example, such a drag will bring the sprite in front, any touching tests are not updated during the drag (and only get updated once dropped), and the x,y positions are not updated during the drag (only once dropped).
The above mean that the best way to make a sprite draggable in the player (you can't stop it in the editor) is to script the drag yourself - and then the drag in editor interferes, unfortunately... :(

**Comment by cslaviero** [comment]
@TheLogFather: 

i got your point, but I was actually concerned about the editor not having the same behavior as the player on the project page since, for instance in a offline editor, I would not like to have to upload the game just to check if a desired behavior works. In this case a "play like in project page" would be more desirable than the "play like in editor" option. I understand this is more like a feature-request than a bug report, but I guess it is some sort of problem that can bug you a lot when programming something that uses dragging.

**Comment by TheLogFather** [comment]
Oh, right, I see. A check-box to disable dragging in editor could be a potential feature (probably global, for all sprites, and always clearly visible, so it wouldn't cause confusion if accidentally switched on for a single sprite?)

OTH, it is actually quite possible to try out a project effectively under 'player conditions' rather than 'editor conditions'  without uploading it... just click the fullscreen button. :)
(OK, there are a couple of potential subtle differences that can arise between behaviour in fullscreen vs normal size player - but they're pretty rare.)
