### ISSUE TITLE
New Block request: When CONDITION occurs

### ISSUE THREAD

**Issue by shacharoz** [LLK/scratch-flash#710]
hi guys,
this is a very useful cube and very simple to build. but i think it should be in the general blocks and not in my extension.

its a simple Hat Block that gets a Condition as a variable. whenever that condition is met, an event is dispatched.

**Comment by as-com** [comment]
Already implemented a while ago and removed: http://wiki.scratch.mit.edu/wiki/List_of_Obsolete_Blocks#When_.28.29_Is_True

**Comment by shacharoz** [comment]
thanks. but why is this workaround better? (p.s. in the online version the "Forever (CONDITION)" block does not exist, so you have to do When flag-> forever -> if (CONDITION).

anyway, the developer should make sure the conditions doesnt cause endless looping. doesnt he?

i dont mind writing this code. i just think it would be easier and more readable.

**Comment by chooper100** [comment]
It's because in the editor if you just put something that always evaluates to true, you could create unstoppable scripts, which defeats the purpose of the stop button. (And yes, I know there are other ways make unstoppable scripts that work)
