### ISSUE TITLE
Pick random ((-1)*10) to (10) hangs

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#714]
On Scratch.ly, if you make a script like this, it will hang when you click on it 

![random](https://cloud.githubusercontent.com/assets/3766964/7134622/8f11561a-e26c-11e4-9f67-19cdf37f8a6c.PNG)

**Comment by 2jour** [comment]
@sclements does staging have latest swf?

**Comment by 2jour** [comment]
Fixed :)
