### ISSUE TITLE
[Tips Window] The "getting started" panel is initially showing help in english regardless of language settings

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#716]
The "getting started" panel to the right shows text in english, even if the user settings are set to something else. To have it translated to swedish, I have to switch the language setting to something else and then back to swedish.

I do not really know in which repository the code for this help panel is so I do not know where to put this issue.

**Comment by as-com** [comment]
The code is located at https://github.com/LLK/scratchr2/. It's a private repo.

**Comment by 2jour** [comment]
Can repro .. Thank you @AndersBillLinden for bringing this to our attention

**Comment by AndersBillLinden** [comment]
Ah, thats why I did not find the code. Searching and searching without success.

**Comment by AndersBillLinden** [comment]
Is this fixed?

**Comment by 2jour** [comment]
@AndersBillLinden it should be fixed in our next release

**Comment by AndersBillLinden** [comment]
:+1:
