### ISSUE TITLE
Frozen Image on Stage

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#720]
Browser: Safari
OS: mac osx 10.10
Reporter: SST st19_galla

1 Run this game https://scratch.mit.edu/projects/57373628/ for a few seconds
2. Remove sprite
3. Remove backdrop1
4. add under when green flag clicked, a clear graphic effects block

You will notice that the stage remains the same.. even if you add multiple backdrops .. the only way to clear is if you refresh

**Comment by AndersBillLinden** [comment]
"Sorry this project is not shared"

**Comment by 2jour** [comment]
@2jour will check to see if still an issue
