### ISSUE TITLE
Editor Costume Editor Buttons Squished 

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#721]
More pronounced in Offline editor because smaller window
Offline mac os 10.10 
v435

Not present in v434

![squished](https://cloud.githubusercontent.com/assets/6530036/7183869/ec1b847c-e427-11e4-8f80-41ee67f6f3bd.png)

**Comment by ntlrsk** [comment]
@2jour This happens online too, yes?

![image](https://cloud.githubusercontent.com/assets/4721032/7260663/a95b96ac-e839-11e4-86ff-5d2938184c2c.png)

**Comment by 2jour** [comment]
sigh :)..  .. i guess for small screens you will notice too good catch will log in flash
