### ISSUE TITLE
after deleting costume, jumps to end of costume list

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#724]
Disorienting when deleting first costume in a list of costumes, then the costume selector jumps to the bottom.

To repro:
1) Pick sprite with multiple costumes, such as 1080
2) Click Costumes tab
3) Click X to delete first costume
4) Notice: It jumps so the last costume is now selected.

**Comment by ntlrsk** [comment]
Is this due to this earlier change? 
https://github.com/LLK/scratch-flash/issues/569

**Comment by sclements** [comment]
It looks like the change to #569 only affected sounds.

**Comment by 2jour** [comment]
@ntlrsk I can reproduce :). Great test case :)

**Comment by 2jour** [comment]
I am marking prio-low @ntlrsk if you disagree let me know :)
