### ISSUE TITLE
Duplicating threads by adding blocks

### ISSUE THREAD

**Issue by djdolphin** [LLK/scratch-flash#726]
When you attach a block to the top of a script that's already running, the thread for the original script isn't stopped. If you run the new script, a new thread is created, but the original still isn't stopped. You end up having multiple copies of the same script running, and blocks that look like this:
![screen shot 2015-04-17 at 9 55 45 pm](https://cloud.githubusercontent.com/assets/5834370/7213446/c474ba4e-e54c-11e4-8ac5-d9f2e3a44d04.png)
[I have a video here.](https://e50e8a3cc18b78b96ec6d26e1c13e1c49b4298a4.googledrive.com/host/0Bwg2KFU5SrIoOVF5QUQtZWpUQnc/Doo%20Doo%20Doo.ogg)

**Comment by 2jour** [comment]
I can reproduce this issue .. @cwillisf for the next iteration perhaps discuss if this is something that requires some design
