### ISSUE TITLE
C blocks try to snap to hidden blocks

### ISSUE THREAD

**Issue by djdolphin** [LLK/scratch-flash#727]
When you're dragging a C block, it tries to snap to blocks even if they're obscured by the palette:
![screen shot 2015-04-17 at 10 17 34 pm](https://cloud.githubusercontent.com/assets/5834370/7213520/cba7a1ca-e54f-11e4-9d32-fb01e7188aeb.png)
The block is just deleted if you drop it. [I have a video here.](https://e50e8a3cc18b78b96ec6d26e1c13e1c49b4298a4.googledrive.com/host/0Bwg2KFU5SrIoOVF5QUQtZWpUQnc/C%20Block%20Glitch.ogg)

**Comment by cwillisf** [comment]
Fixed by #732
