### ISSUE TITLE
Watchers are messed up when hidden in freshly-opened projects

### ISSUE THREAD

**Issue by djdolphin** [LLK/scratch-flash#728]
When I first open a project and try to hide a watcher, this happens:
![screen shot 2015-04-17 at 10 23 50 pm](https://cloud.githubusercontent.com/assets/5834370/7213553/81fa4932-e550-11e4-8001-7affd69214d6.png)
I use OS X 10.10.1, Firefox 39, and Flash 17. [I have a video here.](https://e50e8a3cc18b78b96ec6d26e1c13e1c49b4298a4.googledrive.com/host/0Bwg2KFU5SrIoOVF5QUQtZWpUQnc/Watcher%20Glitch.ogg)

**Comment by 2jour** [comment]
@djdolphin I don't see this issue for editor v435.1 .. Do you still see this issue?

**Comment by djdolphin** [comment]
Yes, it's still happening.

**Comment by djdolphin** [comment]
I found a new forum thread about this bug: https://scratch.mit.edu/discuss/topic/122568/
