### ISSUE TITLE
Colour-picked white no longer draws circle at "pen down"

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#730]
Having 0xFFFFFFFF in the "set pen color to" block doesn't work when just drawing the circle from "pen down" (i.e. then "pen up" without moving the pen).

Anything else, including 0xFFFFFF or even 0xFEFFFFFF, works fine.

If you try to pick white using the eye-dropper, then it doesn't work - I'd assume that's because it's actually putting the value 0xFFFFFFFF in there.

Example project: https://scratch.mit.edu/projects/57657390/

**Comment by AndersBillLinden** [comment]
Maybe this change will not be accepted but the alpha part will instead be cut away.

**Comment by 2jour** [comment]
@sclements does merge #736 fix this issue?

**Comment by sclements** [comment]
Yes.
