### ISSUE TITLE
Auto updater progressbar is wider than parent

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#731]
When I start the offline editor and there is a new version, a download starts.

However, the progressbar goes outside the parent.

![image](https://cloud.githubusercontent.com/assets/1017466/7215279/3dd6b67a-e5d0-11e4-9ed3-65fc22d3825f.png)

**Comment by 2jour** [comment]
able to repro thank you :)

**Comment by AndersBillLinden** [comment]
:+1:
