### ISSUE TITLE
Sub stack 2 (else block) is not updated when dragging an E-block (if-else) getting an insertion in sub stack 1 preview

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#733]
We start with

![1](https://cloud.githubusercontent.com/assets/1017466/7219465/84ebee6e-e6a1-11e4-9fc4-719ef68a7d44.png)

...and now when we drag the left block to the right we get...

![2](https://cloud.githubusercontent.com/assets/1017466/7219466/8cb84b56-e6a1-11e4-8882-f1425c1b9e43.png)

As we see, the "next custome" block is in the wrong position.

**Comment by 2jour** [comment]
@AndersBillLinden Thank you for bringing this to our attention

I definitely see this behaviour. However I do see that the next costume block snaps to position after the drag is complete . Is this what you observe?

editor: v435.2
mac osx 10.10.2 , Firefox 37

**Comment by AndersBillLinden** [comment]
Yes, this only occurs during drag, not afterwards.
