### ISSUE TITLE
Chrome has disabled weDo/PicoBoard (npapi)

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#737]
The recent Chrome update has killed off the default npapi support, hence WeDo/picoboard no longer work in the online version (windows 7)

You can workaround for now using this setting, but this flag won't be there forever:...
chrome://flags/#enable-npapi

**Comment by sclements** [comment]
We're currently finalizing a workaround strategy and getting pretty close.

**Comment by cpseager** [comment]
@cwillisf 
We do already have a Chrome app (http protocol) that we developed so that we could use WeDo with Scratch on Chromebooks (and Windows/Linux/Mac). Is that of interest to you?

**Comment by sclements** [comment]
It could be helpful to see how you did it, yes. Thanks for the offer @cpseager.

**Comment by cwillisf** [comment]
Indeed. The approach I'm taking right now is based on Chrome's [Native Messaging](https://developer.chrome.com/extensions/nativeMessaging) system, which means we get to share code with our current browser plugin, but I recognize that this implies certain tradeoffs. I'd definitely appreciate seeing your approach.

I'm curious: you mentioned that you're using HTTP. Have you tried [message passing](https://developer.chrome.com/extensions/messaging)? I'm not sure whether Chrome allows passing messages between a web page an a packaged app; if not then perhaps it would need an extension as a go-between. At that point, IMO, the added complexity for the user outweighs the benefits of avoiding HTTP.

**Comment by cpseager** [comment]
Http was the link to Scratch itself using the normal http extension method, then direct USB to wedo within the app itself (Chrome has a hid usb api which seems to work fine). 
 
I'm travelling for a couple of days but will sort a repo for you when back.

**Comment by cpseager** [comment]
@cwillisf We've used Native Messaging in the past to call our console microcontroller compilers from Chrome and it does work, but if you wanted to reuse the same DLL I suspect you will need a new 'proxy.exe' to convert the stdout/in strings into calls to your DLL, something like:

[Scratch/js] > Native Message > [proxy.exe] > [DLL] > USB > [WeDo]

The test app we developed takes a different approach as

[Scratch/js] > Http > [Chrome App] > USB  > [WeDo]

The main advantage of this over the first method is you get Unix and, in particular, Chromebooks, instantly working as well. We used http as that is what Scratch already supported, however I don't see why you couldn't substitute 'http' with 'message parsing' within both Scratch and the Chrome App. That would probably be better, as it would help prevent any firewall type issues.

**Comment by cpseager** [comment]
@cwillisf @sclements I've added you to the Chrome helper app repo on my github account. It demonstrates a lego wedo and a vernier go!temp .

**Comment by sclements** [comment]
Thanks!!!

**Comment by 2jour** [comment]
done :)
