### ISSUE TITLE
Please add the gd locale

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#741]
Hi all,

Since my language wasn't added with the last update, I am wondering if you need to do anything manually?

http://translate.scratch.mit.edu/gd/

Thanks!

**Comment by 2jour** [comment]
Hi @gunchleoc . I created a subissue

So I will add the locale to the list . What would be the appropriate term for Scottish Gaelic for our language drop down list?

**Comment by gunchleoc** [comment]
Gàidhlig

Thank you :)

**Comment by ntlrsk** [comment]
I see it on the menu as this:
![image](https://cloud.githubusercontent.com/assets/4721032/7349485/78d5685e-ecc7-11e4-98d5-62dc5b1c3cfb.png)

**Comment by ntlrsk** [comment]
Sorry realized the one I was looking at was Irish Gaelic.

**Comment by gunchleoc** [comment]
A common mistake - we often even get the plural from rules for Irish assigned, which are wrong ;)

**Comment by 2jour** [comment]
closed via https://github.com/llk/scratchr2/issues/2417
