### ISSUE TITLE
Long blocks cause a shift left whilst dragging

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#742]
If you select a long block, such as the WeDo 'set motor direction' and drag it **slowly** to the right into the script area, all of the other blocks suddenly incorrectly shift left (see image). As there is no horizontal scroll bar you can't shift them back again without clicking onto a different palette and then back again..

![scratch_shift](https://cloud.githubusercontent.com/assets/7423187/7393496/19f49772-ee86-11e4-8baa-e14a27e0f682.JPG)

**Comment by Scimonster** [comment]
I've noticed this bug too. Confirmed.

On Wednesday, April 29, 2015, scraxe <notifications@github.com> wrote:

> If you select a long block, such as the WeDo 'set motor direction' and
> drag it *slowly* to the right into the script area, all of the other
> blocks suddenly incorrectly shift left (see image). As there is no
> horizontal scroll bar you can't shift them back again without clicking onto
> a different palette and then back again..
>
> [image: scratch_shift]
> <https://cloud.githubusercontent.com/assets/7423187/7393496/19f49772-ee86-11e4-8baa-e14a27e0f682.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LLK/scratch-flash/issues/742>.
>


-- 
Sent from Gmail Mobile

**Comment by AndersBillLinden** [comment]
I notice this bug frequently. My students as well.

**Comment by TheLogFather** [comment]
I'll just drop a note in here to say that allowing this pane to scroll is the currently the only way to see which custom block is which, if you have several long ones that start with the same string (apart from actually grabbing each of them, one by one, until you find the one you want).

Also, clicking on another palette is not the only way to 'unscroll' the pane – there are two other ways...

The simplest is to hold down the shift key and use the scroll-wheel. Unfortunately, this doesn't work on all browsers. The alternative is to hold a block over near the left edge of the pane, thus causing it to scroll back in the opposite direction.

Neither are particularly great, of course!

What would be preferable, I think, would be to allow the divider to be dragged left/right, so you can change the width to whatever suits you at the time. We can drop scrolling at that point...

**Comment by cwillisf** [comment]
Resolved by #744
