### ISSUE TITLE
Forum posts cannot be edited or deleted

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#745]
Sorry, I have no idea which repository the scratch forum is in. Still, I have to report this "bug" because I find it annoying that forum posts cannot be edited or deleted. Is there any specific reason for this?

**Comment by 2jour** [comment]
@kaschm assigning to you

**Comment by thisandagain** [comment]
Users can now edit forum posts.

**Comment by AndersBillLinden** [comment]
:+1:
