### ISSUE TITLE
[Translation][Website] Tips for reporting list item needs updating

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#748]
In this string, to match Scratch 2.0, replace "any" with "random":

      You can specify which item to report by choosing from the pull-down menu or typing 
      in a number. Choosing "any" reports a random item in the list.

templates/info/help/studio/tips/blocks/item-of-list.html:11

And there is a typo in:

    <p>
    The item block reports the value of the item at the specified place on the list.
    <br><img src="%(STATIC_URL)s/images/help/item-of-list-menu.png" /><br/>
    You can fit an item block into other bocks, for example: say, switch to costume, play
    soud, or broadcast.
    </p>

 templates/info/help/studio/tips/blocks/item-of-list.html:20

soud => sound

Translation file: django.po

**Comment by 2jour** [comment]
Thank you :)

**Comment by gunchleoc** [comment]
I have found another one:

    You can specify which item to replace by choosing from the pull-down menu or 
      typing in a number. Choosing "any" replaces a random item in the list.  The length 
      of the list does not change.

  templates/info/help/studio/tips/blocks/replace-list.html:11

any => random

**Comment by 2jour** [comment]
Moved to LLK/scratchr2#2684
