### ISSUE TITLE
[Translation][Website] Typo in length of list tip

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#749]
<p>
    This block reports how any items are currently in a list.
    <br><img src="%(STATIC_URL)s/images/help/length-mylist.png" /><br/>
    </p>
    
    <p>
    The number is the same as the length shown at the bottom of the 
    list monitor.
    <br><img src="%(STATIC_URL)s/images/help/length-mylist2.png" /><br/>
    </p>

templates/info/help/studio/tips/blocks/length-of-list.html:14

how any => how many

Translation file: django.po

**Comment by thisandagain** [comment]
@ntlrsk Sorry for assigning all of these to you! Feel free to reassign.

**Comment by ntlrsk** [comment]
glad to know about these - fixed and going out soon.

**Comment by gunchleoc** [comment]
Thanks for looking into my bugs :)
