### ISSUE TITLE
Report 2 bugs & 1 enhancemet.

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#757]
bug 1: Translation.
I am a Chinese scratcher. 
When Scratch updated to v435, Scratch has lots of wrong translation:
![image](https://cloud.githubusercontent.com/assets/8316018/7557624/a9c38530-f7c7-11e4-9326-19d6db19d9eb.png)
![image](https://cloud.githubusercontent.com/assets/8316018/7557648/ffc59126-f7c7-11e4-92de-26de243ae7f8.png)
But before v435, this blocks are right.

bug 2: Import sprite by gif
My gif file are all transparent, but when I import it into a sprite, the first costume is not transparent.
![image](https://cloud.githubusercontent.com/assets/8316018/7557664/38ce67fe-f7c8-11e4-855d-95533ffc14a0.png)
![image](https://cloud.githubusercontent.com/assets/8316018/7557670/42a2b73a-f7c8-11e4-9ecf-cd433917ec6a.png)

enhancemet 1: block font size is small
Almost all Chinese teachers said the size of block is too small !!
Not like English, in Chinese editor interface, it's very hardly recognized.
We can make a comparison:
![image](https://cloud.githubusercontent.com/assets/8316018/7557690/a7ac2436-f7c8-11e4-9da3-41f7aad42f9b.png)![image](https://cloud.githubusercontent.com/assets/8316018/7557715/f0211898-f7c8-11e4-88b6-a499a24ae696.png)
![image](https://cloud.githubusercontent.com/assets/8316018/7557999/ee6bb4b8-f7cd-11e4-9543-56a4519ab552.png)![image](https://cloud.githubusercontent.com/assets/8316018/7558007/fa4d0a8e-f7cd-11e4-86d3-67b915242c29.png)

However, not all people know that press 'shift' & click menu:
![image](https://cloud.githubusercontent.com/assets/8316018/7557712/db4967a4-f7c8-11e4-996f-671508dfcb32.png)

So please enlarge Chinese font size to comfortable.

**Comment by 2jour** [comment]
Hi @lize777 

* Bug 1, I believe is fixed. @ntlrsk,@kasshm let me know if I am wrong.
* I logged #874 for bug 2 and #875 for bug 3 and you can track these issues there.

I am going to close this issue . If you think this needs to be reopened, let me know.
