### ISSUE TITLE
I suggest add "Touching Top/Left/Right/Bottom edge" on drop down menu.

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#758]
![image](https://cloud.githubusercontent.com/assets/8316018/7560502/675e1f5a-f7f6-11e4-9054-d8f9ed59f2a0.png)

**Comment by Tymewalk** [comment]
Additionally you should include "touching any edge".

**Comment by lize777** [comment]
@Tymewalk What's difference between your "touching any edge" and 'touching's edge?

**Comment by Tymewalk** [comment]
@lize777 I thought the Touching Top/Left/Right/Bottom edge would replace Touching Edge. Plus, if they don't, Touching Any Edge is clearer.

**Comment by lize777** [comment]
@Tymewalk I agree with you. 
@ntlrsk When will this improvement be done?

**Comment by ntlrsk** [comment]
I suggest:   <touching [ edge/  left edge / right edge / top edge / bottom edge ]
I do not know when this could be added, but it would be very useful in many projects, especially for beginners!

**Comment by chooper100** [comment]
I feel the alternative is pretty easy.
For example, with the top edge:
`if <<touching [edge]> and <(y position) > (160)>>'

I feel if we add too many blocks for easy workarounds we will start taking away the challenge of having to think how to find workarounds. Teaching children how to think logically is one of the goals of Scratch and therefore I think it would be bad to take that away.
