### ISSUE TITLE
Feature Request: Please Support Real Time Data Streaming via Websockets in the Offline Version

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratch-flash#765]
Please provide some mechanism to expose a web socket interface to the Scratch offline editor. I teach in rural schools where broadband is not dependable so I have to rely on the offline editor.
However, many of my projects require data IO to a Scratch extension via websockets. I can only run these lessons when dependable broadband is available, therefore, this is a hindrance. This also applies to conference and coding club scenarios. The offline editor is an important asset. Please put some time into enabling real time data IO support for extensions for offline scenarios.

**Comment by thisandagain** [comment]
Hi @CreativeComputerLab our new device manager that is being used for the LEGO WeDo 2.0 should help us enable this in the future. Stay tuned!
