### ISSUE TITLE
Can't import some WAV files

### ISSUE THREAD

**Issue by sclements** [LLK/scratch-flash#767]
Format reference: http://www-mmsp.ece.mcgill.ca/documents/audioformats/wave/wave.html
Example file: http://www.mediafire.com/download/gqimq5471fp5e4e/FNAF+3+Trailer+song.wav

I debugged this a little and found that the file is using the "extended" format chunk data to specify that it's using the IEEE floating point PCM encoding. We don't have code to support that and a cursory search revealed that that most WAV decoders in Actionscript do not support that format either. If we can find an open source one, or do it ourselves, then we can fix this.

Here's my investigation branch: https://github.com/LLK/scratch-flash/tree/IEEE_WAV_decoding

**Comment by sclements** [comment]
I got a little further with my branch but hit a bug in the Flash player:
https://bugbase.adobe.com/index.cfm?event=bug&id=3104536

That method would be perfect for this but I'm not sure if there is a workaround for the bug.

**Comment by 2jour** [comment]
64-bit floating point IEEE does not work. Sound turns into a hissing sound after its uploaded.

Also mono does not seem to work for 32 bit floating point IEEE 8000z

1. download wav from  http://mauvecloud.net/sounds/index.html 
2. Upload sound in the editor

**Comment by 2jour** [comment]
So just tested for 8000 Hz and here is what i found 

1. 64 bit floating point IEEE 8000Hz works mono and stereo :+1: 
2. 32 bit floating point IEEE 8000z works mono and stereo :+1: 
3. PCM 32 bit does not work (expected?)
4. PCM 8 bit does not work (expected?)
5. u-Law compression (really 'mu'-Law) does not work (expected?)
6. a-law compression does not work (expected?)
7. IMA ADPCM mono works but stereo does not (expected?)
8. MS ADPCM does not work MONO or Stereo (expected?)
9. MPEG Layer 3 works for both Mono and Stereo :+1:

**Comment by sclements** [comment]
I use IMA ADPCM mono internally so the support makes sense.

**Comment by 2jour** [comment]
64-bit floating point IEEE does not import on windows 7 chrome 42

**Comment by 2jour** [comment]
LGTM

**Comment by ntlrsk** [comment]
I just tried uploading two WAV files that come in but show 0 MB when uploaded to Scratch online. Is this the same or a different issue?

**Comment by ntlrsk** [comment]
Note: I saved as MP3 and that worked.

**Comment by 2jour** [comment]
@ntlrsk is behaviour on scratch.ly or production..? Some .wav files do not upload .. it depends on the format. If you provide me the .wav file i can take a look.
