### ISSUE TITLE
[3D] Stage3D stamp of semi-translucent costume is quite unlike the costume itself...

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#769]
See https://scratch.mit.edu/projects/63384160/ for a simple demo project.

I'm pretty sure it didn't used to be as bad as this, because another project of mine stamps costumes like this (https://scratch.mit.edu/projects/25638006/) and used to work as expected - but no longer does while using Stage3D player. (Toggling with ctrl-M/cmd-shift-M shows the difference quite clearly.)
When I've got a bit of time later on, I'll check through some older versions and see if I can pin down when the behaviour changed.

**Comment by sclements** [comment]
Whoa! That's terrible. I don't think this used to be like this in the past. We'll take a look when we get a chance.

**Comment by sclements** [comment]
By the way, you don't have to share those bug demonstration projects if you don't want to.

**Comment by TheLogFather** [comment]
People seem to enjoy seeing weird things happen sometimes... ;D
And it's nice to be able to add a note at some point, too, saying 'FIXED!'

I've noticed before that Stage3D can be rather dodgy when it comes to stamping - it's one reason (of several) that I usually avoid triggering it in projects.

For example, try toggling on Stage3D for my 3D Terrain and Faroes Eclipse projects:
https://scratch.mit.edu/projects/25217786/
https://scratch.mit.edu/projects/25071751/
For some reason, Stage3D seems to decide to not bother stamping the background at all... :/

**Comment by griffpatch** [comment]
I've noticed that if you have a full screen vector background that it
appears offset to the right by like 100 pixels, but if you make it slightly
bigger that full screen them it works fine ;)

**Comment by sclements** [comment]
The fix will be in this area: https://github.com/LLK/scratch-flash/blob/master/src/render3d/DisplayObjectContainerIn3D.as#L1145

**Comment by cwillisf** [comment]
Fixed by #817

**Comment by TheLogFather** [comment]
Looks good to me :) -will update project notes in a bit, but got a few other v438 glitches to have a go at tracking down...
