### ISSUE TITLE
Allow non-breaking hyphen in strings

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#770]
My language (Scottish Gaelic) prefixes single letters to words, e.g. in "na h-uinneagan", "an t-eilean". When entering text for a speech bubble, it would be great if we could copy/paste non-breaking hyphens (U+2011) into scratchblock strings to avoid line breaking.

**Comment by akerbeltz** [comment]
Or, perhaps even better, if Scratch has locale-specific formatting options for text, to make this the default behaviour of the relevant hyphen groups (we could supply a list).
