### ISSUE TITLE
Add separator between 'delete' and 'duplicate' (or move 'delete' elsewhere)

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#772]
A kinda minor, point, but I thought it worth mentioning...

I find that I very rarely want to use the 'delete' item, but I do regularly want to 'duplicate' - and I occasionally hit 'delete' instead.

Since an undeleted script snippet reappears in far top-left, and it may be a long way to drag it back in place, and it may not be straightforward in a complex script to see how it slots back in, having some kind of separator would be helpful to reduce such 'mishits'. (Perhaps even moving 'delete' elsewhere in the menu?)

I'll also note that, since there's only one level of 'undelete', if you make a second slip while trying to undo your accidental delete  (e.g. catch the mouse button while hurrying across to hit 'undelete', and so drag out another block to the blocks pane), then you've lost it...

Reducing such potential mishaps would be helpful...

Note: https://scratch.mit.edu/discuss/post/1046760/

**Comment by MegaApuTurkUltra** [comment]
This happens to me as well, and it's quite annoying. The other annoying thing is that Edit > Undelete doesn't put the script back in the correct position - when I'm working on large projects it's a pain to drag it far down.

**Comment by griffpatch** [comment]
I think there should be a confirmation of delete myself...

**Comment by TheLogFather** [comment]
For further reference...
https://scratch.mit.edu/discuss/topic/86934/
https://scratch.mit.edu/discuss/topic/837/
https://scratch.mit.edu/discuss/topic/19491/

**Comment by MegaApuTurkUltra** [comment]
I don't think there should be a confirmation. If I want to delete a single
block for example, a confirmation would be ridiculous. What scratch needs
is more separation between the delete and duplicate items, and a better
undo function, as stated above.

Other than that, maybe there could be a threshold for number of blocks
about to be deleted after which there would be a confirmation dialog, if
one is really needed.

**Comment by MrFlash67** [comment]
I'd like it if the confirm box pops up if the group of blocks is greater than five or something.
But, still a good idea as-is.

**Comment by griffpatch** [comment]
The only time I would be annoyed by delete popping up a confirmation is
when deleting single block or small at of blocks starting with the hat...
When ever deleting a block with a parent I'd be worried...? I always drag
them off or replace using drag and then delete the thing that I replaced.

**Comment by TheLogFather** [comment]
The ideal solution would be multiple levels of undelete, and better placing of undeleted script - and so no need for a confirmation.

Since that's going to require considerable work, I think a temporary 'band aid' would be useful...

The essential problem, as outlined above, is that 'delete' can sometimes be rather painful to recover from, and even occasionally destructive (loss of chunks of script, requiring total rebuild of the missing script, if you accidentally delete something else before recovery).

Since it's possible to hit 'delete' by accident fairly easily, that increases the severity of above.

Reducing such accidents by separating 'delete' from 'duplicate' (or even moving it) would help mitigate it (though it's not a total solution).

Adding a confirmation would mitigate it, even pretty much solve the problem, though at the expense of some extra clicks - and note that annoyance would always be there, even when there's no reason for it (since there is an undelete button, which will usually allow recovery from an accident, even if a bit tedious sometimes).

An alternative partial solution, which would reduce the potential pain of recovery in most cases (assuming you don't make a further deletion accidentally), would be to make undelete return the script to where it came from, perhaps even putting it back into its parent stack - but I think that would be too much work for a stop-gap fix like this (and much harder if the stack has changed), so at least returning it to the approximate position in the edit pane.


All in all, my preference, for now, would be to simply separate 'delete'. The advantages: it's a trivial change (a couple of lines of code); it won't need reverting once multiple level undelete is implemented; and it will significantly reduce (though not entirely eliminate) the likelihood of accidents when aiming for the oft-used 'duplicate'.

**Comment by TheLogFather** [comment]
Since I'm currently messing around a bit in the Scratch code, it was really easy to try out this separator - just one extra line (in more ways than one!)

And that's when it became obvious...

The separators in these menus don't actually *do* anything other than visually! They're a bit too 'anaemic' to make a difference physically to the separation.

That means adding a separator likely makes hardly any difference to this issue. :(

Sad to say, but I think having a carefully 'controlled' temporary confirmation is the way to go, until such point as multiple undelete is implemented.

**Comment by griffpatch** [comment]
I think the confirmation is a good idea ;) - However, it would be painful
if you were not able to then hit enter to accept the confirmation
dialog...? Do deleting would just be a matter of right click deleting and
then hitting enter... this can be very fast with both hands for large
amounts of deletions unlike having to move the mouse around a lot! I often
end up with heaps of small blocks left on top of each other to the side of
a script when dragging variable names over others to replace them...

You know what...  Might it be a good idea to add a command that allows you
to delete all orphaned expressions? That would make tidying up after code
edits real easy! ;)

**Comment by Paddle2See** [comment]
I would like to bump this suggestion and point out that it is still a desired feature showing up in our Suggestions section of the forums

https://scratch.mit.edu/discuss/topic/270214/

**Comment by rschamp** [comment]
Currently in 3.0 there are confirmation dialogs for all deletions.

**Comment by chooper100** [comment]
> Currently in 3.0 there are confirmation dialogs for all deletions.
I'm able to currently delete single blocks along with with complete scripts without any confirmation blocks?

**Comment by rschamp** [comment]
Oh whoops, sorry I misunderstood this issue when I replied. No confirmation for deleting blocks.  However we will have a full undo stack in the blocks workspace, so deleting is not as dangerous.
