### ISSUE TITLE
Paint Editor - Support importing 'sprite2' files into the Paint Editor

### ISSUE THREAD

**Issue by zFurious** [LLK/scratch-flash#776]
I was trying to import a .svg from a different program (inkscape) into scratch, but it isn't working. zlivvy (https://scratch.mit.edu/users/zlivvy/) said "Scratch doesn't allow SVGs. Only PNGs." But I almost always import an SVG into scratch when I make a project! Is this a new addition, or a glitch?

Please help!
~ @zFurious (https://scratch.mit.edu/users/Furious-/)

**Comment by Paddle2See** [comment]
I'm having trouble with the import command as well - I'm finding that the only way it works for me is when I pull an SVG into the bitmap editor.  SVG into the vector editor silently fails as does GIF into both the vector and bitmap editors.

**Comment by sclements** [comment]
I haven't had any trouble with this in my testing. What's happening for you?

**Comment by Paddle2See** [comment]
To reproduce the SVG import issue:

1. Create a new sprite from the media library - select the Apple
2. Find the apple costume and right-click and select "save to local file" to create an SVG file
3. Create a second vector sprite from the media library - I used the Bat
4. Edit the costume of the Bat and use the Import button to try and load the Apple SVG file
5. The Import button highlights for a while but no Apple appears.
6. Convert the Bat costume to bitmap and try the Import button again - it should work.

**Comment by thisandagain** [comment]
This is specific to importing `sprite2` files rather than SVGs (which I cannot repo).

**Comment by liam4** [comment]
*repro?

**Comment by thisandagain** [comment]
Whoops. Fixed.
