### ISSUE TITLE
Export List Bug in Chrome

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#777]
In IE you can right click a list reporter from the project player to get the context menu allowing for import and export. This is no longer working in the Chrome player (although it does when looking inside). This breaks projects that make use of this as a save/load mechanism.

**Comment by TheLogFather** [comment]
Huh? I've never seen that working in just the player - it certainly doesn't in Safari or Firefox on Mac - have to see inside to be able to right/shift-click to get list menu.

Does that mean you can actually hide a list from the player in IE? What about variables and sprites?
ISTR this was actually mentioned as a bug in the B&G forum at one point...

**Comment by zFurious** [comment]
:/ I'm having the issue with IE as well... I believe that the easiest way to export it without using "export" is to download the project as a zip and copy the lists into another file. I really need this to be fixed. :/
