### ISSUE TITLE
[Sound] Linux Importing WAV MPEG LAYER 3 Becomes Distorted

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#779]
Server: Production 436
OS: Ubuntu
Browser: FF
1. Import  MP308m.wav and MP308S.wav from https://www.dropbox.com/s/a70pszpi56fdy7p/music.zip?dl=0 into the editor

Result: Sound becomes distorted 
![mpeg-layer3](https://cloud.githubusercontent.com/assets/6530036/7842970/99069386-0474-11e5-8c73-21fef8aeec20.jpg)

Works on OS X 10.10.2 Chrome and Firefox

@sclements do you agree with prio?

**Comment by sclements** [comment]
Yeah, sounds good.
