### ISSUE TITLE
Really odd costume-switch slow-down after saving and reloading project

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#781]
I've noticed this oddity before, but the project below now shows it really well...

Go to the following project: https://scratch.mit.edu/projects/64857642/
Run the tests, and note the time for the non-empty costumes test - it's a lot slower than the other two (as you might expect, really).

Now do the following:
1) Make a remix of the project;
2) Without leaving the editor, run the tests again - I see the non-empty test run *way* quicker;
3) Now reload the project page (of your remixed project);
4) Run the tests again - I find the non-empty case is now much slower again.

I also find it even happens for the original project if I make some changes to it and save it - the non-empty case suddenly becomes really quick. That is, until I reload the project... :/

I get the same behaviour in both Firefox and Safari (on a MacBook).

**Comment by griffpatch** [comment]
I have had consistent cases where my project will always be really slow
playing and editing (as in dragging blocks is slow) until I go to another
costume and drag one of those scripts, then return to the first and it all
runs and plays fast again... I could exit the first sprite and is scripts
for ages and it would not get any faster until I go to the second sprite
and edit something... Very consistent work around.

**Comment by TheLogFather** [comment]
Just saw this drop in as I was checking the page again! :)

Yes, it looks like you can get the speed back by making some changes to the project. The speedup remains after the project is saved, too.

But as soon as you reload, then it's slow again. :/

**Comment by TheLogFather** [comment]
UPDATE to above...
It looks as though the slightest change brings back the speed - but *only* if the project is allowed to save.
If the project is running, so autosave is prevented, then it doesn't show the speed up until I manually save the project. (And then it's gone again on reloading.)

**Comment by 2jour** [comment]
Closing issue . #822 seems to fix issue
