### ISSUE TITLE
[Translation][Website] "Followers" forces English plural ending on all languages

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#783]
This string adds an "s" to the end of the translation of "Follower" to all languages, resulting in nonexistent words in the translations.

    Follower%(tPlural)s )

templates/galleries/base.html:103

The string should have the form:

    %(number)s Follower
    %(number)s Followers

And use ngettext to fetch the correct plural form.

**Comment by thisandagain** [comment]
@mewtaylor Is this still an issue?

**Comment by gunchleoc** [comment]
It is. For example, in my studio here:

https://scratch.mit.edu/studios/1083832/

with interface set to Scottish Gaelic (Gàidhlig), it says (0 Luchd-leantainns), The correct translation would be (0 Neach-leantainn), (1 Neach-leantainn), (3 Luchd-leantainn), ...
