### ISSUE TITLE
Bug with duplicating sprites with local lists

### ISSUE THREAD

**Issue by Znapi** [LLK/scratch-flash#784]
Duplicating a sprite with a “this sprite only” list causes all kinds of glitches to appear in the resulting sprite's list.
To replicate this, all you need to do is make a new sprite, and then make a list with “this sprite only” checked. Then you just duplicate the sprite.  
Just play around with the two lists and you will see problems pop up.
I only have found a couple problems:
- Both lists cannot be showing at the same time, the checkbox to show and hide them is glitchy
  The name of the list in the duplicated sprite sometimes says “sprite1:list” instead of “sprite2:list”
- I am suspecting that the contents of the second list are glitchy too, but simple tests showed that they have separate contents. However, in a more complicated situation where I am duplicating a sprite, the lists appear to not work.

**Comment by TheLogFather** [comment]
Could be related to https://github.com/LLK/scratch-flash/issues/591?

**Comment by 2jour** [comment]
osx : 10.10.2
Browser: ff 38


Thanks @Znapi for the test case

I definitely observed this 
```
Both lists cannot be showing at the same time, the checkbox to show and hide them is glitchy The name of the list in the duplicated sprite sometimes says “sprite1:list” instead of “sprite2:list”
```
