### ISSUE TITLE
[Translation][Website] Duplicate word in source string (close - closed)

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#786]
birth month and year - We use this to confirm ownership of the account if the owner loses the password and email, or writes to ask us to close the account closed.

templates/info/faq.html:89

The last word in this string should go (to close the account closed. -> to close the account.).

**Comment by ntlrsk** [comment]
Thanks for reporting this @gunchleoc  - fixed for upcoming release.
