### ISSUE TITLE
Inappropriate project names set in Editor are not rejected

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#787]
If you attempt to set a sexual-severe or vulgarity-severe project name on the project page, you get the warning message about inappropriate text and the name is not set.  However, if you set that same project name from within the editor, you do not get a warning message and the project name does get set.

This explains how the phone number spammers were setting the project names to phone numbers that had clearly been defined as inappropriate in Cleanspeak.

This problem exists in production and on Scratch.ly so it is not a bug introduced in this release.

**Comment by 2jour** [comment]
spoke to @Paddle2See non issue ..
