### ISSUE TITLE
[3D] Green flag sometimes doesn't work when video is on

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#788]
When I play with this Soccer Video sensing project:
    https://scratch.mit.edu/projects/63809044/#editor
often when I try to click the green flag a second time, it will fail to do anything. I then have to reload to get the project to replay.
Mac 10.9.5 production server (no errors apparent in Console) 
Can anyone reproduce?

**Comment by cpseager** [comment]
Same problem on windows, but....

...drag a loose 'turn video off' onto your script area and simply double click it by itself between green flag clicks...

**Comment by 2jour** [comment]
Thanks for the workaround @cpseager :)

This is very reproducible,

mac osx 10.10.2
Browser: FF 38, Safari

1. Goto  https://scratch.mit.edu/projects/66505732/ (simplified project)
2. click green flag and allow permissions for video to be turned on
3. Click stop
4. click green flag again and nothing happens

I think this may be influenced by 3d mode
