### ISSUE TITLE
Importing .sprite2 with local variable with existing global variable name

### ISSUE THREAD

**Issue by jorenl** [LLK/scratch-flash#807]
When you import a sprite with a local variable name that is already used as a local variable name, the 'Data' blocks pane shows 2 identical reporters, but
- both checkmarks (to show/hide the inspectors) don't function
- when you click them, they both report the value of the local variable
- when you drag _new_ reporters from the Data pane, they report the local value
- _new_ show/hide variable blocks affect the _global_ variable, regardless of which one you pick in the dropdown
- _new_ set/change variable blocks affect the _local_ variable, regardless of which one you pick in the dropdown
- _imported_ reporters return the value of the local variable
- _imported_ set/change blocks change the value of the local variable

This effectively creates a local "ghost" variable that you can't open an inspector for and is impossible to debug. This functionality is important for the community media library, which will (hopefully) significantly increase the usage of the sprite import functionality.

To reproduce, first create the .sprite2 file:
- create a new project
- open Sprite1, create a new variable 'for this sprite only', called 'my color'
- add block 'set [my color v] to [orange]' to sprite scripts and execute
- add block 'say (my color) for (2) secs' to sprite scripts
- right click sprite thumbnail, and export to file.

...then import it into a fresh project where that variable name already exists:
- create a new project
- create a new variable 'my color'. but don't check 'for this sprite only'
- add block 'set [my color v] to [blue]' to sprite or stage scripts and execute
- import the file from earlier and open the new sprite's Data blocks pane.

You can now:
- click the imported sprites' 'say (my color) for (2) secs' block. It will say 'orange'.
- click the imported 'set [my color v] to [orange]' block. The global 'my color' variable will still be 'blue'.
- click the checkmarks in the Data pane, they don't function.

Possible fixes (just thinking out loud here, feel free to critique/comment/suggest)
- when a sprite has a local variable whose name is already used as a global, prepend "my " (or translated) to the variable name. e.g., an existing global called "health", when you import a sprite that has a local "health" rename it and all its uses in the imported scripts by "my health" so the names become unique (messy)
- have a clear visual distinction between local and stage variables (Scratch 1.4 used to have different colors) instead of showing them all alphabetically, then allow them to have the same name. (I think this is better)
- ...

**Comment by TheLogFather** [comment]
It's quite easy to reproduce this kind of problem without importing any sprites.
Just create a local variable in a sprite, and then drag its watcher from the Data palette and drop it onto the Stage (left of the 'Sprites' pane). Then switch to the Stage and click the watcher in there.
On switching back to the sprite, you'll see both the local & global var in the Data palette...
