### ISSUE TITLE
[3D] clicking stop doesn't clear graphic effects on Stage

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#808]
Click "change color effect" on Stage.
Click stop sign. The graphic effect does not clear, but should (like it does for sprites). thanks!

**Comment by ntlrsk** [comment]
To clarify - try the block on the Stage scripts (not in a sprite). :)

**Comment by 2jour** [comment]
staging server project id 1000004724

Verified stop does not clear graphic effects

1. go to staging server project id 1000004724
2. Click play
3. Click Stop
4. Only cat is original colour . Stage is not
