### ISSUE TITLE
[Translation][Scratch Tips] Speech instead of thought bubble

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#809]
This string:

    To remove the speech bubble, use a blank block: <img src="%(STATIC_URL)s/images/help/think-blank.png" />.

templates/help/studio/tips/blocks/think.html:20

should be:

    To remove the thought bubble, use a blank block: <img src="%(STATIC_URL)s/images/help/think-blank.png" />.

**Comment by 2jour** [comment]
Moved to LLK/scratchr2#3142
