### ISSUE TITLE
A block's parameter index cache can become invalid when disconnected from definition

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#810]
This is something that's been troubling me for some time now, producing incorrect script behaviour on seemingly random rare occasions.
But I've just realised what's going on, and how to reproduce it... (and fix it!)

* Create a custom block with a single parameter - call it "p1"
* Connect a "set var to p1" block
* Drag out the 'caller' block for that custom block, and put 100 in the param slot

So, when you click that, "var" ends up set to 100, as expected.
Note that the "p1" block in that "set var to p1" has been pointed to the first parameter (index number zero) in its parameter index cache (setting b.parameterIndex in primGetParam of Interpreter.as).

Now, the important bits:
* *Disconnect* the "set var to p1" block from the definition
* Then, edit the custom block as follows:
 - change the parameter's name, from "p1" to "p0"
 - add a second parameter, and give it the original name "p1"

At this point, the 'orphaned' "set var to p1" block still has parameter index 0 for that p1 block, so...

* Reconnect it to the definition
* Put 200 and 300 in the caller slots for p0 & p1 respectively
* Click the caller to run it with those values

Expected: "var" gets set to 300, since p1 is now the second parameter.
Actual: "var" gets set to 200, since the p1 block in that 'set' still has parameter index 0 in its cache.

I think it's easy to fix, though... a single line added to blockDropped in ScratchRuntime.as during the function within the allBlocksDo will ensure that any time a stack is dropped, every block in that stack gets its parameter index cache cleared:

		stack.allBlocksDo(function(b:Block):void {
			var op:String = b.op;
			if (op == Specs.GET_PARAM) b.parameterIndex = -1;     <---- New fix
			if (('senseVideoMotion' == op) ||    ...etc...

Are there any other ways that the index cache could become invalid...?

**Comment by TheLogFather** [comment]
Decided to make a simple demo project for this: https://scratch.mit.edu/projects/69851944/
It shows how moving around a custom block parameter can give incorrect values.
The instructions to replicate the issue are *much* simpler than above...

**Comment by 2jour** [comment]
Thanks @TheLogFather :)

**Comment by 2jour** [comment]
able to repro .. thanks to the demo :)

**Comment by cwillisf** [comment]
Fixed by @TheLogFather with #949
