### ISSUE TITLE
Hacked "set/change/show/hide var" block causes exception when renaming any var

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#815]
Dunno if you want to bother fixing this since it's only a 'hacked' block issue, but I thought I'd point it out anyway (and it's a simple fix)...

The exception happens in ScratchRuntime.as when it's searching for references to the var name, and it comes across the offending 'set/change/show/hide' block, and assumes the first arg will have an argValue (rather than an expression that would normally get evaluated).

The line of exception in release v437 (since it's now changed in master since original post):
https://github.com/LLK/scratch-flash/blob/release/v437/src/scratch/ScratchRuntime.as#L834

The consequence is that renaming a variable doesn't change references in the scripts (and renaming appears to not even happen at first, since it doesn't do the palette update straight away).

**Comment by TheLogFather** [comment]
I put this (and the (_of_) exception, #831) into a project so you could more easily see what I mean:
https://scratch.mit.edu/projects/70022728/  (not bothered to share it)

**Comment by cwillisf** [comment]
Fixed by @TheLogFather with #949
