### ISSUE TITLE
[Translation][Scratch Tips] Turn it -> them off

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#816]
In this string:

    <img src="%(STATIC_URL)s/images/help/wedo-turn-on-ex1.png" />
    <p>Turn the lights on for 2 seconds when the space key is pressed, then turn it off.</p>

templates/help/studio/tips/ext/wedo-turn-off.html:11 templates/help/studio/tips/ext/wedo-turn-on.html:11

"turn it off" should be "turn them off".

**Comment by ntlrsk** [comment]
Here's to spring cleaning of old bugs!
