### ISSUE TITLE
how to build on linux

### ISSUE THREAD

**Issue by stormchaser3000** [LLK/scratch-flash#829]
i use linux and of course adobe air ws discountinued on linux for the most part. and well. when i want to compile the source code. i don't seem to be able to due to there not being a unix/linux makefile. can someone give me some instruction as to how to build scratch on a linux system without a unix/linux makefile?

**Comment by isabela-angelo** [comment]
Hi!
I don't know if someone still want to know how to build Scratch on linux... but I followed this link:

https://cwiki.apache.org/confluence/display/FLEX/Installation+help
"The Ant-based installer doesn't require AIR to be installed, or use the installer app, and is the preferred method of install on Linux."
So I've downloaded the Linux Binaries from here: http://flex.apache.org/download-binaries.html
Decompressed it and used the following command in a terminal:
ant -f installer.xml -Dair.sdk.version=2.6

Then Flex SDK is installed! Now just follow the BUILDING chapter in the README file of this repository.
