### ISSUE TITLE
Project changes not saving

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#830]
This project here

https://scratch.mit.edu/projects/41749048/

is not saving any more.  It's coming back with "changes not saved; network not connecting..." in the upper right-hand corner of the screen.

I replicated this by downloading the project from our production environment to an .sb2 file and then uploading it to a new project on scratch.ly.  After displaying the "saving" message for a while, the error message shows up.  Looking at the console on scratch.ly, I'm seeing this:

Mixed Content: The page at 'https://scratch.ly/projects/1000004954/#editor' was loaded over HTTPS, but requested an insecure plugin data 'http://projects.scratch.ly/crossdomain.xml'. This content should also be served over HTTPS.
(index):1 

Mixed Content: The page at 'https://scratch.ly/projects/1000004954/#editor' was loaded over HTTPS, but requested an insecure plugin data 'http://projects.scratch.ly/internalapi/project/1000004954/set/?v=v438&_rnd=0.5604829746298492'. This content should also be served over HTTPS.

<snip - Mark notes that many other Mixed Content messages were not included here>

projects.scratch.ly/internalapi/project/1000004954/set/?v=v438&_rnd=0.5604829746298492:1 POST http://projects.scratch.ly/internalapi/project/1000004954/set/?v=v438&_rnd=0.5604829746298492 net::ERR_CONNECTION_RESET
app.getsentry.com/api/20103/store/:1 POST https://app.getsentry.com/api/20103/store/ net::ERR_CONNECTION_RESET

**Comment by TheLogFather** [comment]
It contains a really long list.

See https://github.com/LLK/scratch-flash/issues/587

**Comment by thisandagain** [comment]
Tracking root issue in #587
