### ISSUE TITLE
Exception when using left menu in ( _ of _ ) sensor block when right side contains an expression

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#831]
This is similar to the set/change/show/hide hacked block exception (https://github.com/LLK/scratch-flash/issues/815) in that it assumes the right side will have an argValue rather than an expression:

https://github.com/LLK/scratch-flash/blob/master/src/scratch/BlockMenus.as#L209

If the right side has, for example, a variable dropped in it, then the behaviour caused by the exception is that an attempt to use the left menu acts as if the block was clicked (rather than showing the menu).

The issue of what menu to actually show in this case is yet another question (it can't show any local variables if the sprite's name is not explicitly given, so I guess it'll just be the 'standard' ones... but they can be different depending if right menu contained stage rather than sprite... :/ )

**Comment by TheLogFather** [comment]
I put this (and the hacked block exception, #815) into a project to make it easier to see what I mean:
https://scratch.mit.edu/projects/70022728/  (not bothered to share it)

**Comment by cwillisf** [comment]
Fixed by @TheLogFather with #949
