### ISSUE TITLE
[3D] Color Detector Flood - Fill not the same in 3d mode 

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#840]
OS: windows 7
Browser chrome 43
Server: Production v437
1. Go to https://scratch.mit.edu/projects/14318033 and 
2. draw a circle 
3. Ctrl + M
4. F

You will get 
![stage437](https://cloud.githubusercontent.com/assets/6530036/8574665/e524550c-2565-11e5-8883-d0ee95e833c8.png)

For 438 get a different picture (why logging against milestone v438 for investigation)
 @cwillisf  If you think milestone is wrong then let me know

do the same as above with project staging  1000005042

and you get 
![stage438](https://cloud.githubusercontent.com/assets/6530036/8574742/4c6a3e70-2566-11e5-9951-9f3d3f0b6baa.png)

**Comment by griffpatch** [comment]
Has to be said neither of these is working as it used to! ;)
