### ISSUE TITLE
Trying to create an account causes a new user to lose their work if there is a network problem

### ISSUE THREAD

**Issue by mgatland** [LLK/scratch-flash#842]
To reproduce:
1. Create a scratch project when you are not logged in to a Scratch Account.
2. Disconnect your internet connection
3. Click "Sign in"
4. Click "Or Join Scratch"

Desired behaviour:

The 'Join Scratch' UI appears, OR an error is displayed and the user can return to the editor. 
Whatever happens, they should not be forced to lose their work.

Actual behaviour:

The user is shown a blank page with no text. There is nothing to click on.

Even if the network connection is restored, they have no choice except to close the tab and lose all their work.

Motivation\Why I care:

I'm running a series of Scratch workshops at different libraries. The wifi at many libraries is patchy. So far, we've had 2 students hit this bug. We think it is quite demotivating for them as (if you don't know the workaround) you cannot recover your work.

Workaround:

Simply press escape to return to the previous screen. (This is really easy once you know, but it took a long time before we thought to try it.)

**Comment by mgatland** [comment]
This affected us again today, this time because of a Scratch website outage rather than our own network failing.

The result was the same - the user sees a blank page with no obvious way to return to the editor.

**Comment by 2jour** [comment]
Hi @mgatland ,

What OS and browser are you using?

I tried the steps on chrome 43 windows 7 and mac OS X 10.10 and what I saw was this when i tried to sign in if network was off 

![harper](https://cloud.githubusercontent.com/assets/6530036/8733369/8e4bf312-2bd1-11e5-9bb3-85ec406719f2.jpg)


However, I could click on the 'x' and the dialog would close which would take me back to the editor.

**Comment by mgatland** [comment]
Hi 2jour, the problem happens when you click 'Or Join Scratch' on that screen. (So it only affects first-time Scratch users.)

Aside: I just realised that pressing Escape returns to the previous screen, so this is much easier to work around than I thought. (However, it's still potential data loss for users who don't try pressing escape).
