### ISSUE TITLE
Sound tab vanished

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#844]
As shown in this project (a copy of the original)

https://scratch.mit.edu/projects/69943842/

the sound tab has disappeared for some reason.  The creator of the original project 

https://scratch.mit.edu/projects/69389332

is

https://scratch.mit.edu/users/spyrofan

spyrofan states that the project was created entirely in the online editor.  It developed an issue with sound playback and when sprofan went into the project to check it out, they found that the sound tab had vanished.

**Comment by 2jour** [comment]
Sorry need to reopen please see staging project number 13269

**Comment by 2jour** [comment]
My mistake .. closing
