### ISSUE TITLE
[3D] Presentation Mode Shrinks Item On Stage

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#845]
OS: Windows 7
Server: Staging v438
Browser: chrome 43

1. Go to the following project in staging and play in presentation mode 1000005072
 You will see this 
![image](https://cloud.githubusercontent.com/assets/6530036/8602848/96e64340-2642-11e5-84e2-cd646af1cd4b.png)

2. Ctrl +m and you will see the following
![image](https://cloud.githubusercontent.com/assets/6530036/8602889/d50be97c-2642-11e5-8b58-8c8f8f85e170.png)

This is not the case in production

https://scratch.mit.edu/projects/69959724

**Comment by cwillisf** [comment]
Fixed by #847
