### ISSUE TITLE
[3D] Robo Game Behaves differently

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#850]
Server: v438

OS: Windows 7
Browser: Chrome 43

1  https://scratch.mit.edu/projects/2734299/#player 
 
*  Move right and if you go offstage it will reappear to the left of the stage
*  Move all the to the left and ball is not trapped

2 Staging project 1000005164

Do the same steps as above

* You will see ball not reappearing to the left of stage

![stage](https://cloud.githubusercontent.com/assets/6530036/8680339/bf77b0ce-2a2e-11e5-9557-1bc8b731b8f3.png)

* You will see ball stuck on the left side of stage
![stage](https://cloud.githubusercontent.com/assets/6530036/8680405/22e79ebc-2a2f-11e5-9d0d-c81371ff5a74.png)

If i do a ctrl-m it works as in production

**Comment by sclements** [comment]
https://scratch.ly/projects/1000005164/

**Comment by 2jour** [comment]
game looks good in the offline editor

**Comment by cwillisf** [comment]
I see strange behavior at the right edge on Firefox / Windows 8.1 as well.

**Comment by sclements** [comment]
Here's an even better project to demonstrate the "deviant" behavior: https://scratch.mit.edu/projects/68808268/

**Comment by cwillisf** [comment]
The edge-of-stage behavior has been fixed with #916
Collision differences have been logged separately as #917
