### ISSUE TITLE
 [3D] Stamp of large costume not correctly scaled

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#854]
Before v438, Stage3D failed to stamp large costumes at all, so it has improved... :)

Demo project: https://scratch.mit.edu/projects/41598016/

Above project doesn't use any effects, so it works fine as is, since it's not using Stage3D. But switch into Stage3D and you'll see the problem - looks like it's stretching it in an odd way. Also, the behaviour is different in fullscreen (scaling changes).

**Comment by 2jour** [comment]
Hi @TheLogFather 

Thanks for logging the 3d issues..

I am going to take a look

**Comment by 2jour** [comment]
I see the issue 

Checked with v437.. and behaviour has improved  :). 

However, as mentioned, we do have an outstanding issue

I am going to remove the 438 tag since it hasn't broken regression @TheLogFather.  If you disagree let me know.

**Comment by TheLogFather** [comment]
OK, if you want the [v438] 'tag' to specifically refer to regression, then that makes sense.

**Comment by TheLogFather** [comment]
OK, more news about this and its relation to #985 / #856...

After testing on a non-retina display, I still see this issue with stamping a large costume in Stage3D, even though there is no problem with stretching of text/costumes (i.e. no sign of #985 / #856).

It leads me to conclude that I was wrong to suggest it's the same issue as #985 / #856.

One of #985 and #856 should most likely be marked as a duplicate of the other, and one of them closed.
