### ISSUE TITLE
[v438] [3D][Vector-Helvetica] Text incorrectly scaled in costumes

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#856]
See https://scratch.mit.edu/projects/62499800/

Note the text costume which appears when you move the cursor to the sliders at the top.

This has no effects, so works fine as is. But now switch to Stage3D...

Seen this happen in numerous projects - think it may be to do with text going beyond bounds of stage...?

Could be related to https://github.com/LLK/scratch-flash/issues/854 which also has costumes going beyond bounds of stage...?

**Comment by 2jour** [comment]
https://scratch.mit.edu/projects/70609604 remixed project to make test case simpler
Definitely an issue

trying to see if we broke regression

So in v437 text placement is off in 3d mode 
![437-text](https://cloud.githubusercontent.com/assets/6530036/8726106/1c418ad2-2ba6-11e5-8368-c92fa4f27175.jpg)

and in v438 looks like placement is off and the text is stretched as mentioned by @TheLogFather  text is stretched

![438-text](https://cloud.githubusercontent.com/assets/6530036/8726309/71b86ce6-2ba7-11e5-9cc1-63de3a0392a9.jpg)


@cwillisf regression? 

I have a sample project which does not look affected https://scratch.mit.edu/projects/70611322/
