### ISSUE TITLE
[v438] [3D] Effects can be slower than non-3D player?

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#858]
See https://scratch.mit.edu/projects/25638006/

Contains effects, so uses Stage3D player by default.

Compare behaviour when toggling to normal player.

Also note that brightness effect isn't working when in Stage3D.

**Comment by 2jour** [comment]
Yes see the issue and definitely a change from v437 to v438

1. download  https://scratch.mit.edu/projects/25638006/
2. upload to my staging port and you will notice that there is no lag in Stage3D player

**Comment by TheLogFather** [comment]
Could it be due to it doing so much stamping?
(A bit later, I'll create a diagnostic test project that tries a few things to investigate this - the brightness issue, too - and see if a normal costume behaves correctly vs stamping.)

**Comment by cwillisf** [comment]
The performance seems OK these days... are you still seeing performance problems relative to previous versions? (Note: soft edges project performs terribly in 2D for me, but 3D is OK.)
I do see the brightness problem, so I'll try to fix that.

**Comment by TheLogFather** [comment]
Oh, yes - forgot about this!
Performance looks good now (for Stage3d, anyway - expected to be bad for 2d, of course).
Good to hear about brightness :)

**Comment by 2jour** [comment]
@cwillisf can you close issue with PR?  Logged https://github.com/LLK/scratch-flash/issues/920 for brightness issue

**Comment by cwillisf** [comment]
Unfortunately I don't have a specific PR that fixed the performance problem. It was probably a combination of the various performance improvements that @sclements and I have made recently.
