### ISSUE TITLE
vector backdrop stretched out of shape with presentation mode

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#863]
Going to presentation mode the vector backdrop didn't scale properly
Then returning from presentation mode, it still was in a distorted shape:
![image](https://cloud.githubusercontent.com/assets/4721032/8767080/6fd0ec0e-2e1e-11e5-922c-61dad442d31b.png)

(I was using the party backdrop from the image library. I had ungrouped the items.)

Not sure how to reproduce yet.

**Comment by ntlrsk** [comment]
Normal proportions on reloading:
![image](https://cloud.githubusercontent.com/assets/4721032/8767156/b03c2094-2e21-11e5-9abe-e76ce44de8eb.png)

**Comment by 2jour** [comment]
@ntlrsk can you post a link to the project?

**Comment by ntlrsk** [comment]
It happened while I was working on this - though when I reloaded it went away and hasn't reoccurred, so may need to wait for more info / to repro (forgot to look at javascript window to see if it said anything at that point)
https://scratch.mit.edu/projects/70853246/
