### ISSUE TITLE
[Translation][Scratch Tips] Wrong key combination for Mac (Shift+click)?

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#869]
In this string:

    Or, use the right-click menu (Shift+click on Mac), and choose 'delete'.

templates/help/studio/tips/howto/dance2.html:21

the key combination is *Shift+click*. In other tips, it is *Ctrl+click*. So, either this string or the others are wrong.

**Comment by bobbybee** [comment]
I believe it should be Ctrl-Click

**Comment by 2jour** [comment]
Hi @guncheloc, Thanks again for helping us with the tips windows.
I verified for chrome firefox and safari that Shift-Click or Ctrl-Click works on the mac for the editor on mac OS X 10.10 .

I am going to close the issue and leave the text as is. If you think this needs to be reopened let me know

**Comment by gunchleoc** [comment]
I'm not a Mac user, so I don't really have an opinion on this matter. I'm always in favour of consistency though.

I am happy to file the bugs - translating from scratch was just a good opportunity to get some free proofreading on the source strings done. BTW I am done now :)

Now I need to create the localized images. I think the archive linked on the Wiki is a bit outdated now.
