### ISSUE TITLE
[Translation][Scratch Tips] Scratch projects starts -> start

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#870]
Typo in this string:

	<p>How will people learn how to interact with your holiday card? 
    Give help by adding instructions that appear when someone starts your card.</p>

	<p>Scratch projects starts when the <img class="intext" src = "%(STATIC_URL)s/images/help/green-flag.png"> is clicked.</p>
	
    <div class="steps last">	

	<p>Try adding a <span class="eventscolor">when <img class="intext" src = "%(STATIC_URL)s/images/help/green-flag.png"> clicked</span> block and a <span class="soundcolor">say</span> block to explain what the viewer should do.</p>
	<img src = "%(STATIC_URL)s/images/help/hoc-7-green-flag.png">
	
  templates/help/studio/tips/howto/hoc-7.html:11

**Comment by ntlrsk** [comment]
Fixed and will be going out soon.
