### ISSUE TITLE
x/y position values not updated when sprite returns to drag starting point after drop outside bounds

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#873]
See https://scratch.mit.edu/projects/71349912/

Note this explanatory post: https://scratch.mit.edu/discuss/post/1253172/

(Note also the difference in project behaviour when in Stage3D player.)

**Comment by TheLogFather** [comment]
Remixed the original project to show a bit more clearly what's happening:
https://scratch.mit.edu/projects/86570632/

**Comment by 2jour** [comment]
Thanks for that @TheLogFather
