### ISSUE TITLE
Default Chinese Character Font Size Larger

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#875]
enhancemet 1: block font size is small
Almost all Chinese teachers said the size of block is too small !!
Not like English, in Chinese editor interface, it's very hardly recognized.
We can make a comparison:
![image](https://cloud.githubusercontent.com/assets/8316018/7557690/a7ac2436-f7c8-11e4-9da3-41f7aad42f9b.png)![image](https://cloud.githubusercontent.com/assets/8316018/7557715/f0211898-f7c8-11e4-88b6-a499a24ae696.png)
![image](https://cloud.githubusercontent.com/assets/8316018/7557999/ee6bb4b8-f7cd-11e4-9543-56a4519ab552.png)![image](https://cloud.githubusercontent.com/assets/8316018/7558007/fa4d0a8e-f7cd-11e4-86d3-67b915242c29.png)

However, not all people know that press 'shift' & click menu:
![image](https://cloud.githubusercontent.com/assets/8316018/7557712/db4967a4-f7c8-11e4-996f-671508dfcb32.png)

So please enlarge Chinese font size to comfortable.

#757

**Comment by thisandagain** [comment]
Resolved in #1064
