### ISSUE TITLE
[REGRESSION] When Space Key Not Working

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#876]
OS: windows 7
Browser Chrome 43
server: staging v439

Go to project 1000005401 on staging and press space key . Nothing happens

**Comment by cwillisf** [comment]
I believe this is https://github.com/LLK/scratch-flash/issues/884

**Comment by 2jour** [comment]
I agree closing dupe of #884

**Comment by 2jour** [comment]
https://scratch.mit.edu/projects/72272636 and this behaves differently  staging 1000005486/#editor
