### ISSUE TITLE
[REGRESSION] Renaming Cloud Variable Gives 2 Clouds

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#877]
OS: windows 7
Browser: chrome 43
Server: staging
1. Rename a cloud variable and choose default name

Result 
![cloud](https://cloud.githubusercontent.com/assets/6530036/9010266/e9b5a5a6-3773-11e5-84fc-70aed163d6e7.png)

Please see 1000005412 staging

**Comment by TheLogFather** [comment]
Bit surprised this wasn't fixed before rolling out v439 with the glitch...
I guess renaming a cloudvar is sufficiently unusual, and maybe it's not obvious what it should actually show for the var name in the text box...?
