### ISSUE TITLE
List watchers grow by two pixels on reloading

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#883]
Probably about time this got added, since it's been around a while and is presumably a simple fix...

See https://scratch.mit.edu/discuss/topic/68228/ for a good description.

**Comment by Dylan5797** [comment]
Just subtract a few pixels from the width and the height of the list. This is Scratch not calculating the size of the list properly when you save your project.

**Comment by 2jour** [comment]
Are you still noticing this issue @TheLogFather ? Can't reproduce :(

**Comment by Dylan5797** [comment]
Only after save

**Comment by 2jour** [comment]
https://scratch.mit.edu/discuss/topic/176265/

**Comment by griffpatch** [comment]
I get this all the time :) however, it's not from loading and saving the
project in my experience, I get it from exporting the project and then
uploading it again. I do this all the time when I have a shared project and
am updating it and my list watchers always grow huge in no time at all...
Very frustrating!

**Comment by TheLogFather** [comment]
Sorry, yes - "saving" here *doesn't* refer to saving to the website while in the online player. It means actually saving to disk.

I suspect the problem happens when it is decoded from the json in the zipped .sb2.

It may be worth noting https://github.com/LLK/scratch-flash/blob/ca4b17110be697da83203b2802229240aff7c706/src/util/ObjReader.as#L399 which is, I think, what it does when reading an old .sb (i.e. Scratch 1.4) file...?

**Comment by TheLogFather** [comment]
It's also quite interesting to note what happens to a list watcher for a local if you save a sprite to disk and then reload it... :/

**Comment by Paddle2See** [comment]
I can reproduce this by going into the project editor of a project with a displayed list watcher, just dragging a few blocks around until the "Save" button becomes clickable, click on Save, then refresh the window.  I'm using Chrome on Win 10.

**Comment by chooper100** [comment]
I can reproduce this (both in online and offline editor) and this has been the source of numerous OC related rage quits for a long time ;)

Also, expanded comment blocks suffer the same issue for me

(Chrome, Windows 10, everything latest version)

**Comment by TheLogFather** [comment]
Script comments, yes...
They can do some weird resizing on save/reload, particularly when the editor view is not at the standard scale. I often edit projects down one from 100% (i.e. one click on the minus button), and it's clear the project comments have increased in size after saving and coming back to a project several times.

**Comment by chooper100** [comment]
@TheLogFather my browser is kept at 100% zoom (except for when that annoying chrome downloads bar messes everything up) yet I still get the issue

Could the issue for you be related to the retina display?

**Comment by TheLogFather** [comment]
Note that I'm not referring to browser zoom above, if that's what you mean (I also nearly always have browser zoom at 100%.). I'm referring to the Scratch script pane zoom level.

**Comment by chooper100** [comment]
Oh OK
