### ISSUE TITLE
Suggestion: Drop-down menus should not have focus when closed

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-flash#884]
Currently, a drop-down menu can have input focus even when the menu is closed. There is no visual indication that it has focus, but it "eats" keyboard input when in this state. This can be especially confusing with the "When [] key pressed" hat block since pressing the indicated key won't work immediately after selecting one from the drop-down menu: you'll need to move focus off the block first.

Steps to reproduce:
1. Place a "When [] key pressed" block which triggers something noticeable, such as a "Say" block.
2. Click the drop-down menu and choose a key. Click only once and don't click anywhere else afterward. Note that the drop-down menu will close when you choose the key. For this example, suppose you choose "up arrow".
3. Press "up arrow" and notice that nothing happens.
4. Click the background of the script area, or a sprite, or just about anywhere within Scratch that isn't a text field or dropdown menu.
5. Press "up arrow" again and notice that it works this time.

**Comment by 2jour** [comment]
I am concerned workaround may not be known to user. I am putting this as pro-medium

**Comment by ntlrsk** [comment]
I am encountering this as a problem for our tutorials for HOC and in general, so I'm raising to prio-high. 

To reproduce (as described above) pull out a when key pressed block, add a say block. Choose another key from the menu, such as right arrow. The block does not trigger until you click elsewhere on the screen and then press the key again.

**Comment by kaschm** [comment]
@2jour @thisandagain - adding this to the 2.2.3 milestone, as it is a bug that may interfere with HOC tutorials. Thanks @nrusk for flagging.
