### ISSUE TITLE
[Animated Gif] Issue Upload Animated Gif Pic

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#887]
OS: osx 10.10
Browser : Chrome
Reporter: https://scratch.mit.edu/discuss/topic/140148/?page=1#post-1283858

Open up https://scratch.mit.edu/projects/72447602/

or staging 1000005620 project

Original gif can be found here
https://www.dropbox.com/s/wmblho978a16dim/80843_szybka-ewolucja.gif?dl=0

**Comment by 2jour** [comment]
This may be fixed :)

**Comment by 2jour** [comment]
Still an issue

![80843_szybka-ewolucja](https://cloud.githubusercontent.com/assets/6530036/9793459/81a1638c-57b3-11e5-9de7-f754a8f472dc.gif)

**Comment by 2jour** [comment]
Still an issue

**Comment by cwillisf** [comment]
This was fixed by @sclements with LLK/scratch-flash-online@d7d917e and will go out with 441.
