### ISSUE TITLE
update block selection when costume (or backdrop) renamed

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#890]
Right now if you rename a sprite, the "touching" block updates the current selection to reflect the new name (nice!). However, if you update a costume or backdrop name, the blocks don't update the current selection, so they stop working.

To summarize: this change would involve updating: 
- "switch costume to"
-  "switch backdrop to" 
- "when backdrop switches to"
  blocks to update when the current costume or backdrop is renamed.

**Comment by 2jour** [comment]
ah yes I noticed this to :)

**Comment by 2jour** [comment]
prio-medium because this does cause confusion to our users and there is a workaround (click on dropdown and reselect)
