### ISSUE TITLE
Dragged sound from backpack does not appear in project

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#891]
Chrome / Win 7
Production

1. Go to this project https://scratch.mit.edu/projects/15803196/
2. Drag the Bryan Adams song into your backpack
3. Navigate to another project and open the sound tab of a sprite
4. Drag the song from the backpack to the sound tab
5. Expected:  The sound should appear on the sprite.  Actual result: The sound did not appear on the sprite

I opened the JS console and noticed that there was an error on it:

Failed to load resource: the server responded with a status of 404 (Not Found)
https://cdn.assets.scratch.mit.edu/internalapi/asset/52383171e1199f8d99f05f20c9dc0dac.wav/get/
(program):1 Sound not found on server: 52383171e1199f8d99f05f20c9dc0dac.wav

**Comment by 2jour** [comment]
Could it be there is a delay @Paddle2See ? I notice that there is a delay and visual notification that anything is happening. Perhaps this is the issue

I was able to see song if i wait a few seconds https://scratch.mit.edu/projects/72903826

**Comment by Paddle2See** [comment]
@2jour - I waited several minutes and saw nothing.  I'm not sure what is going on.  Perhaps we should have some sort of progress bar if something is really happening?

**Comment by 2jour** [comment]
Hi @Paddle2See ,

Do you still notice issue? I was able to get summer of 69 from your project and drag it to my project https://scratch.mit.edu/projects/89135945

**Comment by Paddle2See** [comment]
@2jour - The issue appears to have self-cured.  I can no longer reproduce the problem.

**Comment by 2jour** [comment]
Ok will close :). Please reopen if you see this again.
