### ISSUE TITLE
Can't open project editor - possibly missing assets

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#892]
Got a report in the forums about a project that lost assets and that the editor wouldn't open

https://scratch.mit.edu/projects/2761691/

I find that when I try and see inside on Chrome / Win 7, it just gets stuck in fullscreen mode showing a blank screen.

The author claims that it has not had any recent changes made to it - but now it mysteriously will not open.  Can somebody take a look and hopefully restore it to a working version?

Here's the forum topic

https://scratch.mit.edu/discuss/topic/142080/

**Comment by 2jour** [comment]
@Paddle2See is this still issue? I can load project

**Comment by Paddle2See** [comment]
It now opens for me as well.  I wonder how it got fixed?  Well, since the issue is no longer present, we might as well close.
