### ISSUE TITLE
Visualize difference between global and local variable

### ISSUE THREAD

**Issue by sdmeijer** [LLK/scratch-flash#893]
In Scratch 1.4 there was a bar between global and local variables.
In Scratch 2 this bar disappeared. It would be great to have it back, so you can see which variables are global and which are local.

**Comment by TheLogFather** [comment]
There was a time in the 2.0 beta stage when variables were separated in the Data pane, and just appeared in the same order as they were created. That wasn't great, so it was changed to have them sorted - but also all mixed together.

Unfortunately, the variable list in the set/change/show/hide menus (and variable getter's right-click menu) remained unsorted, though still with divider - and they are still the same today.

I'd really like to see some consistency between the variables in the Data pane and the variable list in those menus.

Either sort the menu the same as the Data pane and remove the divider (in which case, it's up to the programmer to use some way to distinguish global vs local, such as a prefix to the name), or add a divider into the Data pane like the menus (but it's still useful to have it sorted, and so the menu could also do with sorting, to make them consistent).
