### ISSUE TITLE
Show amount of used blocks, sprites etc. in 'My Projects'

### ISSUE THREAD

**Issue by sdmeijer** [LLK/scratch-flash#895]
It would be great to be able to have the amount of used blocks, sprites etc. on the 'My Projects' page.
I have many projects which looks empty on 'My Projects, because I didn't change the stage. But they do have code in it, which I maybe want to keep.
So I have to open all projects to see if it's really empty or not.

[Shane told me to open up an issue here, so you can move it to the website repo.]

**Comment by ealgase** [comment]
Open this on the Suggestion forum on Scratch.
