### ISSUE TITLE
Clones executing a Say block don't all delete when project stopped

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#905]
If you set up a project that creates a number of clones that are all using the non-timed version of the Say block like this

![hard to kill clones](https://cloud.githubusercontent.com/assets/3766964/9525734/91c25704-4cb3-11e5-9270-93794e867435.PNG)

And run it - then drag the clones off each other so you can view them separately, then click on the red stop sign, it seems that only a little over half of the clones disappear.  Multiple clicks of the red stop sign continue to remove more clones until finally they are all gone.  Expected behavior is that all the clones would vanish when the stop sign is clicked.

Sample project showing the behavior is here

https://scratch.mit.edu/projects/74329572/#editor

My experiments show that when they are running other scripts, like a loop that changes costumes continually, they disappear as expected.

**Comment by Dylan5797** [comment]
They will all delete at once if you don't drag them.

**Comment by ealgase** [comment]
That is weird.

**Comment by 2jour** [comment]
Can reproduce 

OS: mac osx 10.10.5
Browser: Chrome 46
