### ISSUE TITLE
Galleries?

### ISSUE THREAD

**Issue by Cats-United** [LLK/scratch-flash#907]
When you are the manager of a studio, you can select if anyone can add projects, if they are a curator or not. However, when you click it, it says "All Scratchers can now add projects to this **gallery**". Same things happens when you unselect that option. I first noticed it [here](https://scratch.mit.edu/discuss/topic/145160/).

**Comment by Dylan5797** [comment]
This is the source code of the scratch editor, not the website

**Comment by Cats-United** [comment]
Whoops, I thought you could add all Scratch-related issues there.

**Comment by 2jour** [comment]
@Cats-United you can log here :)

**Comment by 2jour** [comment]
Moved to LLK/scratchr2#2815

**Comment by Cats-United** [comment]
Gives me a 404.

**Comment by 2jour** [comment]
Moved to our website repo which is private
