### ISSUE TITLE
Suggestion (& qn): commitPenStrokes every so often during non-refresh to improve pen performance and avoid Flash crash

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#915]
See discussion https://scratch.mit.edu/discuss/topic/149256/ and projects https://scratch.mit.edu/projects/61873680/ & https://scratch.mit.edu/projects/75641024/

Actually, a more generic approach might be to have a counter which increases at every pen stroke/pen down, and commits when it reaches some value. It gets reset on any commitPenStrokes.

That should get triggered in the right circumstances (i.e. most likely drawing in non-refresh loop - but it could potentially also happen if drawing lots in an unfeasibly long script, which is probably when it should happen too...)

Question: are there any side-effects to doing such a commit...?

**Comment by TheLogFather** [comment]
Partially answering my own question above (about side-effects)...

One side-effect is the difference in the behaviour of pen alpha when committed between strokes:
Demo here: https://scratch.mit.edu/projects/75816570/

Interestingly, though, since Scratch commits pen strokes at every step at runtime (https://github.com/LLK/scratch-flash/blob/master/src/scratch/ScratchRuntime.as#L91), that means there is already a difference in pen alpha behaviour between strokes drawn in refresh loop vs non-refresh loop.

I suspect this is also a subtle enough difference in the vast majority of cases for it not to be a showstopper to this suggestion...?

A positive side-effect is that committing strokes every so often will prevent certain Flash crashes...
In the case when the project draws loads of strokes/circles in a non-refresh loop, it's possible to crash Flash. See this project for a demo: https://scratch.mit.edu/projects/75641024/ -push the "loops" variable up to its maximum and click GF again to see it crash.

**Comment by griffpatch** [comment]
If this feature was implemented would it mean that pen drawn projects that
take longer than one frame to draw their scene would draw only part of
their work in one refresh and then the next bit in the following frame,
etc... That would break games like that right?

**Comment by TheLogFather** [comment]
Woah, no - definitely wouldn't want that to happen!

It could help speed up some drawing a little, though.
See Martin's project for a demo of that: https://scratch.mit.edu/projects/75641024/

Since stamping does a commit of pen strokes (see code line linked in original post above), it helps a lot to stamp (blank costume) every so often in this case.

It seems to be particularly helpful for the case of overlapping pen drawing, which we saw a while back could cause a performance hit: https://scratch.mit.edu/projects/61873680/
Adding an occasional "stamp" in there (every few hundred dots) speeds it up a lot.
