### ISSUE TITLE
3D collision doesn't match 2D precisely

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-flash#917]
In some situations, collision tests such as those done with the `touching color _?` block are a little bit off in 3D as opposed to 2D. For example, in the following projects the player "floats" a pixel or two above the ground in 3D but touches the ground in 2D:
https://scratch.mit.edu/projects/2734299/ (staging 1000005164)
https://scratch.mit.edu/projects/68808268/

This issue was previously logged as part of #850

**Comment by 2jour** [comment]
I see this in
https://scratch.mit.edu/projects/25266003/
and 
https://scratch.mit.edu/projects/2176968/

switch to 3d and mario brothers slips down
