### ISSUE TITLE
Bitmap select shouldn't clear the redo stack

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-flash#918]
Currently the act of selecting a region in the bitmap editor clears the redo stack. We shouldn't be doing that until something actually changes.

**Comment by 2jour** [comment]
Is this fixed?

**Comment by 2jour** [comment]
If not fixed put in backlog

**Comment by thisandagain** [comment]
@bsb20 could you take a look at this bug for us?

**Comment by bsb20** [comment]
Fixed in [1005](https://github.com/LLK/scratch-flash/pull/1005)
