### ISSUE TITLE
[3d]Brightness differences

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#920]
From @TheLogFather 
See https://scratch.mit.edu/projects/25638006/

Also note that brightness effect isn't working when in Stage3D.

from @cwillisf
The performance seems OK these days... are you still seeing performance problems relative to previous versions? (Note: soft edges project performs terribly in 2D for me, but 3D is OK.)
I do see the brightness problem, so I'll try to fix that.

**Comment by TheLogFather** [comment]
Should note that it's just for stamping that brightness isn't working with Stage3D.
When a sprite is showing then negative brightness effect values give something that's basically as expected, while positive values have the usual HSV vs HSL colour-space issue for Stage3D (https://github.com/LLK/scratch-flash/issues/570).

**Comment by DevanWolf** [comment]
You can also [see my Stage3D Detector that uses the Stage3D effect bug](http://scratch.mit.edu/projects/72678954).

**Comment by CelloCodez** [comment]
Would this be like trying to use brightness 100 to make a sprite white works in Internet Explorer but not in Chrome, as in https://scratch.mit.edu/projects/78338376/?
