### ISSUE TITLE
MIDI sounds being dropped

### ISSUE THREAD

**Issue by as-com** [LLK/scratch-flash#921]
When there are a certain number of notes being played at the same time, additional notes will be dropped.

Demo: https://scratch.mit.edu/projects/76004096/
Press space to listen to the "actual" version rendered by an actual MIDI synthesizer. I promise it isn't a rickroll. :smile:

**Comment by TheLogFather** [comment]
Isn't there a max of 32 sound channels in Flash...?

I certainly came across that for https://scratch.mit.edu/projects/34570836/

**Comment by thisandagain** [comment]
Will address in the audio engine for the next version of Scratch.

**Comment by TheLogFather** [comment]
Wouldn't my suggestion above be a relatively straightforward improvement on the current behaviour?
(I.e. if there's a new sound/note to start, but there are already 32 playing, then it drops either the oldest or the one which is nearest to finishing.)
