### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by tinygg** [LLK/scratch-flash#923]
Information:[Debug (module scratch-flash)]: Starting Flex compiler:
"C:\Program Files (x86)\JetBrains\IntelliJ IDEA 13.1.6\jre\jre\bin\java.exe" "-Dapplication.home=D:\Program Files\Flex4.14" -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 13.1.6\plugins\flex\lib\idea-flex-compiler-fix.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 13.1.6\plugins\flex\lib\flex-compiler.jar;D:\Program Files\Flex4.14\lib\flex-compiler-oem.jar" com.intellij.flex.compiler.FlexCompiler 59612

Information:[Debug (module scratch-flash)]: mxmlc -load-config=C:\Users\tiny\.IntelliJIdea13\system\compile-server\_temp_\IntelliJ_IDEA\idea-975BA05D-972124F6.xml
Information:[Release (module scratch-flash)]: mxmlc -load-config=C:\Users\tiny\.IntelliJIdea13\system\compile-server\_temp_\IntelliJ_IDEA\idea-975BA05D-388899EA.xml
Information:[Debug (module scratch-flash)]: Loading configuration file C:\Users\tiny\.IntelliJIdea13\system\compile-server\_temp_\IntelliJ_IDEA\idea-975BA05D-972124F6.xml
Information:[Release (module scratch-flash)]: Loading configuration file C:\Users\tiny\.IntelliJIdea13\system\compile-server\_temp_\IntelliJ_IDEA\idea-975BA05D-388899EA.xml

Information:[Debug (module scratch-flash)]: Apache Flex Compiler (mxmlc) Version 4.14.1 build 20150325 Copyright 2015 The Apache Software Foundation.
Information:[Release (module scratch-flash)]: Apache Flex Compiler (mxmlc) Version 4.14.1 build 20150325 Copyright 2015 The Apache Software Foundation.

-----------------------------------------------------------------------------------------------------------------------
Error:[Release (module scratch-flash)]: exception 'org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 41; Invalid byte 2 of 2-byte UTF-8 sequence.' while setting variable ''

**Comment by 2jour** [comment]
Hello tinygg,

Sorry for the late reply. Were you able to figure out the issue with the compilation error?

**Comment by tinygg** [comment]
thanks 2jour,but I gave up.
