### ISSUE TITLE
Backpack items vanished

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#931]
I've received a couple of reports on my profile from users on our production environment that their packbacks have become empty spontaneously.   Because of the timing of the reports, it is possible that this issue is related to our recent issues with the servers (Upgrade, revert, etc.)

Here are the users I know of with this issue along with their comments:

https://scratch.mit.edu/users/Alpachi/
https://scratch.mit.edu/users/Paddle2See/#comments-16337904

Hi again! I'm sorry to bother you will all my problems :'( Sooo after scratch fixed up a few things and after the website was a bit inactive lately, I opened up scratch and went into a project of mine, only to find that my ENTIRE backpack got deleted! D: I had a lot of music and my art I really wanted to keep in there... will it be fixed soon?

https://scratch.mit.edu/users/Ninjabon/
https://scratch.mit.edu/users/Paddle2See/#comments-16314008

Excuse me, @Paddle2See (lol that rhymed), my backpack got reset and i got loads in it! Please help!

**Comment by 2jour** [comment]
Moved to LLK/scratchr2#2845
