### ISSUE TITLE
Experimental Blocks In Custom Blocks with strings report incorrect results

### ISSUE THREAD

**Issue by DevanWolf** [LLK/scratch-flash#932]
See: http://scratch.mit.edu/projects/73888046
There is a problem with an experimental loop C-block: "for each [ v] in ()" inside a custom block containing a string insert. For example, for each [ v] in (3) "Hello World" in custom block = "Hello World" in variable "word to match", the string in the custom block reports 1,2,3 instead of "Hello World" and after the for each loop, the string in the custom block now reports 0 instead of "Hello World"

**Comment by ealgase** [comment]
I don't think you'll get help with this because the ST doesn't support or even allow experimental blocks.

**Comment by liam4** [comment]
I just encountered this bug myself (i.e. https://scratch.mit.edu/projects/92524229/). Perhaps if somebody figures out the cause of the bug they could make a pull request to fix this..? For-each is a useful block!

**Comment by thisandagain** [comment]
Hi @DevanWolf . This is not a part of `scratch-flash` and not supported.
