### ISSUE TITLE
Motion/Looks/Sound slider watchers don't adjust

### ISSUE THREAD

**Issue by DevanWolf** [LLK/scratch-flash#933]
See: http://scratch.mit.edu/projects/77609952
The sliders for x position, y position, size, etc. in the project don't adjust. For example, use the cat x position slider, the slider still moves but the cat's x position doesn't move. However, variable slider watchers work fine.

**Comment by 2jour** [comment]
Hi DevanWolf, 

Did you write up the JSON for this project to create the sliders for the monitors?

**Comment by DevanWolf** [comment]
Yes, I did since there was no option to use the "slider" on the motion/looks/sound watchers, but there is only on variables. So there are 3 watcher types: 1 for normal readout, 2 for large readout, and 3 for slider.

**Comment by ntlrsk** [comment]
I can understand why you would like to have a slide control a sprite. But the Scratch editor team agreed that reporters (such as x position) would be best not to control with a slider, and only directly with blocks. Scratch on!

**Comment by ntlrsk** [comment]
Since this is an intentional design decision, I'm going to go ahead and close this. I left a comment on your project about a way around it, if you want to use a variable slider to set x position.
