### ISSUE TITLE
if else block dragging render issue

### ISSUE THREAD

**Issue by ScratchOs** [LLK/scratch-flash#941]
When you are dragging an if-else block the blocks inside it do not always update.

how to replicate - 
1. create an if-else element with blocks in the else section.
2. drag it over some more blocks so it the if section would have new blocks put in it.
3. the blocks in the else section do not update their position relative to the top of the if-else block.
demo at https://scratch.mit.edu/projects/81153056/

**Comment by TheLogFather** [comment]
Is this the same as https://github.com/LLK/scratch-flash/issues/733?

**Comment by 2jour** [comment]
i am going to mark as duplicate and close.  @ScratchOs if you disagree please reopen

**Comment by ScratchOs** [comment]
yes, sorry about that

**Comment by 2jour** [comment]
no worries :) .  Thank you for bringing this to our attention

and thanks @TheLogFather :)
