### ISSUE TITLE
Condition block disappears when switching language (en -> he)

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-flash#942]
Found it is this project: https://scratch.mit.edu/projects/79077572/#editor

When I switch to hebrew this part:
![image](https://cloud.githubusercontent.com/assets/15109618/10460032/88df01a2-71a0-11e5-9c61-6b9fec4fd74e.png)

Become this: 
![image](https://cloud.githubusercontent.com/assets/15109618/10460066/a39eb082-71a0-11e5-819c-413b18f28abb.png)
(the "paused=false" is missing, and the project doesn't work)

Switching back to English, it is still missing from the code, but the project is working. 

When then switching to Arabic some more blocks disappered:
![image](https://cloud.githubusercontent.com/assets/15109618/10460128/e838b51c-71a0-11e5-891b-61060fcf7f2d.png)

**Comment by colbygk** [comment]
Pretty sure the reason for this is the translations issues we've been seeing with translations changing the formatting phrases in the strings.

**Comment by 2jour** [comment]
I can repro issue

@cwillisf i am assigning to you . Let me know if too busy
