### ISSUE TITLE
trying to upload mp4 in Sounds should give error

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#944]
If you try to upload an mp4 movie or sound into Sounds, it acts like it's uploading, but then gives a blank sound. It would be good to give an error.

Same for uploading a PDF (as @2jour had mentioned, but is much less likely).

![image](https://cloud.githubusercontent.com/assets/4721032/10465581/8e6496e2-71bd-11e5-9263-47af95fcf195.png)

**Comment by 2jour** [comment]
https://github.com/LLK/scratchr2/issues/2949 https://github.com/LLK/scratch-flash-online/issues/75

**Comment by ntlrsk** [comment]
Perhaps this could be similar to what happens when you try to import a file into the New sprite button 

![image](https://cloud.githubusercontent.com/assets/4721032/10621721/713b2b74-7750-11e5-9fb3-e1abc1ad71b5.png)

**Comment by thisandagain** [comment]
@bsb20 Would you be up to take this and llk/scratch-flash-online#75?

**Comment by bsb20** [comment]
Fixed in [1006](https://github.com/LLK/scratch-flash/pull/1006)

**Comment by bsb20** [comment]
^Wrong, fixed in [1004](https://github.com/LLK/scratch-flash/pull/1004)
