### ISSUE TITLE
[Hebrew] Custom Block Parameter Order Wrong

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#948]
English
![english](https://cloud.githubusercontent.com/assets/6530036/10950883/2fbc7248-8308-11e5-994e-5e31e8852ff5.jpg)

Hebrew
![hebrew block](https://cloud.githubusercontent.com/assets/6530036/10950886/35c339c4-8308-11e5-8f55-2b2d10bd844b.jpg)

Expected:

5, 2 Block

**Comment by 2jour** [comment]
@cwillisf let me know if you think this should go to 441 hoc

**Comment by cwillisf** [comment]
I believe this is working as intended: it's a little confusing since "Block" isn't translated, but in a right-to-left language the parameters are supposed to display in right-to-left order.

**Comment by ntlrsk** [comment]
In Scratch 1.4 right-to-left languages showed blocks going the other way, which helps to make sense of the parameter order. But it hasn't been implemented yet in Scratch 2...

**Comment by cwillisf** [comment]
@ntlrsk could you clarify what you mean?

This is what I see:

 | English | Hebrew
--- | --- | ---
Scratch 1.4 | ![image](https://cloud.githubusercontent.com/assets/7019101/10952943/066d4894-82fa-11e5-8e22-271b1a88545f.png) | ![image](https://cloud.githubusercontent.com/assets/7019101/10952962/25787bd2-82fa-11e5-93f8-9d1abfc0b317.png)
Scratch 2.0 | ![image](https://cloud.githubusercontent.com/assets/7019101/10953001/6b5043b0-82fa-11e5-8474-07036239659a.png) | ![image](https://cloud.githubusercontent.com/assets/7019101/10953025/9662b358-82fa-11e5-9134-ade3c1ea3902.png)

I also just noticed that the parameters in the block definition hat are always in LTR order, which seems like it could be confusing when paired with the behavior in the table above. It seems like these two should be consistent with each other. Is this what you were referring to, @ntlrsk?
![image](https://cloud.githubusercontent.com/assets/7019101/10953094/177b4982-82fb-11e5-91a3-d4546da24404.png)

**Comment by 2jour** [comment]
See what's odd about this is that mathematical equations are LTR even in Hebrew . Perhaps this is a bigger design issue

**Comment by cwillisf** [comment]
[According to Wikipedia](https://en.wikipedia.org/wiki/Hebrew_punctuation#Mathematics), that seems to be conventional: mathematical expressions are typically written LTR in Hebrew. However, [it appears](https://en.wikipedia.org/wiki/Modern_Arabic_mathematical_notation) that this may not always be the case in Arabic. I'm no expert... we should probably get some input from native speakers of our supported RTL languages to see which things we're doing correctly (or at least acceptably) and which things need work.

I know we have a Hebrew speaker in the office now... could someone on-site (@ntlrsk, @kaschm, @thisandagain) check with her? I'm not sure if we have an Arabic speaker in the office since @adlogi left...

**Comment by ntlrsk** [comment]
Thanks for investigating and clarifying! I'll check with each of them...

**Comment by morantsur** [comment]
Hi, I'm Moran - the new Hebrew speaker :) 

in Hebrew, we write math in LTR - so for example:
![image](https://cloud.githubusercontent.com/assets/15109618/10975439/f424cd18-83b4-11e5-83b9-f041449d6209.png)

About the custom block, it does seem confusing to me... 
I think it will be best if both the define block and the usage block will show the first var or the right. so the define block for Hebrew will look something like:
![image](https://cloud.githubusercontent.com/assets/15109618/10975566/9a614f26-83b5-11e5-8d1c-95b85450dc79.png)

Does that make sense to you?

**Comment by ntlrsk** [comment]
That makes sense to me.

**Comment by ntlrsk** [comment]
Oh, but can the word "custom" and "number1" and "number2" be translated (or am I not understanding something)?

**Comment by morantsur** [comment]
They could, but the order of the words will remain the same

![image](https://cloud.githubusercontent.com/assets/15109618/10977612/1bcee604-83c0-11e5-86f2-03c33f276ee1.png)

**Comment by ntlrsk** [comment]
Thanks, that makes sense to me.
