### ISSUE TITLE
[Question] Scripts of deleted sprite remain 'active' - should they stop?

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#951]
This is something of a (relatively minor) implementation question, but it's something I noticed when looking at #235...
When deleting a sprite, its scripts stay 'active', if not actually running. (In the case of #235, specifically, it means that its Ask prompt remains, even though the asking sprite has gone.)

I can see that there is the option to "undelete", and so get all the scripts back again (as long as nothing else was deleted by then), and the scripts then continue where they left off.

But might it make some sense to have a sprite's scripts stop when it gets deleted? (Or, at least, if the sprite never got undeleted, stop its scripts at the point something else gets deleted...?)

**Comment by 2jour** [comment]
Interesting question @TheLogFather . I will ask my team mates about this one
