### ISSUE TITLE
[COMPARE BLOCK] COMPARE is Case Insensitive

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#952]
OS: mac osx 10.10.5
Browser: Safari
Server production 2.2.2
1. Look at project https://scratch.mit.edu/projects/87233582/

Notice how the costumes spell out HELLO

Expected: Hello

---

Moved from LLK/scratch-flash-online#225
/cc @2jour

**Comment by TheLogFather** [comment]
Of course, changing the implementation of the equals block (and greater/less-than) to make it(/them) case-sensitive doesn't seem that feasible now - it would no doubt break a not insignificant number of projects which already assume (and rely upon) case-insensitivity in their existing comparisons.

However, it would certainly be handy to provide some 'official' mechanism for detecting case (though it looks like it'd mean introducing a new block, or perhaps a new functionality to an old block...)
