### ISSUE TITLE
When making a copy of a project, initially inconsistent share/ unshare aspects result: no "share" button, unshared project says "shared"

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-flash#955]

**Comment by morantsur** [comment]
Oops, hit enter too early. 

When I go into the editor on one of my shared project, and click "save as a copy" my new project doesn't have the "share" button at the top-right. 

![image](https://cloud.githubusercontent.com/assets/15109618/11223075/0177f8e2-8d3c-11e5-8fff-2fb72ad006ff.png)

Reloading solves the problem.

**Comment by jwzimmer** [comment]
Making a copy of a shared project seems to result in an inconsistent state of shared/ unshared aspects. 
Specifically, I noticed that the text still says "shared" under the project title even though the project is unshared.

To repro:
- Open a shared project in the editor
- Choose File > Save as a copy
- Note that the text under the copy's title still says "shared"
- Go to My Stuff - note that the project is not shared
- Click on the project - note that you see the "not shared" banner message

<img width="579" alt="screen shot 2016-06-10 at 2 27 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/15974651/8f1400d8-2f17-11e6-8fe7-572ef1b1481f.png">
<img width="495" alt="screen shot 2016-06-10 at 2 26 40 pm" src="https://cloud.githubusercontent.com/assets/1320456/15974652/8f199f16-2f17-11e6-9d51-34754c03f316.png">
