### ISSUE TITLE
[3d] variable watchers in small-stage editor become larger when dragged

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#958]
![Project thumbnail](https://cdn2.scratch.mit.edu/get_image/project/89174734_144x108.png)
Instructions inside https://scratch.mit.edu/projects/89174734/
(Only happens with Stage3D player.)

**Comment by 2jour** [comment]
Yes I can reproduce :) thanks for the project !

**Comment by ealgase** [comment]
Funny bug!  Hope it gets fixed.
