### ISSUE TITLE
Text input for non-Latin scripts doesn't work properly on backdrops

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#971]
This was posted by an Arabic speaker in the forum, and I thought it might be of interest.

> I am trying to create an interactive storybook in Arabic.
> I see that I can add Arabic text to the “say” blocks for the sprites, but I can't seem to type in Arabic script when designing backdrops. 

https://scratch.mit.edu/discuss/topic/154962/

**Comment by ntlrsk** [comment]
Thanks for posting this, @gunchleoc 
The ability to type non-Latin characters is a high priority issue our team has been hoping to find a good way to address it, as it worked in Scratch 1.4 but is hard to address in the current online version:
https://github.com/LLK/scratch-flash/issues/231
