### ISSUE TITLE
[cloud, suggestion] accumulate cloudvar changes, and send as a single 'lumped' server request

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#973]
At the moment, each and every change to a cloudvar is sent in a chunk of JSON something like:

```
{"name": ..., "user": ..., "value": ..., "method": "set", "token": ...etc...}
```

When setting multiple cloudvars in quick succession (or even one cloudvar several times in quick succession), this becomes unnecessarily verbose, due to sending separate requests for each change.

How about collating all changes made within a fairly short period of time (or maybe up to a yield of a script?), and then lumping them together into a single request, perhaps like this:

```
{"names": [..., ..., ...], "user": ..., "values": [..., ..., ...], "method": "set", "token": ...etc...}
```

...so "name" becomes an array of "names", and similarly, "value" becomes a "values" array of the same length as "names".

I'd have thought the changes at the server end would be pretty straightforward, and it should help ease some of the load as the number and popularity of near-real-time multiplayer projects increases.

EDIT: the same goes for a project receiving multiple var changes sent _from_ the server, too...

**Comment by chooper100** [comment]
Nice idea, but you need to make sure projects that rely on up-to-date cloud variables aren't affected by this - eg. real-time multiplayer games

I would probably recommend a max of 0.3s delay either end to reduce the impact on real time as much as possible

**Comment by griffpatch** [comment]
If the messages are batched as thelogfather said so that they were sent on
the next screen refresh that would be every 1/30 of a second 0.0333 so that
wound be fine in sure :). After all, games like scratcharia have a 1 second
lag ;).

**Comment by TheLogFather** [comment]
Yes, if it was based on a time interval then it was something like 0.1s that I had in mind.

But I was really thinking more along the lines of making it send the lumped update only after all threads have completed a pass - which would normally be at refresh time (so 1/30th sec in non-turbo), with some kind of maximum of ~0.1s, say.

There would need to be something a bit different for non-refresh, though.

I wondered if there's any point to including, within a lumped send, multiple values for the same cloudvar during the refresh time? -It's not like it's going to be picked up by anyone else.

That suggests it would even make sense to only put the *latest* value into the lumped send (rather than including all changes during that short time)... [doing that would break my fallback tester project, but I always considered it a bit odd that was able to get so many changes of a cloudvar, over such a short time, into the cloud - so there we go...]

**Comment by TheLogFather** [comment]
I should say, too, that it was my fallback tester project that started me thinking over this kind of thing.

Also, I'm a bit concerned that my recent cloud snow project ( https://scratch.mit.edu/projects/91847721/ ) is somewhat 'spammy' for the cloud - it updates all ten cloudvars at ~1.7s intervals (it'd look better at ~1s, but I think that's pushing it too far - its total number of cloud requests within a minute is currently similar to Scratcharia being played by three people at once).

At the moment, then, that means it's sending an average of about twenty cloud requests every two seconds (ten "set" requests, and the extra handshake for each of those).

With this suggested change, during that time it would only send one "set" request (which would contain all ten changes), and one handshake. It's probably the most extreme example (which is partly why I made it, to demo that), but there are plenty of people who change two or more cloudvars within the same script, so it would I think it would be a reasonably significant reduction in those cases.
