### ISSUE TITLE
[cloud] The cloud log is no longer showing changes longer than a few digits

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#975]
For example, my christmas cloud-snow project's cloud log now appears to be totally empty, even though it is running pretty much 24/7, and sets ten cloudvars to about 60 (hex) digits every couple of seconds:
https://scratch.mit.edu/cloudmonitor/91847721/

I can understand not wanting to show really long values in the cloud log, but I think showing *nothing* is probably not a such good move - it makes it impossible to see at what point a cloudvar might have been corrupted, or when it was last changed.

A compromise would be to show a line in the log for all changes, but only show the start and end of the string if it's longer than a few dozen characters.

For example:

User | Data Name | Action | Data Value | Time
----- | ----- | ----- | ----- | -----
DadOfMrLog | ☁ cloudvar | set_var | 123456789…987654321 | 4 hours ago

**Comment by thisandagain** [comment]
Thanks for reporting this as it is indeed confusing and appears to be a regression. We are trying to track down the issue now and will keep you updated.

/cc @colbygk @sayamindu @cwillisf

**Comment by griffpatch** [comment]
Super :) really confused me! ;)

**Comment by thisandagain** [comment]
We were able to track this issue down to our search service (ElasticSearch) that is the backing datastore for `/cloudmonitor`. We have a patch pending and should have a deploy out soon.

**Comment by thisandagain** [comment]
Patch has landed in production and cloud logs should now be working again for integers up to 64 digits. Integers greater than 64 digits will not be displayed in `/cloudmonitor` but are still persisted. Unfortunately this fix required another purge of our datastore (ES) but this patch should prevent this purge from happening as frequently in the future.

/cc @colbygk @sayamindu

**Comment by TheLogFather** [comment]
Great to see this fixed so quickly! :)

Not so keen that it still doesn't show anything at all for long values, though.

Also, I'm not seeing any log entry for creation or deletion of a cloudvar - is that meant to be missing now...? (But renaming a cloudvar still shows an entry.)

**Comment by Dylan5797** [comment]
Just to be safe, you may want to still have an api to get the full value

**Comment by thisandagain** [comment]
Made a small tweak to show something even if it's >= 10^64. Creation / deletion should also be restored.

**Comment by griffpatch** [comment]
Super! :) Thanks

**Comment by TheLogFather** [comment]
Ah, yes, good! -Helpful in confirming that something really is happening to a long cloudvar...
(Would be even nicer to see couple of dozen characters of start & end, though, if that were possible.)

**Comment by thisandagain** [comment]
@TheLogFather Agreed. I added that to the schedule for the my next pass at the Cloud variables system (later this month).

**Comment by liam4** [comment]
New cloud variables system confirmed late January 2016!

**Comment by TheLogFather** [comment]
@liam4: Ah, yes, indeed - you heard it here first...

Everything will be sorted by next month now @thisandagain is on the job: no more problems with fallback polling (#976), cloud will work embedded (#602), multiple instances of a project will work from the same account (http://scratch.mit.edu/discuss/post/123518/), and, of course, we'll be able to use letters in cloudvars, and cloud lists will appear.

Then, for an encore, in the following month, he'll create per-user cloud variables (#689).

Looking forward to it... ;D

**Comment by griffpatch** [comment]
Woo hoo :)

**Comment by thisandagain** [comment]
LOL.

**Comment by Icelys** [comment]
Ah! Finally! :+1:

**Comment by TheLogFather** [comment]
Have we lost long changes again? I'm not seeing entries in the cloud log for anything longer than a few digits...

**Comment by Icelys** [comment]
I believe so…

**Comment by griffpatch** [comment]
I noticed that too!

**Comment by colbygk** [comment]
Somehow, our elasticsearch indexer was incorrectly storing these values as Number vs string. Any number string that was longer than ~18 digits was generating an error in elastic search related to formatting. This is an issue we've dealt with in the past and in fact,  was the source of earlier tickets related to the fix that @thisandagain added earlier.  I've fixed the indexing issue, and have now also added the feature of the longer variables being printed per the suggestion in the above issue as originally filed.

**Comment by colbygk** [comment]
It appears that elasticsearch continues to create indexes that assume Number when the first number string stored is short enough.  _shake fist at elasticsearch_

**Comment by TheLogFather** [comment]
Hey, great to see the long entries in there now! :)
