### ISSUE TITLE
[cloud, polling] A project changing a cloudvar too quickly prevents it seeing external changes

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#976]
This has been a problem with Scratch cloud for a very long time, and I'm sure it's caused much confusion over the years for Scratchers trying to make reliable multiplayer games.

I've wanted to demonstrate it before, but not seen an easy way to do that. However, I realised that I can use an external cloud client to make it much more clear:

Demo project:  https://scratch.mit.edu/projects/92748708

NOTE: you need to be connected to Scratch cloud with fallback polling, rather than the usual port 531 connection, so go make your router/firewall block port 531 in order to see the issue (EDIT: and port 843 - see below).

**Comment by TheLogFather** [comment]
OK, I've looked at this a bit more and realised the blocking I set up was not just port 531 but also 843. That was historically due to https://scratch.mit.edu/discuss/post/133191/ where @sayamindu mentions both.

After some further experimentation, it seems blocking only port 531 does not lead to the problem I describe - at least, eventually the problem isn't there... but updating does appear to be blocked for the first few seconds after starting the above project. I will investigate to see whether it's starting the project that causes it, or starting to change the cloudvar.

I do still see the problem if I block *only* port 843, though - even leaving 531 open.

I don't know quite what all this means - gonna have to investigate more...

**Comment by TheLogFather** [comment]
With cloud in fallback-only mode at the moment, this looks to be a pretty major issue right now.

Check out my demo project (now that I've updated the client that controls it to change the relevant cloudvar through HTTP rather than 531):  https://scratch.mit.edu/projects/92748708

When running the project, which is changing the lower cloudvar at a rate of about once per second, the project sees *no changes* to the other cloudvar.

It basically means the complete failure of ANY cloud-based project which makes changes to any of its cloudvars at a rate of more than about once per second.  :/

**Comment by griffpatch** [comment]
This is what I feared might be the case , and tried to bring up before...
:( but of a shame! I do hope the new cloud var system will help elevate
these issues! No idea what they are planning.

**Comment by TheLogFather** [comment]
@cwillisf:
I guess it's possible that correctly dealing with the exception in #1261 might fix this, if the exception was happening soon after a cloudvar got changed, and that was somehow preventing it from sending its next poll to the cloud server, or receiving it, or something. (And the poll after that would then be successful – unless there was another cloudvar changed before that, leading to another exception.)
If so, that's a big help for cloud in its current state. :)

@griffpatch: does this mean some of your older multiplayer games might now be working to some extent? Or is the polling time gap still too low? (I think it's nearer 1.5 secs now, rather than ~1 sec, right?)

**Comment by griffpatch** [comment]
As far as I could see the old ones were still failing, I did try upping the
poling length but I haven't seen any activity on the project, it may be
that people just don't bother trying any longer...

**Comment by TheLogFather** [comment]
Closing, since I can no longer see any evidence this is still happening (perhaps due to changes of #1261).
