### ISSUE TITLE
Capture Scroll Wheel Events

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#977]
Projects that make use of the Scroll Wheel work well in fullscreen mode, but on the project page the scroll wheel also scrolls the project page making it very confusing to use. Could the scroll wheel action be captured by the flash player when focused to prevent this from happening?

See: https://scratch.mit.edu/projects/92803451/
or: https://scratch.mit.edu/projects/88564231/

**Comment by liam4** [comment]
I totally didn't remind you about this.. ;)
