### ISSUE TITLE
Magic Wand

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-flash#978]

**Comment by liam4** [comment]
Is it just me who doesn't get what "magic eraser" means?

**Comment by griffpatch** [comment]
I think it gets stains out of carpets, etc

**Comment by liam4** [comment]
Well, yes, but what does that have to do with Scratch? :P

**Comment by Racer500** [comment]
Uh...
Delete all scripts of a certain type?

**Comment by ntlrsk** [comment]
It will let you easily edit photos to remove the background.

**Comment by liam4** [comment]
Cool. Sounds useful for importing images from Google. :)

**Comment by Racer500** [comment]
Ah yes, this would be very useful when I don't have access to image editing software! :+1:
