### ISSUE TITLE
Add WeDO 2.0 to extensions menu in Scratch

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-flash#979]
Need new image

**Comment by cpseager** [comment]
and new 'set LED color' block?

**Comment by kaschm** [comment]
New LEGO WeDo 2.0:

Name: LEGO WeDo 2.0 
Image is here: 
https://a248.e.akamai.net/cache.lego.com/images/leshop/Products/45301/45301_350x350_1_xx-xx.jpg

Let's rename / new image for the older version:

Name: LEGO WeDo 1.0 
Image: https://a248.e.akamai.net/cache.lego.com/images/leshop/Products/9581/9581_350x350_1_xx-xx.jpg
