### ISSUE TITLE
[Translation][Website] Translations not loaded without login

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#980]
On the main Scratch homepage, when the user isn't logged in, the language choice is ignored and all strings displayed in English. I tried both German and Gaelic.

Browser used: Firefox on Windows 7.

This but didn't exists a few months ago, so it must have been introduced with one of the recent changes.

After logging in, most of the Scottish Gaelic translation has disappeared (I know I'm not at 100% anymore, but the main menu headers used to be translated, for example).

**Comment by thisandagain** [comment]
@mewtaylor Can you confirm?

**Comment by mewtaylor** [comment]
@gunchleoc I'm having trouble reproducing for Firefox v45 on Windows 7 – are you still seeing the issue? If so, am I using a different version of Firefox than you?

**Comment by gunchleoc** [comment]
This seems to have fixed itself with the last update.
