### ISSUE TITLE
FYI: I ported Scratch to Haxe

### ISSUE THREAD

**Issue by my2iu** [LLK/scratch-flash#983]
I just wanted to give you a heads up that I was able to port the core of Scratch to Haxe (Flash-variant). 

It's at https://github.com/my2iu/scratch-flash/tree/haxe-port

In order to make the port easier, I removed support for SVG, extensions, sound, picture editing, sound editing, and probably some other things. Given those constraints, it works enough that I can open up projects that don't contain any SVG, move things around, and run them.

I will now look into porting the Haxe code to OpenFL to see if it's possible to get an HTML5 version working that way.

**Comment by my2iu** [comment]
I finished getting the Haxe code to work using the OpenFL libraries, and I was able to get it running under html5. Code for the OpenFL port is here:

- https://github.com/my2iu/scratch-flash/tree/openfl-port

Here is a demo of it running with html5:

- http://www.programmingbasics.org/icantbelieveitsnotscratch/index.html#projects/Cat%20and%20Mouse%20complete.sb2

**Comment by my2iu** [comment]
Is it possible to get some information about what your plans are for creating an HTML5 version of Scratch? It looks like it would probably take me maybe 2-6 weeks of full-time effort to finish porting the Flash code to HTML5, but I'm reluctant about putting in all that effort if you have other plans for creating an HTML5 version of Scratch.

I was considering completing the port regardless, thinking that even if you had other plans, you could still maybe make use of some of the code there. But then I realized that since the GitHub code is licensed under GPL, you wouldn't actually be able to use the code at all since the actual Scratch distribution contains proprietary components and is not GPL.

**Comment by thisandagain** [comment]
Thanks @my2iu ! This is great to see.

We are currently in the process of building the next version of Scratch that is indeed built using javascript.  We hope to have some of the initial code involved in this new build released to the community soon.
