### ISSUE TITLE
Scratch editor doesn't duplicate modified operator blocks correctly

### ISSUE THREAD

**Issue by asweigart** [LLK/scratch-flash#987]
My browser / operating system: Windows 7, Chrome 47.0.2526.111, Flash 20.0 (release 0)

This also happens in the Windows offline editor (v442 I think), and I was able to reproduce it in the browser. Screenshots here: https://imgur.com/a/uzdnT

Repro steps:
1. Create a script that has a green < block. (see first screenshot)
2. Right-click the green < block and change the sign to >. (see second screenshot)
3. Drag this script to another sprite to duplicate it on that sprite. (see third screenshot)
4. Notice that the green > block has reset back to <. (see fourth screenshot)

Note that this ONLY happens when you modify the < block by right-clicking to change the sign. If you originally drag a > block from the blocks palette, it will duplicate correctly. This bug also happens if you right-click to set it to the = sign: it will change back to the original < sign.

Furthermore: On the second sprite's drag-duplicated code, you will not be able to change the sign by right-clicking on the block and selecting a different sign.

Furthermore: This also happens with the green + - \* / mathematical blocks as well. (And I assume any other blocks that have this feature that I'm forgetting.)

(Originally posted to Bugs and Glitches forum: https://scratch.mit.edu/discuss/topic/178941/ )

**Comment by liam4** [comment]
I've noticed this, and it's rather annoying.

**Comment by griffpatch** [comment]
Yep, me too!!! It can be very hard to debug once it's happened as the
symbols are not what they seem! Good job reporting it!

**Comment by TheLogFather** [comment]
Wow, yeah, this has been around for soooo long (been mentioned in forums a few times), but I was a bit shocked it's not reported here already – not that I could find, anyway.

It can end up being so subtle 'cos the script can look like it's what you want, but could well be doing the opposite. I guess what stops it being more of a problem is that reloading the project fixes it.

**Comment by TheLogFather** [comment]
Just ran into this again (probably) on forums: https://scratch.mit.edu/discuss/topic/240076/

Is there any reason it still has the "needs discussion" label...?

(Maybe I'll @thisandagain and @cwillisf, just in case nobody would notice otherwise.)

**Comment by cwillisf** [comment]
I just fixed a vaguely similar issue with #1273... I just checked, and unfortunately it doesn't look like that change fixed this issue too.
