### ISSUE TITLE
[Translation] Missing Strings for Record Project Video

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-flash#989]
(not sure if there's already an issue for this somewhere)
On the translation server, the German translation is complete. However, there are still untranslated strings in the editor:
- Save as a copy
- Go to my stuff
- Record Project video
- clean up

We've had these ghosts for quite some time now, but even after completing the translation on the translation server, they seem to be untranslatable!

**Comment by kaschm** [comment]
good catch, @LiFaytheGoblin ! 

@thisandagain @rthorn is there something we need to do to add these strings to pootle?
