### ISSUE TITLE
Support for Unicode text in the paint editor

### ISSUE THREAD

**Issue by freakshow1217** [LLK/scratch-flash#992]
There is no support for Unicode in the paint editor. When I try to enter text in Chinese, the editor does not register the change. I tested this with Japanese text, just to make sure it was all of Unicode, which it seemed like it was. This is a burden for people in other countries using Scratch. A very clumsy workaround is to export a sprite made in Scratch 1.4 and then import it into 2.0, or to edit the image in an outside program.

**Comment by ntlrsk** [comment]
Yes, this is a difficult issue to address given that Scratch 2.0 is available online and that adding fonts greatly increases the size of the file. This issue is discussed here: https://github.com/LLK/scratch-flash/issues/231
